zooniverse/panoptes

lib/subjects/fallback_selection.rb
avoid ordering on set member subject random field before selecting data from it for fallback selector...just grab some data and show it.
=> avoid random order on fallback selection

db/migrate/20170727142122_modify_collections_subjects_index.rb, db/structure.sql
final part and closes #2406 - avoid table scans when looking up what collections a subject belongs to
=> add subject_id index to collections_subjects

Gemfile.lock
Attempting to fix no new relic staging data. Seems it may need the puma manual restart added back in, see https://github.com/zooniverse/Panoptes/pull/2358/commits/a940046c963c098ea7c283174c0ec86e81007fa7
=> bump newrelic_rpm gem

app/controllers/api/v1/field_guides_controller.rb, app/controllers/api/v1/tutorials_controller.rb, app/controllers/concerns/pages.rb, app/serializers/field_guide_serializer.rb, app/serializers/tutorial_serializer.rb, spec/controllers/api/v1/field_guides_controller_spec.rb, spec/controllers/api/v1/project_pages_controller_spec.rb, spec/controllers/api/v1/tutorials_controller_spec.rb
partially address #1091 & #2348
closes #2405 
Allow query param language filtering for non _content translation resources: Field Guide, Project/Org pages, Tutorials. 
When no language query param is used it will default to "en" hard coded to match current behaviour.
=> Non content resource translations language filtering

app/controllers/api/v1/users_controller.rb, spec/controllers/api/v1/users_controller_spec.rb
provide api support for admins to ban users. 
A banned user cannot create content in the panoptes API, nor create content in talk-api. This does not apply to Ouroboros era, instead use the talk moderations page to ban a user, e.g. https://talk.penguinwatch.org/#/moderation
=> allow admins to globally ban users

app/serializers/organization_serializer.rb, spec/serializers/organization_serializer_spec.rb
closes #2397 allow the orgs to get access to their external URL's
=> add urls to organisation serialiser

app/operations/memberships/create.rb, spec/operations/memberships/create_spec.rb
When a user tries to re-join a user group they had been deleted from, the existing, inactive membership causes an error on `Membership.create!`. Now, memberships are either created or reactivated on a successfully validated create request.
Primary use for this is adding/removing users from Education classrooms, which correspond directly to Panoptes user groups.
=> Reactivate existing membership on create

app/controllers/api/v1/subjects_controller.rb, app/serializers/subject_selector_serializer.rb, spec/controllers/api/v1/subjects_controller_spec.rb
avoid calling this method on for each subject. Instead just pass it in as it's static from the calling context.
=> pass the user has finished workflow context in to the subject selector serializer

app/operations/organizations/create.rb, app/operations/organizations/update.rb, app/schemas/organization_update_schema.rb, app/serializers/organization_serializer.rb, db/migrate/20170824165411_add_categories_list_to_orgs.rb, db/structure.sql, spec/controllers/api/v1/organizations_controller_spec.rb, spec/factories/organization.rb, spec/serializers/organization_serializer_spec.rb
Closes #2437 this adds categories attributes to organization model for use as org -> project tag filters.
There were no operation specs so i just tested in the controller actions, i'm happy to add these in and extract the controller specs but wanted to get something out when pairing with @mcbouslog .
=> Add categories to orgs

Gemfile, Gemfile.lock, app/workers/classifications_dump_worker.rb, app/workers/concerns/dump_worker.rb, app/workers/subjects_dump_worker.rb, app/workers/workflow_contents_dump_worker.rb, app/workers/workflows_dump_worker.rb, config/database.yml.hudson, spec/spec_helper.rb
Use Slavery Gem https://github.com/kenn/slavery to read from slave db for data dump workers
possibly supersedes #2494 - and will need a `_slave` entry in the database.yml before merging.
=> read from slave for dump workers

app/controllers/api/v1/collections_controller.rb, spec/controllers/api/v1/collections_controller_spec.rb
Was in the `allowed_params` for create but not for update. Also added it to the test object.
=> Allow description in collections update

app/counters/workflow_counter.rb, spec/counters/workflow_counter_spec.rb
count all the retired subjects as some projects launch with their beta sets still linked. Allow the retirement counter to decide which classifications count towards retirement and respect project launch date there instead of here.
Note, some subjects that are beta tested and make it through to launch without retirement will ignore any classifications prior to launch. 
The best way to avoid this situation is to beta test with a sample of your data in a different subject set and upload and link new data for the launch. All launches should be on a clean slate of data. Failing that we should look at specifying when a project records classifications from de-coupled from the launch data.
=> ignore the project launch date when counting workflow retired subjects

app/controllers/concerns/recents.rb, app/workers/concerns/dump_worker.rb, lib/database_replica.rb
some of the recents queries can be costly as they invert the order on created at before selecting the first page. push this to the read replica where we can
=> feature flag read recents from read replica

lib/routes/json_api_routes.rb, spec/routes/constraints/translations_spec.rb
Only allow integers for route ids. Note: this would have to change if we move to UUID, etc but for now this is what we need.
=> only match integers in route ids

app/controllers/api/v1/projects_controller.rb, spec/controllers/api/v1/projects_controller_spec.rb
`launch_approved` project boolean field added to the list of card fields in controller and spec.
Fixes https://github.com/zooniverse/Panoptes/issues/2483
=> Add launch_approved to card fields

.github/stale.yml
https://github.com/apps/stale - configure the stale bot to warn about inactive issues after 120 days (4 months), close after 7 and mark as stale.
=> add stale bot configuration

app/models/csv_dumps/direct_to_s3.rb, spec/models/csv_dumps/direct_to_s3_spec.rb
Ensure we write email exports to a special bucket path and not clobber files based on envs.
=> Email export bucket and path locations

app/serializers/user_serializer.rb, lib/serialization/page_with_cached_metadata.rb, lib/serialization/panoptes_restpack.rb
closes #2472 allow any panoptes restpack serializer to cache the total count value via a DSL option
=> add cache_total_count dsl to panoptes restpack

app/models/user.rb, spec/controllers/api/v1/subjects_controller_spec.rb, spec/models/user_spec.rb
closes #2197 - short circuit the check on seen linked counts vs linked counts. Only run this if the workflow isn't finished.
Also this flows into subject selection response context `finished_workflow` attribute. This now signals that a workflow is finished or the user has finished and can be used after each selection to determine if the client should prompt the user to choose a new worklfow and/or move to another project.
=> user has finished a workflow if the workflow is finished

app/controllers/api/v1/media_controller.rb, spec/controllers/api/v1/media_controller_spec.rb
Ensure the media resources restrict the media_type scope to the relevant route. 
E.g. get /projects/1/background should only return media resources with `type: 'project_background'`. fixes a bug reported in https://github.com/zooniverse/Panoptes-Front-End/pull/4142#issuecomment-344628072
=> Media resources scope fix

app/controllers/api/v1/media_controller.rb
Fix typo and make comment wording clearer.
=> fix typo and comment wording for media controller scopes

lib/subjects/postgresql_in_order_selection.rb, lib/subjects/postgresql_random_selection.rb, lib/subjects/set_member_subject_selector.rb
ensure the order by happens on the sub select instead of ordering the complex join / unnest statement.
=> optimize internal pg selection queries

app/models/csv_dumps/direct_to_s3.rb, app/models/csv_dumps/full_email_list.rb, app/services/media_storage/aws_adapter.rb, spec/models/csv_dumps/direct_to_s3_spec.rb, spec/models/csv_dumps/full_email_list_spec.rb, spec/services/media_storage/aws_adapter_spec.rb
Handle sidekiq params symbol -> string round trip lookups and ensure we use the correct s3 signature version for the emails bucket.
=> Fix email dump uploads

app/services/media_storage/aws_adapter.rb, spec/services/media_storage/aws_adapter_spec.rb
v1 url_for accepted this header, v2 presigned_url does not. the client was ignoring this header anyway as it was supplying the known mime type during PUT to the presigned URL so it’s not needed.
For ref, I've tested this manually on the console and that gave me the way to create the failing spec.
=> remove unused header for response mime type

app/services/media_storage/aws_adapter.rb, spec/services/media_storage/aws_adapter_spec.rb
give the clients more time to use the presigned URL’s by default, this options can still be overridden in the calling methods.
=> extend the default get / put presigned urls timeouts

CONTRIBUTING.md
Adds a contributing guide, inspired by the rails contributing guide, https://github.com/rails/rails/blob/master/CONTRIBUTING.md
=> Create CONTRIBUTING.md guide

app/models/classification.rb, db/migrate/20171120222438_add_compound_project_last_id_index.rb, db/migrate/20171121120455_rebuild_classification_indexes.rb, db/structure.sql, spec/models/classification_spec.rb, spec/serializers/classification_serializer_spec.rb
closes #2334 #2319
adds an index to filter by project_id and order by id at the same time e.g. 
`Classification.where(project_id: 1).where("id > ?", last_id).order(:id).limit(page_size)`
*Note: the rebuilt index is ~2x smaller than it was (4148 MB vs 1696 MB).* 
~I'm going to issue a new PR~ I've included a migration to concurrently rebuild and drop classifications table indexes. We should look at rebuilding the db / table indexes during downtimes or routinely rebuilding and dropping old ones to ensure we remove the index bloat. The code in the migration could be a nice target for extraction, i can do this if people think it'll be used more widely.
=> add compound index for classifications by project and id

app/controllers/api/v1/organizations_controller.rb, app/controllers/api/v1/projects_controller.rb, app/controllers/concerns/filter_by_tags.rb, app/models/organization.rb, app/models/tag.rb, app/operations/organizations/create.rb, app/operations/organizations/destroy.rb, app/operations/organizations/update.rb, app/operations/tags/build_tags.rb, app/schemas/organization_update_schema.rb, spec/controllers/api/v1/organizations_controller_spec.rb, spec/controllers/api/v1/projects_controller_spec.rb, spec/operations/tags/build_tags_spec.rb, spec/support/taggable.rb
Adds tag resource to organizations. Extracts tag logic into concerns and support specs and adds filtering via query params on index methods.
Tags are now built (find or init) in a little service object that's used by the project and organization update and create methods/ops.
Bonus: should make it easy to add tags to other things. Lookin' at you, collections.
Fixes #2436
=> Add tags to Organizations

app/controllers/api/v1/subjects_controller.rb, app/models/subject.rb, spec/controllers/api/v1/subjects_controller_spec.rb
I put the mimetype map right in the Subject model cause that's where it seemed like it should go. Can be generalized into a global constant via initializer or similar if you'd prefer.
These are the only two nonstandard MIME types that I remember facing outside of one weird instance from the Python client that might have been a bug. Were there more?
Resolves #2458 and https://github.com/zooniverse/Panoptes-Front-End/issues/4029
=> Override nonstandard mimetypes on subject upload

Gemfile, Gemfile.lock
Rails 5 upgrade drops this in favour of `mini-mime`. For now, let's just add this explicitly.
=> Add mime-types as explicit dependency

app/schemas/workflow_create_schema.rb, app/schemas/workflow_update_schema.rb, app/serializers/event_stream_serializers/workflow_serializer.rb, app/serializers/workflow_serializer.rb, db/migrate/20171214121332_remove_workflows_nero_config.rb, db/structure.sql, spec/controllers/api/v1/workflows_controller_spec.rb
this configuration has moved into caesar itself
=> remove nero_config from workflows

app/models/concerns/translation_strings.rb, app/models/translation.rb, lib/tasks/translations.rake, spec/factories/organization_contents.rb, spec/models/concerns/translation_strings_spec.rb
Batch process to seed the conversion of translatable resources to new translations data model. This will be run in a rake task to initially seed the data / iron out schema bugs.
=> Sync translated resource strings to translations data model

spec/models/workflow_content_spec.rb, spec/models/workflow_spec.rb
Don't ask me why. Especially don't get me started on the naming of a `varchar` column called `current_version_number`
=> Convert version numbers to ints in specs

apiary.apib
linked to #2591 - update the docs for the allowed strategy configuration for workflow retirement via the API.
=> update workflow retirement configuration docs

db/structure.sql
the structure got updated from a local 9.6 pg server dump and it's incompatible with 9.4. this will remove warnings when loading a new db from structure.
=> sync to the prod db schema dump of PostgreSQL 9.4.9

app/controllers/api/v1/translations_controller.rb, app/models/translation.rb, db/migrate/20171213144807_add_unique_translated_langauge_index.rb, db/structure.sql, spec/controllers/api/v1/translations_controller_spec.rb, spec/factories/translations.rb, spec/models/translation_spec.rb, spec/serializers/translation_serializer_spec.rb
Make sure we ever only save 1 language translation for a resource. this adds a unique compound db index that satisfies the validation query and our controller scope_for access queries. 
TODO
=> Add unique db index and validation for translated resource languages

spec/models/csv_dumps/finds_medium_spec.rb
remove warning by replacing escape \p`warning: invalid Unicode Property \p: /\project_(\w+)_export\z/`
=> Fix unicode regex warning

app/controllers/api/v1/organizations_controller.rb, app/models/concerns/translation_strings.rb, app/models/organization_content.rb, app/operations/organizations/create.rb, app/schemas/organization_update_schema.rb, app/serializers/organization_content_serializer.rb, app/serializers/organization_serializer.rb, db/migrate/20180115214144_add_announcement_to_organization_contents.rb, db/structure.sql, spec/controllers/api/v1/organization_contents_controller_spec.rb, spec/controllers/api/v1/organizations_controller_spec.rb, spec/factories/organization_contents.rb, spec/models/concerns/translation_strings_spec.rb, spec/models/organization_content_spec.rb
I added this field to the organization contents. Projects store announcements in their config JSON blobs, but orgs don't/shouldn't have one of those and they should be translatable, anyway.
Resolves https://github.com/zooniverse/Panoptes/issues/2600
=> Add announcement field to organizations

spec/controllers/api/v1/project_preferences_controller_spec.rb
Trying my best to avoid intermittent spec errors in our CI tools, this will convert the date time strings to time and allow a delta of 1 second difference between the two
=> fix intermittent spec failure matching date time strings

config/sidekiq.yml.hudson
i use these queue lists for figure out what we have in the sidekiq options, without these listed here i need to look them up in a configuration file not in this repo.
=> sync our sidekiq worker queues to the CI defaults

db/structure.sql
Old indexes crept into the structure from #2611 and due to whitespace formatting, the diff was large so didn't show in the PR by default. We should either leave the whitespace as is output from the `rake db:migrate` task or all strip whitespace on this file for any PR. I vote leave whitespace as it is the easiest to avoid messing up. 
Either way we need to ensure we see the diffs on this file and they do what we expect.
=> remove old indexes from structure.sql 

db/migrate/20180122134607_add_previous_refresh_token_to_access_tokens.rb, db/structure.sql
=> Remove not-null for Doorkeeper previous_token migration

app/models/medium.rb, spec/controllers/api/v1/subjects_controller_spec.rb, spec/models/medium_spec.rb
plain text subjects can now be uploaded for use in projects
=> allow text/plain media resources

app/models/medium.rb, app/models/organization.rb, db/migrate/20180115214144_add_announcement_to_organization_contents.rb, spec/factories/organizations.rb, spec/serializers/medium_serializer_spec.rb
@camallen added the specs, I made "org" say "organization". This fixes the broken href in serialized orgs. 
Fixes https://github.com/zooniverse/Panoptes/issues/2586
=> Org serializer link update

app/controllers/api/v1/classifications_controller.rb
When updating a classification to be complete, there is a race condition where the classification lifecycler sidekiq job is kiqed off before the update transaction completes, resulting in the job being run against the old data and not properly creating a Recent and a UserSeenSubject.
Subsequently incoming will be a new rake task to create recents for the classifications that slipped through the cracks.
=> Update records before triggering sidekiq job

app/controllers/api/v1/classifications_controller.rb, app/counters/subject_workflow_counter.rb, spec/counters/subject_workflow_counter_spec.rb
Fixes #2471, closed #1956 and resolves #2394
Ignore incomplete, gold_standard and user has seen before classifications in counts, specifically for retirement.
Making a note that  https://github.com/zooniverse/Panoptes/blob/fbb0d47e9d4a6b3e5d603d734b27bb66c69c60df/app/models/classification.rb#L28
Is currently a seq scan...it's only used with other more specific scopes
so it's a filter when walking the index but this is still row lookup (not pure index query), note: the below is a warm cache query.
>"Nested Loop  (cost=1.14..573.03 rows=2 width=4) (actual time=0.085..0.431 rows=10 loops=1)"
"  Output: classifications.id"
"  ->  Index Scan using index_classification_subjects_on_subject_id on public.classification_subjects cs  (cost=0.57..74.08 rows=58 width=4) (actual time=0.050..0.148 …
=> Better subject classification counts used for reporting & retirement.

Gemfile, Gemfile.lock
sidekiq 5.1 require redis 4 gem but attention relies on redis 3. Attention redis dep needs to bump to 4
Note: the failure is only in the sidekiq web UI and should be fixed by a manual redis bump to 4. Also i've issued a PR to sidekiq to fix this, https://github.com/mperham/sidekiq/pull/3748
=> lock sidekiq at 5.0.5

app/controllers/api/v1/users_controller.rb, spec/controllers/api/v1/users_controller_spec.rb
Linked to https://github.com/zooniverse/Panoptes-Front-End/issues/4220#issuecomment-361304385 and https://github.com/zooniverse/Panoptes-Front-End/pull/4229
When a user sets `project_email_communication` to false it should unsubscribe all their user project preferences.
=> Unsubscribe all project email preferences when user unsets project_email_communication

app/controllers/api/api_controller.rb, app/controllers/api/v1/projects_controller.rb, app/controllers/api/v1/workflows_controller.rb, app/controllers/concerns/api_errors.rb, app/models/classification.rb, app/models/project.rb, lib/classification_lifecycle.rb, spec/controllers/api/v1/projects_controller_spec.rb, spec/controllers/api/v1/workflows_controller_spec.rb, spec/lib/classification_lifecycle_spec.rb, spec/models/classification_spec.rb, spec/models/project_spec.rb, spec/support/disabled_exports.rb
some projects may contain sensitive data that we need to control access to. this is a first step to avoid leaking that data to the stream and associated services. If this becomes widely needed it should be a column on the project with an index.
=> add project metadata config option to restrict self service data access

app/controllers/api/v1/subject_sets_controller.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb
don’t just have these sitting in redis taking up memory, schedule them in seconds not minutes to clear this queue.
=> queue remove subjects in a realistic time frame

app/counters/subject_workflow_counter.rb, spec/counters/subject_workflow_counter_spec.rb
switch to the proposed filtering on classification index scopes to avoid counting duplicate, incomplete and gold standard data.
Note: linked to code experiment in #2636 - If the code experiment proves to have little impact then this filtering technique can proceed as planned. Failing that we will have to look at different index access patterns to speed up this count.
=> remove code experiment on subject workflow counters

db/migrate/20180207120238_add_default_project_config.rb, db/structure.sql
ensure the project configuration jsonb value exists for all projects, this will backfill missing data then update the default and null settings for the column.
=> add default configuration value to projects

app/controllers/api/v1/project_roles_controller.rb, app/models/project.rb, app/models/workflow.rb, app/workers/concerns/dump_mailer_worker.rb, spec/models/project_spec.rb, spec/workers/concerns/dump_mailer_worker_spec.rb
Fixes #2524 and closes https://github.com/zooniverse/Panoptes-Front-End/issues/1703
Add communications email list for projects that includes the owner by default and any user with the communications role. Dumps will use this as a fallback when there is no requesting user.
=> Communications role for projects

app/workers/project_classifications_count_worker.rb, app/workers/retirement_worker.rb, app/workers/workflow_classifications_count_worker.rb, app/workers/workflow_retired_count_worker.rb, spec/workers/project_classifications_count_worker_spec.rb, spec/workers/workflow_classifications_count_worker_spec.rb
do not allow duplicate count jobs to start, drop any new ones until the current one has finished and then fallback to congestion control.
=> count things less and space them out more

app/models/csv_dumps/classification_scope.rb, spec/models/csv_dumps/classification_scope_spec.rb
Classification dump workers should only export classifications from workflows that have not been deleted (via the Activatable module). That is, only workflows with `activated_state: "active"` should have their classifications included.
rationale: some deleted workflows have malformed tasks that occasionally cause exports to fail due to  an un-tracked-down PFE bug. This should be happening anyway, and will clean/speed up exports for researchers.
This should not be confused with `active`, which is a flag researchers can set. Those classifications are correctly included already.
=> Process only undeleted workflows in cls exports

app/models/subject_workflow_status.rb
avoid joins for this query as they do not use the subject_id index. Moving to a CTE that allows the sub-select to access the subject_id index. "CTEs can be thought of as defining temporary tables that exist just for one query" effectively exploding the find all subjects for this set to be used in a subquery IN operation. 
Benchmarking shows a massive improvement when accessing the index ~5-15x.
I've left in comments and example sql of the query for docs. happy to take this out / modify it.
Links on CTE and Arel query construction
https://www.postgresql.org/docs/9.4/static/queries-with.html
https://github.com/rails/arel#cte
=> optimise the subject workflow status by_set query

lib/formatter/csv/subject.rb, spec/lib/formatter/csv/subject_spec.rb
Fixes a bug reported by @CKrawczyk for incorrect data in subject exports. Reset the memoized subject workflow status lookup for each subject, do not reuse old data.
=> do not memoize data between runs

app/controllers/api/v1/users_controller.rb, spec/controllers/api/v1/users_controller_spec.rb
reverts the unsubscribe behaviour added in #2644. 
Use the project_email_communication field as a state to copy to new project prefs when users first classify. The UI will now offer a button to unset all project email prefs and allow the user to modify the state this way.
=> do not modify any user project email prefs

db/migrate/20180119110708_drop_collection_project_ids_column.rb, db/structure.sql
Related to #2606 - if we are happy that the HABTM collection -> projects relation is working as expected then this will clean up the unused `project_ids` collections column and associated GIN index.
=> remove collection belongs_to_many project_ids col & index

app/controllers/api/v1/users_controller.rb, spec/controllers/api/v1/users_controller_spec.rb
When handling spam complaints we only have the user's email address, so I need to be able to use that to look up the user. This looks for an `email` param and splits it on commas in the same way as `login`.
=> Allow admins to look up users by email

app/counters/workflow_counter.rb, app/models/subject_workflow_status.rb, spec/models/subject_workflow_status_spec.rb
this is heavily optimised and only used in one place, moving closer to the place of use as it requires query execution as it no longer returns AR Relations in the current form, so is not chainable.
=> extract by set cte query from SubjectWorkflowStatus

app/controllers/api/v1/set_member_subjects_controller.rb, app/controllers/api/v1/subject_sets_controller.rb, app/controllers/api/v1/subjects_controller.rb, app/controllers/api/v1/users_controller.rb, lib/json_api_controller/deactivatable_resource.rb, lib/json_api_controller/destructable_resource.rb
add transactions to destroy actions and move the worker calls outside the transaction to ensure consistent state when they run and avoid race conditions.
=> move workers outside of destroy transactions

Dockerfile.dev, Gemfile, Gemfile.lock, README.md, docker-compose.yml, scripts/docker/start.sh
avoid the cost of installing gems and rebuilding docker images, instead rely on a persisted cached volume. This should speed up dev builds. I've also updated and tested the readme instructions to get started.
=> add bundle gem cache volume for panoptes docker dev env

db/migrate/20180404144354_backfill_ux_testing_default.rb, lib/tasks/user.rake
backfilling the ux testing email comms attribute may consume all the read IOPS for the database (it did on staging db). If this is the case we should ensure we can stop (and restart) to avoid slowing down the API nodes.
=> move ux testing attribute backfill op to rake task

app/controllers/concerns/filter_by_current_user_roles.rb, spec/support/filter_by_current_user_roles.rb
This would happen if using `?current_user_role[]=a` style params, which Rails
will automatically parse and turn into an array of strings. Rails adds an
Array#split method, which caused the .try to execute and return a nested array,
which in turn happened to work with PostgresExt, but not with the new syntax.
=> Fix current_user_roles filter param after PostgresExt removal

app/models/workflow.rb, spec/serializers/workflow_serializer_spec.rb
ensure large workflow responses don't tie up API resources but still allow the client to enumerate all the workflows via paging.
pinging @mcbouslog - as per our discussion in chicago, limiting this should be ok for all our sites right?
=> limit the max workflow page size to 25

app/models/collection.rb, spec/models/collection_spec.rb
closes #2473 - show the latest added subjects in a collection first and the oldest ones last.
=> sort the subjects in a collection by default

lib/subjects/designator_selector.rb, spec/lib/subjects/designator_selector_spec.rb
We were getting reports that training images were "clustering" rather than being interleaved. This was a side effect of getting the SetMemberSubjects without any explicit ordering.
=> Ensure subjects selected with Designator are returned in selection order

apiary.apib, app/serializers/user_serializer.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/serializers/user_serializer_spec.rb
A user's credited name is collected for the purpose of displaying publicly and therefore should be included in public user requests. In the event that credited_name is nil OR includes an `@` (to protect against leaking an email address), the user's login is serialized as credited_name instead.
This will allow science teams (SGL, specifically) to query the API for user information and update their discoveries with appropriate names.
=> Include credited_name in all user requests

app/models/concerns/retirement_validator.rb, app/models/workflow.rb, spec/models/workflow_spec.rb
add custom workflow retirement validatator and ensure the classification count option has an integer in it.
=> do not allow empty retirement counts

docker-compose.yml
rails console can't start with gem path errors with spring, disable spring to avoid this. Seems there is a PR in to fix this but it hasn't been merged yet, https://github.com/rails/spring/pull/546#issuecomment-382812781
=> disable spring in docker compose envs

app/workers/calculate_project_completeness_worker.rb, app/workers/refresh_workflow_status_worker.rb, app/workers/retire_subject_worker.rb, app/workers/workflow_retired_count_worker.rb, spec/workers/refresh_workflow_status_worker_spec.rb, spec/workers/retire_subject_worker_spec.rb, spec/workers/workflow_retired_count_worker_spec.rb
Reduce the workflow deadlocks scope and count things less during retirement and set link events.  This will now rely on the retired count worker to call the project completeness worker to update the stats more regularly combined with more restrictive congestion rate limits on count workers to avoid concurrent workflow updates.
=> Refresh workflow worker deadlock issues

app/workers/retire_subject_worker.rb, spec/workers/retire_subject_worker_spec.rb
Avoid extra work if the subject is already retired. Do not run retired count worker of notify the selector services if the subject is already retired.
=> only recount and notify if a subject retires

.editorconfig, app/assets/stylesheets/base.css, app/controllers/registrations_controller.rb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.erb, config/routes.rb, spec/controllers/registrations_controller_spec.rb
I think that it might be easiest to keep features like these in Panoptes as HTML rather than APIs. That way we enforce consistency across frontends.
* Renamed "sign up" to "create account". The suble distinction between "sign up" and "sign in" confuses me every time I look at this screen.
Closes #2410
=> Allow users to edit and delete their account

app/workers/retire_subject_worker.rb, app/workers/retirement_worker.rb, spec/workers/retire_subject_worker_spec.rb, spec/workers/retirement_worker_spec.rb
Avoid 2 retirement workers (1 via the custom API & one from classification receipt) and consolidate on one for the retirement behaviour. 
The `RetireSubjectWorker` will still be called from the operation and will find or create the `subject workflow status` resource and pass this to the retirement worker. This allows us to consolidate behaviour on the `RetirementWorker` for post retirement behaviour (counting, notifications, publishing) in one worker.
=> Consolidate retirement worker behaviour

app/controllers/api/v1/workflows_controller.rb
workflow retired_subjects link shoud not update the resource. Avoid saving and reloading via link management on this relation.
=> Remove save reloads on updates

config/puma.rb, scripts/docker/restart_puma.sh
switch from preloading app via master with COW memory savings to standard workers that can be phase restarted. This cleans up the worker / boot hooks to avoid connection management as any worker will contain the connection information it needs.
One thing to note is that this will use a bit more RAM than before as we don't fork from a common master process.
=> move puma to phased restarts

app/workers/calculate_project_completeness_worker.rb, spec/workers/calculate_project_completeness_worker_spec.rb
closes #2772 - when projects link new data and the completeness metric resets we should also remove the paused project state so it's active again
=> move a paused project to active if there is data to classify

app/workers/calculate_project_completeness_worker.rb, spec/workers/calculate_project_completeness_worker_spec.rb
closes #2242 - when we update the completeness metric and activity states we should flush the serializer cache so the UI updates.
=> touch the project to clear the serializer cachesafter updating completeness 

app/controllers/api/v1/workflows_controller.rb, app/operations/workflows/retire_subjects.rb, spec/operations/workflows/retire_subjects_spec.rb
When retiring subjects we can use the `params[:workflow_id]` instead of the workflow resource in the operation. 
The authorization scheme will still issue a check via `controlled_resources.exists?` which is a count query on the db to ensure we have access to retire subjects for a given workflow. As we only use the `workflow_id` attribute and don't need the whole workflow, we can avoid paying the cost to serialize and instantiate this data from the db.
=> Avoid db fetch of the whole workflow in the retire operation

app/workers/retire_subject_worker.rb, spec/workers/retire_subject_worker_spec.rb
Follow up to #2785 - we really only want to know if the workflow exists we don’t need the whole resource to do this in the RetireSubjectWorker. 
I am going to look at our workers and how they use the workflow resource as we could be serializing more data over the wire and from the db than we currently need / use. 
However littering the code with `Workflow.select(:id, :project_id, ..).find(id)` is not ideal and will probably mean we miss it in the future. It may be easier to just slice the task object to it's own model and `accept_nested_attributes` from the workflow to deal with this. That way we can safely use the workflow resource and ensure we pre/eager_load the tasks association for the serializers.
This may also be a time to think about how to better store these json task definitions …
=> avoid repeat loading of the workflow resource in RetireSubjectWorker

lib/formatter/csv/subject.rb, spec/factories/subject_sets.rb, spec/lib/formatter/csv/subject_spec.rb
Fixes a bug in the subjects export that reported a row for each project workflow without checking if that subject was linked to that workflow. This will now print a row for each uniq subject set / workflow link including any non-linked subjects the project may have.
=> Respect set workflow links in subject dumps

app/workers/retire_subject_worker.rb, app/workers/retirement_worker.rb, spec/workers/retire_subject_worker_spec.rb, spec/workers/retirement_worker_spec.rb
Linked to changes in #2773 - force the retirement operation when calling it via the API instead of relying on the retirement checks on the `SubjectWorkflowStatus` resource. 
Noting that i forgot that sidekiq doesn't handle keyword parameters but luckily i remembered just in time. Still had to have two bites at this..Also some changes here are me renaming the `count` testing resource to `status` and some formatting in `spec/workers/retirement_worker_spec.rb`
=> Ensure we retire subject from custom retirement api end point

db/structure.sql
Update the postgres structure doc from output of pgdump with a version post 9.4.17 (most of our dev envs). 
This change reflects the comments i made in https://github.com/zooniverse/Panoptes/pull/2759#issuecomment-389215000 and may supersede #2759 if we want to keep the code and database version in sync.
=> upgrade structure.sql with secure schema paths

app/counters/workflow_counter.rb
move from CTE to simple non AR join query that runs in ~20ms on sql benchmarks. 
This both optimizes the query significantly but is much simpler code to understand and maintain. I don't know why i didn't see this the first time vs using a CTE with AREL to speed up this original query.
=> simplify and optimize the worflow counter

app/workers/calculate_project_completeness_worker.rb, spec/workers/calculate_project_completeness_worker_spec.rb
Don't automatically change a finished project's state, allow this to be a place we archive projects manually from the paused state.
=> ensure a finished project doesn't change state automatically

lib/subjects/cellect_selector.rb, lib/subjects/complete_remover.rb, lib/subjects/designator_selector.rb, lib/subjects/fallback_selection.rb, lib/subjects/postgresql_in_order_selection.rb, lib/subjects/postgresql_random_selection.rb, lib/subjects/selector.rb, lib/subjects/strategy_selection.rb, spec/lib/subjects/complete_remover_spec.rb, spec/lib/subjects/designator_selector_spec.rb, spec/lib/subjects/fallback_selection_spec.rb, spec/lib/subjects/postgresql_in_order_selection_spec.rb, spec/lib/subjects/postgresql_selection_spec.rb, spec/lib/subjects/selector_spec.rb, spec/lib/subjects/strategy_selection_spec.rb
Consolidate selectors to return only subject ids vs the extra lookup on `SetMemberSubject` as we trust the selector services correctly deal with the links between subjects and workflows. This avoids the extra query costs to convert subject_ids to sms scopes via the external selectors which were join queries and used on every selection request.
=> remove set_member_subject scope lookups on all subject selections

app/workers/requeue_classifications_worker.rb
ensure we don't queue multiple requeue workers at any given time, especially if the query execution time is slow.
=> add unique rate limiting to requeue classifications worker

db/migrate/20180614131933_invert_upp_user_project_index.rb, db/structure.sql
allow project volunteers counters to use this index as well as the search by project_id and user_id for creating / finding upps. 
Specifically https://github.com/zooniverse/Panoptes/blob/36217cd5e18cd6f23fae43006bd5a1d417ffa706/app/counters/project_counter.rb#L9 and https://github.com/zooniverse/Panoptes/blob/36217cd5e18cd6f23fae43006bd5a1d417ffa706/app/operations/user_project_preferences/find_or_create.rb#L8
=> invert the upp multi column index order

app/controllers/api/v1/subjects_controller.rb, spec/controllers/api/v1/subjects_controller_spec.rb
on selection avoid trying to respect the ordering of an empty list.
=> only order subject ids if they exist

app/models/workflow.rb, app/serializers/workflow_serializer.rb, spec/controllers/api/v1/workflows_controller_spec.rb
Avoid copying / modifying workflow task hash objects (especially large objects) just to serialize them. Instead modify the strings in place via task visitor as they won’t be updated post the serialiser stage.
=> avoid copy / dup on workflow tasks just to serialize them

app/controllers/api/v1/users_controller.rb, app/serializers/user_serializer.rb, spec/controllers/api/v1/users_controller_spec.rb
fixes #2733 
Allow the filters to cascade into the serialiser to construct the meta href for paging. Care has to be taken here to ensure we don’t allow non-admins to activate the filter in the serialiser and that we also don’t pollute the custom AR scopes with the non-lowered params, hence the custom Restpack::Options class.
=> fix paging when filtering on login and email for users

app/serializers/project_serializer.rb, spec/serializers/project_serializer_spec.rb
closes #2699 - Remove the feature flag in code as it's been the default for a while now. Also ensure we preload the `project_contents` model for projects as we've removed the eager load AR restriction on this.
=> rework project relation preloading

lib/gem_ext/doorkeeper/access_cleanup.rb, spec/lib/gem_ext/doorkeeper/access_cleanup_spec.rb
avoid the oauth token table index bloat. Cleanup any expired and/or revoked grants/tokens. Also remove all non-refreshable expired tokens and clean up old refreshable tokens if the haven't been refreshed after 14 days (default).
I've also manually cleaned and rebuilt the index on the tokens table to reduce it from over a GB to ~400MB, we may have to look at recreating and dropping the old one on a schedule to avoid the bloat.
=> add better cleanup token code

app/controllers/api/v1/subject_sets_controller.rb
ensure we aren’t in the transaction when the count workers run and leave us with incorrect data.
=> run set count workers outside the destroy transaction

app/controllers/api/v1/set_member_subjects_controller.rb, app/controllers/api/v1/subject_sets_controller.rb, app/controllers/api/v1/workflows_controller.rb, app/workers/subject_set_statuses_create_worker.rb, app/workers/subject_workflow_status_create_worker.rb, spec/controllers/api/v1/set_member_subjects_controller_spec.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb, spec/controllers/api/v1/workflows_controller_spec.rb, spec/workers/subject_set_statuses_create_worker_spec.rb, spec/workers/subject_workflow_status_create_worker_spec.rb
This will ensure the internal pg selector has the records it needs for the optimized query in #2817.
Ensure the subject workflow status records are automatically created when creating set member subjects (import via sets and on the resource) and when linking a set to a workflow (copy a set paradigm).
=> Auto create SubjectWorkflowStatus records for subject selection

lib/tasks/export.rake
Sometimes we want to set up lists for non-launch approved projects, or
manually update a list outside the normal schedule.
=> Add a rake task to export a project's email list

app/controllers/api/v1/translations_controller.rb, app/policies/aggregation_policy.rb, app/policies/field_guide_policy.rb, app/policies/membership_policy.rb, app/policies/organization_page_policy.rb, app/policies/project_page_policy.rb, app/policies/subject_policy.rb, app/policies/tutorial_policy.rb, spec/policies/field_guide_policy_spec.rb, spec/policies/membership_policy_spec.rb, spec/policies/organization_page_policy_spec.rb, spec/policies/project_page_policy_spec.rb, spec/policies/subject_policy_spec.rb, spec/policies/tutorial_policy_spec.rb
ensure we test translators can add resource translations by moving the policy scope specs to the `PunditScopeTester` with explicit scope checks across translated resources. Also removed the resource policy `*_links` action scopes that aren't wired up via routes so can't be reached and updated associated policy specs.
=> Add explicit translation scope tests for resources

Gemfile.lock
seems there is a fix to remove all orphaned keys in this 6.0.5 release. https://github.com/mhenrixon/sidekiq-unique-jobs/issues/234#issuecomment-411070779
=> update sidekiq-unique-jobs again

app/workers/subject_set_statuses_create_worker.rb, app/workers/subject_workflow_status_create_worker.rb
Ensure these run when they can.
NOTE: take care when launching large numbers of unique lock jobs as they can increase redis memory usage (possibly OOM and kill redis).
=> decrease SWS create worker run priority

lib/classification_lifecycle.rb, spec/lib/classification_lifecycle_spec.rb
This PR addresses the scheduling failures of classification lifecycle jobs, e.g. redis goes down after this jobs starts, and this job fails to schedule others / can't requeue itself. Ensure the runtime order of data updates and worker calls as follow:
1. Updating the classification data and save the record (fast fail if invalid)
2. Queue up the associated worker jobs
3. Update the `lifecycled_at` field if all workers are scheduled.
Should any failure occur in step 2 and the job doesn't make it back to sidekiq to run again the `RequeueClassificationsWorker` will ensure these jobs eventually get processed and ensure we update the associated data records.
=> Ensure classifications records are processed correctly.

Gemfile, Gemfile.lock, spec/spec_helper.rb
I was sharpening up my editor--testsuite integration with some hotkeys
to run a single test, file, or rerun the last one. Because this made it
faster to run tests, it made it more apparent that we're wasting a bunch
of time in our tests.
Specifically, it turns out that in our case, deletion is faster than
truncation as a "reset the db" strategy in DatabaseCleaner. This means
we don't reset IDs back to 1 every test run, but who cares, right? This
was the cause of the delay between RSpec saying "Randomized with seed"
and it actually starting to run the first example.
A further delay was caused by Celluloid (used by Sidetiq). We've already
worked around it somewhat by setting the timeout to 1 second in test.
It's also not as bad as the truncation fix, since this delay sits at the
very end of …
=> Speed up tests

app/controllers/api/v1/workflows_controller.rb, spec/controllers/api/v1/workflows_controller_spec.rb
fixes https://app.honeybadger.io/projects/40595/faults/38901874
Ensure we handle the non-array link_ids format when handling update & destroy links in the workflows controller.
=> handle the non-array link_ids format on workflow links update / destroy

Gemfile, Gemfile.lock
4.4.1 changes bearer token to Bearer as per the oauth spec, out JS client check doesn't handle the change in case and thus breaks login for CFE. Once v2.11.2 of https://github.com/zooniverse/panoptes-javascript-client/commit/1b2fb0550608cc5e142e36e9038d0a75ef81379f is deployed to all CFEs we can revert this and upgrade the doorkeeper gem
=> lock doorkeeper at 4.4.0

Gemfile, Gemfile.lock, spec/spec_helper.rb
sidetiq depends on the old pre 0.18 celluloid API. This error stops sidekiq from running. Ideally we can fork and bump sidetiq to get it working again to reap the timeout benefits but that'll have to wait. 
```
There was an error while trying to load the gem 'sidetiq'.
Gem Load Error is: Celluloid is not yet started; use Celluloid.boot
Backtrace for gem load error is:
/usr/local/bundle/gems/celluloid-0.18.0.pre/lib/celluloid.rb:38:in `actor_system'
/usr/local/bundle/gems/celluloid-0.18.0.pre/lib/celluloid.rb:208:in `actor_system'
/usr/local/bundle/gems/celluloid-0.18.0.pre/lib/celluloid.rb:214:in `actor_options'
/usr/local/bundle/gems/celluloid-0.18.0.pre/lib/celluloid.rb:185:in `new'
/usr/local/bundle/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/deprecate/supervise.rb:61:in …
```
=> revert celluloid gem upgrades

Jenkinsfile
The current jenkins file relies on the workspace of the operations repo to exist and it may not (see failed jobs for panoptes master branch in jenkins). This PR fixes the above failures and moves the Jenkinsfile to a declarative (https://jenkins.io/doc/book/pipeline/syntax/#declarative-directives) instead of the scripted format. 
The declarative format should provide greater consistency of the Jenkins file format across repos and allow us to use tag builds longer term (https://jenkins.io/blog/2018/05/16/pipelines-with-git-tags/), while still using a script step to build and reuse the docker image caches.
=> Move jenkins file to declarative format and use existing jobs

app/controllers/api/v1/projects_controller.rb, app/models/organization.rb, app/operations/concerns/content_from_params.rb, app/operations/concerns/url_labels.rb, app/operations/organizations/create.rb, app/operations/organizations/update.rb, db/migrate/20180808140938_add_content_fields_to_organizations.rb, db/structure.sql, lib/tasks/migrate.rake, spec/controllers/api/v1/organizations_controller_spec.rb, spec/factories/organizations.rb, spec/operations/organizations/create_spec.rb, spec/operations/organizations/update_spec.rb
This is part of a series of PRs to eventually remove the *Content models.
This one makes it so that we write what used to go in OrgContent also to the Org directly. It has a rake data migration to backfill existing data. A followup will then be able to use the Org directly for reading.
I'll do the same in two more PRs for Project and Workflow contents.
Once nothing is read from the content models anymore, I'll do a final PR which cleans up those models (removing the tables, we'll discuss whether to keep the API - which would then read from the main models but simulate the old resources).
=> Also write org contents to org itself

lib/subjects/remover.rb, spec/lib/subjects/remover_spec.rb
fixes https://app.honeybadger.io/projects/40595/faults/39095676
Since https://github.com/zooniverse/Panoptes/pull/2822 SWS records are being auto created to optimize internal pg subject selection. These records need to be cleaned up before the subject is removed to avoid the database FK constraints. 
This PR checks for any linked SWS records with non zero classification_counts OR non-empty retirement status. Any of these linked SWS records will fail the orphan test and not attempt to cleanup the subject. All empty placeholder SWS records are cleaned up before deleting the orphan subject.
=> Cleanup subject placeholder SubjectWorkflowStatus records when removing subjects

app/controllers/applications_controller.rb, app/views/doorkeeper/applications/_form.html.erb, config/initializers/doorkeeper.rb, db/dev_seed_data/dev_seed_data.rb, spec/controllers/applications_controller_spec.rb
Use the Doorkeeper `force_ssl_in_redirect_uri` config option to allow localhost apps to be insecure. 
Note: this will have to change when v5 of the gem is released (see comment in code).
=> allow insecure localhost oauth apps

Jenkinsfile
TAG_NAME env var is not available in the script block (yet?), instead use the scm and git shell to determine when we are on a tag https://notesfromthelifeboat.com/post/building-git-tags-with-jenkins/
=> use shell to check if we are on a prod tag

Jenkinsfile
the jenkins tag job does this via SCM and BRANCH_NAME so no need to manually do an extra push.
=> remove manual docker prod tag push

app/controllers/api/v1/workflows_controller.rb, spec/controllers/api/v1/workflows_controller_spec.rb
This PR adds greater targeting of the called workers when updating/deleting workflow links for subjects_sets and/or retired_subjects. E.g. when adding subject_sets the SWS Create worker should be called but not the Notify Selector of retirement worker.
=> focus the called workers for workflow link actions

app/controllers/api/v1/workflows_controller.rb, spec/controllers/api/v1/workflows_controller_spec.rb
fixes https://app.honeybadger.io/projects/40595/faults/39292400#notice-trace
Seems the previous fix for this was overwritten by a recent PR from myself. This is currently blocking subject sets from linking to workflows and needs to be patched asap.
=> handle non-array link payloads for workflow links

app/views/dormant_user_mailer/email_dormant_user.text.erb, spec/mailers/dormant_user_mailer_spec.rb
Give users multiple options to unsubscribe from these dormant user emails.
=> add extra email pref management options to footer

app/controllers/api/v1/organizations_controller.rb, app/serializers/organization_serializer.rb, app/serializers/project_serializer.rb, spec/operations/organizations/update_spec.rb, spec/serializers/organization_serializer_spec.rb
Organization URLs weren't being properly translated via the task visitor prior to serialization.
=> Fixes serialization of org URLs

app/serializers/organization_serializer.rb, app/serializers/project_serializer.rb, app/serializers/workflow_serializer.rb, spec/factories/projects.rb, spec/factories/workflows.rb, spec/serializers/organization_serializer_spec.rb, spec/serializers/project_serializer_spec.rb
This moves the read operations away from the content models. This should save some DB queries. Still writing to both the content model and the main one directly, which leaves us the option of rolling back this PR easily.
Note that Workflow still does have to load the content model from the DB in order to determine the current version. Next up will be swinging back to the versioning system in order to decouple that (that work was what prompted me to first do some PRs to remove the use of content models. The final bit will have to look at both simultaneously at least for Workflows).
=> Contents read from model

Dockerfile.dev
fixes #2907  reflect on the ruby debian image codename and use this for PG package installation
=> use correct debian version for apt-get

app/workers/email_dormant_users_worker.rb, spec/workers/email_dormant_users_worker_spec.rb
avoid sidekiq's retry mechanism to send emails, instead go straight to the dead set for appraisal.
=> do not retry emailing dormant users on error

app/mailers/dormant_user_mailer.rb, app/views/dormant_user_mailer/email_dormant_user.text.erb, spec/mailers/dormant_user_mailer_spec.rb
This pull request addresses issue 2951.
When we send dormant mailers, if the user has contributed to a project previously then they get sent a project-specific callback. However, in some cases, the last project a user contributed to may be in beta/inactive or completed and so a general call back to all projects would be better.
=> Ensure dormant mailers are not directing people to inactive or complete projects

lib/subjects/selector_context.rb, spec/lib/subjects/selector_context_spec.rb
Bug fix - ensure the final state of subject selection makes it to the selector context and then the serializer for use in the clients. This changes from hard coded to normal which is useless information as it's ignoring the selection state.
=> ensure the final selector state propogates to selector context

app/serializers/organization_serializer.rb, app/serializers/project_serializer.rb, app/serializers/workflow_serializer.rb, spec/factories/projects.rb, spec/factories/workflows.rb, spec/serializers/organization_serializer_spec.rb, spec/serializers/project_serializer_spec.rb
Revert "Revert "Contents read from model (#2925)" (#2946)"
This reverts commit b1389baeca89961c5d62da6d811de8e9a3f7e9dd.
=> reinstate the reverted PR #2925 - reverted in #2946

app/models/workflow.rb, db/migrate/20181001154345_workflow_version_numbers.rb, db/seeds.rb, db/structure.sql, lib/tasks/migrate.rake, spec/models/workflow_spec.rb
This will start keeping track of the workflow version in a way that's independent from the Papertrail calculation. It's in a new column so that it can be done while keeping the old method online for now. This will allow us to check that after a while of having this running and tracking, the version numbers are exactly the same as the papertrail ones. After that, a PR will remove the old style and get the serializer to use these new columns.
=> Track workflow versions without Papertrail

app/models/workflow.rb, spec/models/workflow_spec.rb
Linked to #2787 - Update the method to avoid loading large workflow json blobs for workers when we don't need them.
=> more robust spec testing workflow load no json

app/models/set_member_subject.rb, lib/subjects/set_member_subject_selector.rb, spec/controllers/subject_selection_strategies_controller_spec.rb, spec/factories/set_member_subjects.rb, spec/lib/subjects/postgresql_selection_spec.rb, spec/lib/subjects/selector_spec.rb, spec/lib/subjects/set_member_subject_selector_spec.rb, spec/models/set_member_subject_spec.rb
The SMS table has grown significantly with our adoption. As such the left outer joins no longer scale. A few of these queries  and can consume a lot of database resources to the detriment of all our projects. This work moves away from the JOINS, specifically the LEFT OUTER JOINs to detect non-retired linked subjects as the selectivity on these joins was terrible and resolved long loops :(
Instead we now compose a simpler AREL with the unnested  seen subject ids, it no longer uses exists / not exists but instead uses a left outer join the SMS table to detect seen/unseens. This LOJ query requires a very selective scan on the SMS table to accompany it at all times. I've made a note in the code and i'm going to refactor this to ensure we only create very selective queries to ensure we can't …
=> Optimize pg selection queries to be more selective

Jenkinsfile
avoid PR merging / branch commit activity kicking off multiple builds that could have race conditions to which version gets run (deployed / built).
Add jenkins job options to:
1. Increase the quiet period to 2 minutes to collapse branch / PR activity into the same build
2. disable concurrent builds per branch / PR and queue them instead. This is important as we want master branch / production tag deploys to run serially.
https://jenkins.io/doc/book/pipeline/syntax/#options
=> limit the number of concurrent builds

lib/subjects/strategy_selection.rb, spec/lib/subjects/strategy_selection_spec.rb
closes #2982 - don't run the internal selector if we fail to get subjects from the external selector. Instead just return an empty list of subject_ids and allow the Subjects::Selector class to handle the failure mode.
=> avoid using internal selector on exernal failure

app/models/concerns/unversioned.rb, app/models/concerns/versioning.rb, app/models/field_guide.rb, app/models/organization_page.rb, app/models/project_page.rb, app/models/translation.rb, app/models/tutorial.rb, app/schemas/translation_create_schema.rb, app/schemas/translation_update_schema.rb, spec/factories/translations.rb, spec/models/translation_spec.rb
This makes the string_versions editable through the API, but checks that the referenced version numbers make sense.
=> Translation update string versions

app/workers/unfinish_workflow_worker.rb, spec/workers/unfinish_workflow_worker_spec.rb
Low hanging 🍎🍊, fixes https://github.com/zooniverse/Panoptes/issues/2146 
Use `update_attribute` instead of an extra query and update_all when querying by id. `update_attribute` bypasses validation because the RetirementValidator complains about the JSON attribute-less workflow object, but it's always nil, so it doesn't matter.
=> Update WorkflowUnfinishWorker to update workflow's updated_at when updating workflow

lib/json_api_controller/resource_ids.rb, spec/lib/json_api_controller/check_resources_exist_spec.rb
ensure we don't 500 on invalid id params (`{id:nil}`) instead handle these as if they weren't passed in at all.
=> handle nil resource id param values in controllers

app/controllers/api/v1/organizations_controller.rb, app/controllers/concerns/sync_resource_translation_strings.rb, app/operations/organizations/update.rb, lib/json_api_controller/updatable_resource.rb, spec/controllers/api/v1/field_guides_controller_spec.rb, spec/controllers/api/v1/organization_pages_controller_spec.rb, spec/controllers/api/v1/organizations_controller_spec.rb, spec/controllers/api/v1/project_pages_controller_spec.rb, spec/controllers/api/v1/projects_controller_spec.rb, spec/controllers/api/v1/tutorials_controller_spec.rb, spec/controllers/api/v1/workflows_controller_spec.rb, spec/support/syncs_resource_translation_strings.rb
Solves failing sync translations jobs, by not enqueuing them when they would fail.
=> Sync only when strings change

app/models/workflow.rb, spec/models/workflow_spec.rb
If tasks/strings are not set during the create call, the workflow
version needs to be incremented anyway.
=> Start workflow versions at 1

app/models/concerns/classification_validator.rb, spec/models/classification_spec.rb
Linked to https://app.honeybadger.io/projects/40595/faults/41349333#notice-summary
Gold standard classifications can only be made by logged in users (bots can) so to have them be unauthenticated when processing the payload is abnormal. This PR will reject as invalid records any gold standard classifications for users that have their tokens expire during classification submission. 
The invalid record will return a 400 response which will force the client to resubmit the data (with updated tokens) instead of erroring server side (which still would have resulted in the same outcome).
https://github.com/zooniverse/Panoptes/blob/3a573b65b1bf13e7c9632cd1e947d21b7fc338b7/app/controllers/api/api_controller.rb#L19
https://github.com/zooniverse/Panoptes/blob/3a573b65b1bf13e7c9632cd1e947d21b7fc338b7/ …
=> ensure user is logged in for submitting gs data

spec/models/workflow_spec.rb
Not sure how we managed to get this broken on master, but it was.
=> Fix missing first_task attribute in spec

app/serializers/aggregation_serializer.rb, app/serializers/concerns/acl_serializer.rb, app/serializers/concerns/filter_has_many.rb, app/serializers/medium_serializer.rb, app/serializers/membership_serializer.rb, app/serializers/organization_content_serializer.rb, app/serializers/organization_serializer.rb, app/serializers/project_content_serializer.rb, app/serializers/project_serializer.rb, app/serializers/set_member_subject_serializer.rb, app/serializers/subject_set_import_serializer.rb, app/serializers/tags_serializer.rb, app/serializers/user_collection_preference_serializer.rb, app/serializers/user_group_serializer.rb, app/serializers/user_project_preference_serializer.rb, app/serializers/version_serializer.rb, app/serializers/workflow_content_serializer.rb, app/serializers/workflow_version_serializer.rb, lib/serialization/panoptes_restpack.rb, spec/serializers/collection_serializer_spec.rb, spec/serializers/project_serializer_spec.rb, spec/support/panoptes_restpack_serializer.rb
Fixes #2902 
Empty associations would be ignored by Restpack, and not serialized in the links at all. This change overrides the method in Restpack doing so, such that these will appear in the links as an empty array.
=> Serialize empty associations as an empty array

app/serializers/project_serializer.rb, spec/serializers/project_serializer_spec.rb
fixes an issue reported where paused / finished projects are showing on the active list. 
This happens as the state enum only has paused & finished so we have to manually check the null (active) state. Ideally this would be migrated to a new enum value of active
=> filter the paused and finished project states correctly

app/models/workflow.rb, spec/models/workflow_spec.rb
This field is tracked by the new versioning, and thus should also be in either major or minor version numbering calculation. 
It wasn't included in Papertrail, but that seems like an oversight. When adding WorkflowVersion, I fixed that without realising the implication of not adding it to the version numbering.
=> Increment major version if first_task changes

lib/formatter/csv/annotation_for_csv.rb, spec/lib/formatter/csv/annotation_for_csv_spec.rb
handle strange dropdown select payloads found in real exports - fixes https://app.honeybadger.io/projects/40595/faults/36814777
=> more robust dropdown annotation conversion

app/workers/calculate_project_completeness_worker.rb, app/workers/project_classifications_count_worker.rb, app/workers/workflow_classifications_count_worker.rb, app/workers/workflow_retired_count_worker.rb
until_executed combined with congestion we needs the job to complete to  remove the lock, if congestion rate limits the job then the lock is  never removed.
=> switch worker to until_executing locking strategy

app/services/designator_client.rb, spec/services/designator_client_spec.rb
This param wasn't actually used by Designator.
=> Remove Designator strategy parameter

app/controllers/api/v1/translations_controller.rb, app/controllers/concerns/polymorphic_resource_scope.rb, app/models/translation.rb, spec/controllers/api/v1/translations_controller_spec.rb, spec/requests/v1/translation_route_constraint_spec.rb
Only allow updates to translations that are not the translated resources primary language. I.e. If my `project.primary_language == 'en'` then i should not be able to update a translation resource for that project with the 'en' language. All other language translation updates are fine. 
This applies to all users owners included as owners should be updating the translations via the originating resources to keep the string keys in sync.
=> Primary language translations only via lab

Jenkinsfile
This will message slack in the following cases:
* production webserver AMI builds successfully
* production webserver AMI build failure
* production dumpworker AMI builds successfully
* production dumpworker AMI build failure
* staging webserver AMI build failure
* staging dumpworker AMI build failure
* staging migration failure
* staging deploy failure
=> Message slack

Dockerfile, Dockerfile.dev
cut down on RAM use by using a better memory allocator - jemalloc
https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
https://brandonhilkert.com/blog/reducing-sidekiq-memory-usage-with-jemalloc/
https://github.com/docker-library/ruby/issues/182
https://packages.debian.org/stretch/libjemalloc1
=> use jemalloc memory allocator

Dockerfile
linked to #3088 ensure we don't update the libjemalloc1 package accidently, debian won't release a major update for this version
Note: Dockerfile.dev isn't being locked to stretch and can be used to test any debian upgrades to the official ruby versions.
=> lock debian to stretch version

app/serializers/workflow_serializer.rb, lib/classification_dump_cache.rb, spec/lib/classification_dump_cache_spec.rb
This makes it so that we can export classifications when they refer to a workflow version that we don't have in the database. Best effort guess is to use the next one-higher workflow version, but if all else fails, just use the latest.
=> Workflow version number fixes

app/controllers/api/v1/set_member_subjects_controller.rb, app/controllers/api/v1/subject_sets_controller.rb, app/workers/subject_set_statuses_create_worker.rb, spec/controllers/api/v1/set_member_subjects_controller_spec.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb, spec/workers/subject_set_statuses_create_worker_spec.rb
Switches SubjectWorkflowStatusCreateWorkers to use `perform_in` instead of `perform_async`. The duration is just `number of elements * 4` to pad it out a bit. Perform times for each job are a chosen randomly from within that duration.
Not a genius-at-work situation over here but it's better than locking the database. Better ideas encouraged.
=> perform_in instead of perform_async

app/models/concerns/versioning.rb, spec/support/shared_specs_for_versioning.rb
avoid a costly order on possibly large tables to then select a subset of filtered rows.
Instead take the max id from the optimal version_ids to find the latest known version association via the auto-incrementing PK.
=> optimize the latest_version_id lookup

app/assets/javascripts/forms.js, app/assets/stylesheets/forms.css, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb
This PR adds under age conditional strings to the registration form. Initially, I need some feedback on what I'm doing wrong. The conditions and strings are set, but I can't get the virtual attributes to work with toggling to `under_age` attribute.
=> Update Registration Form with Underage Text

app/serializers/workflow_serializer.rb, spec/serializers/workflow_serializer_spec.rb
Why serialize them if they are not used? These relations will quickly become hundreds to thousands.
Allow the lookup of workflow versions via the workflow_versions controller instead.
=> avoid serializing worklfow versions

app/serializers/subject_selector_serializer.rb, lib/subjects/selector_context.rb, spec/lib/subjects/selector_context_spec.rb, spec/serializers/subject_selector_serializer_spec.rb
embedd the timing of selection into the selector metadata to feed back to classification metadata, this will allow us to better debug the selection events that are causing the already seens issue
=> add selected_at timestamp to track server side events

db/migrate/20190411125709_change_workflow_steps_default.rb
Running the migration on an empty test db doesn't run the update_all line. Fixed the syntax.
=> Fix syntax on update_all

app/serializers/collection_serializer.rb, app/serializers/field_guide_serializer.rb, app/serializers/organization_serializer.rb, app/serializers/project_serializer.rb, app/serializers/set_member_subject_serializer.rb, app/serializers/tutorial_serializer.rb, app/serializers/user_group_serializer.rb, spec/controllers/api/v1/set_member_subjects_controller_spec.rb, spec/serializers/collection_serializer_spec.rb, spec/serializers/organization_serializer_spec.rb, spec/serializers/project_serializer_spec.rb
Add in missing preload resource link relations that cause N+1 lookups on serializer page methods. This should speed up some end points.
=> Add missing serializer preload statements

db/migrate/20190524111214_add_pg_stats_statements_extension.rb, db/structure.sql
Record the API database queries to gain more insight into the db performance. This extension looks to be available in both staging & production RDS instance.
=> add pg_stat_statements extension

app/workers/subject_metadata_worker.rb, config/database.yml.hudson, config/initializers/panoptes.rb, lib/tasks/configure.rake, spec/workers/subject_metadata_worker_spec.rb
In non local envs disable prepared statements, manual SQL work relies on testing these code paths.
Allow Rails 4 to correctly inject the bind vars for the raw SQL
=> Inject bind variables in rails 4 with prepared_statements set to false

apiary.apib, app/counters/workflow_counter.rb, app/models/workflow.rb, lib/subjects/postgresql_selection.rb, spec/counters/workflow_counter_spec.rb, spec/lib/formatter/csv/workflow_spec.rb, spec/lib/subjects/postgresql_selection_spec.rb, spec/models/workflow_spec.rb
towards #2795 - Ignore all subject sets that are marked as training sets on the workflow configuration when counting the workflows retired and classification counts.  These counts propagate up to project counts via the workflow resource.
And When selecting data due internally from postgres, avoid selecting from training sets.
Thanks to @amyrebecca and @eatyourgreens for the idea to use subject sets markers to determine which records are included in the counts.
~~Benchmarking the query to filter the subject sets on metadata attribute presence / absence to determine the training sets look like a simple filter on the index scan for workflow -> subject sets. I think this is ok even though it's a `NOT` query. Thoughts welcome.~~
Modified the AR association scope query to reflect on the marked …
=> ignore training subject sets for counters and selection

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb
Updating the devise views to have the credited name inputs use the same browser validations as the front end apps do.
=> Update registration forms

app/controllers/api/v1/subject_sets_controller.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb
Keep the API consistent with the UI, run the subject removal worker when unlinking subjects. Also internally consistent with the subject destroy and set_member_subject destroy operation.
If project owners have linked a subject across multiple sets and they unlink it from one, this may result in the subject being removed but still being referenced with a SetMemberSubject(SMS) record.
As subject reuse across sets isn't common** the orphaned SMS issue shouldn't come up much. We can revisit the cleanup operations if this becomes an issue.
** Caesar [add to subject set effect](https://github.com/zooniverse/panoptes-client.rb/blob/13b34ea1e0b66ceec147e20ffa699aa8e0a81bd6/lib/panoptes/client/subject_sets.rb#L22) being the exception and that is driven by classifications so any removal worker will …
=> run subject cleanup worker when unlinking subjects from a set

app/views/classification_data_mailer/classification_data.html.erb, app/views/classification_data_mailer/classification_data.text.erb, app/views/subject_data_mailer/subject_data.html.erb, app/views/subject_data_mailer/subject_data.text.erb, app/views/workflow_data_mailer/workflow_data.html.erb, app/views/workflow_data_mailer/workflow_data.text.erb, app/workers/classification_data_mailer_worker.rb, app/workers/concerns/dump_mailer.rb, app/workers/subject_data_mailer_worker.rb, app/workers/workflow_data_mailer_worker.rb, spec/workers/classification_data_mailer_worker_spec.rb, spec/workers/concerns/dump_mailer_spec.rb, spec/workers/subject_data_mailer_worker_spec.rb, spec/workers/workflow_data_mailer_worker_spec.rb
fixes #1871 #2830 closes https://github.com/zooniverse/Panoptes-Front-End/issues/5241 
Remove the s3 URL from the data export emails, instead replace it with a link to the project lab data exports page where the link will be generated properly.
=> Remove s3 download export link

app/workers/subject_workflow_status_create_worker.rb
allow all these jobs to run as they shouldn't be enqueued multiple times.
If they are let the db unique index control state vs swamping redis with lock structures
=> remove the SWS create worker locks

app/services/designator_client.rb, spec/services/designator_client_spec.rb
Depends on https://github.com/zooniverse/designator/pull/86
This will allow a user's seen subjects for a workflow to sync between the panoptes and designator APIs. This works by extending the designator client `add_seen` API to match the public designator API added in https://github.com/zooniverse/designator/pull/86
This will be called each time a classification is received by worker https://github.com/zooniverse/Panoptes/blob/f039669292a9709ca83a9e7e382b6ce3c8da2c6b/app/workers/notify_subject_selector_of_seen_worker.rb which in turn calls the designator selector https://github.com/zooniverse/Panoptes/blob/f039669292a9709ca83a9e7e382b6ce3c8da2c6b/lib/subjects/designator_selector.rb#L15 to call this client method to call the remote API.
=> extend designator client with add_seen method

Gemfile, Gemfile.lock, config/initializers/strong_migrations.rb
Initializer tells the gem to ignore all old migrations, so we're just checking from here forward and only in test/dev envs. 
For reference: https://github.com/ankane/strong_migrations
=> Added strong_migrations gem and initializer

app/models/concerns/versioning.rb, lib/classification_dump_cache.rb, lib/formatter/csv/annotation_for_csv.rb, lib/tasks/migrate.rake, spec/lib/classification_dump_cache_spec.rb, spec/lib/formatter/csv/annotation_for_csv_spec.rb
Continuing on @adammcmaster's work in https://github.com/zooniverse/Panoptes/pull/3161/files in addition to letting an export proceed in case the version can't be found, this branch will create a version on the fly if the requested version is the latest, but the WorkflowVersion for it doesn't exist. It will also ensure that Honeybadger is still notified in case of issues, even though we continue with the export.
I'm also adding a rake task to make sure that every workflow has at least a version for the current state (which would otherwise not be captured anywhere if someone classifies and then a project owner makes a change). **We should be run this as soon as possible.**
=> Export catch nomethoderror

app/models/workflow.rb, lib/subjects/selector.rb, spec/lib/subjects/selector_spec.rb, spec/models/workflow_spec.rb
Allow the selector page_size to be derived from the `workflow.configuration` object.
default is to respect the incoming `page_size` param value, then if `workflow.configuration['subject_queue_page_size']` and then a default value of 10 (current). 
The use case is from @hughdickinson, specifically some workflows need to select less than the default to ensure their expected training ratios are met.
this will allow a workflow configuration setting to set a default page size when requesting subjects.
The only issue i can see with this is more round trips to the selector for that workflow, especially once the user has seen past the point where they would receive training subjects. Perhaps we could do more introspection on the user seens but that would add more work into a critical path of the …
=> allow selector page size to be set from workflow configuration

config/initializers/session_store.rb
closes #3123 Allow cookies to be reused across subdomains as per https://github.com/plataformatec/devise/wiki/How-To:-Use-subdomains
=> allow cookie reuse across zooniverse subdomains

config/initializers/session_store.rb
Reverts zooniverse/Panoptes#3176
With this change when using staging API i get a cookie with domain `.zooniverse.org`, i then try to log into the production API and the browser sends both cookies due to the `.zooniverse.org`  domain matches and the server doesn't process them in any order, thus wiping any known state of the production session.
This is due to setting the cookie domain value to conflated value of `.zooniverse.org` for both staging and production domains. 
More details about this here
https://xebia.com/blog/caveats-and-pitfalls-of-cookie-domains/
Our current setup is conflated for domains. It may be that we can isolate our staging API and app subdomains completely but this might have other impacts, e.g. `.preview-zooniverse.org` or `zooniverse.dev`?
FWIW i considered …
=> Revert "allow cookie reuse across zooniverse subdomains"

.travis.yml, Dockerfile, Dockerfile.dev, Dockerfile.docs, docs/Dockerfile
Bump next ruby version 2.5 for testing and running the system. Also test ruby 2.6 which has some failures we need to upgrade on.
=> Upgrade ruby 2.5

app/services/talk_api_client.rb, spec/services/talk_api_client_spec.rb
Get error reports and retries via sidekiq when HTTP connection errors for project talk role creation.
This should ensure we don't leave project teams without talk roles
=> raise errors for 4xx and 5xx HTTP status codes for talk api

lib/tasks/translations.rake
modify translations rake task to setup any missing primary language translation resources for project and linked resources (field guides, tutorials, workflows, pages, etc)
Some projects have not been edited in the project builder and we've never backfilled the primary language translation resources, this rake task will help fill them in.
Call the rake task with the offending project ids like so:
```
rake translations:sync_projects_missing_primary_lanugage_translations['1 2 3 4']
rake translations:sync_projects_missing_primary_lanugage_translations[1,2,3,4]
rake translations:sync_projects_missing_primary_lanugage_translations['1 2',3,4]
```
=> create a project's missing primary language translations

spec/workers/subject_metadata_worker_spec.rb
try to avoid tranasction races for intermittent failing specs. 
I'm not sure this will fix it but i can't see how the `ActiveRecord::Base.connection.exec_update` statement doesn't block to get the return val of num rows updated, hence i've tried to ensure the tests have the state setup when creating the subject resources before running each test.
=> setup the test explicitly

Dockerfile.dev
closes #3197 we don't need the jemalloc memory allocator in the develoment mode
using the latest ruby image uses a different debian version (buster) and thus changes the underlying version of jemalloc (v5) so our install fails.
Pros: dev docker file works on latest debian, `docker-compose up` works again
Cons: underlying dev debian version differs from staging / production, and we use a different memory allocator (ruby default). 
see https://github.com/zooniverse/Panoptes/issues/3197#issuecomment-553839050 for links / more details on the allocator tradeoffs and performance of jemalloc versions in ruby.
=> remove jemalloc from dev docker file

config/application.rb
Adding `credentials: true` to the cors_config.yml doesn't mean much if it's ignored by Panoptes and Rack::Cors when Rails loads. Without trying to build that resources call conditionally, though, this will add `credentials: nil` to every allow that doesn't have it. But I think that'll translate to `credentials: false` (the new default), which is what it should be anyway.
=> Add credentials to resource options when loading Rack::Cors middleware

app/workers/subject_metadata_worker.rb, spec/workers/subject_metadata_worker_spec.rb
provide a workaround till we debug the underlying queries and why they are causing DB cpu spikes and blocking the worker queues.
=> add feature flag to skip subject metadata worker

app/models/membership.rb, app/models/user_group.rb
Remove dead authorization code - some of this is very old, others has moved to *_policy.rb code. I found this code when reviewing the state of #3165 for merge.
=> remove old authorization code

app/controllers/api/v1/subject_sets_controller.rb, app/workers/subject_metadata_worker.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb, spec/workers/subject_metadata_worker_spec.rb
This PR changes the scope of each called worker to be idempotent and targets the update queries to known set_member_subject records. It will now also avoid clobbering any previously set priority values and thus avoid update rows where possible.
Current code flow means that anytime we add subjects to a set we queue a worker to update all the SMS records for the known set. For a large set upload this can leave us with blocking updates via concurrent workers. This PR should avoid these issues via more selective worker update queries.
=> Scope SubjectMetadataWorker updates to know subjects and sets

app/schemas/medium_create_schema.rb, spec/controllers/api/v1/media_controller_spec.rb
Allow externally hosted media resources to specify their src URL on create actions. Pinging @adammcmaster
=> allow externally hosted media resources on create

app/models/subject_workflow_status.rb
set_member_subject_ids is not used anymore, remove it.
=> remove set_member_subject_ids

app/workers/subject_metadata_worker.rb, spec/workers/subject_metadata_worker_spec.rb
SetMemberSubject (sms) resources are created in a transaction via [add_relation](https://github.com/zooniverse/Panoptes/blob/1fbc53d2ca2feddf14f24437fe5babd69ebd2507/app/controllers/api/v1/subject_sets_controller.rb#L106) and straight after this worker is fired. 
DB isolation levels mean that this worker will most likely run before the transaction is committed, thus the sms record won't be visible to the update statement resulting in no actual updates and the priority field not propagating to the sms record or the selector services. Thanks to @hughdickinson for finding this bug.
This PR will ensure we raise the error and use sidekiqs retry attempts to re-reun the update after transaction commit.
=> check the sms resources exist attempting an update

config/environments/production.rb, config/environments/staging.rb
Linked to https://github.com/zooniverse/operations/pull/295 and https://github.com/zooniverse/operations/pull/296 
Use a different asset prefix to avoid clashes with PFE UI assets paths. This can then be used behind a CDN to appear as hosted on the origin domain
=> change assets pipeline prefix path

app/controllers/api/v1/projects_controller.rb, spec/controllers/api/v1/projects_controller_spec.rb
Add `project.status` and `project.completeness` to the fields returned by `/projects?cards=true`.
=> Add project status to the cards route

config/initializers/cellect.rb
missed this in #3259 remove the initializer ref to the cellect client gem
=> remove reference to Cellect::Client gem

app/services/cellect_client.rb, spec/services/cellect_client_spec.rb
ensure the cellect faraday client can encode the payload params to json correctly
=> add json encoding middleware for requests payloads to cellect client

app/models/project.rb, spec/models/project_spec.rb
support more featured projects, specifically by allowing more than 1 project to be featured at the API
=> remove featured uniqueness constraint on projects

config/database.yml.hudson
record the config we are using to timeout long sql queries at the db connection layer
I'm going to update our system database.yaml to include this config. The plan is to set the ENV variable for API nodes to just longer than the load balancer (60s). As the loadbalancer will terminate connections that surpass the timeout, we can safely cancel the db queries as the results won't make it to the client.
The 5min (300000ms) value here is for sidekiq and should handle any long running queries in this env. This default can be changed via ENV vars if needed.
=> add statement_timeout to db template

app/serializers/project_serializer.rb
fallback to N+1 loading the workflow* association ids vs preloading the workflow data to then throw it away. this should allow us to test the association pressure on the db using flipper and view the results in new relic etc
=> add flipper experiement for db preloading on project

docker-compose-db.yml
Remove the old compose file for running just the db. This is out of date with the pg version and i don't think anyone uses it. An alternative way to run the db is specified in the readme, 
```
Run docker-compose run -d --name postgres --service-ports postgres to start the postgres container
```
=> remove unsued db compose file

app/models/csv_dumps/dump_scope.rb, config/initializers/panoptes.rb, lib/database_replica.rb, spec/lib/database_replica_spec.rb
~allow the dump workers to have twice as long to run than normal sidekiq queries~
remove query timeouts for the  the dump workers and ensure we reset the default timeout after dump query execution
=> Fix dump worker sql statement timeouts

app/serializers/recent_serializer.rb, spec/serializers/recent_serializer_spec.rb
these are expensive queries and we don't need them
this work can be augemented by the turning recents into a capped collection for users, e.g. each user has 100 recents each, the rest are deleted
=> avoid count queries on the recent serializer

app/serializers/project_serializer.rb, spec/serializers/project_serializer_spec.rb
avoid loading all the json attributes (some very large) for project workflow associations. As the links only need to lookup the association id we can use a custom preloader to select only the required data for serializing the association links
=> add custom workflows preloading project serializer

app/serializers/project_serializer.rb, spec/serializers/project_serializer_spec.rb
Remove the test introduced for #3280, this was successful and reduced the loading times of project workflow resources
custom workflow(s) preloading for project serializer paging is a win, keeping this around.
=> remove flipper experiment for project workflow association pre-loading

config/database.yml
* `DATABASE_URL` was missing from the secret. Added it with full creds and included `/panoptes` at the end to specify database.
* staging adapter was missing from database.yml. Included `database: panoptes` at the risk of being redundant with the URL above.
=> Add staging adapter to database.yml

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
These will need to change back to 80 once we either reconfigure Puma
(see #3315) or add an Nginx container.
=> Temporarily change service port to 81

app/models/user.rb, app/workers/concerns/rate_limit_dump_worker.rb, app/workers/random_order_shuffle_worker.rb, app/workers/reset_project_counters_worker.rb, app/workers/subject_set_subject_counter_worker.rb, config/cache_store.rb, config/database.yml, config/initializers/1_panoptes.rb, config/initializers/cors.rb, config/initializers/subject_selection_config.rb, config/initializers/user_limits.rb, config/sidekiq.yml, lib/http_cacheable.rb
Cast env var strings to integers so that Rails doesn't choke on comparisons. Also cast a few to time in seconds to match default types.
And one float.  🌬️
=> Add .to_i to ENV.fetch calls that should be ints

config/puma.rb
scale via k8s pods and reduce the CPU / RAM load in the web server container
As per docs here, https://github.com/puma/puma#thread-pool
THIS needs to be tested locally, i haven't done this yet. `docker-compose build` then `docker-compose up` would do it for non production setup
=> update puma configs for K8s deployments

.travis.yml
travis will run on PR automatically but we don't need 2 runs (pr branch) as well.
=> only run travis CI on master branch changes

Dockerfile, scripts/docker/start.sh
Improve container startup times: 
1. avoid building at startup of the container
0. setup the tmp pid dirs at build time
=> Improve container startup times 

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
allow the API containers to consume 1vcpu as the puma web server will most likely need 1vcpu for processing the incoming requests. 
Running more pods will increase the RAM pressure on the K8s system. So we've got to find a balance between the number of threads a puma server (share the same RAM cost) can handle before we scale via pods to handle the traffic. 
FWIW on each ec2 instance, we ran 2 puma processes, each with 4(staging)/8(production) threads.
The puma web server will have at least 2 threads running (more in production, https://github.com/zooniverse/panoptes/blob/33c3475a885da0821a2336f55485703b7ef055d2/config/puma.rb#L16).
=> increase the CPU limits

Dockerfile
Add a RAILS_ENV argument to production and staging Dockerfile to ensure at build time the asset pipeline correctly wires up the assets in the expected dir** 
The Dockerfile ARG will allow us to modify the RAILS_ENV environment variable at build time if we chose to (via jenkins etc). Noting that as staging and production produce the same underlying image we don't need this right now but it's better than inlining the RAILS_ENV to the rake assets:precompile CMD.
**modified in https://github.com/zooniverse/panoptes/pull/3249 to accomodate both PFE assets and panoptes assets on www.zooniverser.org domain.
=> add RAILS_ENV to prod & staging Dockerfile

kubernetes/deployment-staging.tmpl
allow testing of azure deployed staging API via PFE & CORS, e.g. https://master.pfe-preview.zooniverse.org/?panoptes-api-host=https://panoptes-staging.azure.zooniverse.org
=> allow azure zooniverse.org subdomain

kubernetes/deployment-staging.tmpl
Reverts zooniverse/panoptes#3341 - remove this addition once we switch staging to azure k8s cluster
=> Revert "allow azure zooniverse.org subdomain"

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Adding one for staging too so we can test applying the K8 config. Prod will scale between 2 and 8 pods, targeting 80% CPU utilisation (based on the resource limit we've set, so 80% of one core in this case).
=> Add horizontal pod autoscaler

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
consolidate the volume and mount declarations together, avoid clobbering details.
Debugged via `$ kubectl describe pod panoptes-staging-app-859c97896d-p26jf` and seeing the `jwt-*` volumes missing from the pods.
=> avoid clobbering volume and mount declarations

Gemfile, Gemfile.lock, config/application.rb, config/cache_store.rb, kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Adds a memcached service, renames the cache class and config env var to not mention ElastiCache.
I've set the container's memory limit to 100 MB, and the runtime memory limit in memcached to 90 MB. The current production cache seems to be consistently using less than half this amount:
=> Add memcached

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Extracted from #3345 
Remove local dev work ip based entries in allow list, folks switch to `local.zooniverse.org` or `myapp.zooniverse.org` with local DNS (/etc/hosts) overrides.
Remove old CFE apps that are already redirecting to www.zooniverse.org
=> remove old CORS allow list entries

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
allow sidekiq to scale up when it's under high CPU
=> add prod sidekiq pod autoscaler

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
disable linux kernel transparent huge pages feature to avoid latency spikes in redis, http://antirez.com/news/84
use `initcontainers` to disable on the underlying k8s node, note this setting is permanent on the nodes so it may impact other apps. If we need isolation we can have another node pool for containers that need / do not need this setting, https://stackoverflow.com/questions/45279477/disable-transparent-huge-pages-from-kubernetes
=> disable kernel THP for redis nodes

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Moves staging config from operations, and adds prod config with temporary `panoptes.azure.zooniverse.org` domain.
=> Add ingress config

config/puma.rb, kubernetes/deployment-production.tmpl
Update the puma prod config from AWS to K8s
remove the STDOUT logging redirection and use RAILS_MAX_THREADS env var for puma thread count
=> update prod puma configs

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl, scripts/docker/sidekiq_status
add a liveness exec cmd that uses a custom sidekiq bin (ruby) script for sidekiq process state
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command
Ruby bin script is a modified version of sidekiqctl (removed in v6), https://github.com/mperham/sidekiq/blob/74ccba6c68b1df31d615991fb2749fc19de8fbf7/bin/sidekiqctl
(removed in v6) https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md
=> Add sidekiq liveness probe

lib/configurable.rb
ensure we load from UPCASE env var names, e.g. https://github.com/zooniverse/panoptes/blob/700d65c883b6590fc96ded48da74f6cacf14d980/kubernetes/deployment-production.tmpl#L140
before this was looking for key `TALK_API_host` after change it's looking for `TALK_API_HOST`
=> Fix env var value loading in configurable

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Prevent these services being interrupted by cluster scaling.
=> Put redis and memcached on longlife nodes

kubernetes/deployment-staging.tmpl
surprisingly nginx handles TERM (default k8s pod signal) to fast shutdown, http://nginx.org/en/docs/control.html
This can lead to dropped connections, let's avoid that and try to shutdown gracefully, https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html
=> graceful nginx shutdown prehook

Jenkinsfile
When the `production-release` tag is pushed:
- Push `zooniverse/panoptes:production-release` to Docker Hub
- Build AMIs for panoptes-api and panoptes-dumpworker
- Deploy panoptes-api and panoptes-dumpworker
=> Reinstate AWS production deployments

kubernetes/deployment-staging.tmpl
https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
From my reading this should use the mounted temp disk on the node host FS to map the dump workers scratch space and avoid IOPS on the `/` OS disk. Trying in staging and if it works then i will roll out to production
=> use tmp disk for dumpworker tmp files

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
linked to #3389 #3390 - switch to using tmp disk for static asset serving via nginx
=> Use tmp disk for static assets

Jenkinsfile, kubernetes/job-db-migrate-production.tmpl, kubernetes/job-db-migrate-staging.tmpl
Commit ID seems to be too long.
=> Use build number rather than commit ID for migration jobs

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes
only route traffic to the new pods once they are ready to accept it. I tested boot on my dev machine and it was ~25s so going with 20 for production.
=> Add readiness probes for rollout traffic routing

kubernetes/deployment-production.tmpl
Reverts zooniverse/panoptes#3380
We can switch this back to see how it performs at 80% cpu target. 
Re reading the docs https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#how-does-the-horizontal-pod-autoscaler-work
It appears that it will take the 80% of the resource request limit, so 800 as the denominator in the calcs. so ~650m cpu average for the API pod containers before a scale up event occurs. 650/800=0.8125 or 81.25%
That scaling threshold should provide good CPU use on each API container node before a scale up event, while leaving a little headroom before maxing out if we reach our HPA scale max limit. Running less API nodes will also be more efficient on RAM resources in the k8s cluster.
=> Revert "decrease the HPA cpu target to 50%"

config/database.yml, kubernetes/deployment-staging.tmpl
Ensure we have an AR connection pool of the appropriate size for the API and sidekiq nodes
New setting: 
- API Puma threads = 4
- Sidekiq = 4
- DB connection pool = 4 (set via RAILS_MAX_THREADS)
- API Puma threads = 8
- Sidekiq = 8
- DB connection pool = 8 (set via RAILS_MAX_THREADS)
=> Fix ar connection timeouts through DB pool settings

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
95% cpu target is causing pods x 2 to come into and out of service. It appears that the high cpu target is causing the sidekiq nodes to get busy for longer and thus they activate pods in groups due to servicing the sidekiq queues. 
Decreasing this cpu target should allow the nodes to scale up and respond to the queue pressure and then down when the queue is alleviated.
```
Type    Reason             Age                   From                       Message
----    ------             ----                  ----                       -------
Normal  SuccessfulRescale  12m (x2 over 3d2h)    horizontal-pod-autoscaler  New size: 3; reason: cpu resource utilization (percentage of request) above target
Normal  SuccessfulRescale  11m                   horizontal-pod-autoscaler  New size: 4; reason: …
```
=> Descrease sidekiq hpa cpu target

db/migrate/20200513124310_remove_paper_trail_gem_versions_table.rb, db/structure.sql
Drop the unused paper trail gem versions table to cleanup the schema, shrink the total db size and avoid migrating this data.
~NOTE: we must ensure we have a backup of the table data stored somewhere in case we need to restore data from it.~ Done
=> remove paper trail gem versions table

docs/Gemfile.lock
Reverts zooniverse/panoptes#3355
this breaks the doc builds due to `Content-Length header was 10952, but should be 10964` - downgrading the gem is the only solution i could find quickly. 
Looks likely related to `Change MockRequest#env_for to rely on the input optionally responding to #size instead of #length` 
```
error  build/stylesheets/screen.css
Content-Length header was 10952, but should be 10964
/usr/local/bundle/gems/rack-2.1.4/lib/rack/lint.rb:22:in `assert'
/usr/local/bundle/gems/rack-2.1.4/lib/rack/lint.rb:695:in `verify_content_length'
/usr/local/bundle/gems/rack-2.1.4/lib/rack/lint.rb:719:in `each'
/usr/local/bundle/gems/rack-2.1.4/lib/rack/response.rb:236:in `buffered_body!'
/usr/local/bundle/gems/rack-2.1.4/lib/rack/mock.rb:173:in `initialize' …
```
=> Revert "Bump rack from 2.0.7 to 2.2.3 in /docs"

Gemfile.lock
Reverts zooniverse/panoptes#3356
so many breaking changes in minor gem versions, WAT!?
=> Revert "Bump graphql from 1.9.15 to 1.11.1"

Gemfile, Gemfile.lock
linked to #3397 - switch Gemfile to the newly released gems instead of the manual git settings
https://github.com/parrish/Sidekiq-Congestion/pull/3#event-3531826075
=> update sidekiq-congestion and congestion gems

lib/validators/one_favorite_per_owner_validator.rb, spec/controllers/api/v1/collections_controller_spec.rb
Existing issue that this PR is fixing:
The `OneFavoritePerOwnerValidator` was throwing a validation error when an existing collection record was being updated, e.g. to add a new subject to the favorites collection. For example, the validation would fail when "favorite" collection id 7 was updated, since it would pass through the OneFavoritePerOwnerValidator, the validator would say "we already have a favorite collection for this owner/project", and then the validation would fail. This PR updates the validator such that if the record being validated is not a new record (`record.persisted?`), filter out collections with the same id as the current record when checking for favorite collections for the current owner/project.
Worth noting that this failure mostly due to the fact that I wrote …
=> Update validation to account for when validated record is not new

app/workers/notify_subject_selector_of_change_worker.rb, app/workers/notify_subject_selector_of_retirement_worker.rb, app/workers/notify_subject_selector_of_seen_worker.rb, app/workers/subject_metadata_worker.rb
Avoid transient jobs piling up in the morgue. 
Selector notifications can dissapear as this data is in flux. 
Metadata update workers may sometimes be fired for data that is deleted, not commited etc. These can just fail without going to the [sidekiq morgue](https://github.com/mperham/sidekiq/wiki/Error-Handling#dead-set) after 10 retries to ensure they have time for transactions commit visibility.
=> No morgue workers

Jenkinsfile, kubernetes/deployment-staging-azure-canary.tmpl
The kubernetes/deployment-staging-azure-canary.tmpl contains the instructions for configuring the canary deployment. It includes a deployment template, a ConfigMap with env vars that tell the canary service to use azure storage, and an Ingress. My thought is to initially have the canary-weight be set to 0, and first just test using the canary-by-cookie option. Once we confirm that this works, we can switch over to having a % of requests go to azure. See these articles for more information about canary deployments: 
- [Canary deployment with ingress nginx](https://www.elvinefendi.com/2018/11/25/canary-deployment-with-ingress-nginx.html)
- [Canary release based on Ingress-Nginx](https://kubesphere.io/docs/quick-start/ingress-canary/)
- [Canary …
=> Canary deployment setup

kubernetes/deployment-staging-azure-canary.tmpl
Accidentally removed the `---` when I removed the configmap def and only the ingress got deployed.
=> Add break between resource defs

kubernetes/deployment-staging-azure-canary.tmpl
The cookie annotation should take precedence over the weight, but just in case this is confusing things, let's remove it.
=> Remove the canary weight

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
allow serving requests proxied from the www.zooniverse.org domain without incorrect host name redirection. 
Extract the common nginx config blocks to it's own config map and reuse these across different server name blocks.
=> add www.zooniverse.org nginx server block

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Fixes bug Introduced in https://github.com/zooniverse/panoptes/pull/3439#discussion_r464427625
Avoid clobbering `/etc/nginx`, instead mount the shared config files via a sub directory in `/etc/nginx/shared`
=> Nginx panoptes shared conf files

kubernetes/deployment-staging-azure-canary.tmpl
Reverts zooniverse/panoptes#3442
We want the canary deploy to only be reachable via the cookie presence. Removing the weight will modify how the traffic is routed. 
We want the canary to only be reachable while the header is set, if it's missing we don't want traffic to hit the canary inadvertently.
=> Revert "Remove the canary weight"

lib/tasks/user.rake
> will there be a follow up PR to backfill the default and switch the default column value over? without it this might end up with inconsitent data `null, false, true`
_Originally posted by @camallen in https://github.com/zooniverse/panoptes/pull/3421/files_
=> Add NASA comms field backfill rake task

app/schemas/tutorial_create_schema.rb, app/schemas/tutorial_update_schema.rb, app/serializers/tutorial_serializer.rb, db/migrate/20200717155424_add_configuration_to_tutorials.rb, db/structure.sql, spec/controllers/api/v1/tutorials_controller_spec.rb
Closes #3296 
This PR adds the configuration JSON blob to tutorial resources. No changes here to the apiary file, as it looks like there is not a section there for the Tutorial resource.
=> Add Configuration Blob to Tutorial

kubernetes/deployment-staging-azure-canary.tmpl
> Canary rules are evaluated in order of precedence. Precedence is as follows: `canary-by-header -> canary-by-cookie -> canary-weight`
This will allow for the use of canary.pfe-preview.zooniverse.org to test the Azure media adapter via header. The cookie isn't being forwarded through PFE, so that staged brach uses a monkeypatched version of the client that always adds the `Canary: always` header to API requests.
=> Add Canary header to ingress config

.rubocop.yml, kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Update deployment templates to use `panoptesuploads` and `panoptesuploadsstaging` storage accounts.
Also update `rubocop.yml` to remove vs code warning "The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file ..."
------
=> Update storage accounts

.rubocop.yml
using the Gemfile robocop (0.87.1) I get, removing these fixes it. Noting i also get these errors with the latest version (0.89) https://rubygems.org/gems/rubocop/
```
Error: unrecognized cop Layout/EmptyLinesAroundAttributeAccessor found in .rubocop.yml, unrecognized cop Lint/DeprecatedOpenSSLConstant found in .rubocop.yml, unrecognized cop Lint/MixedRegexpCaptureTypes found in .rubocop.yml, unrecognized cop Style/AccessorGrouping found in .rubocop.yml, unrecognized cop Style/BisectedAttrAccessor found in .rubocop.yml, unrecognized cop Style/RedundantAssignment found in .rubocop.yml, unrecognized cop Style/RedundantFetchBlock found in .rubocop.yml, unrecognized cop Style/RedundantRegexpCharacterClass found in .rubocop.yml, unrecognized cop Style/RedundantRegexpEscape found in …
```
=> remove unrecognised cops in .rubocop.yml

kubernetes/job-rake-task-staging.tmpl
Add a k8s job template for running rake tasks, staging only right now.
=> add staging rake task job template

lib/subjects/postgresql_selection.rb, lib/subjects/selector.rb, spec/lib/subjects/selector_spec.rb
select from 100 subjects to increase the variance of available subjects when we return any subject data for a workflow selection.
=> increase fallback selection subject pool

kubernetes/deployment-staging.tmpl
ensure the HPA scaling metric is calculated correctly as we want to run 1 pod under low cpu conditions
target based horizontal pod autoscalers rely on the resource request for the percentage of use metric, thus previously this was using (avg sum CPU)/50Mi to calc the hpa cpu metric for scaling pods. Thus the HPA kept 2 pods running for this deployment
See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
=> increase sidekiq staging cpu resource request

app/services/media_storage/azure_adapter.rb, config/initializers/storage.rb, kubernetes/deployment-staging-azure-canary.tmpl, spec/services/media_storage/azure_adapter_spec.rb
Azure Adapter: 
Construct `stored_path` without env prefix.
`media.src` attributes (in the database) will now look something like this:
`subject_location/7c669787-2677-40ce-90bc-5d3ef185863d.jpeg`
`project_avatar/1adcb95b-06bf-4f84-ab83-530c1df7c086.jpeg`
In leu of using the env prefix, we will have two CDN domains, one for prod and one for staging:
staging: `panoptes-uploads-staging.zooniverse.org`
production: `panoptes-uploads.zooniverse.org`
We will store the respective domain URLs in the `STORAGE_URL` env var. We'll also include the container name in the `STORAGE_URL` env var, so it'll look like `panoptes-uploads-staging.zooniverse.org/public`, etc.
The azure adapter `get_url` method will call the `StoredPath` class, which will use the correct domain to construct the URL at which the …
=> Azure adapter: remove env prefix from stored path

kubernetes/deployment-staging.tmpl
ensure a better scaling metric for the staging api app hpa, ensure the HPA metric used for scaling up the app has a more robust denominator for the target comparison. 
E.g. 40M/50M = 80% whereas 40/100M = 40% (40M is not very busy)
=> increase staging app cpu request

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
save on CPU and memory in the k8s cluster. Allow sidekiq prod to scale down to 1 pod when it's not busy and allow the HPA to scale the pod replicas up when needed
=> decrease min pod replica count for sidekiq prod

kubernetes/deployment-production.tmpl
ensure we have at least 1 sidekiq pod running in the k8s cluster
when i was upgrading the nodepool today i managed to evict these pods and they couldn't reschedule due to limits on the available node pool (autoscaler didn't kick in) so sidekiq was down for 30 mins
this PDB should alleviate this issue as when draining nodes, the pods won't evict till rescheduled properly all without service downtime
=> add sidekiq pod disruption budget

kubernetes/deployment-staging-azure-canary.tmpl
Update `STORAGE_URL` env var to our custom domain https://panoptes-uploads-staging.zooniverse.org. DNS and Front Door have been set up and tested for this domain, it correctly redirects to https://panoptesuploadsstaging.blob.core.windows.net/public.
=> update storage url to zooniverse custom domain

lib/subjects/fallback_selection.rb, spec/lib/subjects/fallback_selection_spec.rb
by default provide at least 1 training subject for every 10 real subjects in fallback selection
avoid showing the user mostly training subjects
=> control ratio of real and training subjects in fallback selection

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
avoid hard coding the number of PDB replicas, instead use a percent of the available replicas https://kubernetes.io/docs/tasks/run-application/configure-pdb/
This allows more lenient eviction rules for the relevant pods. I came across pods that wouldn't evict due to the PDB settings when doing the cluster / node pool upgrades the other day. Specifically from https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
> If you set maxUnavailable to 0% or 0, or you set minAvailable to 100% or the number of replicas, you are requiring zero voluntary evictions. When you set zero voluntary evictions for a workload object such as ReplicaSet, then you cannot successfully drain a Node running one of those Pods. If you try to drain a Node where an unevictable …
=> Modify the production & staging pod disruption budgets (pdb)

app/models/workflow.rb, spec/models/workflow_spec.rb
related to #3486 - @mwalmsley found that he could enable fallback selection for subject sets that were no longer actively linked to the workflow.
This PR fixes the found bug by ensuring the `workflow.training_set_ids` method returns the intersection of workflow config `training_set_ids` and the currently linked `subject_set_ids`. This ensures the configuration directive doesn't allow selection of non linked sets.
=> ensure training_set_ids respect the linked set ids

app/services/media_storage/azure_adapter.rb, app/services/media_storage/stored_path.rb, config/initializers/storage.rb, spec/services/media_storage/azure_adapter_spec.rb, spec/services/media_storage/stored_path_spec.rb
Add method for getting just the media path to the StoredPath module. For use by the azure adapter. This will fix requests for private media items stored in azure.
-----
=> extract azure path from s3 url for private media

app/services/media_storage/azure_adapter.rb, app/services/media_storage/stored_path.rb, spec/services/media_storage/stored_path_spec.rb
We were previously using string concatenation to join the container name to the path:
https://github.com/zooniverse/panoptes/blob/4e1add082c779f3f7bc227cae83c37de1a537506/app/services/media_storage/azure_adapter.rb#L38
In the case of old S3 URLs, this resulted in a path with a double slash, e.g. `https://panoptesuploadsstaging.blob.core.windows.net/private//project_workflows_export/b8821786-f1a4-495e-9fc5-119c01680d5e.csv?sp=r&sv=2017-11-09&se=2020-11-06T19%3A09%3A54Z&sr=b&sig=IZE60%2B2swS2NCWi%2F065lFDr3T2hYaQb9NkoJDbVjrO4%3D`. Use File.join instead of string concatenation to avoid this issue.
Also updated `StoredPath` to use regex matching to remove the `/` at the beginning of the path if present, so that `#media_path` returned path with consistent format no matter whether we passed in …
=> Fix double slash issue in export URLs

kubernetes/deployment-production-azure-canary.tmpl
Like in the staging canary template, the k8s template for the production canary deployment includes definitions for the deployment, the service and the ingress.
I'm thinking that giving it the same resource allocation (memory/CPU) as the staging canary should suffice, since the canary deploy will only be touched by our team. Let me know if you disagree.
Once this PR is deployed, a CDN record and Front Door for the canary production URL needs to be created (akin to https://canary.pfe-preview.zooniverse.org/). URL will be https://canary.zooniverse.org.
-----
=> add production canary deploy template

kubernetes/deployment-production.tmpl
increase the capacity for the issues caused by the kinesis errors
=> temp bump to 2 sidekiq replicas

docs/source/includes/_subject_set_imports.md
update the LSST subject set import docs, deployed at https://zooniverse.github.io/panoptes/#subjectsetimports
=> build on the existing docs for LSST use case

scripts/docker/start.sh
closes #3516 
Use a more aggressive exporter artifacts cleanup in /tmp. avoid these exports filling up our tmp disks and causing more errors
Linked to https://app.honeybadger.io/projects/40595/faults/70494224
=> cleanup left over tmp files every 6h

kubernetes/deployment-production.tmpl
This PR adds a new Kubernetes ingress for `www-panoptes.zooniverse.org`
- This PR is part of a solution for https://github.com/zooniverse/operations/issues/459#issuecomment-726289233
- The `www-panoptes.zooniverse.org` ingress is unique in that it adds a proxy-header to login requests from oAuth apps
- A new Certificate resource is added to the deployment template, _https://_ www-panoptes.zooniverse.org
- `rewrite-target` logic isn't used in the new ingress block
- The Certificate resource doesn't need `use-azuredns-solver: "true"` unlike in other current configurations
- Rules for adding custom NGINX upstream vhost: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-nginx-upstream-vhost
- Correct syntax for `proxy_set_header Host`: …
=> Add Panoptes (production) ingress for www-panoptes.zooniverse.org

kubernetes/deployment-production.tmpl
Updated env vars `STORAGE_ADAPTER` and `STORAGE_URL` - once this is deployed, the panoptes production app will start using the azure adapter.
-----
=> Cutover production to use Azure Blob Storage

app/serializers/organization_serializer.rb, app/serializers/project_serializer.rb, spec/serializers/organization_serializer_spec.rb, spec/serializers/project_serializer_spec.rb
ensure the special card routes have the updated avatar src urls (rewritten) via azure storage adapter.
Since we've modified how the panoptes-upload URLs work we need to avoid serializing the linked avatar URL path directly from the `model.src` attribute. Instead use custom Media storage adapter (Azure in this case) for rewriting the staging `src` attributes to `panoptes-uploads-staging` domain and stripping the `/production` paths on the `panoptes-uploads` domain.
=> use the medium get_path url for avatars

app/operations/subject_groups/create.rb, spec/operations/subject_groups/create_spec.rb
don't nest an object as this may not be handled by PFE correctly as it assumes non nested objects. Ensure these metadata values are hidden in the PFE / FEM interface as they are meant for internal use only (avoid confusing volunteers)
=> ensure hidden subject metadata on the group subject

lib/tasks/migrate.rake
Closes #3539 
Rewrite `src` attribute of export media records in order to resolve https://github.com/zooniverse/panoptes/issues/3539
Reasoning behind this choice explained [here](https://github.com/zooniverse/panoptes/issues/3539#issuecomment-754123093).
The new task will remove `panoptes-uploads.zooniverse.org/{env}/` from the src path. I have tested the rake task locally with manually generated media records, we will also be able to test on staging to confirm that the paths get updated as expected. Since we'll be able to test on staging, separating out the cases for each export type for testing is likely unnecessary, but feel free to comment if you think otherwise.
=> export media src rewrite

app/controllers/api/v1/subjects_controller.rb, spec/controllers/api/v1/subjects_controller_spec.rb
Closes #3551
- This PR adds "http_cache" to the list of acceptable parameters for the `/subjects/grouped` endpoint.
- The "http_cache=true" parameter is sent by the front end (Panoptes JS library) for pretty much most API calls, so this seems necessary.
Ready for review, contingent on the assumption that the http_cache wasn't excluded from the list of acceptable parameters on purpose.
=> Add http_cache parameter to SubjectGroup selection API

kubernetes/deployment-production-azure-canary.tmpl, kubernetes/deployment-staging-azure-canary.tmpl
add a replica directive to scale the prod & staging canary deployments to 0
=> scale the canary deployments to zero

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Let's encrypt cert expiry notifications led me to not find any cert resources for the panoptes ingresses. Luckily these are still valid and stored in the relevant secrets e.g. https://github.com/zooniverse/panoptes/blob/9f0d0e872be06409d67fdbcf8b6444584d95c9fc/kubernetes/deployment-production.tmpl#L517
Previously this worked due to the use of ingress annotations https://github.com/zooniverse/panoptes/blob/9f0d0e872be06409d67fdbcf8b6444584d95c9fc/kubernetes/deployment-production.tmpl#L507 
and the cert-manager shim would respect the annotations and configure a certificate in the defined secret, https://cert-manager.io/docs/usage/ingress/#how-it-works
However post the cert-manager upgrade these annotations are out of date so the cert manager doesn't recognise these anymore, see …
=> Use explicit certificate resource on ingresses

kubernetes/deployment-production.tmpl
ensure the www-panoptes ingress has a valid certificate. Putting all the dns domain on one cert clobbers if they aren't used on the same ingress, i.e. we lose www-panoptes.zooniverse.org on the cert.
I think this is related to the shim and the ingress `cert-manager.io` annotation but i'm not sure.
TBH It's explicit this way and most likely easier to track the certs and ingress domains as well.
=> split default and www-panoptes ingress certificates

app/operations/subject_groups/create.rb, app/operations/subject_groups/selection.rb, spec/controllers/api/v1/subjects_controller_spec.rb, spec/operations/subject_groups/create_spec.rb, spec/operations/subject_groups/selection_spec.rb
Linked to #3549 and #3550  add more checks and validation when creating the special `SubjectGroup.group_subject` Subject resource
Adds validations that the
- group we are creating matches our expected number of subjects
- group is bigger than 1 (else why are we creating a group?)
These will help with issues reported in the above issues where we are incorrectly creating groups
Finally there is a big bug fix in here that ensures we correctly create the `group_subjects` linked image media URLs in the order that they are supplied i.e. the subject ids match the linked images and they aren't mixed. Without this check we may actually show the incorrect image to the user and record the wrong subject ID in the downstream classification - which would corrupt the data and be a very bad thing. 
FWIW …
=> Subject groups creation bug fixes

.travis.yml
ensure the next ruby version (2.6) specs can run against a known test db in travis
=> add db env var for ruby 2.6 job

Gemfile, Gemfile.lock
Remove the sdoc gem - this has been around since the initial commit, i don't think it's used. 
Supersedes and closes #3526
=> remove sdoc gem

app/workers/medium_removal_worker.rb, spec/workers/medium_removal_worker_spec.rb
fixes the errors reported in https://app.honeybadger.io/projects/40595/faults/72161201
as our older s3 medium objects have different paths as what results in azure, we have to ensure we modify these paths to cleanup in azure correctly. 
Use the same path rewriter code as we do for the `adapter.get_paths` to determine which azure object store path we should attempt to delete.
=> rewrite the azure storage paths when cleaning up

app/operations/subject_groups/create.rb, spec/operations/subject_groups/create_spec.rb
Ensure we use the medium.get_url method (and thus the media storage service object) to construct the media location URLs for the SubjectGroup. Without using this change the URLs will be missing the domain prefix and won't be valid.
=> fix subject group media location URLs for Survos API

kubernetes/deployment-production.tmpl
Run only 2 dumpworker threads (2 x concurrent dumps can run) but increase the available RAM & CPU for each dump run.
If we find we need more compute we can scale the replica count to >2 for this dumpworker deployment.
=> [travis-ci skip] increase dumpworker pod RAM & CPU and decrease thread count

app/workers/medium_removal_worker.rb, spec/workers/medium_removal_worker_spec.rb
move on from any 404 errors (missing and probably not uploaded) but ensure we surface any unknown error codes (not 404)
related to https://github.com/zooniverse/panoptes/pull/3538#discussion_r547433486
I've monitored these errors in error tracking and sidekiq and we can safely ignore these now. There are all from failed uploads post our cloud migration, i.e. 404.
=> ignore cleaning up missing blobs in azure

lib/project_copier.rb, spec/lib/project_copier_spec.rb
Closes #3055 and #3126
Ensure we correctly setup the translations when copying a project. To do this we need to reset the string versions to `{}` before the copied project can be saved. After we have saved the project resource we will have a project_version resource, we then use that to update the translation `string_versions` resource to list out what strings belong to what project version.
The `string_versions` are used in the translations app to show what is out of date with the primary language resource.
=> fix translations when project copying

app/models/subject_set_import/csv_import.rb, app/services/url_downloader.rb, docs/source/includes/_subject_set_imports.md, spec/models/subject_set_import/csv_import_spec.rb, spec/models/subject_set_import_spec.rb
Update docs and fix the the Vera Rubin observatory (LSST) subject set imports via the API, specifically
- Update the docs to clarify the
- manifest csv file type
- external_id to track the external data IDs to Zooniverse subjects
- fix a bug when downloading the remote manifest file by using the correct variable name
=> improve API SubjectSetImports docs and fix end point bug

app/workers/subject_set_import_worker.rb, spec/workers/subject_set_import_worker_spec.rb
sync the subject set's subject counts after running the subject set importer
=> update the subject set subject counts post import

db/structure.sql, docker-compose.yml
Staging and production systems are running PG 11.  This PR updates the test / development env to use the 
- docker images `postgres:11`
- updates the structure.sql using the `pg_dump` v 11 format
The structure.sql format is mostly comment updates but has some slightly different index definitions for the indexes that use `gin_trgm_ops`, e.g.
```
CREATE INDEX index_collections_display_name_trgrm ON public.collections USING gin (COALESCE((display_name)::text, ''::text) public.gin_trgm_ops);
```
=> Upgrade pg version to match deployed databases

app/models/subject_set.rb, db/migrate/20210226173243_add_on_delete_constraint_to_subject_sets_import.rb, db/structure.sql, spec/models/subject_set_import_spec.rb, spec/models/subject_set_spec.rb
LSST folks are testing the subject set import functionality and after a successful import they can't remove the subject set.
Accordinly, this PR modifies the
-  `subject_set` to delete any linked `subject_set_imports` on destroy
-  `subject_set_import` FK constraints to `subject_set` table to `cascade delete` to ensure if a subject set is deleted the `subject_set_import` record is as well
=> Allow subject sets to be deleted if they are built by a subject set import

.rubocop.yml, app/controllers/api/v1/subjects_controller.rb, app/operations/subjects/selection_by_ids.rb, config/routes.rb, spec/controllers/api/v1/subjects_controller_spec.rb, spec/operations/subjects/selection_by_ids_spec.rb
Engaging Crowds project has a use case where the user selects a subject id from a UI component** and needs to convert this subject id into the subject selection response format for use in the classifier component. 
This PR adds a new endpoint to retrieve the subject selection response object for known subject ids e.g. 
`GET /api/subjects/selection?ids=1,2,3&workflow_id=1`
As this feature doesn't need to run the selection code (or call designator) we use an `Operation` class to ensure the list of subject ids param is valid and all the subjects belong the the supplied workflow. Once the operation has validated the list of ids the controller loads the active subjects from the database and then serializers these subjects using the `SubjectSelectionSerialzlier` as per the normal selection end …
=> Subject selection endpoint for known subjects

spec/workers/medium_removal_worker_spec.rb
cleanup a spec that tests not `raise_error` as this could fail due to other raises and best practice is to not specify a specific error when testing no raised errors.
=> remove specific error class on not raise_error

apiary.apib
cleanup the apiary docs for projects, remove unused / old attributes that can be confused with the project pages end points
=> remove old project attributes from apiary

app/controllers/api/v1/classifications_controller.rb
Some projects like https://www.zooniverse.org/projects/povich/milky-way-project/classify still use the old GS classification data model for wiring up the UI.
loading the user requires write access to the db, allow these to still work by loading the user outside the the read replica block
=> Fix gold standard classification UI loading for legacy projects

app/controllers/api/v1/workflows_controller.rb, app/operations/workflows/unretire_subjects.rb, app/policies/project_policy.rb, app/policies/workflow_policy.rb, app/workers/unretire_subject_worker.rb, config/routes.rb, spec/controllers/api/v1/workflows_controller_spec.rb, spec/operations/workflows/retire_subjects_spec.rb, spec/operations/workflows/unretire_subjects_spec.rb, spec/policies/project_policy_spec.rb, spec/support/pundit_scope_tester.rb, spec/workers/unretire_subject_worker_spec.rb
I believe this is in a good spot. Let me know if I missed cases.  Mainly followed `retire_subjects` path as a guide. 
**Changes**
- creating a new route to unretire subjects by workflow_id.. route is `/api/workflows/YOUR_WF_ID/unretire_subjects` 
-  updated corresponding controller for route action 
- creating operator that calls an UnretirementSubjectWorker
- created UnretirementSubjectWorker that sets the `retired_at` and `retirement_reason` to nil 
**TODO**
=> Allow subjects to be unretired

app/controllers/api/v1/workflows_controller.rb, app/operations/workflows/unretire_subjects.rb, spec/operations/workflows/unretire_subjects_spec.rb
**Changes**
- update unretire subjects by subject set id (updating corresponding operation to grab subject ids from subject set id and then send it over to the worker.)
=> Unretire subject by subject ids

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Update the K8s pod CPU and RAM limits and modify how the HPA works to have a more stable service and less scaling events. linked to https://github.com/zooniverse/talk-api/pull/264
All values for new requests and limits are based on value inspection from the following cmd to inspect the history of the deployment pods `kubectl top pod --containers | grep panoptes`
Specifically this PR introduces these changes:
- modify the API RAM and CPU requests and limits
- modify the sidekiq pods to request less RAM and decrease their limits now the exports run on their own deployment
- modify the dumpworkers ram requests to allow less pressure on node scheduling 
- increase the replica counts for API and sidekiq pods for spare capacity to soak up spiky load and decrease scaling events
- removed the …
=> Optimise pod limits & requests and hpa scaling

app/schemas/project_preference_update_schema.rb, spec/controllers/api/v1/project_preferences_controller_spec.rb
linked to https://github.com/zooniverse/Panoptes-Front-End/pull/5908
allow user project pref settings json to have an updatable hidden boolean attribute. This attribute will be used by the UI to filter prefs for display and will allow users to choose to hide certain project prefs
=> add hidden boolean field to settings object in user project pref update schema

kubernetes/deployment-production.tmpl
setting these too high means the pod can't schedule on our nodes, e.g.
"Warning  FailedScheduling  2m22s  default-scheduler   0/6 nodes are available: 1 node(s) had taint {servicelife: longlife}, that the pod didn't tolerate, 5 Insufficient cpu."
prod sidekiq dumpworker can be set low as it doesn't have an autoscaler that uses these request values
prod sidekiq uses the request values to trigger scaling events, set this lower to allow scheduling but know that this will cause pods to come up and down with load - note these aren't service pods so shouldn't have any impact with the nginx ingress.
=> tweak sidekiq worker cpu request values

app/services/designator_client.rb, spec/services/designator_client_spec.rb
closes #3630 
Preserve the subject_set_id in the selector client calls to ensure we only select subjects from the specified group
linked to the designator API change in https://github.com/zooniverse/designator/pull/74
=> add per subject_set selection to the designator client

app/controllers/api/v1/subjects_controller.rb, spec/controllers/api/v1/subjects_controller_spec.rb
Allow the 'admin' query param to avoid 422 errors as sometimes zoo team folks are in admin mode and the API returns 422s on these end points.
=> allow admin param for grouped and per subject end points

kubernetes/deployment-production.tmpl
i'm seeing the hpa max out with current traffic volumes (high number of incoming classification)
```
$kubectl describe hpa panoptes-production-sidekiq
...
Reference:                                             Deployment/panoptes-production-sidekiq
Metrics:                                               ( current / target )
resource cpu on pods  (as a percentage of request):  202% (1011m) / 95%
Min replicas:                                          2
Max replicas:                                          8
Deployment pods:                                       8 current / 8 desired`
```
this PR doubles the current HPA limit to 16 sidekiq pod replicas
=> double the number of sidekiq replicas

lib/workflow_copier.rb, spec/lib/workflow_copier_spec.rb
follow up to #3626 ensure we reset the workflow lifecycle state attribtues like counters and finished_at etc.
=> reset the counters and lifecycle state attributes

app/workers/project_copy_worker.rb, lib/project_copier.rb, spec/lib/project_copier_spec.rb, spec/workers/project_copy_worker_spec.rb
Ensure we don't break the translations.zooniverse.org app's expected data model when copying a template project's associated resources, e.g. `project.active_workflows`, `project.pages`, project.field_guides`
In the normal `CRUD` API landscape all translated resources will have these primary language translations setup correctly and the translations app relies on them being present. Thus we need to set these up when copying these template project and their translated association resources. 
Thus this PR syncs the default translation (primary language) strings from the copied association resource to the translation. It does not however copy any existing translations on these translated associations (`active_workflows`, etc). Long term this is probably desired but out of scope for this data …
=> ensure primary language resources are created for template project association resources

app/services/cellect_client.rb, app/services/talk_api_client.rb, kubernetes/deployment-staging.tmpl, spec/services/cellect_client_spec.rb, spec/services/talk_api_client_spec.rb
avoid routing traffic out of the k8s cluster by switching service URLs to their internal k8s service DNS names via HTTP. i.e. pod to pod in the cluster instead of via the ingress combined with TLS termination via HTTPS URL schemes.
see `kubectl get services` for the service DNS discover URLs
=> use internal service end points in k8s cluster

kubernetes/deployment-production.tmpl
Use the internal cluster service DNS via HTTP instead of using the external internet URLs (traffic leaves the cluster) with HTTPS.
Linked to #3642 - after testing this works correctly on staging we can use the same technique on production.
=> add internal prod service routes

kubernetes/deployment-staging.tmpl
This PR attempt to improve the k8s pod probes and isolate the rails and nginx pod probes. In theory this probe setup should provide better pod failure detection without forcing unnecessary pod restarts and thus service traffic loss at the ingress, we can iterate on these settings to improve any pod lifecycle behaviour changes.
This is a test for the staging service setup, once we've used this setup in staging we can revisit on production.
This PR specifically adds / improves the probes by:
1. increasing the response time from 1s to 10s to avoid pods failing probes / being restarted when busy
2. adds a `startupProbe` (allow max 60s boot time) for the rails app to avoid running the liveness probes on boot - https://v1-19.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-livenes …
=> Improve pod probes staging service

kubernetes/deployment-production.tmpl
linked to #3644 but for production panoptes pod containers. 
This PR attempt to improve the k8s pod probes and isolate the rails and nginx pod probes. In theory this probe setup should provide better pod failure detection without forcing unnecessary pod restarts and thus service traffic loss at the ingress, we can iterate on these settings to improve any pod lifecycle behaviour changes.
These changes were tested on staging services via #3644 and worked well.
This PR specifically adds / improves the probes by:
1. increasing the response time from 1s to 10s to avoid pods failing probes / being restarted when busy
2. adds a startupProbe (allow max 60s boot time) for the rails app to avoid running the liveness probes on boot - https://v1-19.docs.kubernetes.io/docs/tasks/configure-pod-container …
=> Improve pod probes prod service

app/models/user.rb
this PR pushes to the replica DB the expensive count queries for how many subjects a user has uploaded to the system. These queries are only run when the cache is missing or invalid but these are serialized on the user resource and also used when determining if a user is over their upload quota.
=> read user subject upload counts from db replica

.rubocop.yml, app/controllers/api/v1/subject_sets_controller.rb, app/counters/subject_set_workflow_counter.rb, app/serializers/subject_set_serializer.rb, app/workers/retirement_worker.rb, app/workers/subject_set_completeness_worker.rb, app/workers/unretire_subject_worker.rb, db/migrate/20210729152047_add_workflow_completeness_to_subject_set.rb, db/structure.sql, spec/controllers/api/v1/subject_sets_controller_spec.rb, spec/counters/subject_set_workflow_counter_spec.rb, spec/serializers/subject_set_serializer_spec.rb, spec/workers/retirement_worker_spec.rb, spec/workers/subject_set_complenetess_worker_spec.rb, spec/workers/subject_set_completeness_worker_spec.rb, spec/workers/unretire_subject_worker_spec.rb
closes #3450 
This PR adds the ability to calculate the completeness of a subject set in the context of a workflow and record these completeness metrics on the `SubjectSet` resource in a json blob that is keyed by the workflow id. 
As a subject set can belong to many workflows in a project we need to record the completeness metrics for the SubjectSet in the context of these workflows. Specifically we need to calculate the ratio of the number of retired subjects in a set divided by the the number of subjects in a set, formula `completeness = total_retired_subjects_for_a_workflow_in_a_set / total_subjects_in_a_set`. 
Finally we clamp the completeness metric to a sensible range, 0.0 (0%) to 1.0 (100%) to ensure we display sensible numbers and avoid issues with incorrect numerators and …
=> Add SubjectSet completeness metrics

app/workers/retire_subject_worker.rb, spec/workers/retire_subject_worker_spec.rb
This PR changes the retirement worker to ignore any unknown subject ids passed in. Previously this would raise and error and stop processing the list of subjects we had for retirement. Thus 1 incorrect subject_id could break the retirement list processing at any point. 
I found this issue due to a failed (dead) job in sidekiq and some data debugging found 1 unknown subject id in the list. 
linked HB error https://app.honeybadger.io/projects/40595/faults/38047692
=> Handle unknown subjects in the retirement worker

app/models/csv_dumps/direct_to_s3.rb, app/models/csv_dumps/dump_processor.rb, app/models/medium.rb, spec/models/csv_dumps/direct_to_s3_spec.rb, spec/models/csv_dumps/dump_processor_spec.rb, spec/models/medium_spec.rb, spec/support/dump_worker.rb
This PR adds a retry mechanism around `put_file` on the Medium resource when uploading to the remote object store. 
When exporting data, the exports are created on the file system and the files have been compressed but when uploading to the object store (s3, azure blob, etc) the `put_file` call fails (e.g. `Faraday::ConnectionFailed: Connection reset by peer`) and the export never finishes and the UX shows broken export requests. 
The problem is outlined in this error https://app.honeybadger.io/projects/40595/faults/78910693
This error is transient thus we can't really predict the failure mode, thus using the retry mechanism seems a reasonable approach to attempt to avoid this error. Longer term having the our network or object store provider not error on upload seems a more reasonable …
=> Add retry mechanism when a medium uploads files to an object store

app/workers/subject_set_completeness_worker.rb, spec/workers/subject_set_completeness_worker_spec.rb
linked to #3450
avoid trying to set NaN values in the DB (0.0 / 0.0), instead raise a custom error which we may ingore longer term via HB via something like 
```
Honeybadger.configure do |config|
config.exceptions.ignore << SubjectSetCompletenessWorker::EmptySubjectSet
end
```
=> explicitly handle error when subject set is empty

app/graphql/json_type.rb, app/graphql/types/project_type.rb
Related to #3653 - app fails to boot due to deprecated type. 
This PR switches away from a custom JSON type to the one provided in the graphql gem - added in rmosolgo/graphql-ruby#2227
Tested locally and with this patch the app now boots
=> Use explicit json type graphql

app/counters/subject_set_workflow_counter.rb, spec/counters/subject_set_workflow_counter_spec.rb
ensure we only count retired subjects in the subject set, not all subjects that are linked to a workflow
=> only count subjects that are in the subject set

.rubocop.yml, app/models/subject_set_import.rb, app/models/subject_set_import/processor.rb, app/workers/subject_set_import_worker.rb, spec/models/subject_set_import/processor_spec.rb, spec/models/subject_set_import_spec.rb, spec/workers/subject_set_import_worker_spec.rb
A follow up to good questions in https://github.com/zooniverse/panoptes/pull/3706#pullrequestreview-780311850
This PR improves the SubjectSetImport behaviour by not failing on individual subject import errors but instead this system will now:
1. log the external UUID in the `failed_uuids` list on the SubjectImport model (accessible by the uploading user)
2. record the number of failed individual subject imports in the `failed_count` on the SubjectImport model
3. stop the import worker running multiple times when there is an error (avoid reprocessing)
=> Improve subject set import error handling

app/serializers/subject_set_serializer.rb
ID is auto incrementing so is a proxy for the created_at attribute but has an index, https://github.com/RestPack/restpack_serializer#sorting
Linked to https://github.com/zooniverse/Panoptes-Front-End/pull/6042
=> add subject_set id attribute sorting

app/controllers/api/v1/subject_sets_controller.rb, app/models/csv_dumps/classification_scope.rb, app/models/medium.rb, app/models/subject_set.rb, app/operations/create_or_update_medium.rb, app/policies/subject_set_policy.rb, app/workers/concerns/dump_mailer.rb, config/routes.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb, spec/models/csv_dumps/classification_scope_spec.rb, spec/models/subject_set_spec.rb, spec/policies/subject_set_policy_spec.rb, spec/support/dump_worker.rb, spec/support/pundit_scope_tester.rb, spec/workers/classifications_dump_worker_spec.rb, spec/workers/concerns/dump_mailer_spec.rb
Linked to the work in #3714 
This PR introduces the notion of classification exports at the subject set level. The subject set will now have it's own `classifications_export` resource link. This is created using the existing `CreateClassificationsExport` operation and the `ClassificationsDumpWorker` code.
=> Subject set level classification exports

app/operations/create_classifications_export.rb
linked to work in #3719 - ensure we preserve the model name correctly, to derive the object's type string when constantizing
=> correctly preserve the model type string when creating exports

app/workers/subject_set_completeness_worker.rb, db/migrate/20211124175756_add_completeness_to_subject_set_workflows.rb, db/structure.sql, spec/workers/subject_set_completeness_worker_spec.rb
This PR adds a completeness attribute to the `SubjectSetsWorkflow` resource (the join table between SubjectSets and Workflows) to track completeness outside of the subject set JSON attributes.
The join model is useful for looking up / searching the completeness state of a known subject set - workflow relation vs trying to look through the JSON data model in subject set.
=> Add completeness to subject set workflows

app/controllers/api/v1/projects_controller.rb, app/models/project.rb, app/models/subject_set.rb, app/schemas/project_create_schema.rb, app/schemas/project_update_schema.rb, db/migrate/20211201164326_add_project_run_subject_set_completion_events.rb, db/structure.sql, spec/controllers/api/v1/projects_controller_spec.rb, spec/models/project_spec.rb
Follow up PR to the good review points raised in https://github.com/zooniverse/panoptes/pull/3714/files#r760323485
This PR adds a `run_subject_set_completion_events` attribute to project model that defaults to false but can be set via the API by Zoo admins. 
This avoids the need for dev team involvement to activate the "set completion events feature" added in #3714 thus saving the team members time and increasing the turnaround time for project teams 🎉
=> Admin attribute run completion events

app/controllers/api/api_controller.rb, app/controllers/api/v1/projects_controller.rb, app/controllers/concerns/api_errors.rb, app/operations/projects/copy.rb, spec/controllers/api/v1/projects_controller_spec.rb, spec/operations/projects/copy_spec.rb
This PR is tied to work on the VRO platform where they will want to quickly spin up projects with existing content in them. As such they need to copy a template project but they need the copied project serialized in the json response so they can programatically interact with the newly copied project without having to search through a list of projects they have access to. 
Thus this PR
- adds an operation to call the ProjectCopier instance
- modifies the copier behaviour to be in-band (not async in a worker)
- serializes the newly copied resource via the HTTP 201 (created) response type
- allows the copier to create a new subject set resource during the copy - used for subsequent data uploads in VRO use case
=> Update project copy end point

app/controllers/api/api_controller.rb, app/controllers/api/v1/subject_set_imports_controller.rb, app/controllers/concerns/api_errors.rb, app/models/subject_set_import.rb, app/models/subject_set_import/csv_import.rb, app/operations/subject_set_imports/count_manifest_rows.rb, spec/controllers/api/v1/subject_set_imports_controller_spec.rb, spec/models/subject_set_import/csv_import_spec.rb, spec/models/subject_set_import_spec.rb, spec/operations/subject_set_imports/count_manifest_rows_spec.rb
This PR ensures we don't allow folks to create SubjectSetImport manifests over a row count limit and thus limit the number of subject records a user imports to a project at any given time (note: all subjects created by this import process are externally hosted).
It does this by counting the incoming manifest data rows before creating a SubjectSetImport resource, thus avoiding the poor UX of erroring while processing and orphaning an resource in an error state (there are no updates on that resource). 
Sadly this means we download the manifest twice**, once on validation check before we create / save the subject set import resource and once when processing. I think that's ok as they shouldn't be very large and the second download is robust via the worker retry mechanisms. 
** We can't pass …
=> Enforce 10k limit SubjectSetImport manifest uploads

app/models/subject_set_import.rb, spec/models/subject_set_import_spec.rb
ensure we cache bust the serializer to report the import progress
=> touch updated_at when saving the imported_row_count

app/controllers/api/v1/subject_set_imports_controller.rb, app/models/subject_set_import.rb, app/workers/subject_set_import_worker.rb, spec/models/subject_set_import_spec.rb, spec/workers/subject_set_import_worker_spec.rb
This PR introduces dynamic progress reporting when importing a manifest based on the manifest size. It balances the we balance useful progress reporting cadence against the cost of db updates.
=> Import manifest import progress reporting

app/models/user_seen_subject.rb, spec/models/user_seen_subject_spec.rb
This PR modifies the behaviour of how we track the subject ids a user has seen in the UserSeenSubject record. Specifically we now touch an existing uss record when we update the tracked subject_ids, this allows us to use the USS model as a proxy for when they've last seen a subject on a workflow.
Also this will switch to an explicit `first_or_create!` method to ensure we are still creating the record when we can't find it in the db.
=> track when a user has seen a subject

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
some classification payloads may be bigger than the k8 ingress default nginx payload size - http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-body-size
=> increase the client body payload max size

app/workers/publish_classification_worker.rb, spec/workers/publish_classification_worker_spec.rb
This PR introduces a change to avoid reporting kinesis publishing errors for some known projects via an 'ignore' list. 
This change came about as some projects don't use the downstream services (caesar etc) - these we can avoid noisy error reports by not reporting. Note all other kinesis publishing errors will be reported and we report all errors for projects that are not on the 'ignore' list
This will be useful to keep the error signal to noise ratio high for debugging possible issue with very large transcription payloads and our k8s nginx ingress.
=> avoid reporting kinesis payload error for specific projects

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
ignore known projects with large kinesis payloads to keep this error signal high
=> add k8s env vars for large kinesis payloads errors

app/serializers/subject_set_import_serializer.rb
Adds the `failed_count` attribute to the SubjectSetImport resource serializer. This allow teams to monitor the number of failed records on import.
=> add failed_count to SubjectSetImport serializer

app/controllers/api/api_controller.rb, app/operations/subject_set_imports/count_manifest_rows.rb, app/services/url_downloader.rb, spec/controllers/api/v1/subject_set_imports_controller_spec.rb, spec/operations/subject_set_imports/count_manifest_rows_spec.rb
Add error handling when a manifest source URL can not be downloaded
=> Handle non public subject import manifests

kubernetes/deployment-production-azure-canary.tmpl, kubernetes/deployment-production.tmpl, kubernetes/deployment-staging-azure-canary.tmpl, kubernetes/deployment-staging.tmpl
This PR updates the version of the nginx reverse proxies to 1.20 stable
Linked to https://github.com/zooniverse/docker-nginx/pull/3
=> use latest zooniverse nginx base image

app/workers/emails_export_worker.rb, spec/workers/emails_export_worker_spec.rb
This PR adds the ability to auto export the nasa email list from the user email subscription settings.
=> auto export nasa email lists

.github/workflows/run_tests_CI.yml
this removes an extraneous `rake db:setup` cmd copied from talk-api setup that doesn't apply here.
=> remove unused db setup cmd

app/models/csv_dumps/finds_medium.rb, spec/models/csv_dumps/finds_medium_spec.rb
fixes #3810 
Ensure we set the subject set display name as part of the file export name via the the content-disposition header for per subject set classification exports. 
This PR adds the SubjectSet resource to the lookup types for setting the content disposition and in turn ensures the value is set on the uploaded object store resource to be used when downloading.
=> use set display name for naming the export file

config/environments/production.rb, config/environments/staging.rb
linked to https://github.com/zooniverse/caesar/pull/1382 - fix the graphiql asset compilation issue
=> uglifier without mangle for asset compilation

app/graphql/types/query_type.rb
this PR fixes the graphql organisation scope lookup methods - they were never ported to use the new Pundit policy scope system.
=> switch to Policy scope lookup

app/mailers/subject_set_import_completed_mailer.rb, app/views/subject_set_import_completed_mailer/notify_project_team.text.erb, app/workers/subject_set_import_completed_mailer_worker.rb, app/workers/subject_set_import_worker.rb, spec/mailers/subject_set_import_completed_mailer_spec.rb, spec/workers/subject_set_import_completed_mailer_worker_spec.rb, spec/workers/subject_set_import_worker_spec.rb
The Vera Rubin team wants to have an email run letting the project team know when the subject set import (manifest) has been processed. 
This PR introduces a `SubjectSetImportCompleted` mailer with the success / failure status of the subject set import resource. This email is sent after the manifest has imported and is run via an async worker.
=> Email notification for subject set manifest import success / failure

app/controllers/api/v1/subjects_controller.rb, spec/controllers/api/v1/subjects_controller_spec.rb
fixes  #3832
fixes a bug introduced in #3815 - this PR will now skip the metadata reserved key transform when metadata params are not present in the update action.
=> fix metadata reserved keys transform

.github/workflows/run_tests_CI.yml, config/environments/test.rb
avoid rails file logging in test CI runs - should help speed up the CI test suite
https://test-prof.evilmartians.io/#/recipes/logging
Slight speed up observed in test runs from ~10-30s depending on which spec group runs, see actions for details.
=> remove rails logging in CI

app/operations/subject_set_imports/count_manifest_rows.rb, spec/operations/subject_set_imports/count_manifest_rows_spec.rb
This PR ensures the subject set manifest import `source_url` param is validated as a URL format vs a normal string. Instead of 500 erroring this will now return a useful error message to the client notifying them that the `source_url` param is invalid
=> Manifest source url input validation

kubernetes/deployment-production.tmpl
Linked to #3841 - turn off sidekiq logs being sent to new relic in production
=> disable sidekiq new relic logging in prod

spec/controllers/api/v1/project_roles_controller_spec.rb
fix the failing rails 5 spec for project roles controller
=> fix ProjectRolesController spec failure

app/models/membership.rb, app/models/organization.rb, app/models/project.rb, app/models/subject.rb, app/models/workflow.rb
follow up to #3865 remove the related but unused model scopes
=> remove unused http cacheable scoped

app/controllers/api/v1/organizations_controller.rb
This PR updates Organization create and update controllers to convert the rails 5 `ActionController::Parameters` to hashes for use in the relevant create and update organization operations (these expect hashes not a ActionController params object).
Note in for rails 4 versions calling `.to_h` on a hash is a no-op that returns self, https://ruby-doc.org/core-2.5.9/Hash.html so this should be an inexpensive change to make, either it passes the hash through (rails 4) or converts to hash before the operation runs (rails 5).
=> convert ActionController::Parameters to hash for operation schema

app/controllers/api/v1/subjects_controller.rb, app/models/subject.rb
This PR fixes the subjects controller spec for the rails 5 upgrade. 
Similar issues as faced in #3868 we need to convert the `ActionController::Parameters` to a hash for us in the operation class and we also needed to allow the `ActionController::Parameters` for the subject locations params building method `location_attributes_from_params`
=> Fix subjects controller spec rails5

spec/controllers/api/v1/project_preferences_controller_spec.rb
rails 5 leaves the values intact but converts the keys to strings. however rails 4 converts the values and leaves the keys intact.
fix this spec but take note - it shouldn't really matter but may change some jsonb stored values.
=> rails5 project preferences spec fix -convert params hash value to string

README.md
This PR adds instructions for running the switching to rails 5 install of the app vs using the next bin cmd. For some reason outside of docker the next shell script doesn't work, thus we can avoid it an override the gemfile env var to determine the version of next gems.
=> switch instructions to use the BUNDLE_GEMFILE env var for env dual boot

lib/gem_ext/rails/query_methods.rb
this PR adds a comment to let folks know this AR library extension code (added AR scope `.or` methods in rails 4.2) can go once we've landed on rails 5.0+
=> add removal note on AR lib extension post landing rails 5.0

app/controllers/concerns/polymorphic_resource_scope.rb
convert the params to a string before splitting them to id lookups. 
Rails 4 controller tests used to parse the params to strings however rails 5 leaves them intact. This PR ensures we are working with string id lookups at all times irrespective of the test setup (request vs controller etc)
=> ensure the id params are converted to strings for lookup

spec/controllers/api/v1/workflows_controller_spec.rb
This PR fixes the failing workflows to tutorials controller linkage spec - ensure we test the relation links on the reloaded resource at the controller spec, not the original one with the empty relation.
=> test the relation link on the reloaded resource

spec/controllers/tokens_controller_spec.rb
change controller request specs to use string keys as symbol keys aren't parsed correctly
=> ensure we use strings param keys

spec/lib/user_info_scrubber_spec.rb
this PR switches from the implicit to an explicit expectation block and fixes noisy deprecation warnings in test runs
=> switch to explicit block expectation

.github/workflows/deploy_staging_canary.yml
The `tag:` option on the `docker/build-push-image` requires the full image path: registry/user/repo:tag.
=> Use whole path to image in tag

config/application.rb, config/cache_store.rb
This PR adds the new rails5 / dalli gem configurations for setting up rails memcached caching systems while still allowing the rails 4 version of the app to configure the old version of the rails caching system and dalli client.
=> add rails5 memcached configs

kubernetes/deployment-staging-canary.tmpl
Remove the canary weight 0 setting as it was stopping traffic from being routed to the canary, https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary
Note: I've manually applied this change to the ingress to ensure traffic routes correctly. 
I also manually removed the old duplicated staging azure-canary-ingress setup `kubectl delete ingress panoptes-staging-azure-canary-ingress` as it was conflicting with the new `panoptes-staging-canary-ingress` configs.
=> allow the canary to route traffic via the header setting

app/models/subject_set_import/csv_import.rb
Updating methods due to deprecation warning: 
` /rails_app/app/models/subject_set_import/csv_import.rb:23: warning: Enumerator.new without a block is deprecated; use Object#to_enum`
=> Enumerator.new without block is deprecated use Object.to_enum instead

app/controllers/api/v1/classifications_controller.rb, app/controllers/api/v1/field_guides_controller.rb, app/controllers/api/v1/memberships_controller.rb, app/controllers/api/v1/tutorials_controller.rb, app/controllers/application_controller.rb, app/controllers/applications_controller.rb, app/controllers/concerns/pages.rb, app/controllers/concerns/preferences_controller.rb, app/controllers/concerns/roles_controller.rb, app/controllers/sessions_controller.rb, doc/pundit.md
`DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.`
`DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead.`
`DEPRECATION WARNING: prepend_before_filter is deprecated and will be removed in Rails 5.1. Use prepend_before_action instead.`
`DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead.`
=> before_filter replaced with before_action

Gemfile, Gemfile.next.lock, spec/controllers/applications_controller_spec.rb, spec/controllers/authorizations_controller_spec.rb
Remove the https://github.com/rails/rails-controller-testing gem
Avoid controller testing features removed in rails 5.0 that were re-added using this gem. Instead test the controller calls the relevant objects on state setup and avoid testing render template actions - instead test the controller response status.
=> remove rails-controller-testing gem

.github/workflows/deploy_staging.yml, .github/workflows/deploy_staging_canary.yml, kubernetes/deployment-staging-canary.tmpl
Follow up to #3911 - after more reflection on the staging rails 5 deploy changes I believe we introduced another possible deployment bug in #3911.
Re using the GH sha id after a production deploy would build a new image and update the container registry at that tag (prod would have a rails 4 gemfile build). The means that the existing staging deploy at the same sha id would be overwritten and would not include the rails 5 gem versions built for the staging deploy, rather it would have the production rails 4 versions :(
This would only happen if the production tag and the GH master branch head were the same (i.e. no changes on master) and the staging system redeployed to a node without the existing rails 5 staging image on it, thus it would pull down the prod rails 4 version and boot …
=> isolate rails 5 staging deploy from prod deploys

Dockerfile.dev
remove the docker build caching - this was added to speed up builds but we don't need it.
=> remove docker build caching

config/environments/test.rb
log less data with less IO work should speedup the CI suite runs - https://guides.rubyonrails.org/debugging_rails_applications.html#log-levels
=> switch to fatal log level to avoid IO in CI

.github/workflows/run_tests_CI.yml
As we aren't testing any gem upgrades (e.g. rails 5.1) the Gemfile and Gemfile.next are the same - thus the CI tests for Gemfile.next don't need to be run. Lets save on GH compute and test CI runtime by not running these tests till we need them.
When we create a PR to upgrade a gem using the Gemfile.next technique (e.g. rails 5.1 in #3940) we will need to re-enable these CI Gemfile.next test runs by removing this commented line
=> disable the Gemfile.next CI tests when there is no upgrade happening

app/workers/concerns/rate_limit_dump_worker.rb, spec/support/rate_limit_dump_worker.rb
This PR is a fix for the automated subject set export functionality added in #3714
Specifically the issue is the congestion rate limiter raises an error when running and stops all jobs linked to it. this issue is due to the special internal user id in https://github.com/zooniverse/panoptes/blob/581ad45e99bc88826dba32aa4978533c21a6d8c9/app/operations/subject_sets/run_completion_events.rb#L26-L29
As we use a special internal user (id=-1) to internally trigger the classification so we can't raise and AR not found error, rather in this PR we catch this error and use the special id to setup congestion rate limiter key and carry on with the rate limiter middleware / job.
=> allow unknown user ids to trigger the congestion rate limiter

app/workers/calculate_project_completeness_worker.rb, spec/workers/calculate_project_completeness_worker_spec.rb
linked to #2492 
this PR switches the project completeness metric from the average of all workflow completion metrics to a proportional metric derived from the number of subjects in a workflow. 
```
E.g. for a project with 2 active workflows this new behaviour results in 
workflow_1 = { completeness: 0.5, subjects_count 100, retired_subjects: 50 } 
workflow_2 = { completeness: 0.9, subjects_count 900, retired_subjects: 810 } 
workflow_1.proportional_completeness = 0.5 (100 / 1000) = 0.05
workflow_2.proportional_completeness = 0.9 * (900 / 1000) = 0.81
project.completeness = 0.86 - more accurate
(0.5 + 0.9) / 2 = 0.7 
project.completeness = 0.7 - not accurate
```
This is because the average metric doesn't factor the proportion of the subjects that each workflow is responsible for and can …
=> switch to proportional project completeness metric

app/workers/calculate_project_completeness_worker.rb, spec/workers/calculate_project_completeness_worker_spec.rb
related to the changes in #3950 switch back to `.to_f` metric representation for the workflow completion and the summed metric to avoid loss of precision via `.to_d`
This fixes the issue with completed projects not moving to the paused state as reported in https://www.zooniverse.org/talk/14/2620044?comment=4287231&page=1
=> switch back to float calculation for completeness metrics

app/workers/calculate_project_completeness_worker.rb, spec/workers/calculate_project_completeness_worker_spec.rb
Follow up to #3950 and #3952 and specifically https://github.com/zooniverse/panoptes/pull/3950#issuecomment-1263051646
This PR changes the way we summate project completeness metrics to avoid issues with FP precision. 
Sometimes the calculation loses / accretes precision due to floating point arithmetic. To avoid this issue we can simple round the summated value to a significant  number of digits (4 by default). This PR provides an env var to change the rounding precision at runtime as needed to avoid code changes.
=> round the project completeness metric to avoid FP precision issues

lib/gem_ext/gem_ext.rb, lib/gem_ext/rails/strong_parameters.rb, spec/controllers/api/v1/workflows_controller_spec.rb
related to #3113 and closes #3960 
The client payload for steps attribute contains nested arrays with json objects. Strong params fails to permit these via the explicit allowlist via `permit!` in our params validator in https://github.com/zooniverse/panoptes/blob/8cfcace49491a4017bfcd017cb95fa0a85f39bcd/lib/json_api_controller/json_schema_validator.rb#L42
This is a rails fraemwork issue that was fixed in 5.2+ https://github.com/rails/rails/pull/23650 so i've backported that fix and added specs on this.
=> fix strong params nested array objects being unpermitted

Gemfile, Gemfile.lock, app/models/set_member_subject.rb, app/policies/aggregation_policy.rb, app/policies/membership_policy.rb, lib/subjects/postgresql_in_order_selection.rb, lib/subjects/postgresql_random_selection.rb, lib/subjects/postgresql_selection.rb
This PR switches the pg subject selection code** from using nested subqueries to find the available pools of subjects to using postgres [CTE](https://www.postgresql.org/docs/current/queries-with.html) queries. This removes the need for custom AR version scoping code and should be faster (benchmarks needed!)
It uses a new PG query [extensions gem ](https://github.com/georgekaraszi/ActiveRecordExtended#common-table-expressions-cte) in place of an older union query gem - it provides a suite of new features and is compatible with rails 5+ and is maintained. 
**used when external subject selector service ([designator](https://github.com/zooniverse/designator/)) is not available
In the benchmarking below it appears that the CTE version is slightly quicker (use total not real values) but there …
=> Refactor pg selection code to use CTEs instead of subqueries

app/controllers/api/v1/media_controller.rb
media routes declare allowed polymorphic resources for use in routes and these are constrained to certain resource names, https://github.com/zooniverse/panoptes/blob/5b0cbf938e1e33830ec4204778aa0c6c9f5030bc/lib/routes/json_api_routes.rb#L34
This PR avoids any possible code injection we avoid using those params and instead rely on an allow list in the media controller. 
Longer term that means if we add new media resources in routes we have to declare them in this controller file as well to ensure they work and not error.
=> explicit avoid code injection via media_route params

app/controllers/api/v1/projects_controller.rb, spec/controllers/api/v1/projects_controller_spec.rb
related to https://github.com/zooniverse/Panoptes-Front-End/pull/6212#discussion_r994067886
This PR ensures we use an array form for the project's workflow links when using the `update_links` controller paths and the relation manager. Thus we avoid clobbering a project's existing workflow links as we never want to lose existing workflows on a project. 
FWIW - I can't see a use case where a client would want to clobber the existing workflow links but we will see if any bug reports come in and Hyrum's law kicks in https://www.hyrumslaw.com/
=> avoid clobbering a project's existing workflows when updating links

lib/json_api_controller/updatable_resource.rb, spec/controllers/api/v1/workflows_controller_spec.rb, spec/support/updatable.rb
This PR introduces a change to controller `update_links` behaviours where we ensure always modify the `resource.updated_at` value. 
When we `save` the resource we need to ensure we modify the cache key (cache bust) on the linking resource so we generate a new serialization response that includes the update_link operations results. As such we run `resource.touch` if the save operation had no changes (no update issued) and we modify the `updated_at`.
=> touch the resource we are linking to on update_links

spec/controllers/api/v1/projects_controller_spec.rb, spec/controllers/api/v1/workflows_controller_spec.rb, spec/support/updatable.rb
=> Rails 5.1 update failing update_links tests with params key

spec/models/user_spec.rb
update user_spec with update_ouroboros_created with stubs to test if method gets called instead of using db transaction checks due to issues testing active record callbacks
=> Rails 5.1 (test fixes) update user_spec with update_ouroboros_created with stubs 

db/structure.sql
This PR udpates the DB's sql representation after the rails 5 upgrade. We need to adopt and isolate these changes so future migrations only have the relevant changes.
=> update sql schema post rails 5 upgrade

db/migrate/20221018032140_update_workflows_add_first_task_default_value.rb, db/structure.sql
related to the changes in https://github.com/zooniverse/Panoptes-Front-End/pull/6217 
This PR ensures that the workflow's `first_task` attribute is always set to a default, not null value, i.e. ''. 
I've included the changes in #3977 here and once that is in i'll isolate the changes to only include the relevant migration commit and decrease the noise in the `structure.sql` file to only include the changes this migration brings in.
=> Add first task default

app/controllers/api/v1/workflows_controller.rb, spec/controllers/api/v1/workflows_controller_spec.rb
Follow up to #3978 and related to fixes in https://github.com/zooniverse/Panoptes-Front-End/pull/6217
This PR ensures we don't set tasks to a null value on create action as the `TasksVisitors::ExtractStrings` class returns nil if there is no task params to process. Instead of setting explicit values (even defaults) all the db defaults to kick in and avoid any possible incompatible states we have with the `workflow_versions` table (as it has a not null constraint on these fields).  
It seems the workflow db table is missing a lot of not null constraints but it does have column defaults which should take care of this issue. However explicitly setting values to nil will skip the db defaults so it's best to avoid setting missing values and allow the db defaults to kick in.
=> only update wf tasks when param is present

.github/workflows/deploy_staging.yml, .github/workflows/deploy_staging_canary.yml, kubernetes/deployment-staging-canary.tmpl
Upgrade staging to Rails 5.1 for team testing and sidekiq worker/s testing 
- update GH deploy staging action to use the -next commit_id tags
- update canary kubernetes template to set replicas to 0
=> Upgrade staging to Rails 5.1 for team testing

lib/inaturalist/api_interface.rb
Keeping the observations cached seemed like a good idea at the time, but the iNat API responses are so huge that holding on to them was causing the memory usage to spike and `exit code 137` the pod. Tests showed that without the cache, mem usage plateaus around 400-500MB but still rises very slowly. Further testing with extremely large datasets (150k+) is required to make sure that it doesn't hit the 700MB limit on staging. If it does, options are "get better at ruby memory management" or "bump the staging dumpworker pod memory limit to compensate", depending on how egregious it is.
=> Remove memory-eating cache from iNat API interface

app/workers/inat_import_worker.rb, spec/controllers/api/v1/inaturalist_controller_spec.rb
More than one job per set of args shouldn't be allowed to run at once. This is difficult behavior to spec, see https://github.com/mhenrixon/sidekiq-unique-jobs#uniqueness
> It is recommended to leave the uniqueness testing to the gem maintainers. 
Because of how the controller gives back a 200 immediately and the job is queued, SubjectSetImport is created, all in the background with no ability to track progress at the moment, so it's important that that request is idempotent. I'll give it a spin with a small set on staging to make sure.
also included an unrelated extra spec I thought of 🙃
=> Add uniqueness constraint to iNatImportWorker jobs

app/models/concerns/ordered_locations.rb, config/environments/test.rb, spec/support/ordered_locations.rb
fixes a 5.2 -> 6.0 deprecation warning about sql code injection in order by clauses.
=> Remove deprecation warning in ordered locations

config/initializers/cors.rb, kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl, spec/requests/v1/api_cors_headers_spec.rb
allow us to block specific domains from CORS API access via a block list that checks against the origin domain host via the `CORS_ORIGIN_HOST_REJECTIONS` env var which takes a comma delimited list of domain hosts to block. 
This blocklist combines with existing behaviour of the explicity allow list in the `CORS_ORIGINS_REGEX` env var. 
Both the allow and block lists are setup at boot time by the env vars and don't change for the life of the server process.
=> add cors block list mechanism

.github/workflows/deploy_staging_canary.yml
Make sure we keep the canary deploy up to date - it's just like staging but uses the Next gemfile to install libs and boot.
I'm not sure why this was set to manual deploys...that seems like an oversight and would have kept possible insecure / broken code running on the canary system.
=> ensure we deploy the staging canary on merges to master

.github/workflows/run_tests_CI.yml, config/environments/test.rb
avoid logging deprecation warnings in CI system but keep them in local dev for visibility.
=> disable deprecation warnings in CI

app/workers/inat_import_worker.rb
Imports should be isolated from the main sidekiq queue.
=> Run iNat imports on the dumpworker sidekiq queue

app/controllers/api/v1/subjects_controller.rb
=> Rails 5.2 deprecation fix use arel.sql in subjects controller

app/operations/subject_groups/create.rb, spec/operations/subject_groups/create_spec.rb
Adding raw sql to query methods will be disallowed in Rails 6.0
=> Rails 5.2 - deprecation fix : Add Arel.sql around query  in create.rb

Gemfile.lock, Gemfile.next.lock
We don't need to be on v1 of bundler anymore so we can use the latest v2 version.
This shouldn't impact on any CI systems to install ruby and setup gems via `bundle install` etc but it will fix the issue of some libs compiling natively, e.g. https://github.com/zooniverse/panoptes/actions/runs/3511260107/jobs/5881865785
=> use v2.3.26 bundler

.github/workflows/run_tests_CI.yml, Dockerfile, Dockerfile.dev
This PR is related to the change in #4023 that switched to v2 bundler version
This is due to the CD system using our ruby2.6 docker image which doesn't have the v2 version of bundler available. 
The bad news is our ruby 2.6 docker image is more than 1 year old and unsupported both in terms of the underlying OS debian version (stretch) and the ruby version. 
https://www.ruby-lang.org/en/downloads/releases/
https://hub.docker.com/_/ruby/tags?page=1&name=2.6-slim-stretch
Sadly we can't rely on this image anymore and it's time to upgrade it. 
The good news is we have an easy upgrade to ruby 2.7 though that too is on the way to EOL https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
The only tricky part here is the upgrade to 2.7 means we are now on debian bullseye which installs …
=> Upgrade ruby to 2.7 and jemalloc to v5

Dockerfile.rails-next
in order to keep next version of app consistent with ruby upgrade in our app, i think we should update the dockerfile.rails-next to use 2.7 as well
=> Update Dockerfile.rails-next to use 2.7

app/workers/inat_import_worker.rb, lib/inaturalist/subject_importer.rb, spec/lib/inaturalist/subject_importer_spec.rb
The activerecord-import call needs to include `recursive: true` in order to include the unsaved Media that are built as each subject's location.
Also includes a fix to reject duplicate Sidekiq jobs based on attribute signature to prevent running multiple simultaneous import jobs.
=> Import Subjects recursively to include locations as Media

app/workers/inat_import_worker.rb, lib/inaturalist/subject_importer.rb
When importing iNat observations, the calculation that determined whether a batch of subjects/smses needed to be inserted only checked the modulo-batch size and was cutting off the last x (where x is less than the batch size) records. It now also checks the enumerable's index against the API responses total_results metadata attr (and subtracts one to account for 0-indexing) so it can finish.
=> iNat: don't cut off the last batch

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging-canary.tmpl, kubernetes/deployment-staging.tmpl
The `commit_id.txt` on some pod deploys was showing inconsistent results (i.e. old deploy sha values) even though the pod contained the new sha value in the commit_id.txt baked into the container. It appears the commit_id.txt file on the shared volume between nginx and panoptes api containers (panoptes api app pods) was sometimes being overwritten with a file from the old containers during deploys and thus leaving us with the possibly inconsistent state.
This PR attempts to fix this issue by now only copying the static assets to the shared nginx volume files system if they are newer, i.e. from the newer pod deployment and not a scaling / restart event.
This is achieved this by using the `cp -u` switch to avoid clobbering new pod static assets with old ones due to race condition on the pod …
=> avoid cloberring static assets from new pods only

Dockerfile, scripts/docker/start.sh
follow up to #4042 - our pre start container hook expects the `commit_id.txt` to be in public but we only cp it there on the container entrypoint execution, this can lead to a race condition where the prestart hooks runs and copies static assets to shared pod's nginx container file system before the `commit_id.txt` has been moved there, i.e. a race condition.
This PR now creates the `commit_id.txt` in the public dir to avoid the race condition.
=> Ensure commit id is in public dir

Gemfile.next.lock, spec/workers/dormant_user_mailer_worker_spec.rb, spec/workers/user_added_to_project_mailer_worker_spec.rb, spec/workers/user_info_changed_mailer_worker_spec.rb, spec/workers/user_welcome_mailer_worker_spec.rb
- Update Rails 5.2 dependencies on Gemfile.next.lock (did this by re-running `next bundle update rails` 
- Fix broken tests due to `mail` gem update (dependency of `actionmailer`).  [when testing rescue logic on invalid email, we raise `Net::SMTPSyntaxError` and `Net::SMTPFatalError` in tests eg. https://github.com/zooniverse/panoptes/blob/master/spec/workers/dormant_user_mailer_worker_spec.rb#L10-L16. `.new` expects an address param]
=> update SMTP::MailerError.new with address param

lib/gem_ext/doorkeeper/access_cleanup.rb
Really tricky to see if this fixes `ActiveRecord::StatementInvalid: PG::QueryCanceled: ERROR: canceling statement due to statement timeout` errors  from cleanup worker. I believe it does (and we probably can be convinced more in staging). Reason why I believe it does: within local testing: with batching we split a longer query of DELETE query to chunks of a bit faster queries.
Testing locally with 4000 rows
**(without batching)**
`DEBUG -- : [primary]  Doorkeeper::AccessToken Destroy (37.4ms)  DELETE FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."refresh_token" IS NULL AND (created_at + interval '1 second' * expires_in < clock_timestamp())`
**37.4ms**
**with batching** 
` DEBUG -- : [primary]   (1.4ms)  SELECT  "oauth_access_tokens"."id" FROM "oauth_access_tokens" WHERE …
=> Doorkeeper cleanup worker update to batch deletes

app/workers/doorkeeper_access_cleaner_worker.rb, lib/database_replica.rb
follow up to the work in #4062 - the worker queries are still timing out :( however we can wrap them in a block that sets the timeout to 0 (no timeout) for execution to allow this cleanup code to run.
=> Remove timeouts on doorkeeper cleanup

kubernetes/deployment-production.tmpl
This PR modifies the way the panoptes dump worker pods are deployed. Instead of running 2 possible concurrent exports (2 sidekiq threads per pod) we switch to 1 thread per pod but run 2 pods. This is an attempt to avoid 2 exports running at once and using more RAM than the limit of the pod the exports dying with OOM errors. 
We also increase the required RAM request and limits for each dump worker pod, and allow pods to schedule where a node has at least 4GB up front but set RAM limit to 10GB per pod to avoid overwhelming the node (or try to) but let the exports use more RAM as needed.
This new deployment setup will use more RAM as we run 2 sidekiq pods / processes but it should improve the behaviors of the data exports while still allowing 2 concurrent exports to run.
=> switch dumpworkers to 2 replica pods deployment with more RAM

Gemfile, Gemfile.lock, Gemfile.next.lock
This is in preparation of moving next? dual boot to 6.0. Prior to this, restpack serializer was limited to support activesupport/record < 6.
=> Updating Restpack serializer panoptes-api-version to support up to activesupport/record 7.1

kubernetes/deployment-staging-canary.tmpl
Update kubernetes template replicas to 1 for staging canary to test rails 6.0 on canary
=> Rails 6.0 in Canary

lib/json_api_controller/updatable_resource.rb
Related to: https://github.com/zooniverse/panoptes/issues/4104
=> Bug Fix: update destroy_links to update updated_at time of resource

app/controllers/api/v1/subject_sets_controller.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb
This PR changes how we bulk insert / link subjects to a subject set to ignore duplicates when importing. 
Currently when a subject already is linked to a subject set then re-adding the subject via update_links causes a `PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint` error as the `subject_id` and `subject_set_id` have a unique compound index that errors when linking subjects that already exist in the subject set.
With the PR change we now ignore the duplicate record via the AR import `on_duplicate_key_ignore: true` setting which does a sql `ON CONFLICT DO NOTHING` insert statement to avoid the insert errors. 
see https://github.com/zdennis/activerecord-import#duplicate-key-ignore for more details.
=> ignore duplicate subjects records when linking to a subject set

app/controllers/sessions_controller.rb
change order of `format` `respond_to` on session destroy. (PFE uses `Accept */*` header when calling `session_controller`'s `destroy` via `DELETE` which causes `ActionController::RespondToMismatchError` errors, since in Rails `respond_to` will take the first format as priority. https://github.com/rails/rails/issues/40023#issuecomment-673675138). 
it seem we have done this in other controllers (i.e. prioritizing format.json vs format.html), eg. `passwords_controller`.
but still worth checking to see if we hit this error elsewhere. 
(EDIT: Testing  if there are still similar issues: Will append below as I test/see issues)
**RELATED ISSUES FOUND WHILE TESTING** 
it does look like https://github.com/zooniverse/panoptes/issues/4096 this deprecation warning might have something to do with these …
=> Rails 6.0 issues on Signing out from PFE

.github/workflows/deploy_staging.yml, kubernetes/deployment-staging-canary.tmpl
This reverts commit 0683d45acfda90f71f890457d894afd7632d4886.
Reverting back to Rails 6.0 because determined that Password Change issues were not due to the upgrade but due to how Panoptes JS Client was setting `withCredentials` on api call.
=> Revert "Revert "build staging with Dockerfile.rails-next to test rails 6 in staging (#4111)" (#4119)"

.github/workflows/run_tests_CI.yml
follow up to #4121  
as we don't have a next rails version ready let's avoid the CI running the same tests for Gemfile.next as we're just wasting compute time / CI system resources
=> turn off CI tests for next rails version

Gemfile, Gemfile.lock
See: https://github.com/AaronLasseigne/active_interaction/blob/main/CHANGELOG.md#upgrading-1
There's been some breaking changes from 3.8.3 -> 4.0 which will affect our Operations. 
FWIW, I did some testing on local and things look fine. The change is tiny, but I wanted a second or third set of eyes to ensure I'm not missing anything. Or if anyone had context on why we had a pinned version for this. (I'm assuming its because we were on Rails 4 for a while).
=> update active_interaction to latest version

spec/controllers/api/v1/organizations_controller_spec.rb, spec/lib/formatter/csv/workflow_spec.rb, spec/models/project_spec.rb, spec/support/optimistic_locking.rb
=> Rails 6.1 spec fixes - change references to deprecated update_attributes to update in specs

spec/controllers/api/v1/users_controller_spec.rb
error message on an invalid put operation for users includes rails generated message 
`\nDid you mean?  controller\n               action\n               id` (in 6.1) vs  just
`"param is missing or the value is empty: users"`
=> Rails 6.1 spec fixes- update error messages assertion when an invalid put operation

.github/workflows/publish_docs.yml
fix publish docs github action 
this was due to git repo ownership issues between the action runner vm and the docker container the code was mounted into. See https://github.com/zooniverse/middleman-gh-pages-action/pull/4 for the specifics
=> test docs publish action fix

app/controllers/sessions_controller.rb, app/workers/revoke_tokens_worker.rb, spec/controllers/sessions_controller_spec.rb, spec/workers/revoke_tokens_worker_spec.rb
Related to latency in sign out. Newly added revoking all user's relevant client app tokens, cause slow sign out (especially if user has many tokens...eg. opening up many tabs of the same client). We move the revoking to a worker to hopefully speed up the process.
=> Sign out revoke tokens in a worker

.github/workflows/deploy_staging.yml, kubernetes/deployment-staging-canary.tmpl
Move Rails 6.1 in staging. And set replicas for staging canary to 0.
=> Rails 6.1 next to Staging

Gemfile, Gemfile.lock, Gemfile.next.lock, config/environments/production.rb, config/environments/staging.rb
Rails 6 uses ES6 as a standard and no longer supports Uglifier. See: https://www.mintbit.com/blog/rails-5-6-upgrade-es6-uglifier-bug. 
https://github.com/zooniverse/panoptes/actions/runs/4577101400
With Rails 6, default compiler is Webpacker, so it probably is safe to drop uglifier altogether. Why this didn't get caught in building staging Canary...is a mystery. :/
=> remove uglifier gem

.github/workflows/deploy_production.yml, config/environments/test.rb
If the image is going to be rebuilt after staging has presumably built the same one on the same sha, then we should at least wait until it finishes rebuilding before deploying.
=> Require prodution image to build & push before deploy

app/services/media_storage/azure_adapter.rb
Update azure_adapter default expires in 5 mins to match Panoptes cache
=> update azure_adapter default expires in 5 mins to match Panoptes cache 

kubernetes/db-migrate-production.tmpl, kubernetes/db-migrate-staging.tmpl, kubernetes/job-task-production.tmpl, kubernetes/job-task-staging.tmpl
Allow extremely long running migrations to run extremely long. Current PG_STATEMENT_TIMEOUT is 65000, and the wait time on the job is set to 24h, but the PG statement should be allowed to run as long as necessary. Ideally not that long, but best to not time it out regardless.
Based on https://github.com/zooniverse/caesar/pull/1467/files.
=> Add infinite PG timeout to migrations

app/controllers/api/v1/project_preferences_controller.rb, spec/controllers/api/v1/project_preferences_controller_spec.rb
Typical API auth is skipped for the ProjectPreferencesController's #update_settings method. It's done manually instead, checking a `project.owners_and_collaborators` includes the api_user. This also skips checking if a user is a global admin, though. This PR adds that check and allows admins to update any project's settings to allow them to assist with project building.
=> Allow admins to update settings in project preferences

app/serializers/user_group_serializer.rb
User Group Serializer to send stats_visibility
=> user group serializer send out stats visibility

app/controllers/api/v1/project_preferences_controller.rb, spec/controllers/api/v1/project_preferences_controller_spec.rb
Admin UPP requests only reflect on whether a user is an admin in the database and does not check whether they included the admin flag in the request, signaling intention to act as one.
This PR uses the `api_user.is_admin?` method directly instead, which checks both `user.admin?` and whether the flag was set in the request. The spec needed just the flag set in the request params.
I though this would be a bigger lift so I started my own branch but it turned out to be as simple as https://github.com/zooniverse/panoptes/pull/4249 so this will supersede that one (thanks @lcjohnso!)
=> Require admin flag for admin UPP requests 

lib/project_copier.rb, spec/lib/project_copier_spec.rb
Fixes a couple project copying bugs. 
* Includes Field Guide attached images in project deep copies.
* Creates Talk admin roles for copied projects. Uses the same TalkAdminCreateWorker that fires on project creation.
=> Project copying fixes: Talk roles and field guide images

app/controllers/confirmations_controller.rb, app/models/user.rb, config/initializers/devise.rb, config/routes.rb, db/migrate/20231025200957_add_confirmable_to_devise.rb, db/structure.sql, lib/tasks/user.rake, spec/controllers/passwords_controller_spec.rb, spec/controllers/registrations_controller_spec.rb, spec/factories/users.rb, spec/models/user_spec.rb
Adds the Confirmable module for Devise along with the requisite database attributes. A "please confirm your email address" email is now sent to the user on account creation. That email is using the default template ([located here](https://github.com/zooniverse/panoptes/blob/email-verification/app/views/devise/mailer/confirmation_instructions.html.erb#L6)) and can be updated if desired. 
When a user creates a new account, the front end should inform them that they will receive a confirmation email (this currently happens on Panoptes' own reg page, but no one uses it). The link in that email will point to Panoptes directly so that the API can process the user's confirmation token. That "thank you for confirming" event will likely have to be updated to redirect to wherever makes the most …
=> Email verification

Dockerfile, Dockerfile.dev
Fixes broken Docker builds due to newest version of [gem update compatible with Ruby 3.0](https://github.com/zooniverse/panoptes/issues/4271) and we're on 2.7. 
I don't think we need this step until we go from 2.7 -> 3.0 (See [Slack thread](https://zooniverse.slack.com/archives/C01M8PJGLR5/p1704216465080689?thread_ts=1703798315.916799&cid=C01M8PJGLR5) )
Looking at diffs/git blame that step was added when we bumped from  2.6 -> 2.7. 
**ERROR ON CURRENT DOCKER BUILD**
```
> [ 7/10] RUN gem i "rubygems-update:<3.5.3" --no-document && update_rubygems:                                                                 
#11 35.12 ERROR:  Error installing rubygems-update:                                                                                             
#11 35.12       The last version of …
```
=> remove gem update step on dockerfile

app/views/devise/mailer/confirmation_instructions.html.erb
Updates the confirmation email copy based on team feedback.
=> Update confirmation email copy

app/controllers/api/v1/users_controller.rb, spec/controllers/api/v1/users_controller_spec.rb
=> set valid_email to true on user email change

app/controllers/api/v1/subject_sets_controller.rb, app/workers/subject_removal_worker.rb, lib/subjects/remover.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb, spec/lib/subjects/remover_spec.rb, spec/workers/subject_removal_worker_spec.rb
=> exclude subjects still linked to set_member_subject in subject_remover

app/controllers/api/v1/user_groups_controller.rb, spec/controllers/api/v1/user_groups_controller_spec.rb
allow setting private attribute of user_groups on create and update
=> allow setting private attribute of user_groups on create and update

lib/subjects/remover.rb, spec/lib/subjects/remover_spec.rb
Bug fix of https://github.com/zooniverse/panoptes/pull/4306 
Bug description: When attempting to delete a subject set (and its corresponding subjects) that has subjects with classifications, we receive the following error: https://app.honeybadger.io/projects/40595/faults/106293131 (`NoMethodError`). This is because `orphan_subject` queried is `nil`. 
- switched order within `can_be_removed` to ensure we have orphan subject before querying for attributes of orphan subject
- Added positive and negative specs (i.e. specs where we expect subject removal vs not) for the case when sending over `subject_set_id` to `remover.rb`.
=> Bug Fix -- ensure orphan_subject existence in remover before referring to its attributes

app/policies/membership_policy.rb, app/serializers/workflow_serializer.rb, spec/policies/membership_policy_spec.rb
Bug found while working on User Groups Features 
Correspondence on issue found in this Slack thread here: https://zooniverse.slack.com/archives/C010QAPB67J/p1715888434468079?thread_ts=1715813389.436219&cid=C010QAPB67J
**TL;DR; of the issue is that when doing a `GET` request to /memberships (either via `/memberships?user_id=_user_group_id=_` or  via `/memberships/id`) to one's own public membership, response responds with duplicates.** 
- The reason is that when querying memberships (in membership policy) we add a union of any public memberships. This leads to duplicates when one is querying one's own public membership. 
- Because of this duplicates issue, we cannot deactivate memberships through `DELETE` because `ETag` headers will never match the precondition (due to response of `GET` …
=> Querying Memberships Fix: ensure distinct memberships when querying for ones own public memberships

app/controllers/api/v1/memberships_controller.rb, spec/controllers/api/v1/memberships_controller_spec.rb
allow updating of membership roles via memberships controller
=> allow updating of membership roles via memberships controller

app/models/user.rb, lib/tasks/user.rake, lib/user_info_scrubber.rb, spec/lib/user_info_scrubber_spec.rb
Follow up on conversation on Slack thread found here: https://zooniverse.slack.com/archives/C06DCM0V9/p1713893304800329
Scrubbing unsubscribe_token on user deactivation . 
- Also added rake task to scrub unsubscribe_token for already deactivated users
=> Clear unsubscribe token on user deactivation

lib/project_copier.rb, spec/lib/project_copier_spec.rb
=> append current time to copied project display name

app/models/workflow.rb, db/migrate/20240531184258_remove_aggregation_from_workflows.rb, db/structure.sql
Remove the deprecated `aggregation` column from the workflows table. The Aggregation model and associated other parts are being refactored by https://github.com/zooniverse/panoptes/pull/4303, and this fully frees up the association.
=> Delete aggregations column from workflows table

db/migrate/20240531184258_remove_aggregation_from_workflows.rb
Strong migrations needs safety_assured to remove the aggregation column from workflows table.
=> Add safety_assured to migration

app/controllers/api/v1/aggregations_controller.rb, spec/controllers/api/v1/aggregations_controller_spec.rb
The AggregationClient already returns the body and Faraday already parses it. Just need to pull out what's needed for the update.
=> AggClient already returns the parsed response body

app/controllers/api/v1/aggregations_controller.rb, spec/controllers/api/v1/aggregations_controller_spec.rb
Neither I nor the hash itself are indifferent to its access.
=> Access parsed json hash with string

app/controllers/api/v1/aggregations_controller.rb, app/mailers/aggregation_completed_mailer.rb, app/views/aggregation_completed_mailer/aggregation_complete.text.erb, app/workers/aggregation_completed_mailer_worker.rb, kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl, spec/controllers/api/v1/aggregations_controller_spec.rb, spec/mailers/aggregation_completed_mailer_spec.rb, spec/workers/aggregation_completed_mailer_worker_spec.rb
If the params to AggregationsController#update include a change to status, send an email to the associated user that includes the links to the output files if the run was successful. "Complete" here means either succeeded or failed.
=> Batch Aggregation mailer

kubernetes/deployment-production.tmpl
The internal kubernetes aggregation service name was changed from `aggregation-caesar` to `aggregation-production-app` to reflect the existence of the staging deploy and multiple services that make up the full deployment. This PR updates the env var that points to that service.
=> Update prod template with new aggregation host

app/controllers/api/v1/subject_sets_controller.rb, spec/controllers/api/v1/subject_sets_controller_spec.rb
Added a check to make sure only active subjects are added to subject_sets. 
Solves for this [issue](https://github.com/zooniverse/panoptes/issues/4281)
=> add check to prevent soft deleted subject added to subject set

app/controllers/api/v1/aggregations_controller.rb, spec/controllers/api/v1/aggregations_controller_spec.rb, spec/workers/aggregation_completed_mailer_worker_spec.rb
The `AggregationCompletedMailerWorker` is sending failure emails for successful runs. Instead of passing a block to `super`, the AggregationsController should finish the update first so that the resource has its new status saved before enqueueing the mailer. Also, let's assume params are strings in the specs.
=> Finish update before enqueueing worker

app/controllers/api/v1/subjects_controller.rb, app/serializers/subject_serializer.rb, spec/controllers/api/v1/subjects_controller_spec.rb
Implement sort functionality to subjects index controller and make sort by id default
=> add sort functionality to subjects and sort by id default

lib/inaturalist/observation.rb, spec/factories/observation.rb, spec/lib/inaturalist/observation_spec.rb, spec/lib/inaturalist/subject_importer_spec.rb
iNaturalist observations come with photo URLs that end with "square.jpg". Previously, this square image was swapped for "original.jpg". These files are proving to be too massive, so the "large.jpg" should be used instead.
=> Use large iNaturalist photos in subject locations

lib/workflow_copier.rb, spec/lib/workflow_copier_spec.rb
Solves for this [issue](https://github.com/zooniverse/panoptes/issues/4364)
=> [issue-4364] add attached_images association to workflow copier

app/models/project.rb, spec/models/project_spec.rb
Remove launch email notifications from Projects
=> [issue-4336] halt launch requested notifications on projects

kubernetes/deployment-production.tmpl
Currently there is clog of UserSeenSubjectsWorker which is clogging up our sidekiq queues, as a quick remedy, we first will up minReplicas of sidekiq pods while more research on underlying queries is done.
=> update minReplicas for sidekiq pods

kubernetes/deployment-production.tmpl
To address high latency in lower priority queues while `UserSeenSubjectsWorker` jobs in data_high are dominating available threads, this PR adds a single dedicated pod that will service the default (most important), data_medium, and data_low queues. This change adds an additional pod to the minimum total number of pods, but this cost makes sense in the short term (i.e., while panoptes replica DB is out of service during migration).
=> Add panoptes-production-sidekiq-alt pod type

app/workers/simulate_long_job_worker.rb, spec/workers/simulate_long_job_worker_spec.rb
Our Sidekiq workers are very fast and rate limitedin a few ways, mostly by the congestion middleware. Makes it kind of hard to test scaling when the jobs complete instantly or are deduplicated and canceled on the way in. 
This PR adds an unexposed job that does nothing but `sleep` for the specified duration. This will facilitate testing (via the console) of scaling systems that use the redis queue length as the determining factor.
Might keep this after if it proves useful in other ways, or I can revert/remove after testing.
=> Add a worker that simulates a long running Sidekiq job

kubernetes/deployment-production.tmpl
Two changes related to post-migration resource cleanup
1. decrease minReplicas back to 2 for panoptes-production-sidekiq
2. remove panoptes-production-sidekiq-alt container that was used during user_subject_seen-related backups
=> Post-DB migration template cleanup

app/serializers/user_project_preference_serializer.rb, spec/serializers/user_project_preference_serializer_spec.rb
Request by FE team to add a filter for non-zero activity count.  See Slack convo: https://zooniverse.slack.com/archives/C0DTP3L2K/p1745424531456379
Since activity_count is either calculated through UserSeenSubjects or through UPP for legacy projects (either as a column record or a summation of legacy_counts column values) on the UPP Serializer, we built a custom filter and override restpack serializer methods. 
Eg callout to get filter is 
```
/api/project_preferences?user_id=1325361&http_cache=true&admin=true&sort=-updated_at&page=1&non_null_activity_count=true
```
=> Filter upp for nonzero activity count

app/serializers/classification_serializer.rb
Update ClassificationSerializer to sort by created_at when param to sort by created_at is given. 
Following up on slack thread: https://zooniverse.slack.com/archives/C06DCM0V9/p1744894820435899?thread_ts=1744684185.651289&cid=C06DCM0V9 and PFE PR https://github.com/zooniverse/Panoptes-Front-End/pull/7299
=> Update ClassificationSerializer to sort by created_at

app/mailers/aggregation_completed_mailer.rb, kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl, spec/mailers/aggregation_completed_mailer_spec.rb
As part of May 2025 updates to Batch Aggregation, edit the mailer to use updated URLs for output files.
Linked to: https://github.com/zooniverse/aggregation-for-caesar/pull/821, https://github.com/zooniverse/panoptes-python-client/pull/328
=> BatchAgg: update filenames for mailer

app/serializers/aggregation_serializer.rb
Allows aggregations to be sorted via query param on: id, workflow_id, project_id, status, created_at,  and updated_at.
=> Add can_sort_bys to agg serializer

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging-canary.tmpl
Staging looks good, so this updates the production deploy to use the updated version 1.29 nginx image from GHCR.
Checks will be the same: static assets (commit_id.txt, robots.txt), served pages (signin, doorkeeper, etc), version & validation inside of new sidecar container.
=> Use updated GHCR image for production nginx container

kubernetes/deployment-production.tmpl
Traffic through the static proxy now Include the new conf file from the docker-nginx base image that contains a list of `set_real_ip_from` directives for all of Azure's Front Door IPs. Also set the correct headers to pass along the correct client IP. The staging backend isn't behind a FD, so it doesn't need this. 
The production API backend, however, is behind the main www-zooniverse-org FD and NOT behind the static proxy, so this allows the sidecar nginx container to include the same config as the static proxy, and for requests routed by the k8s ingress controller directly to the pod to utilize those directives.
=> Include Azure IPs as set_real_ip_from directives in sidecar nginx container

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Explicitly pull the 'latest' tag for the docker-nginx image on both staging and production deploys.
=> Always pull the latest tag for the docker-nginx container
