zooniverse/panoptes

- apiary.apib
Closes all the open documentation issues
> Documentation fixes

- config/application.rb
- spec/requests/v1/api_content_spec.rb
This reverts commit be1f4fc968d0e707ab98e96dcf602e2ec823ecec.
Closes #382
> Revert "remove Api Json parse error middleware"

- app/serializers/collection_serializer.rb
- app/serializers/project_serializer.rb
- spec/controllers/api/v1/projects_controller_spec.rb
> Filter projects by the name attributes

- Gemfile.lock
- app/controllers/api/v1/workflows_controller.rb
- app/models/subject_set.rb
- app/models/workflow.rb
- app/serializers/workflow_serializer.rb
- db/migrate/20150112192525_add_expert_set_to_subject_sets.rb
- db/schema.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
> Create an "Expert Subject Set" with Workflow

- apiary.apib
- app/controllers/api/api_controller.rb
- app/controllers/concerns/json_api_responses.rb
- app/models/set_member_subject.rb
- db/migrate/20150112150640_add_lock_version_to_models.rb
- db/schema.rb
- lib/json_api_controller.rb
- lib/json_api_controller/deactivatable_resource.rb
- lib/json_api_controller/destructable_resource.rb
- lib/json_api_controller/indexable_resource.rb
- lib/json_api_controller/precondition_check.rb
- lib/json_api_controller/showable_resource.rb
- lib/json_api_controller/updatable_resource.rb
- spec/factories/projects.rb
- spec/factories/set_member_subjects.rb
- spec/models/collection_spec.rb
- spec/models/project_spec.rb
- spec/models/set_member_subject_spec.rb
- spec/models/subject_set_spec.rb
- spec/models/subject_spec.rb
- spec/models/user_group_spec.rb
- spec/models/user_subject_queue_spec.rb
- spec/models/workflow_spec.rb
- spec/requests/v1/api_conditional_request_spec.rb
- spec/requests/v1/api_id_spec.rb
- spec/requests/v1/api_locking_spec.rb
- spec/support/controller_helpers.rb
- spec/support/deactivatable.rb
- spec/support/destructable.rb
- spec/support/optimistic_locking.rb
Using Last-Modified. Closes #296
> Add support for Conditional Requests

- app/controllers/api/v1/subjects_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- lib/json_api_controller/indexable_resource.rb
- lib/json_api_controller/precondition_check.rb
- lib/json_api_controller/showable_resource.rb
- lib/subject_selector.rb
- spec/requests/v1/api_conditional_request_spec.rb
- spec/requests/v1/api_locking_spec.rb
- spec/support/controller_helpers.rb
Closes #433 
Sorry @brian-c I forgot some controllers won't use the common index method, until #418 is merged.
> Last modified for all

- lib/json_api_controller/precondition_check.rb
- spec/requests/v1/api_conditional_request_spec.rb
@brian-c this should fix the 412 errors. I'm looking into what was causing the other issues.
> Only compare timestamps to the second

- apiary.apib
- app/controllers/api/api_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/subject_sets_controller.rb
- app/controllers/api/v1/subjects_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/controllers/concerns/json_api_responses.rb
- app/schemas/subject_set_create_schema.rb
- lib/json_api_controller/json_schema_validator.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
> Create subject sets from collections

- Gemfile.lock
- app/controllers/api/api_controller.rb
- app/models/user.rb
- lib/json_api_controller.rb
- lib/json_api_controller/relation_manager.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/json_api_controller/relation_manager_spec.rb
This depends on #418 I will rebase from master after it is merged.
> User owner request

- apiary.apib
- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- app/models/set_member_subject.rb
- app/models/user_seen_subject.rb
- app/models/user_subject_queue.rb
- app/serializers/classification_serializer.rb
- app/serializers/set_member_subject_serializer.rb
- db/migrate/20150128160822_add_subject_ids_and_sms_ids_to_classifications.rb
- db/migrate/20150129171400_remove_classifications_count_from_set_member_subjects.rb
- db/schema.rb
- lib/classification_lifecycle.rb
- lib/set_member_subject_relation.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/factories/classifications.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/models/classification_spec.rb
- spec/models/set_member_subject_spec.rb
- spec/models/user_seen_subject_spec.rb
- spec/models/user_subject_queue_spec.rb
- spec/support/classification_events.rb
> Allow Subject Ids to be sent as a link to Classification

- app/controllers/api/v1/groups_controller.rb
- app/controllers/api/v1/users_controller.rb
- spec/requests/v1/api_cors_headers_spec.rb
> Make GET methods Public for User and User Groups

- app/serializers/user_group_serializer.rb
- app/serializers/user_serializer.rb
- spec/controllers/api/v1/groups_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
> Add type to user and user_group responses

- apiary.apib
- app/models/project.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- db/migrate/20150130202731_ensure_private_project_field.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/models/project_spec.rb
- spec/requests/v1/api_csrf_spec.rb
closes #465 - I think the client should explicitly set false / true with the front end defaulting to true (private).
> ensure private field is set by the client

- lib/role_control/controlled.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/lib/role_control/controlled_spec.rb
- spec/models/user_group_spec.rb
- spec/support/indexable.rb
- spec/support/translatable.rb
Closes #466 
The problem was that I was testing if "target" was truthy in `RoleControl::Controlled.scope_for` when it's always truthy. Now I'm testing if the "target" passed to scope for is logged in.
> Test if actor passed to scope for is logged in

- spec/controllers/api/v1/users_controller_spec.rb
Just adding some specs.
Linked to https://github.com/zooniverse/Panoptes-Front-End/issues/89
> add filter by login spec for user index route

- app/models/concerns/activatable.rb
- app/models/user.rb
- spec/models/user_spec.rb
This should fix that Honeybadger error you were seeing. Also why don't enums work right with JRuby :(
> Make sure only active users are indexable

- .gitignore
- config/mailer.yml.hudson
- scripts/docker/start.sh
> visibility into which version of the code is running on api nodes

- Gemfile
- Gemfile.lock
- spec/requests/ie_p3p_headers_spec.rb
> add IE P3P headers for third party cookies.

- README.md
Adds a couple of links to the readme to help anyone having problems with installation
Fix #480 
Ref #477
> Doc amends

- app/workers/classification_worker.rb
- spec/spec_helper.rb
- spec/workers/classification_worker_spec.rb
> fix classification worker

- app/controllers/api/v1/classifications_controller.rb
- app/workers/classification_worker.rb
- lib/classification_lifecycle.rb
- lib/json_api_controller/creatable_resource.rb
- lib/json_api_controller/updatable_resource.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/support/classification_events.rb
> Persist classifcation before backgrounding for workers

- apiary.apib
- app/controllers/api/v1/classifications_controller.rb
- app/schemas/classification_create_schema.rb
- app/schemas/classification_update_schema.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/factories/classifications.rb
Update apiary for new annotation format
Closes #508 Closes #460
> Use JSON Schema for Classification Validation

- apiary.apib
> updated docs to reflect the new classification annotations format

- app/controllers/api/v1/users_controller.rb
- spec/controllers/api/v1/users_controller_spec.rb
> ensure the api controlled user me route supplies the last-modified header

- app/serializers/acl_serializer.rb
- spec/controllers/api/v1/project_roles_controller_spec.rb
> type key not to_s on custom resource links

- apiary.apib
- app/models/set_member_subject.rb
- app/models/subject_set.rb
- app/schemas/subject_set_create_schema.rb
- app/schemas/subject_set_update_schema.rb
- app/workers/classification_count_worker.rb
- app/workers/retirement_worker.rb
- db/migrate/20150216192914_add_classification_count_to_set_member_subjects.rb
- db/migrate/20150216192936_add_retirement_to_subject_set.rb
- db/schema.rb
- lib/classification_lifecycle.rb
- lib/retirement_schemes/classification_count.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/lib/retirement_schemes/classification_count_spec.rb
- spec/models/set_member_subject_spec.rb
- spec/models/subject_set_spec.rb
- spec/support/cellect_helpers.rb
- spec/workers/classification_count_worker_spec.rb
- spec/workers/retirement_worker_spec.rb
> Add retirement schemes for subjects

- apiary.apib
- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
> Serialize and Document cellect workflow params

- app/controllers/api/v1/projects_controller.rb
- app/models/concerns/translatable.rb
- app/serializers/workflow_serializer.rb
- spec/factories/projects.rb
- spec/factories/workflows.rb
- spec/models/project_spec.rb
- spec/models/workflow_spec.rb
- spec/serializers/workflow_serializer_spec.rb
- spec/support/translatable.rb
Fix workflow 500'ing when there is no content_association.
> serialize a workflow that is missing translatable content

- app/controllers/api/v1/subjects_controller.rb
- lib/json_api_controller/indexable_resource.rb
- lib/json_api_controller/precondition_check.rb
- lib/json_api_controller/showable_resource.rb
- lib/json_api_routes.rb
- lib/subject_selector.rb
- spec/requests/v1/api_conditional_request_spec.rb
- spec/requests/v1/api_locking_spec.rb
- spec/support/controller_helpers.rb
This converts our precondition strategy to use ETags instead of the Last-Modified method.
> Fix preconditions

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- config/initializers/cors.rb
- lib/json_api_controller/precondition_check.rb
- spec/requests/v1/api_conditional_request_spec.rb
- spec/requests/v1/api_cors_headers_spec.rb
> add head to cors headers and provide a better error message when the precondition header is missing

- app/schemas/classification_create_schema.rb
> Require metadata and links for classification hash

- apiary.apib
> revert owner to user for project and collection role create link docs

- Gemfile.lock
Closes #535. Get background error reporting by default.
> upgrade honeybadger gem

- Gemfile
- Gemfile.lock
Closes #415. Production and Staging mode are enabled by default. See config/newrelic.yml for more details.
> add newrelic to panoptes

- app/controllers/api/api_controller.rb
- app/models/api_user.rb
- app/models/classification.rb
- app/models/concerns/preferences.rb
- lib/role_control/controlled.rb
- spec/lib/role_control/controlled_spec.rb
- spec/models/api_user_spec.rb
- spec/models/classification_spec.rb
- spec/support/indexable.rb
> Allow admin overrides of all permission scopes

- app/controllers/api/v1/classifications_controller.rb
- app/controllers/concerns/filter_by_owner.rb
- app/models/classification.rb
- db/migrate/20150223194424_add_gin_index_to_classifications_subject_ids.rb
- db/schema.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/models/classification_spec.rb
Also only allow users to retrieve their incomplete classifications.
Closes #558
> Allow filtering of classifications by subject_id

- app/controllers/api/v1/groups_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/concerns/recents.rb
- app/controllers/concerns/versioned.rb
- app/serializers/recent_link_serializer.rb
- app/serializers/recents_serializer.rb
- app/serializers/user_group_serializer.rb
- app/serializers/user_serializer.rb
- config/routes.rb
- spec/controllers/api/v1/groups_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/support/recents.rb
> Create recents routes for users and user_groups

- db/migrate/20150224161921_add_display_names_to_groups_lacking_them.rb
- db/schema.rb
> Add migration to convert names to display_names

- app/controllers/api/v1/projects_controller.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_content_serializer.rb
- app/serializers/project_serializer.rb
- db/migrate/20150224211450_add_result_faq_and_education_content_to_project_contents.rb
- db/schema.rb
- spec/controllers/api/v1/project_contents_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/project_contents.rb
Adds faq, result, and education_content string fields
Closes #582, Closes #583, Closes #525
> Add additional project content fields

- app/workers/classification_worker.rb
> retry classification processing for as long as we can

- app/controllers/api/v1/collection_roles_controller.rb
- app/controllers/api/v1/project_roles_controller.rb
- app/controllers/concerns/roles_controller.rb
Also consolidate code between the role controllers
Closes #555
> Make project roles show public

- app/models/concerns/subject_counts.rb
- app/serializers/project_serializer.rb
- app/serializers/subject_set_serializer.rb
- app/workers/retirement_worker.rb
- db/migrate/20150225181828_add_retired_set_member_subject_count_to_subject_sets.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/factories/subject_sets.rb
- spec/support/subject_counts.rb
- spec/workers/retirement_worker_spec.rb
> Add Retired Subject count to subject sets

- lib/json_api_controller/creatable_resource.rb
- lib/json_api_controller/updatable_resource.rb
> Yeild in create/update controllers after transaction finishes

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/migrate/20150227223423_add_migrated_to_user.rb
- db/schema.rb
- lib/tasks/import.rake
- lib/zooniverse_user.rb
- spec/models/user_spec.rb
> Update user migration script

- app/models/aggregation.rb
- spec/models/aggregation_spec.rb
> ensure a subject's aggregations are unique per workflow

- app/models/user_subject_queue.rb
- lib/subject_selector.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
> sync default page size between cellect and restpack serializer

- apiary.apib
- app/controllers/api/v1/aggregations_controller.rb
- app/models/aggregation.rb
- app/schemas/aggregation_update_schema.rb
- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/aggregations_controller_spec.rb
- spec/factories/aggregations.rb
- spec/models/aggregation_spec.rb
- spec/support/updatable.rb
aggregation will be an interative process that runs at different time scales, e.g. hourly best effort vs nightly full re-run, etc.
> allow aggregations to be updated after creation

- Dockerfile
> Remove docker bundle cache

- app/controllers/passwords_controller.rb
- spec/controllers/passwords_controller_spec.rb
Fixes https://app.honeybadger.io/fault/40595/6ae2a4fb5439e8a0f3b13c857918894b
> Passwords reset via zoo home users via panoptes

- scripts/docker/start.sh
Resolves [an error](https://gist.github.com/perry/b97079a807f11db816e0) I was running in to whilst setting up a fresh install.
cc @camallen
> Always create the tmp/pids/ dir.

- app/controllers/api/v1/groups_controller.rb
- lib/json_api_routes.rb
- spec/controllers/api/v1/groups_controller_spec.rb
- spec/support/updatable.rb
> Fix destroy links routing

- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- spec/controllers/api/v1/projects_controller_spec.rb
> Add project avatar and background image fields

- app/workers/classification_count_worker.rb
- app/workers/retirement_worker.rb
> Use increment_counters to ignore locks

- app/controllers/api/v1/subjects_controller.rb
- app/models/api_user.rb
- app/models/concerns/subject_counts.rb
- app/models/set_member_subject.rb
- app/models/user.rb
- app/models/workflow.rb
- app/serializers/subject_serializer.rb
- db/migrate/20150309171224_add_random_to_set_member_subjects.rb
- db/schema.rb
- lib/postgresql_selection.rb
- lib/subject_selector.rb
- spec/controllers/api/v1/set_member_subjects_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/postgresql_selection_spec.rb
- spec/models/set_member_subject_spec.rb
- spec/models/user_spec.rb
- spec/support/subject_counts.rb
Not super happy with some bits of this (mostly how it does the retired/already seen marking), but I think it should work for Stargazing.
> Psql selection

- app/controllers/api/api_controller.rb
- app/controllers/concerns/api_errors.rb
- config/routes.rb
- lib/json_api_controller.rb
- lib/json_api_controller/updatable_resource.rb
- spec/lib/json_api_controller/updatable_resource_spec.rb
- spec/requests/v1/api_link_params_errors_spec.rb
> Handle Bad Links params errors

- lib/zoo_user_warden_strategy.rb
- lib/zooniverse_user.rb
- spec/controllers/sessions_controller_spec.rb
fixes honeybadger error: https://app.honeybadger.io/fault/40595/f0f03d97b7554e6df6f42d9ff53f66b8
> fail authentication for a disabled panoptes user

- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/controllers/concerns/translatable_resource.rb
- app/models/concerns/translatable.rb
- app/serializers/project_serializer.rb
- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/projects.rb
- spec/factories/workflows.rb
- spec/models/project_spec.rb
- spec/models/workflow_spec.rb
- spec/support/translatable.rb
> Eager Load translations.

- config/environments/production.rb
> add *zooniverse.org to whitelist for all resource cors

- app/serializers/acl_serializer.rb
> add leading href '/' for project_roles owner 

- public/robots.txt
Revisit this when we’ve got the sign in / oath pages skinned properly, should fix https://app.honeybadger.io/fault/40595/ccaa8c6be7efc6b937425efe4563ba9b after adding a directive in infrastructure. I'll paste a link when it's done.
https://github.com/zooniverse/infrastructure/pull/17
> disallow all robots on panoptes for now

- app/controllers/api/v1/users_controller.rb
- app/serializers/user_serializer.rb
- spec/controllers/api/v1/users_controller_spec.rb
allow the user to update their panoptes global email preference from the front end
> allow a user to update their zoo wide email preferences

- db/migrate/20150317180911_add_created_at_index_to_classifications.rb
- db/schema.rb
> Add created at index

- app/controllers/api/api_controller.rb
- app/controllers/concerns/json_api_responses.rb
- lib/cellect_client.rb
- spec/requests/v1/api_cellect_error_spec.rb
> Catch error from Cellect and return 503

- lib/sha1_encryption.rb
- lib/zooniverse_user.rb
This will work for some of the tested accounts. I'm not sure about a few. I'm going to deploy right away
> Workaround base64 changes in Ruby 2.2

- lib/zooniverse_user.rb
- spec/lib/zooniverse_user_spec.rb
> email and login validiations should case-insentive

- db/migrate/20150318132024_project_contents_text.rb
- db/schema.rb
> bump strings to text for project contents

- lib/zoo_user_warden_strategy.rb
- lib/zooniverse_user.rb
> Handle ruby hash changes by bruteforcing an offset

- db/migrate/20150318221605_remove_classification_subject_ids_gin_index.rb
- db/schema.rb
Most likely fastupdate in batches was causing the db problems, http://www.postgresql.org/docs/9.1/static/gin-implementation.html
> remove the GIN index on subject ids

- app/controllers/api/v1/workflows_controller.rb
- app/models/workflow.rb
- app/workers/workflow_reload_worker.rb
- config/routes.rb
- lib/cellect_client.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/lib/cellect_client_spec.rb
- spec/workers/workflow_reload_worker_spec.rb
> Add reload_cellect endpoint to workflow

- lib/cellect_client.rb
- spec/lib/cellect_client_spec.rb
Also call Thread.pass before retries
Close #687
> Add timeout add retry configuration to Cellect.

- Gemfile
- Gemfile.lock
- README.md
- docker-compose.yml
- dockerfiles/Dockerfile.dev
- dockerfiles/Dockerfile.prod
- lib/tasks/configure.rake
> Migrate to Docker Compose

- app/models/subject_set.rb
- app/serializers/subject_set_serializer.rb
- db/migrate/20150327184058_add_index_to_subject_sets_display_name.rb
- db/schema.rb
- spec/factories/subject_sets.rb
- spec/models/subject_set_spec.rb
> Filter subject sets by display name

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/project_roles_controller.rb
- app/controllers/concerns/api_errors.rb
- app/controllers/concerns/roles_controller.rb
- spec/controllers/api/v1/project_roles_controller_spec.rb
> Better error when no user exists to give a role to

- apiary.apib
> Add documentation for allowed roles

- app/controllers/api/v1/projects_controller.rb
> Always return all content for projects on index

- apiary.apib
> Update docs to refer to If-Match header

- app/serializers/subject_set_serializer.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
including retirement rules and metadata
Closes #715
> Serialize all fields for SubjectSet

- app/controllers/api/v1/collection_roles_controller.rb
- app/controllers/api/v1/project_roles_controller.rb
- app/controllers/concerns/roles_controller.rb
- app/models/access_control_list.rb
- spec/controllers/api/v1/collection_roles_controller_spec.rb
- spec/controllers/api/v1/project_contents_controller_spec.rb
- spec/controllers/api/v1/project_roles_controller_spec.rb
- spec/controllers/api/v1/workflow_contents_controller_spec.rb
- spec/models/project_spec.rb
Make sure ACLs are unique and make them deletable.
> Unique acls

- apiary.apib
> Update doc references to per_page to page_size

- apiary.apib
> Update link name to subject_sets

- app/controllers/passwords_controller.rb
- app/controllers/registrations_controller.rb
- config/initializers/devise.rb
- spec/controllers/passwords_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
> Remove Zoo-Home Login

- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
> Make sure expert_subject_set top level link is singular

- app/controllers/api/v1/workflows_controller.rb
- app/workers/subject_queue_worker.rb
- lib/subject_selector.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
sidekiq doesn't support workers with keyword args, https://github.com/mperham/sidekiq/issues/1356
> remove keywork syntax from sidekiq workers

- apiary.apib
Workflow docs were a bit out of date.
See zooniverse/Panoptes-Front-End#236
> Update workflow docs to describe the latest implementation

- app/models/subject_queue.rb
Don't use the relation method since that puts the ids in ascending order
> Assign new queues from ids field

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/concerns/api_errors.rb
- app/models/api_user.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- db/migrate/20150429163442_add_configuration_to_projects.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/projects.rb
- spec/support/indexable.rb
> Add configuration, approved, and beta to project

- app/models/subject_queue.rb
- app/workers/reload_queue_worker.rb
- lib/postgresql_selection.rb
- spec/models/subject_queue_spec.rb
Fixes https://app.honeybadger.io/projects/40595/faults/12484858
> Make sure PSQL Selection always returns ids

- db/migrate/20150430132128_update_projects_defaults_and_indexes.rb
- db/schema.rb
Closes #769 
Updated the approved and beta fields. Also it seems add_column index: true doesn't actually add the index.
> add default values and indexes to projects

- app/controllers/api/v1/projects_controller.rb
- spec/controllers/api/v1/projects_controller_spec.rb
> Don't filter projects by default

- app/models/subject_set.rb
- app/models/subject_sets_workflow.rb
- app/models/workflow.rb
- db/migrate/20150501162020_add_unique_index_to_workflows_subject_sets.rb
- db/schema.rb
- spec/models/subject_set_spec.rb
- spec/models/workflow_spec.rb
> Set and Workflow relationship should be unique

- app/models/subject_workflow_count.rb
- spec/models/subject_workflow_count_spec.rb
> Use update_all to skip locking during retirement

- app/workers/classifications_dump_worker.rb
- lib/presenter/formatter_csv_classification.rb
- spec/lib/presenter/formatter_csv_classification_spec.rb
- spec/workers/classifications_dump_worker_spec.rb
Removed project name dup row value, add flag to show the real user id and specced the csv formatter output
> update classification csv dumps

- .travis.yml
used to build classification csv dumps
> ensure the tmp dir exists in travis env

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
> Add variation to non-logged queue

- app/models/subject_queue.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/models/subject_queue_spec.rb
> Update queues based on their previous state

- app/models/collection.rb
- app/models/collections_subject.rb
- app/models/subject.rb
- db/migrate/20150504171133_add_unique_index_to_collections_subjects.rb
- db/schema.rb
- spec/factories/collections.rb
- spec/factories/collections_subjects.rb
- spec/factories/users.rb
- spec/models/collection_spec.rb
- spec/models/collections_subject_spec.rb
> Unique Relationship between subjects and collections

- app/models/workflow.rb
- spec/models/workflow_spec.rb
> Destroy subject counts when workflow is destroyed

- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- app/serializers/classification_serializer.rb
- config/initializers/aws.rb
- db/migrate/20150504185433_add_workflow_version_to_classification.rb
- db/schema.rb
- lib/presenter/formatter_csv_classification.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/factories/classifications.rb
- spec/lib/presenter/formatter_csv_classification_spec.rb
- spec/models/classification_spec.rb
- spec/support/classification_events.rb
> Create a new workflow version field and index it

- app/controllers/api/v1/workflows_controller.rb
- app/schemas/subject_set_create_schema.rb
- app/schemas/subject_set_update_schema.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
> Don't create an expert set by default

- app/controllers/api/v1/users_controller.rb
- lib/json_api_controller.rb
- lib/json_api_controller/indexable_resource.rb
- lib/json_api_controller/precondition_check.rb
- lib/json_api_controller/showable_resource.rb
> Include ETags but don't check on GETs

- app/serializers/concerns/belongs_to_many_links.rb
> Fix empty string key in belongs_to_many links

- app/serializers/concerns/belongs_to_many_links.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/controllers/api/v1/set_member_subjects_controller_spec.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/factories/subject_sets.rb
- spec/support/controller_helpers.rb
- spec/support/has_many_filter.rb
- spec/support/indexable.rb
Fixes #809 
had to rework some specs due to intermittent failures i was seeing.
> fix belongs_to_many empty key in links

- app/models/user.rb
- db/migrate/20150507120651_add_valid_email_to_users.rb
- db/schema.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
closes #462 
track which users have bouncing email addresses so we don't get blacklisted for spam
> add valid_email field to users table

- app/controllers/api/v1/users_controller.rb
- app/controllers/registrations_controller.rb
- app/mailers/jisc_mailer.rb
- app/views/jisc_mailer/subscribe.text.erb
- app/views/jisc_mailer/unsubscribe.text.erb
- app/workers/subscribe_worker.rb
- app/workers/unsubscribe_worker.rb
- config/initializers/jisc_mail.rb
- config/jisc_mail.yml.hudson
- lib/json_api_controller/updatable_resource.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/mailers/jisc_mailer_spec.rb
- spec/workers/subscribe_worker_spec.rb
- spec/workers/unsubscribe_worker_spec.rb
> Add management of jisc mail subscriptions

- lib/subject_selector.rb
> Use subject_set_id instead of group_id

- app/controllers/api/v1/projects_controller.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- db/migrate/20150511151058_add_urls_to_project.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/project_contents.rb
- spec/factories/projects.rb
- spec/serializers/project_serializer_spec.rb
> Add labelled urls to project resource.

- app/serializers/project_serializer.rb
- db/migrate/20150512012101_add_migrated_field_to_projects.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
Closes #818.
This flag isn't exposed for manipulation through the API since we will
create Ouroboros projects through the console
> Add migrated flag to projects

- app/controllers/api/v1/subjects_controller.rb
- lib/media_storage/aws_adapter.rb
Closes zooniverse/Panoptes-Front-End#307
> Return s3 urls after a post or put for a subject

- app/models/concerns/preferences.rb
- db/migrate/20150512123559_update_user_preferences.rb
- db/schema.rb
- lib/tasks/import.rake
- lib/zooniverse_project.rb
- lib/zooniverse_user.rb
- lib/zooniverse_user_subscription.rb
- spec/controllers/api/v1/collection_preferences_controller_spec.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
- spec/factories/user_collection_preferences.rb
- spec/factories/user_project_preferences.rb
- spec/factories/zooniverse_user.rb
- spec/lib/zooniverse_user_spec.rb
- spec/support/zooniverse_user_test_db.rb
linked to #615, should finish most of it.
@edpaget second commit, i removed the dependent destroy relation from the `*_preferences` belongs to as it should be the other way around. Can you just double check this.
> migrate scripts for legacy projects, user email & activitiy count subscriptions

- app/models/concerns/preferences.rb
- app/models/user_project_preference.rb
- app/serializers/project_serializer.rb
- db/migrate/20150517015229_add_classifiers_count_to_project.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/models/user_project_preference_spec.rb
Just a count of the number of logged in users who have participated.
I'll work on getting other numbers as part of my stats push post-launch
Closes #567
> Add classifier counts to projects

- app/models/user.rb
- config/initializers/doorkeeper.rb
- lib/zooniverse_user.rb
- spec/controllers/tokens_controller_spec.rb
- spec/lib/zooniverse_user_spec.rb
Closes zooniverse/Panoptes-Front-End#355
> Add ruby base64 workaround to user model

- app/controllers/api/v1/media_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/subjects_controller.rb
- app/controllers/concerns/api_errors.rb
- app/models/medium.rb
- app/models/project.rb
- app/serializers/medium_serializer.rb
- app/serializers/subject_serializer.rb
- app/workers/classifications_dump_worker.rb
- app/workers/medium_removal_worker.rb
- config/routes.rb
- lib/json_api_controller/json_schema_validator.rb
- lib/json_api_routes.rb
- lib/media_storage.rb
- lib/media_storage/abstract_adapter.rb
- lib/media_storage/aws_adapter.rb
- lib/role_control/roled_controller.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/lib/media_storage/aws_adapter_spec.rb
- spec/lib/media_storage_spec.rb
- spec/models/medium_spec.rb
- spec/support/creatable.rb
- spec/support/destructable.rb
- spec/workers/classifications_dump_worker_spec.rb
- spec/workers/medium_removal_worker_spec.rb
Adds support for kicking off a classifications_export through the the API.
> CSV exports

- app/controllers/api/v1/media_controller.rb
- app/models/project.rb
- config/routes.rb
- lib/json_api_routes.rb
- spec/controllers/api/v1/media_controller_spec.rb
> Add attached image resources to projects

- app/controllers/passwords_controller.rb
- app/controllers/registrations_controller.rb
- config/frontend_redirect.yml.hudson
- config/initializers/redirect_urls.rb
- config/routes.rb
- spec/controllers/passwords_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
> Add support for updating a password via json

- app/views/classification_data_mailer/classification_data.html.erb
> Add html version of classification data mailer

- Gemfile
- Gemfile.lock
- app/controllers/concerns/filter_by_owner.rb
- app/models/collection.rb
- app/models/project.rb
- app/models/user.rb
- app/models/user_group.rb
- app/serializers/collection_serializer.rb
- app/serializers/project_serializer.rb
- app/serializers/user_group_serializer.rb
- app/serializers/user_serializer.rb
- db/migrate/20150521160726_add_slug_to_projects_collections_and_users.rb
- db/schema.rb
- spec/controllers/api/v1/groups_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
For Projects, Users, UserGroups, and Collections. Enables
human-readable, but still safe urls
Closes #863
> Use stringex to make url slugs

- app/controllers/api/v1/collections_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/concerns/filter_by_current_user_roles.rb
- app/controllers/concerns/filter_by_owner.rb
- spec/controllers/api/v1/projects_controller_spec.rb
> Add ability to filter by current user role

- config/environments/production.rb
we'll need the frontend deployed on the zooniverse.org domain
> allow preview and zooniverse.org domains

- app/controllers/passwords_controller.rb
- spec/controllers/passwords_controller_spec.rb
So it's consistent with other devise controllers
> Remove format.json_api from devise controllers

- app/controllers/api/v1/projects_controller.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- db/migrate/20150523190207_add_redirect_to_project.rb
- db/schema.rb
- lib/zooniverse_project.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/support/admin_only_option.rb
Only admins may change it
Closes #851
> Add a redirect field to projects

- lib/presenter/formatter_csv_classification.rb
- spec/lib/presenter/formatter_csv_classification_spec.rb
> Don't hash not logged in users in dumps

- app/models/user.rb
- app/serializers/user_serializer.rb
- db/migrate/20150526180444_remove_slug_from_users.rb
- db/schema.rb
All slug look up will be done through the user group models. Also adds
indexes to the slug columns
> Remove slug from user model since

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
In the subject queue enqueue method, as recommended by the PostgreSQL docs
> Use concat operator instead of function

- app/controllers/api/v1/media_controller.rb
- app/models/medium.rb
- app/serializers/medium_serializer.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/models/medium_spec.rb
> Fix media hrefs and include metadata

- app/models/subject_queue.rb
Don't do two separate queries to set subject ids for new queues. I think
this may be related to some of the queue worker slowness we've
seen.
> Set subject ids on queue creation

- lib/zoo_user_warden_strategy.rb
strategies are cascading, do not add the overhead of zoo home connection / import.
> remove zoo home warden strategy

- app/workers/classifications_dump_worker.rb
- lib/presenter/formatter_csv_classification.rb
- spec/lib/presenter/formatter_csv_classification_spec.rb
> Obfuscate private details in classification dumps

- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
> Ignore case when searching for users and signing in

- app/controllers/api/v1/media_controller.rb
- spec/requests/v1/api_conditional_request_spec.rb
Make sure it's testing against the requested media not the parent object
Closes #905
> Fix precondition check on media resource

- app/serializers/project_serializer.rb
- spec/controllers/api/v1/projects_controller_spec.rb
Enables projects to redirect to an external website
> Add project redirect attribute to serializer

- README.md
Replaces https://github.com/arfon/Panoptes/pull/1
> Updating configuration instructions

- lib/export/export_json_project.rb
- lib/tasks/export.rake
- lib/tasks/import.rake
- spec/lib/export/export_json_project_spec.rb
closes #887 
tested locally to import meg's planet four project from staging via a dump file. Probably should break out the import rake task to a class of it's own but it works.
> Export import project

- app/controllers/application_controller.rb
- app/models/user.rb
- db/migrate/20150602140836_add_project_id_to_user.rb
- db/schema.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/models/user_spec.rb
closes #901 allow the project_id param to track which project a user is signing up for when registering.
> track the project id a user signs up for

- app/serializers/concerns/blank_type_serializer.rb
- app/serializers/user_serializer.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/support/controller_helpers.rb
closes #910, add the user’s uploaded_subjects_count and max_subjects to the serialised user response.
> add user subject limits

- app/models/medium.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- config/routes.rb
- spec/controllers/api/v1/media_controller_spec.rb
> Add a profile_header media resource to users

- lib/export/export_json_project.rb
- lib/tasks/export.rake
- lib/tasks/import.rake
- spec/lib/export/export_json_project_spec.rb
More complete solution for project export to json and re-import via rake task.
> fixes for project export / import

- lib/classification_lifecycle.rb
fixes https://app.honeybadger.io/projects/40595/faults/13140114
> rescue correct AR not found error

- app/serializers/medium_serializer.rb
- app/serializers/subject_serializer.rb
> Make sure medium serializers still return get url

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/projects_controller.rb
- app/models/project.rb
- app/workers/talk_admin_create_worker.rb
- config/initializers/talk_api.rb
- config/talk_api.yml.hudson
- lib/talk_api_client.rb
- lib/tasks/talk.rake
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/lib/talk_api_client_spec.rb
- spec/models/project_spec.rb
- spec/workers/talk_admin_create_worker_spec.rb
Adds a worker for creating project admins when a project is created.
> Talk api worker

- app/controllers/api/v1/users_controller.rb
- spec/controllers/api/v1/users_controller_spec.rb
> Filter user by slug

- app/controllers/api/v1/projects_controller.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- db/migrate/20150604214129_add_visibility_flags_to_projects.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/projects.rb
Make sure they're in line with zooniverse/Panoptes-Front-End#243
Closes #941
> Update project visibility flags

- app/serializers/user_serializer.rb
- spec/controllers/api/v1/users_controller_spec.rb
closes #947 allow the requesting user to see their admin status
> add admin field to user response

- lib/zooniverse_user_subscription.rb
reworked the import process to find all uniq user : project combinations and summate their know duplicates if they exist. This process is not repeatable for the same result but is non-optimal due to the use or serialized summary field that can't be queried / summated in the DB.
> make zoo home user subscription migration idempotent

- app/models/concerns/subject_counts.rb
- spec/models/workflow_spec.rb
a workflow can't be finished without any data.
> test for empty subject set on workflow finished?

- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- lib/subject_set_copier.rb
- spec/controllers/api/v1/aggregations_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/support/updatable.rb
closes #954 
Copy a subject set and it's subjects when linked to a different project.
> copy a subejct set and it's subjects when linked via a project

- app/models/subject.rb
- app/serializers/subject_serializer.rb
- app/workers/classifications_dump_worker.rb
- lib/presenter/formatter_csv_classification.rb
- spec/lib/presenter/formatter_csv_classification_spec.rb
- spec/models/subject_spec.rb
Closes #935, closes #951, closes #920 
add workflow name, modified not-logged in to use ip hash and added retired value to the subject metadata
> update classification csv dump format

- config/environments/staging.rb
> Allow local IP address and .local domains on staging

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/subject_queues_controller.rb
- app/controllers/api/v1/subject_sets_controller.rb
- lib/json_api_controller/relation_manager.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/spec_helper.rb
- spec/support/zooniverse_user_test_db.rb
closes #672 - use the fastest import route and run the required validations before attempting the import.
> Speed up subject set update subject links

- app/controllers/api/v1/subject_sets_controller.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
ensure the subject set subjects counter updates
> reset the set_member_subjects counter when bulk importing

- app/controllers/api/api_controller.rb
- lib/subject_selector.rb
- spec/lib/subject_selector_spec.rb
fail fast and provide a better error message if there are no subject sets to build a queue around
> better error message when selecting from no subject set

- app/models/set_member_subject.rb
- db/migrate/20150615153138_add_uniq_subject_subject_set_index.rb
- db/schema.rb
- spec/models/set_member_subject_spec.rb
validate subject and subject set is a uniq relation for the set_member_subject
> do not allow duplicate subjects in a subject set

- app/models/project.rb
- spec/models/project_spec.rb
to be compatible with zooniverse/Talk-Api#39
> Update talk section name

- db/migrate/20150616113453_add_login_to_users.rb
- lib/tasks/migrate.rake
ensure the locking DDL changes and data migration are separate to avoid blocking
> extract the data migration to a rake task

- app/controllers/concerns/recents.rb
- app/serializers/aggregation_serializer.rb
- app/serializers/classification_serializer.rb
- app/serializers/collection_role_serializer.rb
- app/serializers/collection_serializer.rb
- app/serializers/membership_serializer.rb
- app/serializers/project_content_serializer.rb
- app/serializers/project_role_serializer.rb
- app/serializers/project_serializer.rb
- app/serializers/recent_serializer.rb
- app/serializers/set_member_subject_serializer.rb
- app/serializers/subject_queue_serializer.rb
- app/serializers/subject_serializer.rb
- app/serializers/subject_set_serializer.rb
- app/serializers/user_collection_preference_serializer.rb
- app/serializers/user_group_serializer.rb
- app/serializers/user_project_preference_serializer.rb
- app/serializers/user_serializer.rb
- app/serializers/version_serializer.rb
- app/serializers/workflow_content_serializer.rb
- app/serializers/workflow_serializer.rb
- spec/support/api_response.rb
> Add hrefs to all resource responses

- lib/tasks/migrate.rake
and scope the migration to the users namespace.
> add beta users email communication migration

- Gemfile.lock
- docker-compose.yml
- lib/multi_kafka_producer/poseidon.rb
Also fix error in Poseidon producer where the key needs to explicitly
be a string
> Assign kafka container a hostname

- app/controllers/api/v1/users_controller.rb
- spec/controllers/api/v1/users_controller_spec.rb
> Filter users by login name

- app/controllers/concerns/roles_controller.rb
- app/models/collection.rb
- app/serializers/collection_serializer.rb
- app/serializers/concerns/acl_serializer.rb
- lib/role_control/owned.rb
- spec/controllers/api/v1/collection_roles_controller_spec.rb
- spec/controllers/api/v1/collections_controller_spec.rb
Also serialize collection_roles link in response
> Filter role controllers by user_id

- app/controllers/api/v1/collections_controller.rb
- app/serializers/collection_serializer.rb
- db/migrate/20150624131746_add_favorite_to_collections.rb
- db/schema.rb
- spec/controllers/api/v1/collections_controller_spec.rb
Allow collection to be filtered by it
> Add favorite flag to collection

- lib/zooniverse_user_subscription.rb
Group by query on the project subscriptions was creating tmp tables and was killing zoo home db. Do small batches of users to reduce this query cost.
> batch import a set of users project subscriptions

- app/controllers/api/v1/collections_controller.rb
- app/controllers/api/v1/groups_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/concerns/filter_by_display_name.rb
- db/migrate/20150624135643_add_trigram_indexes_to_display_name_columns.rb
- db/schema.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/controllers/api/v1/groups_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/support/display_name_filter.rb
Also creates a trgm index on the fields to make them faster
> Allow wildcard filtering of display_names fields

- app/controllers/api/v1/projects_controller.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_content_serializer.rb
- app/serializers/project_serializer.rb
- db/migrate/20150624155122_add_workflow_description_to_project_content.rb
- db/schema.rb
- spec/controllers/api/v1/project_contents_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
Resolves zooniverse/Panoptes-Front-End#371
> Add translatable workflow_description field to project

- app/models/workflow.rb
- app/workers/classifications_dump_worker.rb
- lib/formatter/csv/annotation_for_csv.rb
- lib/formatter/csv/classification.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
- spec/lib/formatter/csv/classification_spec.rb
> Export labels of used tools when the task type is drawing

- app/controllers/api/v1/projects_controller.rb
- spec/support/export_create.rb
> Make sure to update the timestamp if nothing else changes

- app/controllers/api/events_controller.rb
- spec/controllers/api/events_controller_spec.rb
events queue publishes data using the legacy zooniverse id, find the user by this field.
> use zooniverse_id to find the users

- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
With these changes, it gets through the entire staging dump, which is where the most strange data probably is.
> Robustness against various unexpected data formats

- app/models/user.rb
- spec/models/user_spec.rb
This is the behaviour ouroboros expects
> Set ouroboros api_key on create

- apiary.apib
closes https://github.com/zooniverse/panoptes-javascript-client/issues/8
> project requires a display_name

- app/controllers/api/events_controller.rb
- db/migrate/20150706100343_add_legacy_project_indexes.rb
- db/schema.rb
- spec/controllers/api/events_controller_spec.rb
Once this is active I'll fix the migrated data to link back to the correct projects.
> Ensure existing user activity events link to the correct projects

- app/schemas/event_create_schema.rb
- spec/controllers/api/events_controller_spec.rb
events controller is rejecting new user activities on old projects
> allow panotpes zoo id formats

- app/models/collection.rb
- app/models/project.rb
- app/models/user.rb
- app/models/user_group.rb
Remove the threshold defaults in the search since they're too strict.
> Better threshold defaults

- app/controllers/emails_controller.rb
- config/frontend_redirect.yml.hudson
- config/routes.rb
- spec/controllers/emails_controller_spec.rb
redirect back to the front end for GET and respond ok for creates via POST
> rework unsubscribe end point

- app/controllers/api/v1/project_pages_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/models/project.rb
- app/models/project_page.rb
- app/serializers/project_content_serializer.rb
- app/serializers/project_page_serializer.rb
- app/serializers/project_serializer.rb
- config/routes.rb
- db/migrate/20150629192248_create_project_pages.rb
- db/schema.rb
- spec/controllers/api/v1/project_contents_controller_spec.rb
- spec/controllers/api/v1/project_pages_controller_spec.rb
- spec/controllers/api/v1/project_roles_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/project_contents.rb
- spec/factories/project_pages.rb
- spec/models/project_page_spec.rb
- spec/support/creatable.rb
- spec/support/destructable.rb
- spec/support/indexable.rb
- spec/support/showable.rb
- spec/support/translated_content.rb
This separates project pages into a new resource speeding up load times for project listings between 3-5x. 
It will also allow us to support custom page types. 
I'm still working on the corresponding Front-End pull request.
> Project pages

- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/subjects_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/concerns/admin_allowed.rb
- app/models/api_user.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- db/migrate/20150709191011_add_subject_limit_to_users.rb
- db/schema.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/models/api_user_spec.rb
- spec/models/user_spec.rb
> Allow users subject limits to be set individually

- app/controllers/api/v1/media_controller.rb
- config/routes.rb
- lib/json_api_routes.rb
- spec/controllers/api/v1/media_controller_spec.rb
Fixes #1060, this probably needs a refactor, we could look at adding single and collection methods for the routes in this controller and switch them in the routes setup based on relation types.
> allow delete and show on singluar media relations

- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/tags_controller.rb
- app/models/project.rb
- app/models/tag.rb
- app/serializers/project_serializer.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/models/project_spec.rb
- spec/models/tag_spec.rb
Make sure tags are downcased before saving, when exact filtering by tag,
and when creating tags
> Use correct method to fuzzy search tags

- app/models/collection.rb
- spec/models/collection_spec.rb
> ensure a collection has a display name

- app/models/collections_subject.rb
- spec/controllers/api/v1/collections_controller_spec.rb
Adding better messaging and explicity update_links testing. I spec'd this out when testing a HBadger error.
> test collection update links and provide better error message

- app/controllers/api/v1/subjects_controller.rb
- app/models/medium.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/models/medium_spec.rb
closes #1078 - this must be used via the admin mode flag.
> Allow admin any mime type

- app/workers/classifications_dump_worker.rb
> Obfusticate private details by default

- app/controllers/api/api_controller.rb
- spec/controllers/api/v1/collections_controller_spec.rb
gracefully handle an index violation that passes model validation.
> handle dup inserts that violate the db index constraints

- app/controllers/api/v1/projects_controller.rb
...by allowing a Projects tag relationship to be set to an empty array
> Allow the last tag to be deleted

- app/models/medium.rb
- app/workers/classifications_dump_worker.rb
- app/workers/concerns/dump_worker.rb
- app/workers/subjects_dump_worker.rb
- lib/media_storage/aws_adapter.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/lib/media_storage/aws_adapter_spec.rb
- spec/support/dump_worker.rb
> Upload classification and subject dumps as gzip

- app/serializers/collection_serializer.rb
- spec/controllers/api/v1/collections_controller_spec.rb
Related to zooniverse/Panoptes-Front-End#879
> Return private flag for collections

- app/models/subject_workflow_count.rb
- db/migrate/20150715134211_add_retired_at_to_subject_workflow_counts.rb
- db/schema.rb
- lib/set_member_subject_selector.rb
- lib/tasks/migrate.rake
- spec/lib/set_member_subject_selector_spec.rb
- spec/models/subject_workflow_count_spec.rb
After merging maybe someone can show me how to deploy and run rake tasks. Data migration should run in under a minute. After that I'll send a followup PR to clean up leftover code.
> Migrate retirement to subject workflow counts

- app/models/project_content.rb
- spec/models/project_content_spec.rb
> Add limits to project contents fields

- db/migrate/20150716161318_add_aggregates_unique_index.rb
- db/schema.rb
- spec/models/aggregation_spec.rb
> Add unique aggregate index on subject_id and workflow_id

- lib/formatter/csv/classification.rb
- spec/lib/formatter/csv/classification_spec.rb
ensure we have spec'd the retirement per subject in the classification dumps
> Ensure classification dump marks retired subjects properly

- app/controllers/api/v1/subject_sets_controller.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
Closes #1121 - avoid using the object relation callbacks to cleanup the subject set and linked set_member_subjects and subject_sets_workflows
> speed up subject_set destroy end point

- app/models/project.rb
...for projects
Closes zooniverse/Panoptes-Front-End#1119
> Allow collaborator to act as a translator

- app/schemas/subject_set_create_schema.rb
- app/schemas/subject_set_update_schema.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
> Don't allow additional properties in links object

- apiary.apib
Adds the format for a workflow link to the Subject Set docs
Fixes #1166
> Update subject_sets example

- app/schemas/aggregation_create_schema.rb
- app/schemas/aggregation_update_schema.rb
- app/schemas/classification_create_schema.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/schemas/subject_create_schema.rb
- app/schemas/subject_update_schema.rb
- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
...they shouldn't allow additional properties so error reporting will be consistent
> Make sure all link objects are exclusive

- Gemfile
- Gemfile.lock
My Rails turned out to be unnecessary since the problem was due to
changes in docker networking code
> Return to mainline Rails release

- app/models/medium.rb
- app/models/workflow.rb
- app/serializers/workflow_serializer.rb
- config/routes.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
> Add attached images to workflows

- lib/tasks_visitors/inject_strings.rb
- spec/lib/tasks_visitors/inject_strings_spec.rb
Closes zooniverse/Panoptes-Front-End#1253
> If no help strings in content return old help

- app/controllers/applications_controller.rb
- app/views/doorkeeper/applications/_form.html.erb
- spec/requests/doorkeeper_applications_list_spec.rb
Can correctly update exisiting applicaitons. Non-admin users can manage
their applications.
Closes #1156
> Fix built-in doorkeeper applicaiton manager

- app/controllers/api/v1/subjects_controller.rb
- app/schemas/subject_create_schema.rb
- app/schemas/subject_update_schema.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
> Allow subjects to be linked to external objects

- app/models/concerns/preferences.rb
- lib/tasks/migrate.rake
- spec/controllers/api/v1/project_preferences_controller_spec.rb
Also make sure each user only has one upp object per project
Closes #1122
> Add rake task to create user project prefences

- app/models/user.rb
- lib/tasks/migrate.rake
- spec/models/user_spec.rb
...between users and their identity groups
> Keep logins and display_names in sync

- lib/set_member_subject_selector.rb
- spec/lib/set_member_subject_selector_spec.rb
> Make sure non-logged-in queue is built from active

- app/serializers/concerns/media_links_serializer.rb
> Pluralize media links if they need to be

- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
Close #1086 - Add a seen_before: true flag in classification metadata if the user has a UserSeenSubject with subject id for the workflow in question.
Note this won't apply retrospectively as we dont' track when the UserSeenSubject has the subject id added to subejct_ids array.
> track seen before in classifications

- app/mailers/project_request_mailer.rb
- app/models/project.rb
- app/views/project_request_mailer/project_request.html.erb
- app/views/project_request_mailer/project_request.text.erb
- app/workers/project_request_email_worker.rb
- config/initializers/project_request.rb
- config/project_request.yml.hudson
- spec/mailers/previews/project_request_mailer_preview.rb
- spec/mailers/project_request_mailer_spec.rb
- spec/models/project_spec.rb
- spec/workers/project_request_email_worker_spec.rb
> Add notifications when a project requests beta or

- app/models/collection.rb
- app/models/concerns/slugged_name.rb
- app/models/project.rb
- lib/tasks/migrate.rake
- spec/models/collection_spec.rb
- spec/models/project_spec.rb
- spec/support/slugged_name.rb
Add a rake task to update the slugs in Jenkins
> Update collection slugs similarly to project slugs

- lib/postgresql_selection.rb
- spec/factories/set_member_subjects.rb
- spec/factories/workflows.rb
- spec/lib/postgresql_selection_spec.rb
closes #983 - adds priority and grouped selection combinations to the subject selector.
> Priority and grouped subject selection

- db/schema.rb
db migration wasn't run after the code was updated.
> ensure the profiles are private

- spec/lib/postgresql_selection_spec.rb
super sick of these spec failures...should have just left it as before(:each) blocks...
> don't duplicate prioirities across sms

- app/controllers/api/v1/classifications_controller.rb
- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/support/classification_events.rb
> Dequeue subjects when classificaiton is recieved

- lib/non_duplicate_sms_ids.rb
- spec/models/subject_queue_spec.rb
handle enqueueing subject for logged out user queues
> try the id on a user

- lib/postgresql_selection.rb
- spec/lib/postgresql_selection_spec.rb
set a max number of attempts to create the random sample of subjects
> don't get stuck in a loop

- app/models/user.rb
- spec/models/user_spec.rb
closes #1268 - seems a bunch of ouroboros created users are not getting the model updates required and thus they are not showing up in the controller responses.
> Ouroboros created users

- lib/set_member_subject_selector.rb
- spec/lib/set_member_subject_selector_spec.rb
do not select seen befores for a user, always attempt to show them something they haven't seen
> only select from unseen for logged in users

- Gemfile.lock
- app/assets/stylesheets/base.css
- app/assets/stylesheets/forms.css
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.erb
- app/views/layouts/application.html.erb
- Added base and form css style files for devise views that users may encounter.
- Added semantic layout with classes to devise views and partials, and minor updates to application.html.erb
> Devise styles

- Gemfile
- Gemfile.lock
fix missing celluloid yanked gem that's breaking the builds and use the official version of the ar union gem with union all.
> gem updates

- lib/formatter/csv/subject.rb
- spec/factories/media.rb
- spec/lib/formatter/csv/subject_spec.rb
closes #1070 adds the subject get location urls in order to the subject dump.
> Subject get location dump

- app/assets/stylesheets/base.css
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
provide useful links on landing page and make the logo centered and bigger.
> layout and index page changes

- lib/aggregation_client.rb
> Fix aggregation api client to send token

- app/controllers/api/v1/media_controller.rb
- lib/aggregation_client.rb
> Make sure subject exports and aggregation exports

- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
Partially closes #1045 - in classification dumps added single / multiple task type answer labels instead of the answer index value.
> more useful answer labels in classification data dumps

- lib/subject_selector.rb
- spec/lib/subject_selector_spec.rb
closes #1258 - maintain order of subjects coming our of the queue
> add sort order to subject queue scope

- .travis.yml
- Gemfile
- Gemfile.lock
- app/models/cassandra/classification.rb
- app/models/cassandra/subject.rb
- config/cequel.yml.hudson
- docker-compose.yml
- lib/classification_lifecycle.rb
- lib/tasks/configure.rake
- lib/tasks/migrate.rake
- spec/lib/classification_lifecycle_spec.rb
- spec/models/cassandra/classification_spec.rb
- spec/spec_helper.rb
Duplicate classification records into Cassandra for aggregation engine
Closes #987
> Save classifications to Cassandra

- Gemfile
- Gemfile.lock
merge this when we're happy that the stuck thread issue is gone. maybe mon morning...
> remove rack-timeout

- app/mailers/project_request_mailer.rb
- spec/mailers/project_request_mailer_spec.rb
fixes an email problem @mrniaboc reported
> just use the slug in the mailer

- lib/classification_lifecycle.rb
Something is wrong with the cassandra production cluster
> Disable cassandra in production for now

- app/controllers/authorizations_controller.rb
- spec/controllers/authorizations_controller_spec.rb
Closes zooniverse/wildcam-gorongosa#94
Closes zooniverse/Panoptes#1311
> Skip authorization step if the application is ours

- db/migrate/20150902000226_add_index_to_priority.rb
- db/schema.rb
Since the priority selection sorts by that
> Add an index on set member subject priority

- lib/classification_lifecycle.rb
- lib/subject_selector.rb
- spec/lib/classification_lifecycle_spec.rb
spec dequeue on both ends to ensure we don't allow dups
> spec dequeue on both selection and classification receipt

- app/workers/classifications_dump_worker.rb
- app/workers/subjects_dump_worker.rb
- app/workers/workflow_contents_dump_worker.rb
- app/workers/workflows_dump_worker.rb
- lib/formatter/csv/classification.rb
- lib/formatter/csv/subject.rb
- lib/formatter/csv/workflow.rb
- lib/formatter/csv/workflow_content.rb
- spec/lib/formatter/csv/classification_spec.rb
- spec/lib/formatter/csv/subject_spec.rb
- spec/lib/formatter/csv/workflow_content_spec.rb
- spec/lib/formatter/csv/workflow_spec.rb
workflow contents was using the workflow headres...fix this and standardise the header dump method calls
> fix workflow contents header dumps

- lib/postgresql_selection.rb
~~looks like the prev select between random was doing a seq scan, this change should use an index scan instead.~~ 
It's still a seq scan with an index scan for the order by.
Update: ran some benchmarks and the techniques are similar in terms of response times but the select between two random points doesn't handle larger limits well and relies on loop breaking to not spin lock. Also in my testing the distribution coming out of between random points was sequential, order by random looked more random.
```
#ran @ 3 x sequentially
"random sample for 1000"
"limit was -> 100"
"Using order by select between two random points random()"
0.000000   0.000000   0.000000 (  0.002905)
"random sample for 1000"
"limit was -> 999"
"Using order by random()"
0.010000   0.000000   0.010000 (  0.004057) …
```
> use order by random for selection

- lib/postgresql_selection.rb
should have been removed in #1331
> remove unsused const

- app/serializers/user_project_preference_serializer.rb
- db/migrate/20150908193654_add_index_to_project_preferences_updated_at.rb
- db/schema.rb
To support a customized user home page
> Allow project_preferences to be sorted by updated

- app/models/classification.rb
- spec/models/project_spec.rb
- spec/models/workflow_spec.rb
> Revert remove cache counters #1332

- Gemfile
- Gemfile.lock
They've merged my changes and some other fixes.
> Update Cequel to released gem

- app/serializers/workflow_serializer.rb
- spec/serializers/workflow_serializer_spec.rb
> serialize workflows retirement defaults

- app/workers/enqueue_subject_queue_worker.rb
- config/initializers/subject_enqueue_config.rb
- config/initializers/subject_selection_config.rb
- config/subject_enqueue_config.yml.hudson
- lib/postgresql_selection.rb
specifically the non-logged in queue, allow only 1 every 10 seconds by default. i have built and setup the config file for this.
> Rate limit enqueue subjects worker

- app/workers/aggregations_dump_worker.rb
- app/workers/classifications_dump_worker.rb
- app/workers/concerns/dump_worker.rb
- app/workers/subjects_dump_worker.rb
- app/workers/workflow_contents_dump_worker.rb
- app/workers/workflows_dump_worker.rb
- config/dump_worker_config.yml.hudson
- config/initializers/dump_worker_config.rb
set to default limit of 1 per day configurable via the yaml file and customizable via a direct overide in the worker class
> rate limit data dump workers

- app/models/concerns/subject_counts.rb
- lib/set_member_subject_selector.rb
- spec/lib/set_member_subject_selector_spec.rb
> refactor set member subject selector

- app/controllers/registrations_controller.rb
- spec/controllers/registrations_controller_spec.rb
make sure people can't be added to the email list without successfully signing up
> subscribe to emails after successful save

- app/controllers/api/v1/media_controller.rb
- app/mailers/aggregation_data_mailer.rb
- app/views/aggregation_data_mailer/aggregation_data.html.erb
- app/views/aggregation_data_mailer/aggregation_data.text.erb
- app/workers/aggregation_data_mailer_worker.rb
- app/workers/concerns/dump_worker.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/workers/aggregations_data_email_worker_spec.rb
notify the requester / project owner when the aggregation export has finished uploading
> send email when aggregation update is finished

- app/controllers/api/v1/media_controller.rb
- spec/controllers/api/v1/media_controller_spec.rb
use consistent state signalling
> send email on ready state not finished

- app/mailers/project_request_mailer.rb
- spec/mailers/project_request_mailer_spec.rb
Closes zooniverse/Panoptes-Front-End#1657
> Remove hash from project request email

- app/workers/aggregation_data_mailer_worker.rb
- app/workers/aggregations_dump_worker.rb
- app/workers/classifications_dump_worker.rb
- app/workers/concerns/dump_mailer_worker.rb
- app/workers/concerns/dump_worker.rb
- app/workers/concerns/rate_limit_dump_worker.rb
- app/workers/subjects_dump_worker.rb
- app/workers/workflow_contents_dump_worker.rb
- app/workers/workflows_dump_worker.rb
seperate the rate limiting for dump workers into a composable module.
> do not rate limit the mailer worker

- lib/unique_for_owner_validator.rb
- spec/models/collection_spec.rb
- spec/models/project_spec.rb
> Make sure to ignore case when checking uniqueness of display names

- app/workers/classification_heartbeat_worker.rb
- config/heartbeat_config.yml.hudson
- config/initializers/heartbeat_config.rb
- spec/workers/classification_heartbeat_worker_spec.rb
avoid heavy cpu load via ice cube, https://github.com/tobiassvn/sidetiq/wiki/Known-Issues
> use 15 min schedules to check for missing data

- lib/formatter/csv/classification.rb
- lib/formatter/csv/subject.rb
- spec/lib/formatter/csv/classification_spec.rb
> add user_id to classifications csv dump

- app/models/workflow.rb
- spec/models/workflow_spec.rb
closes https://github.com/zooniverse/Panoptes-Front-End/issues/1696
> workflow display_name must be present

- app/models/user.rb
- spec/controllers/api/v1/users_controller_spec.rb
needed this to allow admin panel in PFE to update user subject limits
> allow admin users to update other users

- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/tutorials_controller.rb
- app/models/medium.rb
- app/models/project.rb
- app/models/tutorial.rb
- app/models/workflow.rb
- app/schemas/project_update_schema.rb
- app/schemas/tutorial_create_schema.rb
- app/schemas/tutorial_update_schema.rb
- app/serializers/project_serializer.rb
- app/serializers/tutorial_serializer.rb
- config/routes.rb
- db/migrate/20151007161139_create_tutorials.rb
- db/migrate/20151007193849_add_default_tutorial_to_project.rb
- db/schema.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/tutorials_controller_spec.rb
- spec/factories/tutorials.rb
- spec/models/tutorial_spec.rb
> Add tutorial resource

- app/models/tutorial.rb
- app/schemas/tutorial_create_schema.rb
- app/schemas/tutorial_update_schema.rb
- spec/controllers/api/v1/tutorials_controller_spec.rb
- spec/factories/tutorials.rb
- spec/models/tutorial_spec.rb
> Media not title for tutorial

- app/serializers/project_serializer.rb
Need this for my project order editor
> Filter projects by private status

- app/controllers/api/v1/workflows_controller.rb
- app/models/workflow.rb
- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- db/migrate/20151013181750_add_order_to_workflows.rb
- db/schema.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/support/default_format.rb
> Add support for ordering workflow results

- scripts/docker/start.sh
Otherwise it just looks in $PWD by default
> Specify supervisor config file location

- app/workers/subject_import_worker.rb
- lib/tasks/subjects.rake
- spec/workers/subject_import_worker_spec.rb
This is based on the script used to load up Wildcam, but with tests and with ids as parameters. This way we can just kick off an import from Jenkins.
> Subject importer

- app/controllers/api/api_controller.rb
- app/models/user.rb
- app/models/workflow.rb
- app/serializers/project_serializer.rb
- app/serializers/workflow_serializer.rb
- lib/classification_lifecycle.rb
- lib/gem_ext/rails/reflection.rb
these were the only ones i found in honeybadger, will add more if we get new errors
> require files causing circular dependency errors

- app/workers/concerns/dump_worker.rb
- spec/support/dump_worker.rb
avoid reading large file to mem, chunk and zip instead.
> read the input file in chunks

- app/models/collection.rb
linked to https://github.com/zooniverse/Panoptes-Front-End/pull/1886
> lower threshold for collection display_name matches

- config/cors_config.yml.hudson
- spec/requests/v1/api_cors_headers_spec.rb
ui app needs this header exposed for a dev server
> expose csrf token headers

- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- db/migrate/20151110135415_add_workflow_config_object.rb
- db/structure.sql
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/workflow_spec.rb
> add workflow configuration object

- app/controllers/api/v1/collections_controller.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/support/belongs_to_many_filter.rb
towards closing https://github.com/zooniverse/Panoptes-Front-End/issues/1894
> filter collections by belongs to many project_ids

- app/controllers/api/events_controller.rb
- app/models/classification.rb
- app/models/user_project_preference.rb
- app/serializers/project_serializer.rb
- app/workers/classification_count_worker.rb
- app/workers/reset_project_counters_worker.rb
- db/migrate/20151026142554_add_project_launch_date.rb
- db/structure.sql
- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/models/project_spec.rb
- spec/models/user_project_preference_spec.rb
- spec/models/workflow_spec.rb
- spec/workers/classification_count_worker_spec.rb
- spec/workers/reset_project_counters_worker_spec.rb
> Add project launch date

- scripts/docker/restart_puma.sh
most likley to be used after a migration to ensure the AR schema is consistent with the DB.
Looks like there will be some changes to AR that will fix some of these errors but probably not good enough for all migration schema changes, https://github.com/rails/rails/issues/12330
This will have to be combined with the jenkins prod db migration job once it's live.
> add script to hot restart puma

- app/models/workflow.rb
- app/serializers/workflow_serializer.rb
- lib/formatter/csv/workflow.rb
- spec/lib/formatter/csv/workflow_spec.rb
- spec/models/workflow_spec.rb
> serialize default retirement criteria in workflow dumps

- Gemfile
- config/puma.rb
closes #1497 - make puma and newrelic play nice in preload cluster mode
> update puma and new relic configs

- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
not much use if it's not available for the client..
> add workflow config object to serializer

- app/controllers/api/v1/field_guides_controller.rb
- app/controllers/api/v1/media_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/models/concerns/language_validation.rb
- app/models/concerns/translated_content.rb
- app/models/field_guide.rb
- app/models/medium.rb
- app/models/project.rb
- app/models/project_page.rb
- app/schemas/field_guide_create_schema.rb
- app/schemas/field_guide_update_schema.rb
- app/serializers/field_guide_serializer.rb
- config/routes.rb
- db/migrate/20151120104454_add_field_guide_resource.rb
- db/structure.sql
- spec/controllers/api/v1/field_guides_controller_spec.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/factories/field_guides.rb
- spec/models/field_guide_spec.rb
- spec/models/project_spec.rb
closes #1502 
@brian-c can you check i've got the schema right (app/schemas/field_guide_create_schema.rb) and that the `icon` attribute will contain the linked id for the media resource?
> add field guide project resource

- apiary.apib
linked to #1519, added notes about hosted and external media subject resources.
> updated docs on subject media locations

- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
closes #1520 added public_gold_standard and added default for null finished_at
> update workflow serialized response

- app/models/workflow.rb
- lib/retirement_schemes.rb
- lib/retirement_schemes/classification_count.rb
- lib/retirement_schemes/never_retire.rb
- spec/lib/formatter/csv/workflow_spec.rb
- spec/lib/retirement_schemes/classification_count_spec.rb
- spec/lib/retirement_schemes/never_retire_spec.rb
- spec/models/workflow_spec.rb
- spec/serializers/workflow_serializer_spec.rb
> Custom retirement config

- app/views/doorkeeper/applications/_form.html.erb
> Fix application form path and method

- app/serializers/project_serializer.rb
- app/workers/calculate_activity_worker.rb
- app/workers/calculate_project_activity_worker.rb
- db/migrate/20151207145728_add_project_activity.rb
- db/structure.sql
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/workers/calculate_activity_worker_spec.rb
- spec/workers/calculate_project_activity_worker_spec.rb
Daily project activity counts based on 24 window of classification counts.
> Project activity counts

- app/models/project.rb
- db/migrate/20151210134819_add_tsvector_to_projects.rb
- db/structure.sql
- spec/controllers/api/v1/projects_controller_spec.rb
Adds tsvector to projects mode for #1546
> Added tsvector to projects model

- app/workers/enqueue_subject_queue_worker.rb
- spec/workers/enqueue_subject_queue_worker_spec.rb
just get the sms ids not a busted pluck result
> unambiguous pluck on the join scope

- app/models/classification.rb
- app/models/subject_workflow_count.rb
- db/migrate/20160104131622_remove_deprecated_columns.rb
- db/structure.sql
To do this zero-downtime-style, **deploy first**, then migrate later.
Fixes #1560
> Remove unused columns

- app/controllers/api/v1/projects_controller.rb
- lib/fast_project_serializer.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/lib/fast_project_serializer_spec.rb
For zooniverse/Panoptes-Front-End#2029
> Rename the ProjectsController#index 'homepage' param to 'simple' for clarity

- app/models/set_member_subject.rb
convert the query to arel and use a not exists subselect with unnest instead of a not in any array comparator.
> Optimize unseen query

- db/migrate/20160106120927_add_lifecycled_at_to_classifications.rb
- db/migrate/20160107143209_add_lifecycled_at_index.rb
- db/structure.sql
merge after #1584 - this should build a partial index on lifecycled_at concurrently outside a transaction block
> Add partial index concurrently to lifecycled_at

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/classifications_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/workers/classification_worker.rb
- app/workers/reload_cellect_worker.rb
- app/workers/reload_non_logged_in_queue_worker.rb
- app/workers/retirement_worker.rb
- lib/classification_lifecycle.rb
- lib/kafka_classification_serializer.rb
try and avoid circular dep errors, add explicit requires.
> explicit requires for circular load errors

- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
just set and forget cellect ignore any connection errors
> ignore collect connection errors on classification lifecycle

- app/models/classification.rb
make sure the queries use the gold standard indexes on classifications and workflow
> use the gold standard indexes

- app/controllers/concerns/filter_by_metadata.rb
- app/models/concerns/preferences.rb
- db/migrate/20160111112417_remove_unused_indexes.rb
- db/structure.sql
- spec/controllers/api/v1/tags_controller_spec.rb
remove unused / duplicates AND update index defs / code to hit indexes
> Audit indexes

- app/models/classification.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
don't just return all the data, filter it with the route's intention.
> only return gold standard data as admin

- app/workers/aggregation_data_mailer_worker.rb
- app/workers/calculate_activity_worker.rb
- app/workers/calculate_completeness_worker.rb
- app/workers/calculate_project_activity_worker.rb
- app/workers/calculate_project_completeness_worker.rb
- app/workers/classification_data_mailer_worker.rb
- app/workers/classification_heartbeat_worker.rb
- app/workers/count_reset_worker.rb
- app/workers/empty_subject_queue_worker.rb
- app/workers/enqueue_subject_queue_worker.rb
- app/workers/honeybadger_worker.rb
- app/workers/medium_removal_worker.rb
- app/workers/project_request_email_worker.rb
- app/workers/queue_removal_worker.rb
- app/workers/random_order_shuffle_worker.rb
- app/workers/reload_cellect_worker.rb
- app/workers/reload_non_logged_in_queue_worker.rb
- app/workers/requeue_classifications_worker.rb
- app/workers/retire_cellect_worker.rb
- app/workers/seen_cellect_worker.rb
- app/workers/subject_data_mailer_worker.rb
- app/workers/subject_set_subject_counter_worker.rb
- app/workers/subscribe_worker.rb
- app/workers/talk_admin_create_worker.rb
- app/workers/unsubscribe_worker.rb
- app/workers/user_welcome_mailer_worker.rb
- app/workers/workflow_content_data_mailer_worker.rb
- app/workers/workflow_data_mailer_worker.rb
move as much as we can off the api nodes and onto the data worker
> move processing off to the data worker

- app/workers/retirement_worker.rb
dont publish data unless it's really retired
> meet the guard criteria

- Dockerfile.dev
- supervisord.conf.dev
Production config will run it on dump workers.
> Don't run sidekiq by default

- app/workers/subject_import_worker.rb
And allow .jpeg as well as .jpg
> Add PNG mime type to import worker

- app/workers/requeue_classifications_worker.rb
- config/initializers/panoptes.rb
- spec/workers/requeue_classifications_worker_spec.rb
don't feeback loop with large queue's, env variable is ready for this.
> ability to disable the requeue worker

- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- app/workers/classifications_dump_worker.rb
- db/migrate/20160113132540_remove_classification_indexes.rb
- db/migrate/20160113143609_remove_user_project_preference_index.rb
- db/structure.sql
get rid of indexes where we can, some classification ones will have to be rebuilt (possibly with partial wheres).
> Remove indexes

- app/controllers/api/events_controller.rb
- app/models/subject_workflow_count.rb
- app/workers/classification_count_worker.rb
- lib/classification_lifecycle.rb
skip the counters for SGL project only. PLEASE Make sure i've got the right project number...https://www.zooniverse.org/lab/764/
> just skip the SGL project id 764 for the meantime

- app/workers/dequeue_subject_queue_worker.rb
especially for the non-logged in queues
> throttle the dequeue events

- app/workers/retirement_worker.rb
> don't dequque all for SGL

- Dockerfile
- Dockerfile.dev
- Gemfile
- Gemfile.lock
linked to https://github.com/zooniverse/docker-ruby/pull/3 - this should be fine to merge before the base PR is updated.
Install pg gem dep locally. Remove jruby gems and the pgclient install on the docker dev image (happy to put this one back in if peeps use it).
> Ruby docker base update

- app/serializers/project_serializer.rb
> allow sort by display_name

- app/workers/classifications_dump_worker.rb
- lib/classification_dump_cache.rb
- lib/formatter/csv/classification.rb
- spec/lib/formatter/csv/classification_spec.rb
closes #1649 - use a random number lookup on the ip string instead of a hash function of the ip string
> increase security of ip hashing

- public/robots.txt
> allow all robots

- app/workers/user_welcome_mailer_worker.rb
- spec/workers/user_welcome_mailer_worker_spec.rb
> handle invalid domain user email

- Dockerfile.dev
- README.md
- docker-compose.yml
Audit the getting started section in the readme and make sure it works. explicit 9.4 postgres and make sure we have a pg_dump tool for db setup / migrations
> fixes for getting started

- app/controllers/api/events_controller.rb
- app/models/subject_workflow_count.rb
- lib/classification_lifecycle.rb
remove the hack overrides to avoid lock contention on the counters
> revert skip overrides from SGL

- app/workers/enqueue_subject_queue_worker.rb
> require the correct dependency

- app/controllers/api/v1/workflows_controller.rb
- app/models/project.rb
- app/operations/workflows/retire_subjects.rb
- config/routes.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/operations/workflows/retire_subjects_spec.rb
> Allow multiple subject ids to retire

- lib/subjects/cellect_client.rb
- spec/lib/subjects/cellect_client_spec.rb
don't let a busted redis connection stop us from serving subjects
> handle cellect client connection failures

- apiary.apib
> Fix URL pointing towards user groups in the apiary docs

- app/serializers/user_serializer.rb
- spec/controllers/api/v1/users_controller_spec.rb
this will be used for zooniverse omniauth strategy
> add zooniverse_id to user serializer for the me route

- app/workers/concerns/dump_worker.rb
- spec/support/dump_worker.rb
closes #1723 - otherwise safari gets weird
> double quote the content-disposition filename

- app/serializers/subject_set_serializer.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
Fixes issue #1727 
Allow display_name sorting for subject sets
> Add sorting of subject sets

- .github/PULL_REQUEST_TEMPLATE.md
Github now supports a template for the description of each pull request.
**Let me know what else you can come up with**
> Initial work on PR template checklist

- lib/formatter/csv/classification.rb
- spec/lib/formatter/csv/classification_spec.rb
> Add classification_id to CSV export

- app/controllers/api/v1/tutorials_controller.rb
- app/models/tutorial.rb
- app/models/workflow.rb
- app/models/workflow_tutorial.rb
- app/schemas/tutorial_create_schema.rb
- app/serializers/tutorial_serializer.rb
- db/migrate/20160329144922_associate_workflows_with_tutorials.rb
- db/migrate/20160330142609_add_kind_to_tutorials.rb
- db/structure.sql
- lib/tasks/migrate.rake
- spec/controllers/api/v1/tutorials_controller_spec.rb
Allow linking tutorials with specific workflows, and allow querying tutorials filtered to a given workflow_id.
Fixes #1730 and #1726 
> Workflow tutorials

- apiary.apib
docs the correct usage of linking workflows & subject sets to a project.
> update project links docs

- app/services/code_experiments/librato_reporter.rb
Found a small but important bug.
> Fix Scientist reporting

- .github/PULL_REQUEST_TEMPLATE.md
Because checking things off is fun.
> Make the PR checklist an actual checklist

- config/puma.rb
> Do not use Puma clustered mode in development environment

- README.md
- docker-compose-db.yml
> Updated Docker instructions, version, date

- app/workers/subject_import_worker.rb
- spec/workers/subject_import_worker_spec.rb
> Queue will reload when subjects are uploaded via sidekiq worker

- app/models/project_content.rb
- spec/models/project_content_spec.rb
Closes https://github.com/zooniverse/Panoptes-Front-End/issues/2239
> raise project introduction limit to 5K

- app/controllers/api/v1/users_controller.rb
- app/serializers/user_serializer.rb
- spec/controllers/api/api_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/factories/users.rb
> Allow setting user languages through api

- app/models/set_member_subject.rb
- app/models/user.rb
- spec/models/set_member_subject_spec.rb
- spec/models/user_spec.rb
closes #1786 use a count of the linked / current seen subjects vs what the workflow has linked
> compare user seens to live data only

- app/schemas/workflow_update_schema.rb
- config/routes.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
Another WIP PR to fix #1784. Updates to routing and JSON validation were simple, but I'm not sure exactly how the spec should look. The WorkflowsController and Updatable spec files shed a little light, but I'd appreciate a few extra eyes.
> Link tutorial to workflow

- db/migrate/20160512181921_add_users_lower_names_index.rb
- db/structure.sql
Used by zooniverse/Talk-Api#90 for autocompleting usernames.
> Adds a case insensitive index on user login and display name for LIKE queries

- lib/formatter/csv/classification.rb
- spec/lib/formatter/csv/classification_spec.rb
Requested by @ggdhines in #1798 (and originally in PFE issue #2543). Included as an array, but whoever's manning the aggregation station now that Greg has left is welcome make suggestions.
> Includes subject_ids in the classification CSV export

- app/models/membership.rb
- db/migrate/20160525103520_ensure_memberships_are_unique.rb
- db/structure.sql
> Adds a unique index for user_group_id and user_id.

- app/controllers/api/v1/workflows_controller.rb
- app/models/workflow.rb
- db/migrate/20160527162831_workflows_activated_state.rb
- db/structure.sql
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/workflow_spec.rb
- spec/support/translatable.rb
Workflows should not be actually deleted from the DB.
> Deactivate workflows rather than deleting

- app/models/collection.rb
- app/models/concerns/translatable.rb
- app/models/project.rb
- app/models/subject.rb
- app/models/subject_set.rb
- app/models/user.rb
- app/models/user_group.rb
- app/models/workflow.rb
- db/migrate/20160527140046_foreign_keys.rb
- db/structure.sql
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/factories/access_tokens.rb
- spec/factories/applications.rb
- spec/models/user_spec.rb
- spec/workers/classifications_dump_worker_spec.rb
Most important things to review are:
* if you agree with my `on_delete:` settings.
* **am i deleting that orphaned data correctly**
No app code changed, just a few specs that tried to set up factories with foreign key constraint failures.
> Add foreign keys for all non-polymorphic relations

- app/controllers/api/v1/workflows_controller.rb
- app/models/workflow.rb
- spec/factories/subject_sets.rb
ensure we don't hit n+1 relations in the serializer. I'm not super wedded to the implementation but this should speed up the NFN landing page @mcbouslog
> Eager load workflow relations index

- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
Use scientist and feature flipping to test out subject queue selection in band and skip the queue state update problem.
This hopefully will fix a lot of the already seens issues users are having (from delayed queue updates) and this will also allow us to use queue's for targeted subject task allocation.
TODO:
> Test out the speed of the subject selector using scientist

- app/controllers/api/v1/workflows_controller.rb
get some metrics on the performance impact of this code, going to start with disabled and then turn on for this a percent of the time, and ramp it up to see if it causes the current behaviour.
> test workflows eager loading with scientist

- app/models/classification.rb
- app/models/set_member_subject.rb
- app/models/user_seen_subject.rb
- app/services/code_experiment.rb
- app/services/code_experiments/log_reporter.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/subjects/postgresql_selection_spec.rb
- spec/lib/subjects/set_member_subject_selector_spec.rb
- spec/models/set_member_subject_spec.rb
- spec/models/user_seen_subject_spec.rb
- spec/models/user_spec.rb
- spec/services/code_experiment_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples_for_postgresql_selection.rb
> Deprecate UserSeenSubject

- lib/subjects/postgresql_random_selection.rb
- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
ensure the page size query param hits the selectors and some minor improvements / refactoring.
> Respect page_size limits in subject selector

- app/models/set_member_subject.rb
reverting changes to test the impact on subject selection.
> re-run code experiment for unseen set_member_subjects

- app/models/set_member_subject.rb
don't conflate running experiments, provide a feature flag to switch code paths for the upstream has_finished? experiment.
allow for testing the different code paths via the upstream experiement  in user.rb#has_finished?
> feature flip the retireving the seen subjects via classification

- app/models/project.rb
- app/workers/calculate_project_completeness_worker.rb
- spec/models/project_spec.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
closes #1873
Exclude inactive workflows from the project completeness score as we should be reflecting the actual current workload for this metric...not any previous / testing workflows.
> Active workflows completeness

- app/controllers/passwords_controller.rb
- app/models/user.rb
- config/initializers/devise.rb
- spec/controllers/passwords_controller_spec.rb
- spec/models/user_spec.rb
Provide useful error messages when resetting passwords (e.g. it's too short, token invalid, etc) for the UI.
> Password reset errors

- app/controllers/passwords_controller.rb
linked to #1877 ~~(i'll rebase after that is merged)~~ rebased
report the context of failing password resets to honeybadger to try and find more info about the reset password failures. Once the UI has better reports then we can combine with this info and if there are no HB reports than the reset token is invalid as it hasn't found any linked user...so that will be confusing.
> Report to honeybadger on invalid passord reset

- apiary.apib
- app/controllers/api/api_controller.rb
- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- config/routes.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/models/classification_spec.rb
Added a route to grab new classifications by sending it the last id you've got. Uses a simple where clause to find them. I'm having trouble with my local setup that breaks requests outside of rspec. I'll try to solve that tomorrow, but in the mean time I'm making this PR to run all the specs and see what happens.
> Added /classifications/offset?project_id=Y&last_id=X

- apiary.apib
- app/serializers/subject_serializer.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
fixes #1898 - add the subject set links to the subject resource
> include subject_sets in subject linked resources

- lib/role_control/controlled.rb
> remove unused code

- app/controllers/cellect_controller.rb
- spec/controllers/cellect_controller_spec.rb
Instead of just returning ids, it returns the necessary fields for cellect.
> Update CellectController responses to be more usable

- app/serializers/user_project_preference_serializer.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
Hopefully this is all that needs to be included.
> Added settings to UPP serializer

- Gemfile.lock
- lib/subjects/remover.rb
- spec/lib/subjects/remover_spec.rb
Use the new version with the server urls in by default.
> bump panoptes client gem

- app/controllers/cellect_controller.rb
- spec/controllers/cellect_controller_spec.rb
Add some caching headers to these end points (i wasn't sure about the max-age values)
> cellect api caching

- app/workers/medium_removal_worker.rb
don't swamp the queues with cleanup
> lower the priority for the medium removal worker

- spec/workers/subject_removal_worker_spec.rb
my bad on this, sorry. I was too rushed trying to get this out.
> remove errant focus

- app/controllers/cellect_controller.rb
- app/models/workflow.rb
- app/services/aggregation_client.rb
- app/services/cellect_ex_client.rb
- app/services/talk_api_client.rb
- config/initializers/cellect.rb
- config/initializers/cellect_ex.rb
- db/migrate/20160824101413_convert_use_cellect_to_enum.rb
- db/structure.sql
- docker-compose.yml
- lib/configurable.rb
- lib/subjects/cellect_ex_selection.rb
- lib/subjects/strategy_selection.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/controllers/cellect_controller_spec.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/lib/subjects/strategy_selection_spec.rb
- spec/models/workflow_spec.rb
- spec/services/aggregation_client_spec.rb
- spec/services/cellect_ex_client_spec.rb
- spec/services/talk_api_client_spec.rb
- spec/spec_helper.rb
- spec/support/configurable.rb
- spec/workers/reload_cellect_worker_spec.rb
- spec/workers/retire_cellect_worker_spec.rb
- spec/workers/retirement_worker_spec.rb
- spec/workers/seen_cellect_worker_spec.rb
> Gravity Spy subject selection service

- Dockerfile
> leave the git repo in the image

- app/services/aggregation_client.rb
- app/services/talk_api_client.rb
- lib/configurable.rb
- spec/support/configurable.rb
Normally you'd scratch your head about why things randomly fail. In this case, I'm actually not sure why it sometimes passes...
This will fix it in any case.
> Fix TalkApiClient random test failure

- .travis.yml
- spec/counters/subject_workflow_counter_spec.rb
Whoops, forgot to set these up in the travis run groups last time.
> make sure the spec counters actually run in travis 

- app/views/user_added_to_project_mailer/added_to_project.html.erb
- app/views/user_added_to_project_mailer/added_to_project.text.erb
I discovered a few of the mailer view links were broken when I finally got the emails. Fixed them here.
> Fixed mailer view links

- Gemfile.lock
For some reason this has been on my todo list...
> upgrade flipper

- apiary.apib
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
> ISO 638 is about wood pulp. ISO 639 is about language codes.

- app/workers/concerns/rate_limit_dump_worker.rb
> Fix congestion config for dump workers

- app/operations/create_classifications_export.rb
- app/operations/projects/create_aggregations_export.rb
- app/operations/projects/create_subjects_export.rb
- app/operations/projects/create_workflow_contents_export.rb
- app/operations/projects/create_workflows_export.rb
- spec/support/shared_for_creates_an_export.rb
> Fixes export content dispositions

- app/controllers/api/v1/users_controller.rb
- spec/controllers/api/v1/users_controller_spec.rb
> Do not send that email if the user is invalid

- app/controllers/api/v1/workflows_controller.rb
- app/models/set_member_subject.rb
- app/models/user.rb
Remove the finished experiments
> remove finished experiements and feature flags

- lib/subjects/postgresql_random_selection.rb
- lib/subjects/postgresql_selection.rb
- spec/lib/subjects/postgresql_random_selection_spec.rb
- spec/support/shared_examples_for_postgresql_selection.rb
small refactor and spec cleanup, still on the hunt for the intermittent spec failure here.
> Random selection cleanup code and specs

- app/controllers/api/v1/subject_sets_controller.rb
- app/workers/subject_removal_worker.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/workers/subject_removal_worker_spec.rb
see if we've solved the issue with high db cpu usage that this was disabled for.
> Reinstate subject removal

- app/controllers/api/v1/organization_contents_controller.rb
- app/controllers/api/v1/organizations_controller.rb
- app/controllers/concerns/filter_by_current_user_roles.rb
- app/models/concerns/translated_content.rb
- app/models/organization.rb
- app/models/organization_content.rb
- app/models/project_page.rb
- app/operations/organizations/create.rb
- app/operations/organizations/destroy.rb
- app/operations/organizations/update.rb
- app/serializers/concerns/content_serializer.rb
- app/serializers/organization_content_serializer.rb
- app/serializers/organization_serializer.rb
- app/serializers/project_serializer.rb
- config/routes.rb
- db/migrate/20161017135917_create_organizations.rb
- db/migrate/20161017141439_add_organization_contents.rb
- db/structure.sql
- spec/controllers/api/v1/organization_contents_controller_spec.rb
- spec/controllers/api/v1/organizations_controller_spec.rb
- spec/factories/organization.rb
- spec/factories/organization_contents.rb
- spec/models/organization_content_spec.rb
- spec/models/organization_spec.rb
- spec/models/project_content_spec.rb
- spec/serializers/organization_serializer_spec.rb
Probably a WIP PR, but I'd like some direction on where I should take this next and what needs to be done before it's safe to merge so that the PFE folks can start working on the UI component. 
Organization models (with content), controllers, and ACL associations are in there and are specced out. What's next?
> Organizations

- config/puma.rb
reduce the number of db connections for staging
> reduce staging puma threads

- config/initializers/doorkeeper.rb
Just the one change. Only the front end apps will need this functionality at start.
> Adds organization scope to doorkeeper

- app/workers/subject_set_subject_counter_worker.rb
Reschedule --> cancel on the SubjectSetSubjectCounterWorker when things get serious.
> Sound the alarm, blare the horn, shut it down, shut it all down forever

- config/initializers/graylog.rb
Filter out messages from sidekiq, sidetiq and about sent emails (which would be fine but ActionMailer logs the email address).
> Add more filters to semantic logger

- app/workers/subjects_dump_worker.rb
- lib/formatter/csv/subject.rb
- spec/lib/formatter/csv/subject_spec.rb
- spec/workers/subjects_dump_worker_spec.rb
closes #1943 dump all subjects in subject sets for a project and report the classification count per workflow as well.
> Dump all subjects

- app/services/cellect_ex_client.rb
- spec/services/cellect_ex_client_spec.rb
supersedes #2058 - handle server down connection error for cellect_ex
use a single request method and refactor the specs to test the active public interface.
> handle request connection errors

- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/media_controller_spec.rb
Also adds specs for workflows + media links.
> Adds classification export info to serialized workflows

- apiary.apib
> Fix jpeg mime type

- .rubocop.yml
> Disable FrozenStringLiteralComment

- app/schemas/tutorial_create_schema.rb
- app/schemas/tutorial_update_schema.rb
- app/serializers/tutorial_serializer.rb
- db/migrate/20161212205412_add_display_name_to_tutorials.rb
- db/structure.sql
- spec/controllers/api/v1/tutorials_controller_spec.rb
- spec/factories/tutorials.rb
Blank by default, but there are only 220 rows in production so there shouldn't be any backfill issues.
> Adds display_name to tutorials

- app/serializers/project_serializer.rb
- spec/serializers/organization_serializer_spec.rb
- spec/serializers/project_serializer_spec.rb
Also adds a couple of specs to check the output against the constants in the controllers, which is about as authoritative a source for that list as is possible.
> Adds researcher_quote to serializer#fields

- README.md
Went through the setup instructions with @camallen and updated a couple of things.
> Update README with newest setup instructions

- app/controllers/api/v1/organization_roles_controller.rb
- app/models/organization.rb
- app/serializers/organization_role_serializer.rb
- config/routes.rb
- spec/controllers/api/v1/organization_roles_controller_spec.rb
- spec/models/organization_spec.rb
> Added role controller/serializer/spec for organizations

- app/serializers/project_serializer.rb
- app/serializers/workflow_serializer.rb
- spec/serializers/project_serializer_spec.rb
- spec/serializers/workflow_serializer_spec.rb
use new relic / cli tools to test this end point behind a feature flag to avoid testing the AR cache layer
> remove preloading projects and workflows experiments

- spec/models/workflow_spec.rb
make sure we check for a specific error and avoid the warning message in the spec output.
> check for an invalid record

- app/controllers/applications_controller.rb
Reviewed offline by @astopy 
Immediate merge.
> Fix doorkeeper application scoping

- spec/controllers/applications_controller_spec.rb
> Add tests for applications controller

- app/serializers/project_serializer.rb
- spec/serializers/project_serializer_spec.rb
avoid the avatar n+1 load on project cards route
> preload load the avatar resource on cards route

- .rubocop.yml
shut the hound up about single quotes...
> ignore string single quote style check in hound

- app/serializers/project_serializer.rb
> only include preloads once

- Dockerfile
- Dockerfile.dev
try and speed up the gem installs when building images.
> parallel gem installs

- Gemfile
- Gemfile.lock
- config/environments/staging.rb
add elastic cache dalli store configuration for staging
> Elastic cache dalli store

- config/initializers/cache_store.rb
my bad on this one...didn't test this code path.
> fix spelling of panoptes module

- app/serializers/organization_serializer.rb
Just adds the `primary_language` attribute to the OrganizationSerializer.
> Adds primary_language to org serializer

- app/serializers/organization_serializer.rb
> Add roles to can_include in organization serializer

- app/serializers/event_stream_serializers/project_serializer.rb
- app/serializers/event_stream_serializers/workflow_serializer.rb
With this, Caesar can be smarter about when to update workflow configuration / subject metadata caches.
> Stream the updated_at for workflows and projects

- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- app/serializers/event_stream_serializers/workflow_serializer.rb
- app/serializers/workflow_serializer.rb
- db/migrate/20170206161946_add_nero_to_workflow.rb
- db/structure.sql
- spec/controllers/api/v1/workflows_controller_spec.rb
Adds a dedicated place for Nero config to go.
> Nero config on workflow

- db/structure.sql
regenerate the auto-generated structure.sql for the db.
> fixes for auto-generated structure.sql

- app/views/classification_heartbeat_mailer/missing_classifications.html.erb
- app/views/classification_heartbeat_mailer/missing_classifications.text.erb
- app/workers/classification_heartbeat_worker.rb
- config/heartbeat_config.yml.hudson
- config/initializers/heartbeat_config.rb
- spec/workers/classification_heartbeat_worker_spec.rb
don't cry wolf in staging system, provide better copy with rails env and only run in staging. Happy to change the recipient list from a yaml config to env vars if peeps want.
> production only classification heartbeat warning

- db/migrate/20170118141452_add_recents_foreign_keys.rb
- db/migrate/20170215105309_remove_recents_foreign_keys.rb
- db/structure.sql
> Comment out recents foreign key migration

- app/mailers/project_request_mailer.rb
- config/project_request.yml.hudson
- spec/mailers/project_request_mailer_spec.rb
add a bcc for slack integration and updated the to address to point to a list now (still via yaml). Happy to change to env vars, etc if folks want.
> add bcc for project-review emails

- app/models/project.rb
- app/models/workflow.rb
actually test the serializer wrapper with data instead of just an empty page.
> test workflow restpack serializer modifications with actual data

- scripts/docker/sidekiq-quiet.sh
- scripts/docker/sidekiq-stop.sh
> Add scripts for cleanly stopping sidekiq

- README.md
Ensure new setups have doorkeeper PKI config files setup.
> setup via the rake task and note doorkeeper keys

- app/workers/publish_classification_worker.rb
- spec/workers/publish_classification_worker_spec.rb
> Shard classifications by subject ids too.

- lib/favorites_finder.rb
- spec/lib/favorites_finder_spec.rb
Adds a feature flag for the 'favorite' bit of the subject serializer.
> Added feature flag skip

- app/operations/create_or_update_medium.rb
- spec/support/shared_for_creates_an_export.rb
> Include state in classifications export metadata on update

- app/serializers/user_serializer.rb
- lib/serialization/panoptes_restpack.rb
- spec/serializers/user_serializer_spec.rb
This can be used by PFE to prevent it needing to do N+1 queries.
> Add user['avatar_src'] to JSON

- app/serializers/project_serializer.rb
Includes the CacheSerializer concern in the ProjectSerializer. One of several PRs incoming to be included incrementally.
> Adds caching to project serializer

- db/migrate/20170310131642_add_inverted_indices.rb
- db/migrate/20170310131642_add_media_linked_id_index.rb
- db/structure.sql
So that asking for included images with a tutorial takes less than 60 seconds.
> Adds index to media.linked_id

- app/models/user.rb
cache this value for a decent session time (1 hour) to avoid paying this cost on page reloads
> count the user uploaded subjects for longer to speed up login refreshes

- app/serializers/field_guide_serializer.rb
> Adds cache to field guide serializer

- app/serializers/collection_serializer.rb
> Adds caching to collections serializer

- app/models/user_seen_subject.rb
pretty sure this was an experiment to get better vis into the seens but the queries times weren't feasible
> remove no longer used code

- app/serializers/workflow_content_serializer.rb
> Adds cache to workflow contents serializer

- app/serializers/project_content_serializer.rb
> Adds cache to project contents serializer

- app/serializers/project_page_serializer.rb
> Adds caching to project page serializer

- config/initializers/panoptes.rb
Went negative on this one since that was the app logic. Also added a DISABLED flipper for this feature.
closes https://github.com/zooniverse/Panoptes/issues/2247
> ENV var --> flipper

- app/schemas/project_update_schema.rb
Was missing, guess no one ever needed to pause a project.
Don't think there are any specs needed.
> Add state to project update schema

- app/controllers/concerns/json_api_render.rb
until we test this is staging, we don't want to activate this code path.
> disable http caching in production

- apiary.apib
Update the docs on subject queues and make a note about task allocation.
> Update docs on subject_queues

- app/workers/notify_subject_selector_of_change_worker.rb
- app/workers/notify_subject_selector_of_retirement_worker.rb
- app/workers/notify_subject_selector_of_seen_worker.rb
- app/workers/project_classifications_count_worker.rb
- app/workers/project_classifiers_count_worker.rb
- app/workers/reset_project_counters_worker.rb
- app/workers/subject_set_subject_counter_worker.rb
- app/workers/subject_workflow_status_count_worker.rb
- app/workers/workflow_classifications_count_worker.rb
- app/workers/workflow_retired_count_worker.rb
- spec/workers/project_classifications_count_worker_spec.rb
- spec/workers/subject_workflow_status_count_worker_spec.rb
- spec/workers/workflow_classifications_count_worker_spec.rb
> Restore pre sgl code

- app/models/subject_workflow_status.rb
> add 'human' as valid retirement reason

- app/controllers/api/v1/organizations_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/concerns/slug.rb
- app/models/organization.rb
- app/models/project.rb
- app/serializers/organization_serializer.rb
- db/migrate/20170524205300_add_index_to_organization_slug.rb
- db/structure.sql
- spec/controllers/api/v1/organizations_controller_spec.rb
- spec/models/organization_spec.rb
Also removes redundant code: The only difference between the included `#slugged_name` and the one in the actual Project model is is the lack of a `#try`, on display_name, which is enforced via the model/schema anyway and shouldn't be needed anywhere. 
Removed also the param-massaging for slugs, since they're computed and are not updatable via the API.
> Includes slug concern on orgs

- .rubocop.yml
does what it says on the tin, trying to get rid of rubocop noise via houndci
> upgrade rubocop config

- .rubocop.yml
- .rubocop_todo.yml
- .travis.yml
- Dockerfile
- Dockerfile.dev
- Gemfile.lock
- README.md
- lib/tasks_visitor.rb
- spec/lib/json_schema_spec.rb
- spec/models/subject_queue_spec.rb
- spec/support/shared_for_creates_an_export.rb
upgrade to latest ruby version
> bump to ruby 2.4

- app/models/medium.rb
- spec/models/medium_spec.rb
related to recent changes in the front end https://github.com/zooniverse/Panoptes-Front-End/pull/3863. Seems browsers / systems may detect them differently, e.g.
test_file.mp3: 
file cmd, terminal: audio/mpeg
chrome browser file.type: audio/mp3
test_file.m4a: 
file cmd, terminal: audio/mp4
chrome browser file.type: audio/x-m4a
> allow upload of audio files

- app/serializers/collection_serializer.rb
- lib/serialization/panoptes_restpack.rb
- spec/serializers/collection_serializer_spec.rb
- spec/serializers/workflow_serializer_spec.rb
- spec/support/panoptes_restpack_serializer.rb
preload the default subject and any media locations
> avoid N+1s in collection serializer

- config/puma.rb
Not sure why this is staging only but this will manually start the agent on boot
> manually start new relic for staging env

- Gemfile
- config/puma.rb
> run new relic in staging

- app/models/user.rb
- app/workers/user_added_to_project_mailer_worker.rb
- app/workers/user_info_changed_mailer_worker.rb
- app/workers/user_welcome_mailer_worker.rb
- lib/user_info_scrubber.rb
- spec/lib/user_info_scrubber_spec.rb
- spec/models/user_spec.rb
Can someone sanity-check if there might be more places we need to strip information?
> Add function to respond to user removal requests

- app/serializers/project_serializer.rb
linked to #2462 allow projects to be filtered on their org id
> add project organization_id filtering

- app/serializers/user_serializer.rb
- lib/serialization/page_with_cached_metadata.rb
Unsure how to approach testing this. :(
> Cache the total count for users resource

- app/models/translation.rb
- spec/models/translation_spec.rb
don't let the db not null error propagate here
> validate presence of language code for translation

- app/workers/classifications_dump_worker.rb
- app/workers/concerns/dump_worker.rb
- app/workers/subjects_dump_worker.rb
- app/workers/workflow_contents_dump_worker.rb
- app/workers/workflows_dump_worker.rb
- spec/workers/classifications_dump_worker_spec.rb
allow dynamic switching from read slave / master using flipper.
> add feature flag to disable dumping from read slave

- app/serializers/organization_serializer.rb
Fixes https://github.com/zooniverse/Panoptes/issues/2514
> Swap listed_at for listed in the org serializer

- app/controllers/api/v1/translations_controller.rb
- app/schemas/translation_create_schema.rb
- config/routes.rb
- lib/json_api_controller/precondition_check.rb
- lib/routes/constraints/translations.rb
- lib/routes/json_api_routes.rb
- spec/controllers/api/v1/translations_controller_spec.rb
- spec/requests/v1/translation_route_constraint_spec.rb
- spec/support/api_request_helpers.rb
Properly test the custom translation route constraints to avoid 404's to unknown_route. Correctly test the ETag resource on update and fill in the polymorphic translated resource keys on the create payload using the schema validation.
> Allow create and update actions for translations

- .github/stale.yml
use the enhancement label to avoid stale bot closing issues we'd like to keep open. Happy to use another label / rethink this.
> Stale bot ignore issues

- app/workers/subject_set_subject_counter_worker.rb
> Add Honeybadger call to get backtrace of enqueue location

- Gemfile
- Gemfile.lock
- app/controllers/graphql_controller.rb
- app/graphql/api_user_type.rb
- app/graphql/avatar_type.rb
- app/graphql/graphql_schema.rb
- app/graphql/json_type.rb
- app/graphql/organization_type.rb
- app/graphql/project_type.rb
- app/graphql/query_root.rb
- app/models/api_user.rb
- app/models/organization.rb
- app/models/project.rb
- config/routes.rb
- spec/models/organization_spec.rb
> Graphql: beginnings

- app/controllers/graphql_controller.rb
- app/graphql/organization_type.rb
- app/graphql/project_type.rb
- app/graphql/query_root.rb
* Fixes displayName fields.
* Adds admin-mode
* Uses existing authorization layer for loading organizations. This lets you access your own private orgs.
> Graphql fixes

- app/workers/subject_set_subject_counter_worker.rb
Reverts zooniverse/Panoptes#2550
Hasn't happened again in these past days. @camallen how often were these errors before?
> Revert "Add Honeybadger call to get backtrace of enqueue location"

- Gemfile.lock
Patches https://nvd.nist.gov/vuln/detail/CVE-2017-17042
> bump versionist and thus yard CVE

- db/migrate/20171208141841_remove_subject_queues.rb
- db/structure.sql
Commit is fine, but tests will be failing until merge of #2561.
> Remove subject_queues table

- app/controllers/api/v1/collections_controller.rb
- app/models/collection.rb
- app/models/user.rb
- app/serializers/collection_serializer.rb
- db/migrate/20171208142645_convert_collection_belongs_to_many.rb
- db/structure.sql
- lib/tasks/migrate.rake
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/factories/collections.rb
- spec/serializers/collection_serializer_spec.rb
- spec/serializers/subject_selector_serializer_spec.rb
- spec/serializers/subject_serializer_spec.rb
We should have a think about how to deploy this seamlessly. I think if we migrate, run the task, and then deploy new API nodes, we should be okay, but someone else also coming to that conclusion would be very much helpful.
> Convert Collection.projects to habtm association

- app/controllers/api/v1/projects_controller.rb
- app/models/project.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- db/migrate/20180110133833_add_featured_to_projects.rb
- db/structure.sql
- spec/models/project_spec.rb
> Add featured flag to projects

- app/models/gold_standard_annotation.rb
noting that this data is for specific projects and was sliced out of classification table and long term can go, not till the projects finish / port to the new feedback subject metadata mechanism though.
I was trying to figure out what this table contained the other day and decided to make a note about it.
> add note about what the gold standard annotations table is

- spec/serializers/medium_serializer_spec.rb
argh - i really hope nothing slipped through with this little beast in there.
> remove focus spec

- .travis.yml
- scripts/no_focus.sh
I expect this to fail first, and then I'll rebase on new master.
> Fail tests if focussed

- app/controllers/api/v1/users_controller.rb
- spec/controllers/api/v1/users_controller_spec.rb
So that I can build micro services for handling bounces and spam complaints.
> Allow admins to edit a user's valid_email attribute

- README.md
> Add note about config for tests to README.md

- Dockerfile.dev
cleanup old tmp files in dev docker image to ensure it's available for the start.sh container entrypoint
> add tmpreaper to Dockerfile.dev

- lib/json_api_controller/updatable_resource.rb
ensure updating resource associations roll back on error by wrapping these operations in the transaction
> wrap the whole update operation in a transaction

- app/serializers/user_serializer.rb
To aid with spam complaint processing (but also at some point the front end should tell users when their email address is invalid).
> Serialise User's valid_email attribute

- .rubocop_todo.yml
- README.md
- Rakefile
- config/boot.rb
- db/dev_seed_data/dev_seed_data.rb
remove outdated gem refs and the working around fig (what became docker-compose)
> remove all references to fig_rake and fig (docker-compose)

- app/serializers/user_serializer.rb
- db/migrate/20180403150901_add_ux_testing_email_field_to_user.rb
- db/migrate/20180403160419_add_ux_testing_email_field_index.rb
- db/structure.sql
- spec/controllers/api/v1/users_controller_spec.rb
A new email list for ux testing, this will have to be wired up for email settings page in PFE too.
> Add user ux testing email communications field

- app/views/devise/registrations/new.html.erb
for oauth signup routes we need to match the work on the front end for GDPR compliance.
> add required labels on signup page

- app/workers/calculate_project_completeness_worker.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
Fixes https://app.honeybadger.io/projects/40595/faults/37557468#notice-params
Ensure we handle missing workflows when calculating project completeness metrics.
> handle missing workflows for completeness worker

- app/views/devise/sessions/new.html.erb
> Fix login submit

- .rubocop.yml
avoid hound warnings on valid rspec syntax. https://github.com/rubocop-hq/rubocop/issues/4222#issuecomment-290655562
> allow rspec change block syntax

- app/models/subject_workflow_status.rb
- app/workers/calculate_project_completeness_worker.rb
- spec/models/subject_workflow_status_spec.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
Linked to #2796 - After a review new relic data i've optimized some of the data access paths in some heavily used workers, notably only retrieving required data from the database to avoid serializing information we just ignore.
> Optimize background workers

- app/workers/user_seen_subjects_worker.rb
drop jobs that have the same seen payloads while another is running
> avoid updates for the same seen payloads

- spec/workers/concerns/dump_mailer_spec.rb
avoid brittle spec failures based on db fetch ordering
> ensure email order in dump_mailer specs

- .travis.yml
stay up to date with ruby like our docker builds
> allow travis to bump to the latest minor version

- app/views/devise/mailer/reset_password_instructions.html.erb
> Add note about password reset token expiration

- Jenkinsfile
This uses a new separate Dockerhub repo, since the other one is an automated build and I didn't want to replace Production just yet.
https://jenkins.zooniverse.org/job/Zooniverse%20GitHub/job/Panoptes/job/jenkinsfile/
> Jenkinsfile for staging

- app/views/project_request_mailer/project_request.html.erb
- app/views/project_request_mailer/project_request.text.erb
We should set expectations here, because it'll probably be about a month before they hear from us.
> Change "shortly" to "a few weeks" in project review confirmation email

- app/workers/subject_set_statuses_create_worker.rb
- app/workers/subject_workflow_status_create_worker.rb
> Status workers feature flagged

- spec/workers/subject_set_statuses_create_worker_spec.rb
- spec/workers/subject_workflow_status_create_worker_spec.rb
> Fix worker specs

- app/policies/classification_policy.rb
- app/policies/concerns/filter_by_project_id.rb
- app/policies/gold_standard_annotation_policy.rb
- spec/policies/classification_policy_spec.rb
avoid the NOT IN on index search, use an IN instead.
> Invert the forbidden project to a whitelist of allowed projects

- spec/models/access_control_list_spec.rb
Cleanup old generated spec file
> culling the pending specs for ACL model

- Gemfile.lock
make sure the gem is specifically downgraded in the lockfile
> update Gemfile.lock for 0.17.3 celluloid

- lib/tasks/migrate.rake
Fix the rake task to backfill the org contents to orgs
> inherit the env for the rake task

- Jenkinsfile
closes #2856 - Add production tag reflection to jenkins file to support the building of the production AMIs on production tag updates.
> add production tag image builds

- Jenkinsfile
> remove duplicate latest tag push

- app/controllers/api/v1/workflows_controller.rb
- db/migrate/20180821151555_add_content_fields_to_workflow.rb
- db/structure.sql
- lib/tasks/migrate.rake
- spec/controllers/api/v1/workflows_controller_spec.rb
> Write workflow content strings to Workflow directly

- app/controllers/api/v1/projects_controller.rb
- app/models/project.rb
- db/migrate/20180821125430_add_content_fields_to_project.rb
- db/structure.sql
- lib/tasks/migrate.rake
- spec/controllers/api/v1/projects_controller_spec.rb
> Write project content attributes to projects directly

- apiary.apib
> Update apiary with Org documentation

- apiary.apib
ensure the org docs show up as resources not stuck under the project create docs
> fix organization indentation

- app/views/dormant_user_mailer/email_dormant_user.text.erb
utm_source: 'dormant'
utm_campaign: depends is the email is for a user with a last user
project preference, so 'classification' or no last upp so 'no_classification'
utm_content: depends on which url was followed. 'a' is the all projects
page, 'b' is a specific project link, 'c' is the talk page link.
> Update the urls to contain google analytic codes

- app/serializers/organization_serializer.rb
- app/serializers/project_serializer.rb
- app/serializers/workflow_serializer.rb
- spec/factories/projects.rb
- spec/factories/workflows.rb
- spec/serializers/organization_serializer_spec.rb
- spec/serializers/project_serializer_spec.rb
Reverts zooniverse/Panoptes#2925
Seems this is missing backfilled data or there is a bug: 
1. https://app.honeybadger.io/projects/40595/faults/39591599
0. https://app.honeybadger.io/projects/40595/faults/39591600
> Revert "Contents read from model"

- app/workers/email_dormant_users_worker.rb
- spec/workers/email_dormant_users_worker_spec.rb
send these emails when the system is not busy
> lower sidekiq queue priority for dormant user emails

- app/workers/dormant_user_mailer_worker.rb
- spec/workers/dormant_user_mailer_worker_spec.rb
Make sure we don't keep trying to send emails to invalid email addresses
> unsubscribe dormant users with invalid emails

- lib/tasks/migrate.rake
We have a bunch of invalid models on production (e.g. a project's `display_name` not unique for owner). Easier to just ignore them.
> Do not validate models when copying contents

- Jenkinsfile
Linked to https://github.com/zooniverse/operations/pull/133 and https://github.com/zooniverse/operations/pull/134 
Avoid jenkins issues with it not building the production tag
> switch to production-release tag

- app/models/project.rb
- app/models/project_version.rb
- db/migrate/20181015112421_add_project_versions.rb
- db/structure.sql
- spec/models/project_spec.rb
Intentionally leaving out the published-version part of this, so that I can get this merged and used for the translation work.
> Project Versioning

- db/seeds.rb
> Setup some default enabled flipper features

- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
> Output unknown combo task subtask types directly

- db/migrate/20181203164038_wf_version_indices.rb
- db/structure.sql
- spec/policies/workflow_version_policy_spec.rb
Needed when we start using them for exports, but also useful for the backfill (which upserts using this).
> index workflow versions by workflow and version numbers

- Gemfile.lock
bump the gem to fix locking bugs
> upgrade sidekiq unique jobs

- app/controllers/graphql_controller.rb
Fixes https://app.honeybadger.io/projects/40595/faults/42956731
> Fix Graphiql introspection query

- app/models/workflow.rb
- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- app/serializers/workflow_serializer.rb
- db/migrate/20181002145749_add_workflow_steps.rb
- db/structure.sql
- spec/factories/workflows.rb
> Add steps as a JSON property to workflows

- README.md
Add the OSS badge requirement https://pullreminders.com/badge
> add pullreminders badge for OSS license

- app/serializers/event_stream_serializers/classification_serializer.rb
- app/serializers/event_stream_serializers/workflow_content_serializer.rb
- lib/classification_dump_cache.rb
- lib/formatter/csv/annotation_for_csv.rb
- spec/factories/classifications.rb
- spec/factories/workflows.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
- spec/serializers/event_stream_serializers/classification_serializer_spec.rb
Do not merge until we've backfilled production.
> Export using workflow versions

- spec/lib/formatter/csv/annotation_for_csv_spec.rb
merge of https://github.com/zooniverse/Panoptes/pull/3017 left some differently named variables in the spec
> update spec to fix unknown variables

- .github/main.workflow
thanks to the amazing team from pull reminders who helped setup a GH action https://github.com/pullreminders/label-when-approved-action
> add label for approved pull requests via github actions

- app/workers/calculate_project_completeness_worker.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
> Pause project when there are no active workflows

- db/migrate/20190220114950_add_project_version_timestamps.rb
- db/structure.sql
- lib/tasks/backfill_project_versions.rb
> Backfill project versions

- app/models/translation.rb
- app/models/translation_version.rb
- app/schemas/translation_update_schema.rb
- app/serializers/translation_serializer.rb
- app/serializers/translation_version_serializer.rb
- config/routes.rb
- db/migrate/20190220155414_add_translation_versions.rb
- db/migrate/20190220161628_add_translation_published_version.rb
- db/structure.sql
- spec/models/translation_spec.rb
- spec/serializers/translation_serializer_spec.rb
Track a published version of translations, and provide API support to query it.
> Translation published version

- docs/source/includes/_subject_set_imports.md
- docs/source/index.html.md
Copied over from documentation written for LSST.
> Add docs for subject set imports

- lib/tasks/migrate.rake
This has already been run this way, but documenting for posterity.
> Fix Org/Project page versions backfill rake task

- app/controllers/omniauth_callbacks_controller.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
don't overwrite the current user session if it exists
> check already signed in on oauth callback

- apiary.apib
- app/serializers/workflow_serializer.rb
- spec/serializers/workflow_serializer_spec.rb
filter out complete and incomplete via the workflow's completness attritbue
> add workflow complete filter

- db/dev_seed_data/dev_seed_data.rb
ensure local apps are not set to confidential, this will allow them to convert session cookies to tokens
> ensure first_party apps can login

- .travis.yml
rds instance is 9.5 now, test on travis with the correct server version
> bump to the server version of postgres

- docker-compose.yml
bump the postgres version and remove the unused cellect selection system
> cleanup docker compose

- config/cors_config.yml.hudson
match the changes from in #3206 and #3199
> update the default cors configs

- config/initializers/cellect.rb
- docker-compose.yml
> remove old cellect env var

- Dockerfile.dev
- docker-compose.yml
- scripts/docker/start.sh
streamline the gem install process to the docker image build and re-use these via named volumes, https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container
This allows all gems to be cached between image building / manual install in the container for reuse and avoids the cost of installing gems on boot.
> Optimize docker dev setup

- Dockerfile
- Dockerfile.dev
- README.md
switch to using the docker cmd syntax for easier docker / compose commands
> Use cmd syntax

- app/models/project.rb
- spec/models/project_spec.rb
towards #2968 serialize the available languages for a project
> serialize all published languages for a project

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
> K8s yaml fix

- Jenkinsfile
> Use git commit hash, not branch name, in docker image name

- kubernetes/deployment-staging.tmpl
> Use staging env vars in staging

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
ensure this env var propagates from secret to the container
> add DATABASE_URL to k8s deployment templates

- scripts/docker/start.sh
> remove AWS emergency mode cruft

- config/database.yml
add staging & production standby read replica configurations as per docs here https://github.com/kenn/standby#install
Also, the URL env var overrides any duplicate information in the yaml config,:
>If non-duplicate information is provided you will get all unique values, environment variable still takes precedence in cases of any conflicts.
https://guides.rubyonrails.org/v4.2/configuring.html
> add staging & production db configurations

- scripts/docker/restart_puma.sh
non-clustered mode requires a different restart signal, https://github.com/puma/puma/blob/master/docs/restart.md#restarts
this will be for local / dev restarts as deployment will use K8s rolling restart instead https://github.com/zooniverse/panoptes/pull/3315#issuecomment-631511492
> Puma change to normal restart signal

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
Copies the nginx config from the AWS production deployment
> Add Nginx container for assets

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
> Add liveness probes and nginx resources

- kubernetes/deployment-staging.tmpl
I think this was a copy/paste error.
> Fix typo in liveness probe for staging

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
ensure the nginx live probe to the upstream proxy works without a redirect (fail)
> masquerade as HTTPS to avoid redirects from upstream proxy

- config/initializers/cors.rb
- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
update the env var name and ensure it's aligned to the k8s templates
> use CORS_ORIGINS_REGEX env

- Jenkinsfile
> Add K8 dry run

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
just pass a string without the outer slashes as they are being created at https://github.com/zooniverse/panoptes/blob/d7463caac4c97e29ce058dceac9adf5da1a5014b/config/initializers/cors.rb#L23
> avoid extra outer regex forward slashes

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
> Add doorkeeper jwt key to sidekiq

- Jenkinsfile
> Update production tag name in Jenkinsfile

- kubernetes/deployment-production.tmpl
This is a minor thing, but we may as well be consistent with the names.
> Rename production nginx to panoptes-production-nginx

- kubernetes/deployment-production.tmpl
> Make RAILS_MAX_THREADS a string

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
cancel API db queries after ingress connection timeout
linked to #3278
> add PG_STATEMENT_TIMEOUT to API containers

- .hound.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
use newer version and opt into new linters, http://help.houndci.com/en/articles/2461415-supported-linters
> Update rubocop linter

- kubernetes/deployment-production.tmpl
same as in #3373 just for prod
> add gracefull nginx preshutdown cmd

- kubernetes/deployment-production.tmpl
To be merged when we're ready to switch this domain to Azure. Also needs a DNS update in Route 53.
> Add panoptes.zooniverse.org to ingress config

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
I've already reconfigured the running redis instances accordingly, so it should be safe to deploy this.
> Disable appendonly in redis

- migrate.sh
remove AWS specific config / env setup
> cleanup migrate.sh

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
This new image will log to stdout rather than to disk, which should hopefully help with performance.
> Switch to new (official) nginx image

- Jenkinsfile
> Remove extra Jenkins success notifications

- kubernetes/deployment-production.tmpl
run more API pods to see the perf characteristics at lower pod CPU targets
> decrease the HPA cpu target to 50%

- kubernetes/deployment-production.tmpl
linked to #3389 this time for production
> use temp disk for prod dump scratch space

- Jenkinsfile
Switch to double quotes to allow variable substitution and escape new line.
> Fix sed command for job name

- kubernetes/deployment-production.tmpl
match the old AWS ASG values of 2 webserver processes on each node (8).
> increase the max HPA replica limit to 16

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
> Add PodDisruptionBudget

- kubernetes/deployment-production.tmpl
related to #3334 - remove the unused nginx health_check locations
> remove unused nginx health_check locations

- kubernetes/deployment-production.tmpl
Closes zooniverse/operations#431
> Add signin.zooniverse.org to ingress

- kubernetes/deployment-production.tmpl
update cors allow list to remove heirtagger
> remove heirtagger.ox.ac.uk from cors allow list

- README.md
allow cmds like `rails s` to be accessible via host computer
> add service ports for bash example

- db/migrate/20200720125246_remove_classification_export_row_model.rb
- db/structure.sql
linked to #3433 - drop the associated table and indexes from the schema
> drop the classification_export_row table

- kubernetes/deployment-staging-azure-canary.tmpl
> Fix canary serviceName

- kubernetes/deployment-staging-azure-canary.tmpl
add the shared config files / config maps in #3445 to staging API canary
> add nginx config maps config files to staging canary

- kubernetes/deployment-staging-azure-canary.tmpl
> change STORAGE_ADAPTER env var to correct name

- kubernetes/deployment-staging-azure-canary.tmpl
Update env var to reflect change in storage account being used (switching to `panoptesuploadsstaging`)
-------
> update STORAGE_URL env var

- lib/subjects/selector.rb
provide ability to run fallback selection on the read replica
this feature will be enabled via a flipper feature flag, it'll be on by default to move the SQL subject selection load to ther replica which has capacity to run this
> run fallback selection on read replica

- app/controllers/api/api_controller.rb
- app/controllers/concerns/json_api_responses.rb
- spec/requests/kamiari_zero_page_spec.rb
avoid kaminari raising errors, instead provide a decent error message and useful HTTP response code
> handle invalid page_size 0 json api request params 

- app/controllers/api/v1/classifications_controller.rb
move this read query load off the primary db to the replica
> fetch serialised classification data from read replica

- Jenkinsfile
- kubernetes/job-rake-task-production.tmpl
Linked to #3461 add a production env template and ensure we validate these templates via jenkinsfile
> Add prod rake task template for running in K8s

- kubernetes/deployment-staging.tmpl
Cutover to using azure blob storage on staging.
------------
> switch storage adapter to azure

- README.md
closes #3504 - remove the outdated links
> remove wiki links from readme

- Jenkinsfile
What the title says 😎
----------
> add canary production template to prod deploy

- kubernetes/deployment-production.tmpl
Reverts zooniverse/panoptes#3514
kinesis issues are resolved and the backlog is processed, rolling back the temp increase in sidekiq workers to 1
> Revert "temp bump to 2 sidekiq replicas"

- docs/source/includes/_subject_set_imports.md
remove the horizontal rules as they don't fit the page formatting (go across the whole page), https://zooniverse.github.io/panoptes/#feature-description
> remove horizontal rule in docs

- app/views/project_request_mailer/project_request.html.erb
- app/views/project_request_mailer/project_request.text.erb
Add link for "Project Review Best Practices" doc in project mailer (reply for beta requests, project launch updates).
> Add link for project review best practices doc in project beta mailer

- lib/tasks/migrate.rake
* Update incorrect class name `Media` to `Medium` 😓 
* fix use of `.zero?`
Task has been tested successfully locally.
> Supernova task: fix errors

- Jenkinsfile
> Post to #deploys instead of #ops

- config/initializers/cors.rb
ensure our frontends can access this route when running x-domain
> add unsubscribe route to CORS setup

- .github/workflows/run_tests_CI.yml
- spec/controllers/api/v1/subjects_controller_spec.rb
first attempt at migrate the CI tests run from travis to GH actions
> add GH actions run tests CI worfklow

- .github/workflows/run_tests_CI.yml
switch the GH CI test runners from docker to native ruby
linked to #3637 as that syntax isn't supported (easily) in GH actions
> switch to native ruby gh action CI

- spec/services/cellect_client_spec.rb
related to the changes in #3642 
This PR ensures the `CELLECT_HOST` env var is setup for the spec
> add CELLECT_HOST for testing env

- spec/services/cellect_client_spec.rb
avoid race conditions on the ENV vars across specs. Fixes the CI failures on master merges that aren't visible on the PR runs, e.g. https://github.com/zooniverse/panoptes/runs/3172397590
> use class method stub vs ENV var setup

- kubernetes/deployment-staging.tmpl
avoid ipv6 connections on localhost connection (localhost is used to communicate between containers in a pod)
> use ipv4 localhost address

- README.md
updates the status badges away from travis CI
> use GH actions CI runner status badge

- app/workers/calculate_project_completeness_worker.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
This PR adds the project state transition behaviour that moves a project to a paused state if there is no linked subject on any of the active workflows (i.e. it's out of data).
Some project teams unlink all the active subject sets when the workflow / project is finished but leave the workflow active, this will avoid these projects coming back to active.
> improve project paused state transitions

- app/serializers/project_serializer.rb
linked to #3737 - ensure we serialize the attribute on the project resource
> serialise the run_subject_set_completion_events attribute

- .github/workflows/deploy_staging.yml
- .github/workflows/run_task_staging.yml
- Jenkinsfile
- kubernetes/db-migrate-staging.tmpl
- kubernetes/job-task-staging.tmpl
Adds staging deploy workflow, includes migration job. Updates templates to use GHCR. Adds staging task runner.
> Action: staging migration and deploy

- app/views/subject_set_import_completed_mailer/notify_project_team.text.erb
- spec/mailers/subject_set_import_completed_mailer_spec.rb
Linked to #3823 - updates the wording for the subject set manifest completed import email
> update wording email wording

- Gemfile.lock
bumps new relic gem to use APM traffic logging https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/get-started-logs-context
> update newrelic_rpm gem

- spec/lib/export/export_json_project_spec.rb
this PR fixes the project json export spec by ensuring the AR new method has a single hash param
> merge hash attributes for new object param

- .github/workflows/deploy_staging_canary.yml
> Use correct secret name

- .github/workflows/deploy_staging_canary.yml
> Use env without input

- docs/Gemfile.lock
> bundler to previous version

- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- kubernetes/deployment-staging.tmpl
> Prep staging upgrade to 5.0

- app/serializers/workflow_serializer.rb
allow workflows to be sorted on their completeness metrics - useful for some project where they want to find the incomplete / complete workflows for a project.
> allow sorting on workflows completeness attribute

- .github/workflows/codeql-analysis.yml
Adds codeql scanning to the repo https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#scanning-pull-requests
> add code-ql scanning

- app/models/concerns/language_validation.rb
- spec/models/organization_spec.rb
avoid the use of A-z as it includes non alpha chars
> update the language code regex for 3 letter subtags

- .github/workflows/deploy_staging_canary.yml
- kubernetes/deployment-staging-canary.tmpl
> update templates to canary rails 5.1 in staging

- .github/workflows/deploy_staging.yml
> Update deploy_staging.yml to build from Dockerfile.rails-next (related to Rails 5.1 to build in staging)

- Gemfile.next.lock
linked to recent gem patches - this fixes the CI to work with the `BUNDLE_GEMFILE=Gemfile.next bundle install` setup
> install jquery to gemfile next lock file

- app/models/medium.rb
- spec/models/medium_spec.rb
update tests and add validation to medium resource to allow specific content types
> add validation to medium resource 

- .github/workflows/publish_docs.yml
https://github.com/zooniverse/middleman-gh-pages-action/releases/tag/v1.2.0
> use v1.2.0 of zooniverse/middleman-gh-pages-action

- Gemfile
- Gemfile.lock
https://www.mikeperham.com/2019/09/03/welcome-to-sidekiq-6.0/
Upgrading to sidekiq 6. One of the biggest breaking changes is 
>  Remove the daemonization, logfile and pidfile command line arguments and sidekiqctl binary.
which I don't believe we are using anyway.
> upgrade to sidekiq 6

- Gemfile.next.lock
> Update Gemfile.next.lock with sidekiq 6.0.7

- .guardrails/ignore
we're not using this anymore since switching to GH code scanning
> remove guardrails configs

- app/models/csv_dumps/classification_scope.rb
this PR attempts to reduce the memory of large classification exports by using the `ActiveRecord::Base.uncached` method to disable the query cache for exports. https://api.rubyonrails.org/classes/ActiveRecord/QueryCache/ClassMethods.html#method-i-uncached
Note: find in batches does already ignore the query cache, https://github.com/rails/rails/issues/31175#issuecomment-345259529 however any queries in the subsequent block will be cached for the duration of the export. 
If this proves useful on the large classification exports then it may be useful across all exports as we don't reuse the cache AR query cache across batches (hence why it's already disabled for `find_in_batches`). 
If it doesn't prove useful we can revert this pr
Some related reading:
- …
> turn off AR query cache for classification exports

- .github/workflows/deploy_staging.yml
- kubernetes/deployment-staging-canary.tmpl
Update Staging to Rail 6.0 (building from Dockerfile.rails-next)
> Update Staging to Rail 6.0 (building from Dockerfile.rails-next)

- .github/workflows/deploy_staging.yml
- kubernetes/deployment-staging-canary.tmpl
Reverts zooniverse/panoptes#4111
Rails 6.0 in Staging has issues on Password Change via PFE profile Settings page. Reverting back to Rails 5.2 to see if this problem persists in our current version (vs issues with PJC/cors)
> Revert "Update Staging to Rail 6.0 (building from Dockerfile.rails-next)"

- lib/identity_group_name_validator.rb
update identity_group_name validator to add errors vs concat a frozen Array
> Rails upgrade 6.1  spec fixes - update identity_group_name validator to add errors vs concat a frozen Array

- kubernetes/deployment-staging-canary.tmpl
update canary tmpl to have 1 replica to test 6.1 in canary
> Rails 6.1 in Canary

- app/views/devise/confirmations/new.html.erb
Old form's submit button was broken. Updated some of the partials and fixed some warnings. Got as close to the right look as I could.
> Fix & update resend confirmation view

- app/controllers/api/v1/projects_controller.rb
- spec/controllers/api/v1/projects_controller_spec.rb
> 3298 edit project display name on delete activated state = inactive

- app/serializers/workflow_serializer.rb
> allow workflow sorting by id

- app/services/aggregation_client.rb
- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
Couple little changes needed to get the AggregationClient working.
> AggregationClient fix

- docs/source/index.html.md
Minor docs edit: add aggregations page to site, minor link fix.
> docs edit: add aggregations, fix link

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
staging and production redis version bump from  6.0 to 6.2
> staging and production redis version bump from  6.0 to 6.2

- kubernetes/deployment-production.tmpl
- kubernetes/deployment-staging.tmpl
Always dry-run apply template changes!
> Fix preStop indentation error

- Dockerfile.dev
- Dockerfile.rails-next
update dockerfile to use -slim and pg client 13
> update dockerfile to use -slim and pg client 13
