- config/application.rb
- config/environments/development.rb
- config/environments/staging.rb
According to cyu/rack-cors#33 it needs to at the top of the
middleware stack for recent versions of Rails 4
Closes #432 I believe.
> Move rack-cors to the top of the middleware stack

- config/application.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
#435 caused some problems by having multiple rack-cors instances. This makes sure only one is configured per environment.
> Split CORS configuration by environment

- lib/tasks_visitor.rb
- lib/tasks_visitors/extract_strings.rb
- lib/tasks_visitors/inject_strings.rb
- spec/lib/tasks_visitors/extract_strings_spec.rb
Visit by class so we can be more flexible in defining workflows
Maybe revisit (heh) when the format is more locked down
This should fix the 500 errors @brian-c was seeing.
> Visit by class name instead of key

- app/workers/classification_worker.rb
- config/sidekiq.yml.hudson
Panoptes wasn't processing any background jobs since they were all dumping to the default queue.
> Specify worker queue for sidekiq

- app/controllers/api/v1/subjects_controller.rb
- app/models/subject.rb
- db/migrate/20150129122349_add_uploading_user_id_to_subject.rb
- db/schema.rb
- spec/factories/subjects.rb
- spec/models/subject_spec.rb
Store the specific user id without a relation as subjects may outlive their users. Useful if we need to audit which user uploaded a subject. 
Not using an AR relation here just storing the user id as a subject may well outlive a user account.
> track which user uploads a subject

- app/serializers/user_serializer.rb
- spec/controllers/api/v1/users_controller_spec.rb
Closes #471 
Avoid costly queries to possibly large table / index scans. I don't think we need the actual instance ID links on the user instances to traverse the API. Instead we can use the non-instance links element for URL traversing to related models.
> ignore user model association link ids

- app/controllers/registrations_controller.rb
- app/models/user.rb
- lib/identity_group_name_validator.rb
- spec/controllers/registrations_controller_spec.rb
- spec/models/user_spec.rb
closes #494 
Don't use assignment on the `User#identity_group` has_one relation as this autosaves the relation regardless of the `User` model validity. Instead validate via the :through `identity_membership`relation.
I really with rails had builders for the `has_one :through` relations, we live and learn.
> do not orphan user identity groups

- app/models/user.rb
- app/serializers/user_serializer.rb
- db/migrate/20150205121848_add_users_display_name_index.rb
- db/schema.rb
- lib/user_info_scrubber.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/factories/users.rb
- spec/lib/user_info_scrubber_spec.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
closes #501 
Commit history should explain what i was doing. The only funky stuff was retying possibly race conditions on scrubbing personal details with dup UUID values and getting rspec to reuse the transaction after PG error. I had to turn off transactional fixtures (tests) add use a deletion strategy for that specific spec (:no_transaction key).
> allow uniq user filtering on display_name

- apiary.apib
- app/controllers/api/v1/classifications_controller.rb
- app/controllers/api/v1/subject_queues_controller.rb
- app/models/classification.rb
- app/models/user_seen_subject.rb
- app/models/user_subject_queue.rb
- app/schemas/classification_create_schema.rb
- app/serializers/classification_serializer.rb
- app/serializers/user_subject_queue_serializer.rb
- db/migrate/20150210025312_create_database.rb
- db/schema.rb
- lib/classification_lifecycle.rb
- lib/subject_relation.rb
- lib/subject_selector.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/controllers/api/v1/subject_queues_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/factories/classifications.rb
- spec/factories/user_seen_subjects.rb
- spec/factories/user_subject_queues.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/models/classification_spec.rb
- spec/models/user_seen_subject_spec.rb
- spec/models/user_subject_queue_spec.rb
Address Brian's concerns from #512. Hide set_memebr_subjects entirely.
I'll need to update the cellect_panotpes driver to use only subjects
> Subjects in classifications

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/project_roles_controller.rb
- app/serializers/access_control_list_serializer.rb
- spec/controllers/api/v1/project_roles_controller_spec.rb
partly solves #526 @edpaget can you have a look?
Filtering on the polymorphic access control list resource assocation requires the use of `resource_id` instead of the preferred `project_id`.
> expose public project roles 

- app/schemas/classification_create_schema.rb
- lib/json_schema.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/lib/json_schema_spec.rb
closes #520, closes #456 
Ad digit regex for classification id links (probably need to expand these to other links).
Add consistent error formatting for failed json schema validations (there may be more errors that i haven't seen todo).
> add digit regex for classification link ids

- Gemfile.lock
- app/serializers/access_control_list_serializer.rb
- app/serializers/acl_serializer.rb
- app/serializers/collection_role_serializer.rb
- app/serializers/project_role_serializer.rb
- spec/controllers/api/v1/projects_controller_spec.rb
Fixes #527, closes #526, closes #523 
#530 will depend on this work. Also this relies on an updated version of restpack serializer, https://github.com/edpaget/restpack_serializer/pull/3 so it'll fail till that become available via the dev branch.
> ensure the specialized serializers loaded on include by restpack

- config/initializers/honeybadger.rb
honeybadger now looks for a config/honeybadger.yml file by default.
> remove honey badger config init loader

- app/models/user.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
possible security issue where we don't compare hashed values == for older sha1 haah users (we don't have any)
> ensure passwords match for the sha1 hash algorithm

- app/middleware/catch_api_json_parse_errors.rb
- spec/middleware/catch_api_json_parse_errors_spec.rb
- spec/requests/v1/api_json_parser_errors_spec.rb
JRuby seems to raise a JSON::ParserError instead of one raised by MRI,
this just expands our middleware to catch both
> Catch JSON error raised in JRuby

- lib/zoo_user_warden_strategy.rb
- lib/zooniverse_user.rb
- spec/controllers/registrations_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/lib/zooniverse_user_spec.rb
- spec/spec_helper.rb
some real zoo_home_users have setup accounts on panoptes that share the login/display_name. Allow these accounts to be updated from zoo home so we don't have to remove dup account and orphpaning any existing linked instances e.g. projects, etc.
> allow existing panotpes user accounts to be updated

- app/controllers/api/api_controller.rb
- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
- lib/zoo_user_warden_strategy.rb
- spec/controllers/api/api_controller_spec.rb
- spec/controllers/non_paper_trail_controller_spec.rb
This fixes the panoptes-front-end failing api tests.
Paper trail adds before filters to rails's application controller that will call current_user to determine the whodunnit field. Devise controllers implement this method and were triggering the zoo_home warden authentication strategy when they shouldn't have. I've disabled paper trails in the application_controller base class and enabled it for the api end points. I could be more specific here and just enable it for the end points that are using versioning but it might add some surprises when people add new models and expect versioning to work.
> ensure zoo home auth strategy only runs when it should

- app/controllers/registrations_controller.rb
- config/initializers/doorkeeper.rb
- lib/zoo_user_warden_strategy.rb
- lib/zooniverse_user.rb
- spec/controllers/registrations_controller_spec.rb
- spec/controllers/tokens_controller_spec.rb
I think the issue with what was happening in the Front-End specs may have been related to failing to handle the rememberable token in the Warden strategy. I'm still figuring out how to test it but it may be worth hitting it with the front-end specs to see if anything happens.
> Set remember token in Zoo-Home authentication

- Dockerfile
This will run the API nodes on MRI. based on benchmarking on my dev machine MRI is ~3 times faster, I'm not 100% sure why but my first guess would be the jruby gems.
Dont merge untill the ruby:2.2.1 docker image is built, https://registry.hub.docker.com/u/zooniverse/ruby/builds_history/67460/
> Switch to mri ruby for the API nodes

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- config/initializers/cors.rb
- spec/requests/v1/api_cors_headers_spec.rb
Close #648 
Access-Control-Max-Age is set by rack CORS via max_age. This header overrides normal Cache-Control settings.
> ensure CORS requests cache for 5 minutes

- app/workers/retirement_worker.rb
Linked to the badger 11733166 - a cellect error will fail this job before cellect comes back online.
> retirement workers - retry as long as we can

- lib/cellect_client.rb
- spec/lib/cellect_client_spec.rb
spinning sidekiq workers getting stuck, perhaps related to timeout and thread.pass on cellect requests. Pity because this seemed to fix the cellect the scaling down issue.
> remove timeouts on cellect client

- supervisord.conf
Looks like this now defaults to localhost as a result of updates in #739
> Specify bind address for puma

- app/controllers/api/api_controller.rb
- app/workers/subject_queue_worker.rb
- lib/subject_selector.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/workers/subject_queue_worker_spec.rb
Build a subject queue when a user requests one and it doesn't exist. Also provide a better error message on a 404 when one doesn't exist.
Finally fix the workflow string ID in sidekiq param scoping, https://app.honeybadger.io/projects/40595/faults/12434093
> fix subject queues

- apiary.apib
- app/models/project.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- db/migrate/20150430084746_add_live_field_to_projects.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/projects.rb
- spec/models/project_spec.rb
addresses @aliburchard comments about live project https://github.com/zooniverse/Panoptes-Front-End/issues/240. Added a field to determine the status science mode status of a project that can be used to drive the UI and provide warnings to users about changing workflow configs, etc.
> add live mode field to project 

- spec/lib/classification_lifecycle_spec.rb
This should fix the failing spec.
> Use array_includes so order doesn't matter

- app/models/project.rb
- app/models/subject_set.rb
- app/models/user.rb
When a project is destroyed its subject sets and associated models
should also be destroyed, but we should keep subjects around in case
they are being used by other projects. Classifications and workflows
should also remain so we can still redo the since if necessary.
Subjects and Workflows can still be explicitly destroyed on their own.
Closes #652
> Add dependent relationships to models

- app/workers/classifications_dump_worker.rb
- config/application.rb
- config/aws.yml.hudson
- config/initializers/aws.rb
- lib/presenter/formatter_csv_classification.rb
- spec/workers/classifications_dump_worker_spec.rb
- spec/workers/subject_queue_worker_spec.rb
This should upload a csv dump of a project's completed classifications. I had to battle the specs for too long on this one. 
**Requires** the addtion of `export_bucket_path` to the aws.yml files
> classification csv export to s3 for a project

- config/application.rb
- spec/requests/v1/api_empty_array_spec.rb
Closes #743
Because most users of Rails are apparently unable or unwilling to check
params before passing arguments to AR#find, Rails converts empty arrays
in params to nil. This makes 0 sense to me, but whatever, it's easy to
turn off.
> Disable Deep Munging in Rails

- app/models/subject_queue.rb
- app/workers/subject_queue_worker.rb
- spec/models/subject_queue_spec.rb
- spec/workers/subject_queue_worker_spec.rb
Fixes #804 - Avoid calling en/de_queue methods with an empty args.
> don't attempt to update empty queues

- app/models/concerns/association_cache_key.rb
- app/models/concerns/extended_cache_key.rb
- app/models/project.rb
- app/models/workflow.rb
- spec/models/project_spec.rb
- spec/models/workflow_spec.rb
- spec/support/extended_cache_key.rb
Supersedes #815 
allow the resource's cache key to be created from association cache keys and selected method keys e.g. summary counters.
@edpaget I haven't specc'd this yet but wanted to run the idea by you. No need to merge just yet.
> allow the resource cache_key to include associations and methods

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/subjects_controller.rb
- app/controllers/concerns/api_errors.rb
- app/models/api_user.rb
- app/models/subject.rb
- app/models/user.rb
- config/initializers/user_limits.rb
- config/user_limits.yml.hudson
- db/migrate/20150512223346_add_uploaded_subjects_count_to_user.rb
- db/schema.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/factories/subjects.rb
- spec/factories/users.rb
- spec/models/subject_spec.rb
- spec/models/user_spec.rb
Adds a configuration file user_limits.yml with the form:
```
rails_env:
subjects: 1000
```
Leaving it empty for an environment will cause it to not limit the
number of subjects.
Closes #774
> Add limit on subjects uploaded from a user

- app/controllers/concerns/json_api_render.rb
- lib/json_api_controller/indexable_resource.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/support/indexable.rb
- spec/support/indexable_etag_response.rb
Do not enumerate the index action controlled resources to generate etags. Instead allow the serializer to apply the scope filtering and generate the etag from the response object. 
E.g. the users index action has the display_name filter using params[:display_name] but the etag generation used the User.active scope without applying the filter so would enumerate the whole collection of active users before hitting the serializer.
@edpaget so I thought about adding index action `scope_contexts` for the `Class.scope_for` methods but soon realized we'd have to understand which filters each model serializer allows and apply each controllers `scope_context`, that method totally works though. Anyway, instead i reverted back to adding the cache key on the serialised reponse object, except this time …
> generate index action etags on the response objects

- app/models/set_member_subject.rb
- app/models/subject_queue.rb
- app/models/subject_set.rb
- app/models/subject_sets_workflow.rb
- app/workers/queue_removal_worker.rb
- app/workers/reload_queue_worker.rb
- app/workers/subject_queue_worker.rb
- spec/factories/subject_sets_workflows.rb
- spec/models/set_member_subject_spec.rb
- spec/models/subject_queue_spec.rb
- spec/models/subject_sets_workflow_spec.rb
- spec/support/destructable.rb
- spec/workers/queue_removal_worker_spec.rb
- spec/workers/reload_queue_worker_spec.rb
- spec/workers/subject_queue_worker_spec.rb
This _kind of_ handles updating queues to reflect changes in subject sets (being dissociated from workflows/having subjects added or removed). It should handle actually removing the items from queues just fine, but introduces a few problems. 
* When a SubjectSet is deleted. It will double queue subject removal through both the `subject_sets_workflows` and `set_member_subjects` callbacks. This shouldn't cause any errors, but may strain sidekiq for large queues. 
* It could empty a user's queue entirely. This was cause the user's initial request for subjects to fail, but will trigger a reload of their queue. This could be addressed by refreshing queues after deletion. 
Overall it may be worth thinking more about destroying related objects. Right now, destroying a project with two Subject …
> Remove subjects from queues

- app/controllers/api/events_controller.rb
- app/schemas/event_create_schema.rb
- config/events_api_auth.yml.hudson
- config/initializers/events_api_auth.rb
- config/routes.rb
- spec/controllers/api/events_controller_spec.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/factories/user_project_preferences.rb
closes #750 
I think this covers all the use cases for the events api in zoo home. I've set it to raise errors in honeybadger for unknown event kind types so we can add them in. I've added a config file to prod configs with almost the same creds as ouroboros prod has, staging is slightly different but i don't think we'll use this unless we test the staging version of ourobros (prob should now i type this).
I did find that some of the legacy projects are using different basic auth keys so will have to audit them to make sure they are working properly.
> add json events api for legacy projects

- app/workers/classification_worker.rb
- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/workers/classification_worker_spec.rb
Fixes: https://app.honeybadger.io/projects/40595/faults/12807870 which is backing up in sidekiq with retires.
Do not attempt to track seen for anonymous classifications. Also always count towards retirement for anonymous users but don’t count towards retirement if a known user has seen them before.
@edpaget this does raise the question of anonymous users seeing the same subject in a session as per [here](https://github.com/zooniverse/Panoptes/issues/830#issuecomment-101422062) and if we should count these towards retirement as the two classifications are now not independent of each other. @ggdhines does this matter do you think? If we need to ignore these for retirement counts / aggregation then we'll need another field on the classification to track it.
> do not create user seens for anonymous classifications

- lib/zooniverse_user.rb
Fixes: https://app.honeybadger.io/projects/40595/faults/11655067
I ran into this with my account, the password updated but hash function didn't as the user already existed as a panoptes user. Instead now just update all the user account details and only build the avatar and identity group when it’s a new account.
> ensure the user details migrate correctly

- app/models/classification.rb
- app/models/user_seen_subject.rb
- app/schemas/classification_create_schema.rb
- app/schemas/classification_update_schema.rb
- lib/classification_lifecycle.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/factories/classifications.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/models/classification_spec.rb
- spec/models/user_seen_subject_spec.rb
- spec/workers/classification_worker_spec.rb
Closes https://github.com/zooniverse/Panoptes-Front-End/issues/359 based of discussion in #843 
This adds an optional `metadata#seen_before` boolean attribute that can be submitted if a volunteer (logged in & anonymous) has classified this subject before. @brian-c you ok with this solution if the subject has been seen before?
Happy to make changes, thought I'd get this into code for discussion.
> add metadata field to flag classifications for already seen subjects

- app/serializers/subject_serializer.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
Fixes #857 
RestpackSerializer doesn't allow optional conditions on the attribute definition. it uses the optional clause that adds a include_x? method definition that can be overridden.
> correct optional attributes in subject_serializer

- app/models/user_group.rb
- lib/identity_group_name_validator.rb
- spec/models/user_group_spec.rb
closes #871 and #872 
So this will fix the missing identity groups for migrated users. We'll need to recreate them with this code to be able to successfully run the slug creation migration.
> update identity user group validations

- app/models/collection.rb
- app/models/project.rb
- db/migrate/20150521160726_add_slug_to_projects_collections_and_users.rb
Inactive projects fail a validation since they user is also inactive
> Only create slugs for active projects

- app/models/subject_queue.rb
- app/models/user_seen_subject.rb
- db/migrate/20150527200052_enable_int_array.rb
- db/schema.rb
- lib/classification_lifecycle.rb
- lib/subject_selector.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/models/user_seen_subject_spec.rb
- spec/workers/classification_worker_spec.rb
Handle this bit of bookkeeping during the request/response cycle to make
sure seen subjects are never shown to users. Also apply the "uniq"
function in PostgreSQL to queues and seen lists to make sure they don't
contain duplicate data.
Enable the "intarray" extension in PostgreSQL, which is installed in
RDS, in order to make sure these array operations and faster and easier to understand.
This should Close zooniverse/Panoptes-Front-End#426 and zooniverse/Panoptes-Front-End#425
> Dequeue and update user seen subjects in sync

- lib/postgresql_selection.rb
- lib/subject_selector.rb
- spec/lib/subject_selector_spec.rb
If a user has a blank queue make sure to respond by using the database's
random selection with at least a few subjects while their queue is
replenished.
This should Close #882, Close zooniverse/Panoptes-Front-End#402, and
Close zooniverse/Panoptes-Front-End#393
> Always return some subjects from subjects route

- app/models/user_group.rb
- db/migrate/20150527223732_add_unique_index_to_slug.rb
- db/schema.rb
Which is slow and not indexable without using postgresql extensions, and
is also pointless for this task. This adds custom validation of the slug
column and a unique index
Closes #897
> Stringex's unique validation for urls uses SQL LIKE

- app/models/user_group.rb
- spec/models/user_group_spec.rb
Make sure no empty slugs are created and only update slugs if the
display_name actually changed
> Custom callback for creating user group slugs

- app/models/subject_queue.rb
- app/workers/queue_removal_worker.rb
- spec/models/subject_queue_spec.rb
- spec/workers/queue_removal_worker_spec.rb
Closes https://github.com/zooniverse/Panoptes-Front-End/issues/425
Use the union operator for set operations between lists of set_member_subjects to ensure no dups.
Also do not replenish a queue when deleting set_member_subjects, i.e. dequeuing. Dequeue works fine but replensihing all queues that fall below a minium straight after dequeue may add future non-existant data back into the queue. A new selection strategy that will return data and requeue if the queue is empty will avoid this need to replenish ahead of time.
> queue updates for duplicate and deleted set_member_subjects

- app/controllers/api/v1/media_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/mailers/classification_data_mailer.rb
- app/models/medium.rb
- app/models/project.rb
- app/serializers/concerns/media_links_serializer.rb
- app/serializers/medium_serializer.rb
- app/serializers/project_serializer.rb
- app/workers/classification_data_mailer_worker.rb
- app/workers/classifications_dump_worker.rb
- config/routes.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/factories/projects.rb
- spec/factories/users.rb
- spec/lib/accept_language_extractor_spec.rb
- spec/lib/export/export_json_project_spec.rb
- spec/mailers/classification_data_mailer_spec.rb
- spec/serializers/project_serializer_spec.rb
- spec/workers/classification_data_mailer_worker_spec.rb
- spec/workers/classifications_dump_worker_spec.rb
Pass a metadata key "recipients" when a classification export is created
with user ids and only those users will receive email notifications when
the dump is ready.
If no key is passed the project owner will be notified.
Closes zooniverse/Panoptes-Front-End#446
Closes zooniverse/Panoptes-Front-End#399
Closes #914
> Select users to notify about classification dumps

- app/serializers/workflow_serializer.rb
- spec/serializers/workflow_serializer_spec.rb
closes #883, track the workflow version by the index into the versions array not the id of the version model. 
@edpaget FYI - this will change the submitted workfow version ID of all live projects for aggregation.
> use the workflow index number not the id

- app/schemas/classification_create_schema.rb
- app/schemas/classification_update_schema.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
May be useful information to determine when a user classified. This came up the other day when we were assessing Penguin Watch competition annotations. The annotation time stamps are in UTC so it'd be nice to add another field to capture the UTC offset of the client computer to have more insight into when a user classifies.
> add client utc_offset to classification metadata

- app/models/user.rb
- spec/models/user_spec.rb
split the validations between presence and format for migrated / normal users
> ensure user display name is always present

- app/controllers/api/v1/workflows_controller.rb
- app/models/subject_set.rb
- lib/json_api_controller/relation_manager.rb
- spec/controllers/api/v1/groups_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/subject_set_spec.rb
- spec/support/updatable.rb
closes #907 link the subject_set to a workflow and copy a subject set if it belongs to another project.
@edpaget can you make sure i'm doing this correctly and adding the SubjectSet `can_be_linked` scopes to show.
Also looks like we need to spec `Projects#update_links` as per the [docs](http://docs.panoptes.apiary.io/#reference/projects/project-create-links/add-a-link) as well as the `PUT` ones [here](https://github.com/zooniverse/Panoptes/blob/b90088a15a3d079072b795bfa9d5f1d0b253a6a4/spec/controllers/api/v1/projects_controller_spec.rb#L522).
> copy subject_set to workflow via update_links

- lib/talk_api_client.rb
- lib/tasks/talk.rake
- spec/lib/talk_api_client_spec.rb
Include scopes in token and make sure it using the token field instead
of the whole object
> Fix Talk API client to set correct token

- app/controllers/api/v1/users_controller.rb
- app/controllers/application_controller.rb
- app/serializers/user_serializer.rb
- db/migrate/20150605103339_add_beta_email_to_users.rb
- db/schema.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/factories/users.rb
Resolves the back end part of https://github.com/zooniverse/Panoptes-Front-End/issues/415
Add a field to users to track which users want to receive beta emails. Also expose this and the project_email_communications attribute through the user serializer for the logged in user.
The beta list is planned to be managed like the zoo wide list using JiscMail so we may not need the indexes. I can see query use cases for them though.
> Track beta users

- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
Related to #942 copying a subject set didn't copy any subjects. This PR ensures that when copying a subject set from another project that the subjects are also copied.
> copy set_member_subjects with subject_set

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
Change behaviour to ensure a logged out queue will eventually exist when attempting to build a queue for a logged in user.
Ran into this when testing out the project builder as the front end doesn't call workflow show routes now so the logged out queue doesn't get prebuilt under some combination of setup.
> build a logged out queue if none exists

- app/controllers/api/v1/subjects_controller.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
Linked to https://github.com/zooniverse/Panoptes-Front-End/issues/512 
Passing filtering params will exclude valid values from the serialized response. E.g. filtering subjects based on project_id for copied subjects (default subject set) will exclude these values from the response.
> do not allow filtering params to subejct serializer

- app/workers/talk_admin_create_worker.rb
- lib/talk_api_client.rb
- spec/lib/talk_api_client_spec.rb
There's no production talk at the moment, so just log that we tried to talk (heh) to it and do nothing.
> When talk isn't configured log api attempts

- app/controllers/api/api_controller.rb
- spec/support/versioned_resource.rb
whodunnit was storing the user object id and not the id of the database record.
> track the id of the modifying user for paper trail versions

- app/controllers/api/v1/subjects_controller.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
admin users will have to upload large data sets for projects.
> ignore subject limits for admin users

- README.md
Added a couple minor notes that might not be clear to someone who hasn’t done much with Docker yet.
> Expand README for the first-use experience

- lib/tasks/migrate.rake
allow a list of display_name and only migrate users that don't have a login field set.
> Optimize user login migration

- app/controllers/api/v1/subject_sets_controller.rb
- app/workers/count_reset_worker.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/workers/count_reset_worker_spec.rb
Delete links without callbacks and manually queue workers. Closes #974
> Speed up destroy_links for subject sets

- Gemfile.lock
- app/controllers/concerns/filter_by_owner.rb
- spec/controllers/api/v1/projects_controller_spec.rb
older identity groups may have a different case to the login field so we need to use a case insensitive query path here.
http://preview.zooniverse.org/panoptes/#/projects/VVH/prettiest-pugs
http://preview.zooniverse.org/panoptes/#/projects/OxfordGreg/star-trek-aliens
> case insensitive owner filter on the idenity group

- app/serializers/user_serializer.rb
- lib/tasks/migrate.rake
- spec/serializers/user_serializer_spec.rb
Let's the front-end know to ask them if they want to change their login
name on the first visit for returning users.
> Include login_prompt parameter on serializer

- db/migrate/20150622085848_add_not_null_login_users.rb
- db/schema.rb
Seems the prod & staging db’s are slightly inconsistent due to manual migrations last week. Ensure the prod system has a not null constraint on the user’s login column.
> ensure user login field cannot be null

- app/models/project.rb
Multiple export media shouldn't exist. However, my staging dump shows that they do. I wonder if that might be the issue causing #1006, since as far as I can see the medium being returned is always receiving some update call, so the updated_at should always be touched automatically.
> Always return the newest exports if multiple exist

- lib/zooniverse_user_subscription.rb
cache as much as possible to reduce the load on the target db. Not really happy with the coupling between the instance and class methods but i didn't want to refactor to extract the state to a migration driver.
> optimize the subscription migration

- spec/support/dump_worker.rb
@camallen mentioned in #979 that running the specs leaves exports in the ./tmp. This is the reason that happens.
> Make sure to still remove tempfile after spec runs

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/controllers/concerns/api_errors.rb
- app/controllers/concerns/json_api_responses.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/factories/projects.rb
Closes #894 - live projects should not have workflows added to them without consultation / approval. A project should downgrade use the front end to development and re-apply for launch / beta approval status.
> reject creation of a workflow for a live project

- app/workers/classifications_dump_worker.rb
- spec/factories/classifications.rb
- spec/workers/classifications_dump_worker_spec.rb
Classifications for deleted workflows should not be included in the export ad most of the classification knowledge is embedded in the workflow.
FYI - i found a chain of factory girl create associations that creates an unexpected number of records. We can seriously reduce our test setup limes by finding these and eliminating them.
> Do not export classifications for workflows that have been deleted

- app/controllers/api/events_controller.rb
- spec/controllers/api/events_controller_spec.rb
more robust error handling for the events api message as well as using the correct param, my bad.
> better error handling and correct message type is event

- app/controllers/passwords_controller.rb
- app/models/user.rb
- config/initializers/devise.rb
- spec/controllers/passwords_controller_spec.rb
- spec/models/user_spec.rb
Fixes #1051.
Still returns an error if the user supplied no email param at all (form error vs leaking information about existence of users). Not sure if the way it's doing it currently works well with the frontend, possibly we need to return it like a validation error on `email` instead of just a blanket 422 status without body?
> Return HTTP 200 unless no email param was supplied

- app/models/user.rb
- spec/models/user_spec.rb
hijacked the valid password method to ensure users are valid to login, this will allow migrated staging users to login. I can alternatively run the data migration on staging if this is too hacky.
> ensure migrated users have a valid unsubscribe token

- app/schemas/event_create_schema.rb
- spec/controllers/api/events_controller_spec.rb
fix the legacy events api first visit messages
> first_visit message don't have counts

- db/migrate/20150706133624_fix_index_definitions.rb
- db/schema.rb
seems our partial indexes were not being used by queries, e.g.
```
######## BEFORE ##########
[1] pry(main)> Project.where(beta_requested: true).explain
Project Load (0.7ms)  SELECT "projects".* FROM "projects" WHERE "projects"."beta_requested" = $1  [["beta_requested", "t"]]
=> EXPLAIN for: SELECT "projects".* FROM "projects" WHERE "projects"."beta_requested" = $1 [["beta_requested", "t"]]
QUERY PLAN
-----------------------------------------------------------
Seq Scan on projects  (cost=0.00..18.47 rows=1 width=332)
Filter: beta_requested
(2 rows)
######## AFTER ##########
[1] pry(main)> Project.where(beta_requested: true).explain
Project Load (1.3ms)  SELECT "projects".* FROM "projects" WHERE "projects"."beta_requested" = $1  [["beta_requested", "t"]]
=> EXPLAIN for: SELECT "projects".* …
```
> update partial indexes to allow our queries to hit them

- app/controllers/emails_controller.rb
- config/routes.rb
- spec/controllers/emails_controller_spec.rb
Linked to https://github.com/zooniverse/Panoptes-Front-End/pull/964
Allow json post requests and try to avoid exposing email addresses.
> redirect only unless a required param is missing

- app/mailers/jisc_mailer.rb
- app/views/jisc_mailer/subscribe.text.erb
- app/workers/subscribe_worker.rb
- spec/mailers/jisc_mailer_spec.rb
- spec/workers/subscribe_worker_spec.rb
add commands were bouncing due to invalid real names, using no names now via spec http://www.lsoft.com/manuals/16.0/htmlhelp/list%20subscribers/LSCommands.html
> use wildcard for real name in jiscmail list

- app/models/user_seen_subject.rb
- app/serializers/user_project_preference_serializer.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
- spec/factories/projects.rb
- spec/factories/user_seen_subjects.rb
- spec/models/user_seen_subject_spec.rb
closes #1080 use the counts on the UPP if they are set, otherwise sum from the user seens in the DB.
> Project pref serialized responses

- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
Should fix #1087 - we we're updating the seen subjects then testing if a user had seen the subject to fire the count workers. Seems we only ever managed to count towards retirement was when the ClassificationWorker fired off before the UserSeenSubject update seens transaction completed.
This PR reworks the order of events in the lifecycle transact method to make sure the count worker fires before we update the user seens. I don't think this will impact on duplicate subjects for users see [this commit](https://github.com/zooniverse/Panoptes/commit/2ec96166d2e619bf0cdc4a447edc1770a435a026) but it's something to keep in mind when reviewing.
> Ensure retire workers fire for incoming complete classifications

- app/controllers/api/v1/users_controller.rb
- app/controllers/registrations_controller.rb
- app/workers/subscribe_worker.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
allow subscribe worker to accept email and name params but only forward the email onto the mailer.
> update subscribe worker params

- app/workers/user_welcome_mailer_worker.rb
- spec/workers/user_welcome_mailer_worker_spec.rb
Users created via the API and then deactivated / deleted will not have an email. Staging tests this process and may try to fire emails with a to field.
> do not welcome users without an email

- app/controllers/api/v1/workflows_controller.rb
- app/models/project.rb
- app/models/workflow.rb
- lib/json_api_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
@marten - ok so this was a little more complex but related to the check a resource exists before_action. Our system uses custom authorisation which is defined on the models via roles and is then checked in `controlled_resource(s)` controller actions / filters. Since you were adding a non-standard controller action it wasn't obvious that this is what needed to happen. 
Have a look around and fire any questions via this PR so we've got some context to talk about it.
> Retire via api

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/serializers/project_serializer.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
...allows projects to be included property wherever they're needed
Closes #1064
> Always include the language context

- lib/subject_selector.rb
- spec/lib/subject_selector_spec.rb
allow page size selection params to cascade into the subject selector.
> convert page size string values to ints

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
PostgreSQL will always sort the integers when performing some array operations, including union and difference. That meant that `set_member_subject_ids` would become sorted upon both enqueue and dequeue of any subject (but the initial creation of the queue would be with a shuffled array).
By simply always returning a random selection from the list of enqueued ids, we ensure that we always return a random selection. This also allows for more complicated ordering on a per-workflow basis later on by doing something other than `array.sample()`.
It also means you can use F5 to get a different subject (which @aliburchard wanted I believe).
Fixes #1033
> Always return randomly selected subjects from the queue

- app/models/subject.rb
- app/models/subject_workflow_count.rb
- app/serializers/subject_serializer.rb
- db/migrate/20150717123631_add_uniq_subject_workflow_count_index.rb
- db/schema.rb
- lib/formatter/csv/subject.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/formatter/csv/subject_spec.rb
- spec/models/subject_spec.rb
- spec/models/subject_workflow_count_spec.rb
Move away from the `SetMemberSubject#retired_workflow_ids` instead use the `SubjectWorkflowCount#retired_at` field in data dumps and the `Subject#retired_for_workflow?` method.
> update code to use new retirement schema

- app/controllers/api/v1/media_controller.rb
- lib/json_api_controller/precondition_check.rb
- spec/requests/v1/api_conditional_request_spec.rb
closes #1149 - generate an etag via the index route for linked media has_one relations and modify the precondition check for the media controller.
> proper etags for singular linked media resources

- app/workers/count_reset_worker.rb
- spec/workers/count_reset_worker_spec.rb
Seems some subject set are deleted before classifications came back from clients and the .reset_counters calls .find internally so will raise the not found error.
> handle deleted subject sets in the count workers

- app/workers/user_welcome_mailer_worker.rb
- spec/workers/user_welcome_mailer_worker_spec.rb
closes https://github.com/zooniverse/Panoptes-Front-End/issues/1155
catch the errors don’t try and send again and mark the user as invalid email.
Not sure if the `rescue Net::SMTPSyntaxError => e` is too broad or will catch the errors we need with invalid params here. I think it's ok but i couldn't quickly find any decent docs on it.
> handle an invalid email address on welcome

- app/controllers/api/v1/user_groups_controller.rb
- app/serializers/user_group_serializer.rb
- config/routes.rb
- spec/controllers/api/v1/user_groups_controller_spec.rb
Tried to start writing something against the front-end and ran into 404s
looking for the 'user_groups' route and realized my inconsistent naming
was making this a lot more difficult than it needed to be.
Since nothing relies on these routes it should be safe to just change
/groups routes to /user_groups routes.
> Rename groups_controller to user_groups_controller

- app/controllers/emails_controller.rb
- spec/controllers/emails_controller_spec.rb
Keep existing behaviour of pre email links allow /unsubscribe url to redirect to front end no token is supplied.
> consistent redirect behaviour

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/projects_controller.rb
- app/models/project.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- db/migrate/20150722180408_add_ranks_to_projects.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/projects.rb
- spec/support/admin_only_option.rb
When projects are requested with beta_approved or launch_approved they
will be sorted by default by their assigned ranking.
Closes #1161
> Add ranking to projects

- app/workers/retirement_worker.rb
- spec/workers/retirement_worker_spec.rb
HBadger is reporting these errors from our retirement worker. It's most likely a counter being updated behind the scenes so just avoiding the error as we just want to deactivate the workflow when it’s finished.
Maybe not the best way to avoid these errors so happy to change if there are better ideas.
> avoid optimistic lock errors when deactivating workflows

- app/models/set_member_subject.rb
- lib/set_member_subject_selector.rb
- spec/factories/subject_workflow_counts.rb
- spec/lib/set_member_subject_selector_spec.rb
- spec/models/set_member_subject_spec.rb
- spec/models/subject_workflow_count_spec.rb
- spec/workers/count_reset_worker_spec.rb
I was classifying on a project that was returning no subjects when i was logged in, turns out I'd seen all the non-retired images. This PR will return data as if the user has seen all data / workflow is finished by a merge of the two clauses `non_retired_for_workflow` and `unseen_for_user`. 
Also when i was breaking up the queries, I'm pretty sure we were being too restrictive with the join on user_seen_subjects (inner join) which wouldn't have returned subjects we hadn't seen. 
@edpaget @marten I'd like a few sets of eyes on this to make sure the resulting sql is correct, also happy to spec out more examples if needed.
> Always return some data to classify

- lib/classification_lifecycle.rb
- lib/subject_selector.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/lib/subject_selector_spec.rb
- spec/models/subject_queue_spec.rb
closes #1176 - get set member subject ids out of the queue asap and let them replenish if they are needed when the queue's replenish.
This should hopefully avoid any race condition between classification processing and next subjects calls by increasing the time window between.
> dequeue set_member_subject ids after selection

- app/controllers/api/v1/subjects_controller.rb
- app/models/subject.rb
- app/serializers/subject_serializer.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
Record the index of the location (as it was sent by the client) in the
metadata field of the medium object and order by that field when its
serialized
Closes #1159
> Make sure subject locations remain ordered

- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/workers/classification_worker_spec.rb
Closes #1164 - Added live_project field to incoming classification metadata and refactored how classification lifecycle events work to ensure errors are raised before updating touching other models / firing new worker events and db calls are kept to a minimum.
> track project live state in incoming classifications

- lib/gem_ext.rb
- lib/gem_ext/doorkeeper/application.rb
- lib/gem_ext/doorkeeper/client_credentials_creator.rb
- spec/controllers/tokens_controller_spec.rb
Prevent applications marked insecure from using their credentials to
retrieve tokens. Make sure the token belongs to the application owner
Closes #1095
> Allow tokens retrieval with client credentials

- app/controllers/api/api_controller.rb
- app/controllers/application_controller.rb
- spec/requests/v1/api_id_spec.rb
- spec/requests/v1/api_not_found_spec.rb
We only use session to get OAuth tokens, which will fail 422 with a null
session anyway, so instead of throwing and error on non-api routes and
skipping CSRF protection on api routes, we'll just use the null_session
handling instead.
Closes #1117
> Handle CRSF errors with a null session

- db/migrate/20150729165415_remove_set_member_subjects_retired_workflow_ids.rb
- db/schema.rb
closes #1205 - I'm pretty certain we don't use this any more for retirement so we should be good to remove the col and the index from the db.
> remove legacy retirement tracking

- app/models/project.rb
- spec/models/project_spec.rb
As discussed in #1139
I'm not sure if/when we want this to go, but it's a pretty straightforward change.  Of course, it'll require updating the existing records as well as the front end.
> Form project slugs to include owner name

- app/models/project.rb
- spec/models/project_spec.rb
skip this callback on create actions, only run on updates.
> only send notifications for persisted projects

- app/controllers/api/v1/memberships_controller.rb
- lib/role_control/actor.rb
- lib/role_control/roled_controller.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/user_groups_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/lib/role_control/actor_spec.rb
- spec/support/active_controlled_resources.rb
Closes #1222 - only use active resources in controlled scopes when the controlled resource responds to the activatable enum scope.
> Deactivated controlled resources

- app/controllers/api/v1/aggregations_controller.rb
- app/models/aggregation.rb
- db/migrate/20150730160541_add_aggregation_config_for_workflow.rb
- db/schema.rb
- lib/role_control/roled_controller.rb
- spec/controllers/api/v1/aggregations_controller_spec.rb
- spec/models/workflow_spec.rb
- spec/support/indexable.rb
Closes #1213 - Add per workflow aggregation config object and open up the index route to allow access if the supplied workflow id is public.
> Public aggregation access by workflow config

- config/application.rb
- config/cors_config.yml.hudson
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- config/initializers/cors.rb
closes #1233 - Replace env specific hard coded configs for a derived envs from the yaml file. the yaml file requires requires some care to conform to the expected format
> config cors middleware from yaml file

- app/controllers/sessions_controller.rb
- spec/requests/sign_in_spec.rb
closes #1236 - spec out the behaviour required for the sign in json route
> set csrf headers on sign_in json request

- app/models/concerns/preferences.rb
- app/serializers/user_serializer.rb
- db/migrate/20150727212724_add_private_profile_to_users.rb
- db/schema.rb
- spec/factories/user_collection_preferences.rb
- spec/factories/user_project_preferences.rb
- spec/models/user_project_preference_spec.rb
- spec/support/preferences.rb
Allows users to mark their classification counts (and possibly future
parts of their profile) as private
Closes #1066
> Add private_profile flag to users

- app/models/subject_queue.rb
- spec/lib/postgresql_selection_spec.rb
- spec/models/subject_queue_spec.rb
closes #1241 - turns out it's hard to maintain order of arrays in postgres. All the operators i found / tried modified returned sorted lists (asc).
This will just iterate over the scoped models calling update with ruby land array ordering. These methods should not be called outside of background workers unless the scope is restrictive enough e.g. [here](https://github.com/zooniverse/Panoptes/blob/0bce1f69f7bdd192b284bfd8be31250a596fad4f/lib/subject_selector.rb#L88).
I looked into something funky in the db to keep the `update_all` command but failed to get it working properly. Any ideas for AREL / SQL optimisations here are welcome.
```
select * FROM 
unnest(array[8,7,6,1,2,5]) WITH ORDINALITY AS set1(ids, num)
full join
(select * from unnest(array[5, 55]) as ids) as set2
on set1.ids = …
```
> preserve queue id ordering

- lib/postgresql_selection.rb
- spec/lib/postgresql_selection_spec.rb
sort by ascending order for priority to allow open ended lists and prepend via negative numbers.
> make priority sort order static

- app/controllers/api/v1/subject_sets_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/models/subject_queue.rb
- app/workers/empty_subject_queue_worker.rb
- app/workers/enqueue_subject_queue_worker.rb
- app/workers/reload_non_logged_in_queue_worker.rb
- lib/postgresql_selection.rb
- lib/set_member_subject_selector.rb
- lib/subject_selector.rb
- lib/tasks/subject_queue.rake
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/subject_queue_spec.rb
- spec/workers/empty_subject_queue_worker_spec.rb
- spec/workers/enqueue_subject_queue_worker_spec.rb
- spec/workers/reload_non_logged_in_queue_worker_spec.rb
I've had a few cases recently when i've had to empty existing queues, so i've added more explicit existing subject queue worker names and added worker to empty workflow queues. Also added a rake task to run them.
> subject queue workers

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
Revert "Always return randomly selected subjects from the queue, since the queue is always sorted by id"
This reverts commit 0f9e41a6383590be807ec87cf3b66428b14aa6e3.
This will be needed for priority queues.
> Access queue in order they were built for a logged in user

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
Linked to #1069, try and get some visibility about queueing errors. This will check if
1. a duplicate id is being enqueued to the current queue
2. the queue is growing beyond 2 * the set default
3. a seen before id is being enqueued
This is temporary and should be deployed after #1249 is in and the queues have been emptied. Manual inspection of the queues showed some have grown very large and may not be refreshing at all.
> add notifications around duplicate being queued

- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
Vestigal cellect behaviour to load data, panoptes should not enqueue on every workflow show event. This was adding dups to the queues and growing the queues past expected sizes. 
Happy to add a check on queue sizes via enqueue if needed in future but it'd be nice to see if this PR cleans up the erroneous behaviour we're seeing.
> Subject Queue enqueue duplicates and unbound growth

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
do not enqueue subjects the user has already seen. workaround until the underlying cause of the seen_before dups are found. Note: we still get notified of the error event in honey badger but this will not queue the seen before dup for future classification.
> strip any seen before ids before enqueue

- app/models/subject_queue.rb
- lib/non_duplicate_sms_ids.rb
- spec/models/subject_queue_spec.rb
more robust dup removal and cleaner service class. 
Not sure how long we want this to hang around so specc'd its behaviour through subject queue, can spec the class itself if needed but kind of want to get this into prod to get better messaging (more info on dups)  and not queue any kind of dup for end users.
> refactor to dup removal class for existing queue

- spec/lib/postgresql_selection_spec.rb
Should fix intermittent spec failures as pg selection cutoffs may not construct the max random sample before being cutoff.
> check between expected limits

- app/models/medium.rb
- app/views/classification_data_mailer/classification_data.html.erb
- app/views/classification_data_mailer/classification_data.text.erb
- app/views/subject_data_mailer/subject_data.html.erb
- app/views/subject_data_mailer/subject_data.text.erb
- app/workers/concerns/dump_worker.rb
- spec/models/medium_spec.rb
> Allow downloading subject/classification dumps for 24 hours

- app/models/subject_queue.rb
- lib/subject_selector.rb
- spec/lib/subject_selector_spec.rb
- spec/models/subject_queue_spec.rb
Ensure the queue that data is being added to is for the right user and that we only update the sms_ids when new data is coming in.
Should fix the unbound queue growth and queueing seen_ids for users when they've finished the workflow.
> Queue improvements

- app/controllers/api/events_controller.rb
- app/serializers/user_project_preference_serializer.rb
- db/migrate/20150817145756_add_legacy_count_to_project_preferences.rb
- db/schema.rb
- lib/zooniverse_user_subscription.rb
- spec/controllers/api/events_controller_spec.rb
> Import and store legacy project counts by workflow

- app/models/user.rb
- spec/models/user_spec.rb
clean up empty sanitized logins from ouroboros by using the zooniverse id. 
I'm not sure if we should have the sanitize method in ouroboros as well so we don't end up with unicode logins in the db. that said any attempt to login on the new infrastructure *should* clean these up anyway.
> do not leave invalid blank logins

- app/models/user_project_preference.rb
- app/models/user_seen_subject.rb
- app/serializers/user_project_preference_serializer.rb
- spec/controllers/api/events_controller_spec.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
- spec/factories/user_project_preferences.rb
- spec/models/user_project_preference_spec.rb
handle busted per workflow counts like `{ "" => nil, "bars" => 10 }` from legacy data.
> User project preferences updates

- scripts/docker/start.sh
To temporarily work around a bug in Docker which can stop the assets
container from being created during build. It should be rare that this
happens, and worst case this will just add a couple of minutes to the
deploy time.
> Add fallback to compile assets on start

- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
closes #1227 - attempt to use the workflow version for the specified classification workflow version. if there is no version available it will revert to the latest version.
> respect workflow and content versions for classification dumps

- app/models/user_project_preference.rb
- spec/models/user_project_preference_spec.rb
some migrated activity counts are actually strings..
> treat counts as numbers

- Dockerfile
- supervisord.conf
So that we can use net=host in Docker when we deploy, without it conflicting with Nginx.
> Switch Puma to listen on port 81

- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- app/serializers/workflow_serializer.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
closes #1239 - allow aggregation configuration object to workflows. Currently used to set the aggregations to be public, e.g. `aggregation: { "public": true }`.
> Aggregation config schemas to workflow for create / update actions

- Gemfile
- Gemfile.lock
- app/models/classification.rb
- config/initializers/active_model_serializers.rb
- lib/classification_lifecycle.rb
- lib/kafka_classification_serializer.rb
- lib/kafka_project_serializer.rb
- lib/kafka_subject_serializer.rb
- lib/kafka_user_serializer.rb
- lib/kafka_workflow_serializer.rb
- lib/serialization/v1_adapter.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/lib/kafka_classification_serializer_spec.rb
The V1Adapter I've added is compatible (for this case, in general there might be a few minor differences with RestPack, haven't exhaustively checked) with output from RestPack. The V1Adapter is basically a copy of an older AMS adapter from before they started working towards JSON-API 1.0, with a few naming changes to be like RestPack.
AMS has a built-in JsonApi adapter (which I've made default in initializer) which follows the 1.0 spec for JSON-API.
Apart from that, AMS "just works" with things like belongs_to_many, has support for virtual associations as well, just define a method on the serializer and state at the top that it has_many or belongs_to that method name.
Fixes #1072
> Kafka classification stream using AMS instead of RestPack

- apiary.apib
- app/controllers/api/v1/subject_queues_controller.rb
- config/routes.rb
- spec/controllers/api/v1/subject_queues_controller_spec.rb
- spec/support/updatable.rb
closes #1245 - does what it says on the tin.
I'd rather have a `has_many :subjects, through: :set_member_subjects` relation on SubjectQueue working but the has_many_through scope didn't work with the belongs_to_many link.
> Prepend queue ids

- lib/media_storage/aws_adapter.rb
In the version we use it's called `expires`.
Fixes #1177 for real this time.
> The expires_in option is only in newer versions of the AWS SDK gem

- lib/classification_lifecycle.rb
- lib/subject_selector.rb
- spec/lib/subject_selector_spec.rb
This was making the subject and classification routes unbearably slow.
For grouped workflows we can assume that subjects are only queued in
their respective group queue and make sure we're only dequeuing from
that install of all the queues
> Scope enqueues/dequeues to subject set

- app/controllers/api/api_controller.rb
- lib/subject_selector.rb
- spec/lib/subject_selector_spec.rb
- spec/support/dump_worker.rb
don't try and idx an empty array and raise an error to indicate no data to select from for the client
> handle empty database subject selection

- app/controllers/api/v1/subject_sets_controller.rb
- app/controllers/concerns/filter_by_metadata.rb
- db/migrate/20150901222924_add_index_to_metadata.rb
- db/schema.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
Introduced metadata filters for subject sets via a param in the form
metadata.field
Adds a gin index to subject sets
> Allow subject sets to be filtered by metadata

- docker-compose.yml
I'm happy to change the ports if it collides with anyone's docker containers, but this just makes it so much easier to open a postgresql shell etc. I keep making this change and then not committing it, so I figured it'd poll opinions on a PR.
> Expose ports for easier debugging

- app/models/subject_queue.rb
- app/workers/enqueue_subject_queue_worker.rb
- app/workers/reload_non_logged_in_queue_worker.rb
- lib/classification_lifecycle.rb
- lib/subject_selector.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/subject_selector_spec.rb
- spec/models/subject_queue_spec.rb
- spec/workers/enqueue_subject_queue_worker_spec.rb
don't assume building on all subject sets for a workflow, allow them to be explicitly specified.
> explicit queue build for the subject set

- app/models/classification.rb
- spec/models/project_spec.rb
- spec/models/workflow_spec.rb
seems the project / worfklow counter cache from classifications are causing lots of deadlocked updates and slowing the api nodes down. Removing to see if this is the problem.
> remove cache counters

- app/controllers/api/v1/classifications_controller.rb
- app/workers/dequeue_subject_queue_worker.rb
- lib/classification_lifecycle.rb
- lib/subject_selector.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/lib/subject_selector_spec.rb
- spec/workers/dequeue_subject_queue_worker_spec.rb
Work on queue's to stop in request cycle concurrent queue updates, e.g. non-logged in user dequeues for a very active workflow. See the commit messages for more details.
1. only dequeue after selecting from the queue, on classification receipt we can assume these have been removed.
2. do not refresh the low queues when selecting. this could have re-added recetly dequeued data back into the queue and led to duplicate classifications.
3. extracted dequeue to a high priority background worker. get this out of the request / response cycle to avoid concurrent updates. dequeue's can happen in any order so we just need to make sure sidekiq is working!
4. now all low queue refreshes run after updating user seens in the background during classification lifecycle transact to avoid possibly adding …
> Queue updates

- .gitignore
- spec/spec_helper.rb
This enables the rspec options —only-failures and —next-failure
> Persist example status

- app/workers/retirement_worker.rb
- spec/workers/retirement_worker_spec.rb
when retiring don't try and update all queues in one go, set a background worker to run each dequeue.
Seems the subject queues are under heavy load when the retirement worker is firing (this may be correlated to another issue though), see below. 
Also i'm not 100% that the way we're using `.update_column` in de/enqueue [here](https://github.com/zooniverse/Panoptes/blob/5b7288636a59b1d9f942561796df5e81703c708c/app/models/subject_queue.rb#L92) is respecting concurrent udpates. I'm wondering if we should move back to `.update` and using the locking column to signal underlying updates that we can rescue and retry / reschedule via sidekiq.
> use background workers to retire from queues instead of a large set of updates

- app/controllers/api/v1/subject_sets_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/workers/reload_non_logged_in_queue_worker.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/workers/reload_non_logged_in_queue_worker_spec.rb
Only reload non-logged in queues with the subject set context as things like adding / removing subject sets, retiring subjects, etc would do a mass call to reload non-logged in queues.
> more specific non logged in queue reload events

- app/models/concerns/with_optimistic_retry.rb
- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
update queues respecting stale versions with a retry component. hopefully we won’t see too many re-raised stale object errors in sidekiq but with the combination of retires in code and sidekiq we should get consistent data in the queues.
we can always look at serializable transaction isolation level as well but thought i'd try this method first.
> update queues using optimistic locking with retires

- app/workers/retirement_worker.rb
- spec/workers/retirement_worker_spec.rb
This reverts commit b7812bd7cb3b9f77561d431ac24dbdbba7556290.
see if this helps with the db load - just run the serial dequeue instead of spanwing lots of concurrent workers.
> Revert "use background workers to retire from queues"

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
select from head of queue if workflow is prioritized and randomly sample if not.
> respect prioritized workflows in next subjects

- app/models/api_user.rb
- app/models/subject.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- db/migrate/20150916161203_add_index_subjects_upload_user_id.rb
- db/migrate/20150916162320_remove_user_uploaded_subject_counter.rb
- db/schema.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/models/api_user_spec.rb
- spec/models/subject_spec.rb
- spec/models/user_spec.rb
avoid trying to update this counter during subject creates. only update this value when checking for subject limits currently but it could be called at other times.
> Subject uploader counter cache

- lib/classification_lifecycle.rb
- lib/subject_selector.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/lib/subject_selector_spec.rb
I was looking into rate limiting the non-logged in queue rebuilds and thought instead that it should not dequeue as often. As we don't guarantee that  non-logged in won't see duplicates then we should only dequeue from the non-logged in on classifications receipt.
> Dequeue non logged in on classification receipt not subject selection

- app/controllers/api/v1/set_member_subjects_controller.rb
- app/controllers/api/v1/subject_sets_controller.rb
- app/models/set_member_subject.rb
- app/models/subject.rb
- app/models/subject_queue.rb
- app/models/subject_workflow_count.rb
- app/models/workflow.rb
- app/workers/classification_count_worker.rb
- app/workers/retirement_worker.rb
- db/migrate/20150827124834_alter_subject_workflow_counts_add_subject_id.rb
- db/schema.rb
- lib/formatter/csv/subject.rb
- lib/tasks/migrate.rake
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/factories/subject_workflow_counts.rb
- spec/lib/formatter/csv/subject_spec.rb
- spec/lib/set_member_subject_selector_spec.rb
- spec/models/set_member_subject_spec.rb
- spec/models/subject_spec.rb
- spec/models/subject_workflow_count_spec.rb
- spec/models/workflow_spec.rb
- spec/workers/classification_count_worker_spec.rb
- spec/workers/count_reset_worker_spec.rb
- spec/workers/retirement_worker_spec.rb
This isn't actually a difference in counting styles, because we used to increment counters and mark retirement on all SMSes for a subject-workflow pair. This just removes that so that we just have a single SWC for each pair.
Fixes #1162
> Count subjects directly, not individual set members

- app/serializers/workflow_serializer.rb
- spec/serializers/workflow_serializer_spec.rb
linked to https://github.com/zooniverse/Panoptes-Front-End/pull/1679 serialize the defaults in the proper schema format.
> workflow - proper serialised retirement defaults

- app/controllers/api/v1/projects_controller.rb
- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/serializers/project_serializer.rb
- db/migrate/20151005093746_add_experimental_tools_to_project.rb
- db/schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
closes #1385. Allow the front end to wire up experimental tool features for a project.
> add admin only per project front end tools

- app/controllers/api/v1/project_preferences_controller.rb
- app/schemas/project_preference_create_schema.rb
- app/schemas/project_preference_update_schema.rb
closes #1401, allow front ends to store free form data in the preferences object.
> use json schema for user project prefs

- app/workers/classifications_dump_worker.rb
- lib/classification_dump_cache.rb
- lib/formatter/csv/annotation_for_csv.rb
- lib/formatter/csv/classification.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
- spec/lib/formatter/csv/classification_spec.rb
- spec/workers/classifications_dump_worker_spec.rb
Most importantly I've added a cache for the reified old versions of workflows and contents. This seemed to be amazingly slow even if dealing with the latest version. I'm also preloading subjects and handling the check for retiredness less stupidly.
> Optimize exports

- app/controllers/sessions_controller.rb
support log out via json cors requests. will require us to whitelist the cors domains that can access this route.
> skip csrf token auth on /users/sign_out json request

- app/controllers/api/v1/media_controller.rb
- app/workers/aggregation_data_mailer_worker.rb
- spec/controllers/api/v1/media_controller_spec.rb
- spec/workers/aggregations_data_email_worker_spec.rb
aggregation engine uses update url's like `https://panoptes.zooniverse.org/api/projects/1154/aggregations_export` that don't have a media resource id. this PR correctly handles the media resource lookup for sending the aggregation export success email.
> correctly handle aggregation export media updates

- app/models/project.rb
- spec/models/project_spec.rb
select only the first expert role a user has on a project from the prioritized list of EXPERT_ROLES. This fixes some broken gold standard classification workers in the backend.
> extract only expert roles for classification marking

- lib/tasks/workshop_export.rake
Worked on my machine. Because `bin/rake` through Spring already had Rails loaded. Without Spring, it doesn't really work. :(
> Fix env dependency

- app/workers/classification_worker.rb
- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/workers/classification_worker_spec.rb
mark upps as recently updated when we get classification for them. this will show a more realistic list on the logged in landing page / ordered stats
> Update user prefs for native panoptes projects on classification receipt

- app/models/concerns/preferences.rb
- app/models/user_project_preference.rb
- spec/models/user_collection_preference_spec.rb
- spec/models/user_project_preference_spec.rb
- spec/support/preferences.rb
don't dependant destroy a project when deleting a user project preference, allow the relation to have the correct options passed via the preferences_for method.
> explicit pref belongs_to options

- app/models/collection.rb
- db/migrate/20151023103228_add_default_to_collection_private.rb
- db/structure.sql
- spec/models/collection_spec.rb
linked to https://github.com/zooniverse/Panoptes-Front-End/pull/1822 ensure collections in panoptes default to explicit private setting.
This migration took 2 secs to run on my machine so should be good to go out as is.
> ensure collections default to private

- app/controllers/api/v1/collections_controller.rb
- app/models/collection.rb
- app/serializers/collection_serializer.rb
- app/serializers/concerns/belongs_to_many_links.rb
- app/serializers/set_member_subject_serializer.rb
- db/migrate/20151024080849_collections_belongs_to_many_projects.rb
- db/structure.sql
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/factories/collections.rb
- spec/lib/json_api_controller/relation_manager_spec.rb
- spec/lib/json_api_controller/updatable_resource_spec.rb
- spec/models/collection_spec.rb
towards #1448 - allow multiple project tracking on the collections model.
> Collection project tracking

- lib/media_storage/aws_adapter.rb
use correct default expiry times and convert to use the expires param in seconds to expire.
> update aws adapater s3 signed urls

- app/models/user.rb
- spec/controllers/api/v1/users_controller_spec.rb
closes #1230 - search by field prefixes to widen the result scope, https://github.com/Casecommons/pg_search#prefix-postgresql-84-and-newer-only
> update search add prefixes for users

- app/controllers/concerns/recents.rb
Rake routes suggest this isn't used, I'm not sure why this was in there twice but i'm going to run it through CI to see if it'd needed.
> dup recents route

- lib/tasks/migrate.rake
Otherwise we would be trying to insert null values and failing the
constraints.
> Take new rows without subject_ids into account

- .dockerignore
- Dockerfile
- scripts/docker/start.sh
build the latest commit tag during the docker build and then copy across to public on start.
This is needed since docker hub now respects the .dockerignore file and the .git data isn't available at runtime in the resulting images.
> rework commit_id.txt build

- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- config/routes.rb
- db/migrate/20151110101156_add_gold_standard_sparse_index.rb
- db/migrate/20151111154310_add_public_gold_standard_to_workflow.rb
- db/structure.sql
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
closes #1475 
adds a new end point at `/classifications/gold_standard?workflow_id=X,subject_ids=Y` to get approved workflow(`public_gold_standard=true`) gold standard classifications. 
Note workflows must have the public flag in order to open up gold standard access. This should be a concious choice for the researchers / project owners.
> Gold standard filter

- spec/models/set_member_subject_spec.rb
allow different result ordering and avoid intermittent spec failures.
> use match_array not eq for expectation

- app/controllers/api/v1/collections_controller.rb
- spec/controllers/api/v1/collections_controller_spec.rb
closes #1485 and based on #1486 create a backwards compatible api for existing projects (e.g. wildcam) when finding fav collections by project id.
> Fav filtering

- app/controllers/api/v1/collections_controller.rb
- spec/controllers/api/v1/collections_controller_spec.rb
closes https://github.com/zooniverse/Panoptes-Front-End/issues/1908 
allow the singular and pluarl link keys to be specified independently, allows for backwards compatable clients.
> backwards compatable collection project links

- Gemfile.lock
- Procfile
- config/puma.rb
- docker-compose.yml
- scripts/docker/restart_puma.sh
- supervisord.conf
~~**Don't merge this yet**~~ This is good to go now.
~~We'll need to get the logging format sorted as it's not using the rails log format any more.~~ This setup is req'd in order to use the restart_script in #1481.
Bumps puma gem, switches to running puma on it's own in clustered mode with 2 workers that use code preloading leveraging MRI COW mem savings. It should respect AR connections on boot / app restart (see config/puma.rb). 
All up this should be more resource efficient for the production nodes some simple dev benchmarking showed a speedup of the projects page load of 1-1.5s (4.5 over 5.5). Time will tell what we see in prod. I also tested some hot restarts running the whole stack in docker and both AR and redis connections didn't grow but reset and stabilised to prev values.
> Puma cluster mode

- db/migrate/20151116143407_add_users_login_index.rb
- db/structure.sql
user registration routes were doing full table scans and stressing the databse.
> add normal index for users#login

- app/controllers/api/v1/projects_controller.rb
- app/workers/concerns/dump_worker.rb
- spec/support/dump_worker.rb
closes #1421 - don't update in the request, just in the dump worker when it runs. Fixes busted links in the front end that don't show case the state is not correct but they won't run cause the rate limiter has kicked in.
> Export media state change in dump workers

- app/models/user.rb
- db/migrate/20151117154126_add_user_login_trigram_index.rb
- db/structure.sql
- spec/controllers/api/v1/users_controller_spec.rb
some logins are hard to find for tsvector, this will add the user login scope to the search whenever the search result set drops below a threshold. The only drawback is an  extra count function that i have limited but it's a db cost that should be pretty fast.
> complement search scope with a login match

- app/workers/retirement_worker.rb
- lib/classification_lifecycle.rb
- lib/event_stream.rb
- lib/multi_kafka_producer.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/lib/event_stream_spec.rb
- spec/lib/multi_kafka_producer_spec.rb
- spec/spec_helper.rb
- spec/workers/retirement_worker_spec.rb
Two events are implemented:
* a classification is made: publish an event to indicate this. the event-id is derived from the record id, so that duplicates aren't possible. this allows us to build histograms of how many classifications we see per timeslot
* a subject is retired: publish the current values of various counters, so that we can chart these over time later.
> Publish events to Kafka

- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- app/serializers/workflow_serializer.rb
- db/migrate/20151120161458_rename_workflow_config_attribute.rb
- db/structure.sql
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/workflow_spec.rb
closes #1503 - avoid serializer method name clash for config.
> rename config object to configuration

- app/models/classification.rb
- config/initializers/kaminari_config.rb
- config/page_size_limits.yml.hudson
- spec/controllers/api/v1/classifications_controller_spec.rb
had some very long running classification index requests causing latency spikes for the API, added sensible configurable defaults for page limits
> api request page size defaults

- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- db/migrate/20151127150019_sparse_index_updates.rb
- db/structure.sql
- spec/controllers/api/v1/users_controller_spec.rb
closes #1509 and attempts to address [this](https://github.com/zooniverse/Panoptes/issues/1230#issuecomment-159040608)
removes some sparse indexes that weren't used as the query was a full table scan for both and adds a layer strategy to finding users with narrow and broad scopes. Seems its a trade off between high accuracy and speed.
> Attempt to speed up user searches

- apiary.apib
- app/serializers/workflow_serializer.rb
- app/workers/retirement_worker.rb
- db/migrate/20151201102135_add_finished_at_to_workflows.rb
- db/structure.sql
- spec/workers/retirement_worker_spec.rb
Instead of deactivating, set a timestamp column. This allows us to see
which workflows are supposed to be visible but have just run out of
data. In turn, that will allow us to automatically unfinish a workflow
when more data becomes available (either due to recounts or simply
because more data is added to a subject set).
> Set finished_at instead of deactivating workflows

- app/controllers/api/v1/collections_controller.rb
- spec/controllers/api/v1/collections_controller_spec.rb
ensure project links work on collection create, fixes a bug that @simoneduca found in the api.
> correctly link singular project

- app/serializers/project_serializer.rb
Sadly Restpack doesn't support customizing the parameters used for each sorting, so I can't really call this "popularity" outward-facing, unless anyone has any ideas?
> Allow sorting by number of people that have classified

- app/controllers/api/events_controller.rb
- spec/controllers/api/events_controller_spec.rb
Spec changes were already provided by Cam Allen
Because calling upp.save automatically unsets upp.new_record? I capture the state of upp.new_record? in was_new and then decide whether or not to increment the counter based on that value.
> Resolves #1514 should not increment classifiers count every time a user performs an action

- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
take care of the situtation where projects like shakespeares world setup the upp before the first classification is submitted and the email prefs / counter incs were missed.
> always setup project email prefs on first classification receipt

- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
Works around optimistic locking issues (retiring updates a counter on
the workflow and increments the lock version, so afterwards the
existing workflow object cannot be saved until doing a reload.
> Save resource before retiring

- app/controllers/api/v1/projects_controller.rb
- app/workers/calculate_project_activity_worker.rb
- app/workers/calculate_project_completeness_worker.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/workers/calculate_project_activity_worker_spec.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
Seems the api allowed full project delete and some background workers were failing with missing record.  I've reworked the destroy route to just deactivate instead, note that users with rights can hard delete workflows, subject_sets and set_member_subjects so any deactivate could possibly be a shell.
I'm thinking we should keep projects around for posterity and possibly restores. Should we just allow the project to be hard deleted instead?
> Deactivate instead of destroy projects

- app/controllers/api/v1/projects_controller.rb
- app/controllers/concerns/filter_by_current_user_roles.rb
- app/controllers/concerns/filter_by_owner.rb
- app/controllers/concerns/index_search.rb
- app/models/concerns/translatable.rb
- app/serializers/project_serializer.rb
- lib/role_control/owned.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/lib/json_api_controller/relation_manager_spec.rb
- spec/serializers/project_serializer_spec.rb
similar to #1552 but using the default v1 serializers to provide a slimmed down resource representation. I've also tried to optimise data sideloading eager loads and language queries from loaded / non-loaded associations. 
This PR uses the `?cards=true` params on the projects index route to get a cut down resource rep. Also benchmarking on my machine shows this route come in at ~85ms.
@marten @parrish thoughts? Also we could try out both this and the other PR and get the front end calling on the different override params for testing.
> Projects index speed up

- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- db/migrate/20150706185722_add_trigram_index_to_login.rb
- db/migrate/20151117154126_add_user_login_trigram_index.rb
- db/migrate/20151231123306_modify_user_trigram_search_index.rb
- db/structure.sql
- spec/controllers/api/v1/users_controller_spec.rb
closes #1554 - limit user search scopes to login field only, removed the prefix matching and updated trigram to use indexes. This will now attempt to find a user by login field and if missing try and match on a full search using tsvectors and trigram (fuzzy). 
Note, tsvectors can return large, similar rank results sets for similar strings so the fuzzy matching is used in the rank to tie break, in my testing it worked well so limiting the page size (like the front-end does) should return the most relevant hits first.
> Faster user search on login field

- app/models/collection.rb
- app/models/project.rb
- app/models/user.rb
- app/models/user_group.rb
- db/migrate/20160103142817_ensure_trigram_searc_indexes.rb
- db/structure.sql
waiting on #1565 - i reviewed the use of search indexes and made some changes. 
1. notably never use a trigram threshold as it currently will [not use an index](https://github.com/Casecommons/pg_search/issues/278).
2. don't use prefixes for tsvectors just use the trigram properly for fuzzy matches.
3. user_groups only search the display name for trigrams to keep the index size down.
4. use gin trigram op indexes, i couldn't get the derived pg_search queries to use the gist indexes.
> pg search indexes

- app/workers/enqueue_subject_queue_worker.rb
- app/workers/reload_non_logged_in_queue_worker.rb
- lib/subjects/postgresql_selection.rb
- lib/subjects/selector.rb
- spec/lib/subjects/postgresql_selection_spec.rb
- spec/lib/subjects/selector_spec.rb
non-logged in queues may not replenish via the subject selector for grouped selection. So this will now instead just return some data from the workflow taking into account the group if set.
> fallback selection should return some data

- app/controllers/api/v1/subject_sets_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/workers/reload_cellect_worker.rb
- app/workers/retirement_worker.rb
- config/initializers/cellect.rb
- lib/classification_lifecycle.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/workers/reload_cellect_worker_spec.rb
- spec/workers/retirement_worker_spec.rb
check that cellect is on and the workflow is configured to use cellect.
> Only use cellect when global config and the workflow settings match

- db/migrate/20160106120927_add_lifecycled_at_to_classifications.rb
- db/structure.sql
- lib/classification_lifecycle.rb
- lib/tasks/migrate.rake
- spec/lib/classification_lifecycle_spec.rb
closes #1517 adds a lifecycled at timestamp, that is updated in the lifecycle. Also have a rake task to backfill, i wasn't sure if this will break the app adding in this col, anyway to pre-load the cols on the model to not break?
> add lifecycled at migration for classifications

- db/migrate/20160106120927_add_lifecycled_at_to_classifications.rb
- db/structure.sql
split the index build out, add_column took < 1s on my dev box. I will generate this index with a concurrent outside a transcation block in a sep PR.
> add column without an index build in the transaction

- app/controllers/api/v1/users_controller.rb
- spec/controllers/api/v1/users_controller_spec.rb
Also prevents non-exact matches for short (< 3 character) queries.
At the moment, the specs have one failure, but I'd like some feedback here.
> Sanitize User login search criteria.

- app/controllers/api/v1/workflows_controller.rb
- app/workers/retire_cellect_worker.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/workers/retire_cellect_worker_spec.rb
notify the cellect client of retire events and don't force cellect to reload the whole workflow.
> Reload cellect vs retire cellect

- app/workers/requeue_classifications_worker.rb
- db/migrate/20160106120927_add_lifecycled_at_to_classifications.rb
- db/structure.sql
- lib/classification_lifecycle.rb
- lib/tasks/migrate.rake
- spec/lib/classification_lifecycle_spec.rb
- spec/workers/requeue_classifications_worker_spec.rb
merge this only after #1577 and the data migration to mark all as processed is finished.
Introduces a scheduled worker to automatically reprocess classifications that are saved but not lifecycled (redis down / api failure but db persistence, etc).
> Non lifecycled classification worker

- app/workers/reload_cellect_worker.rb
- app/workers/retire_cellect_worker.rb
- app/workers/retirement_worker.rb
- app/workers/seen_cellect_worker.rb
- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/workers/reload_cellect_worker_spec.rb
- spec/workers/retire_cellect_worker_spec.rb
- spec/workers/retirement_worker_spec.rb
- spec/workers/seen_cellect_worker_spec.rb
closes #1592 - extract the cellect communications to their own workers with a small retry limit on them. If cellect is down then when it comes back up it should reload the correct data state from the db so these messages should only really be retried for a period of small network outage. 
Happy to bump the retry count taking into account this, https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry.
> Cellect notification workers

- app/workers/classification_worker.rb
- app/workers/requeue_classifications_worker.rb
- config/initializers/panoptes.rb
- spec/workers/classification_worker_spec.rb
- spec/workers/requeue_classifications_worker_spec.rb
closes #1593 - only back process classifications that were skipped due to redis / api errors by ignoring the live stream via a window period (configurable via the ENV["LIVE_WINDOW"] var).
> Lifecycle at window

- app/controllers/api/api_controller.rb
- lib/subjects/selector.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/subjects/selector_spec.rb
closes #1586 - error gracefully with a useful message.
> raise error when no data available for selection

- app/models/concerns/cache_model_version.rb
- app/models/workflow.rb
- app/models/workflow_content.rb
- app/serializers/workflow_serializer.rb
- db/migrate/20160113133848_alter_workflows_add_version.rb
- db/structure.sql
- lib/formatter/csv/workflow.rb
- lib/formatter/csv/workflow_content.rb
- spec/models/workflow_content_spec.rb
- spec/models/workflow_spec.rb
- spec/serializers/workflow_serializer_spec.rb
Instantiating old Papertrail versions is slow, and we need this for
every workflow we return. Caching this makes it faster.
> Add a cache for model version

- app/controllers/api/v1/classifications_controller.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/support/classification_events.rb
if the user has a valid token they'll have the correct it
> avoid the association assignment via link_params

- app/workers/enqueue_subject_queue_worker.rb
- app/workers/reload_cellect_worker.rb
- app/workers/reload_non_logged_in_queue_worker.rb
- app/workers/retire_cellect_worker.rb
- app/workers/seen_cellect_worker.rb
- High priority for filling Cellect subject queues (`:really_high`)
- Moves Cellect subject lifecycle workers from `:data_high` to `:high`
A config change will change the sidekiq queue priority from:
```
queues = [
'data_high',
'high',
'data_medium',
'medium',
'default',
'data_low',
'low'
]
```
to: 
```
queues = [
'really_high',
'high',
'data_high',
'data_medium',
'default',
'data_low',
]
```
Changes are tagged with
``` ruby
```
so we can revert them easily when the API instances are running the workers again.
> Reorder worker priorities

- app/models/set_member_subject.rb
- app/models/subject_queue.rb
- app/serializers/workflow_serializer.rb
- app/workers/calculate_project_completeness_worker.rb
- app/workers/enqueue_subject_queue_worker.rb
- lib/belongs_to_many_association.rb
- lib/classification_lifecycle.rb
- lib/subjects/cellect_client.rb
- lib/subjects/cellect_session.rb
- spec/workers/enqueue_subject_queue_worker_spec.rb
Resolves application boot-time errors like "RuntimeError: Circular dependency detected while autoloading constant <Whatever>"
Probably not high priority, but crashing on boot is never good.
> Adds explicit requires for non-eager-autoloaded constants.

- app/workers/classification_count_worker.rb
- app/workers/project_classifications_count_worker.rb
- spec/workers/classification_count_worker_spec.rb
- spec/workers/project_classifications_count_worker_spec.rb
@parrish should we do `track_rejected` on this?
> Move project/workflow classifications counter updates to ratelimited

- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- app/workers/classifications_dump_worker.rb
- db/migrate/20160114135531_re_add_classification_indexes.rb
- db/migrate/20160114141909_add_complete_index_to_classifications.rb
- db/structure.sql
concurrently create indexes to track created_at, lifecycle and user_id indexes (recents)
Time on my dev machine..
```
== 20160114135531 ReAddClassificationIndexes: migrating =======================
-- add_index(:classifications, :created_at, {:algorithm=>:concurrently})
-> 15.3824s
-- add_index(:classifications, :user_id, {:algorithm=>:concurrently})
-> 18.1663s
-- add_index(:classifications, :lifecycled_at, {:where=>"(lifecycled_at IS NULL)", :algorithm=>:concurrently})
-> 3.0346s
== 20160114135531 ReAddClassificationIndexes: migrated (36.5836s) =============
```
> re-add classification indexes concurrently

- app/models/subject_queue.rb
- app/workers/retirement_worker.rb
- spec/models/subject_queue_spec.rb
- spec/workers/retirement_worker_spec.rb
avoid locking updates on the subject queue table with large dequeue scopes. Also changed the default queue size to be 2 x the default limit selections to reduce the chance of retired data being in them. This may push more queries into the db when selection happens on an empty queue. Something to keep in mind when running on a smaller db instance.
> Disable dequeue workers and reduce queue sizes

- app/workers/retirement_worker.rb
- spec/workers/retirement_worker_spec.rb
Scenario is:
- 3 people classify the same subject simultaneously.
- The subject will retire after the next classification
- The subject will attempt to retire and dequeue 3 times
This just adds a check to ensure it's not already retired.
I'm sure it's possible for a race condition to allow multiple retirements in cases of very high concurrency, but this should take care of the majority of them.
> Guard retirement

- .travis.yml
- Dockerfile
Primarily to fix [this bug](https://app.honeybadger.io/projects/40595/faults/23124244) and the performance hit it causes.
2.3 also includes [the lonely operator](https://bugs.ruby-lang.org/issues/11537) and other performance improvements.
> Upgrade to Ruby 2.3.0

- Gemfile
- Gemfile.lock
* byebug adds commands like `step` (step-into), `next` (step-over), `continue`, `finish`. Also adds ability to set more breakpoints once you're in a pry session.
* stack_explorer adds `show-stack`, `up` and `down` to inspect state higher up in the call stack. byebug adds some of this, but that only works with a stack that starts at the point the pry started, so you can't look at state higher up the call chain, hence this additional gem.
> Make debugging with pry more awesome

- .gitignore
- Dockerfile
- config/initializers/loadbalancer_ips.rb
We could do fancier and subscribe to the SNS topic that publishes changes, but this probably works acceptably for our purposes. Just have to keep deploying ;)
> Fetch and use latest AWS proxy ips on container build

- app/controllers/concerns/filter_by_current_user_roles.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/factories/subject_sets.rb
closes #1646 - uses preload to create a valid sql query when filtering only on the owner role. I've taken the streamline the projects_controller testing state as well, should be less cruft in the db for each test run.
> Fix owner role filter

- app/models/user.rb
- lib/classification_lifecycle.rb
- spec/lib/classification_lifecycle_spec.rb
This is so we can associate classifications with user groups (in post-processing done by education api)
> Add user group ids to classifications

- app/workers/publish_classification_event_worker.rb
- lib/event_stream.rb
- spec/lib/event_stream_spec.rb
- spec/workers/publish_classification_event_worker_spec.rb
ensure a consistent event time format before serializing to kafka
> consistent event time format

- .travis.yml
- Gemfile
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/known_dirs.txt
Split the spec tasks up to the concurrent build limit on travis (currently 5) to decrease the total run time (prev 23m, now ~7m).
> split the travis build up on different concerns

- app/workers/publish_classification_worker.rb
- app/workers/publish_retirement_event_worker.rb
- config/initializers/kinesis.rb
- lib/kafka_classification_serializer.rb
- lib/kinesis_publisher.rb
- spec/lib/kafka_classification_serializer_spec.rb
- spec/workers/publish_classification_worker_spec.rb
- spec/workers/publish_retirement_event_worker_spec.rb
**Please note that this will also start pushing `user_ip` into Kafka's `classifications` topic** (This should be fine, Nero is the only one reading from that topic, since ZooEventStats is using the `events` topic.
Both Kinesis and Kafka use the same serializer. I'm doing this so that we can stop having a separate `PublishClassificationEventWorker` (if/when we migrate), instead moving the onus on the stream consumer to pluck items out of the global stream that it cares about (by looking at `type` field) and choose how to publish that. I'll make that change when I swap ZooEventStats over from Kafka to Kinesis.
> Kinesis evaluation

- app/workers/publish_classification_worker.rb
- lib/kinesis_publisher.rb
- spec/workers/publish_classification_worker_spec.rb
I started working towards having JSON-API linked models be in the stream too (Nero uses that feature of the Kafka stream). Needed a place to store some thoughts (since I won't be working all the way through them yet), so making the PR way ahead of it being ready. This'll be dependent on us wanting to complete the migration from Kafka -> Kinesis.
* Remove old `EventStream` (possibly rename `KinesisPublisher` to be `EventStream`)
* `KinesisPublisher` should just take JSON-API-conforming hashes. Since those may contain an array of models (remember, format is `{classifications: [...], linked: {...}}`), the publisher should take care of outputting one event per model in the main collection ("classifications"), passing along all (or just appropriate) linked data. I really feel like one line in …
> Add linked models to Kinesis

- app/workers/dequeue_subject_queue_worker.rb
- app/workers/enqueue_subject_queue_worker.rb
Merge after the latest build / deploy - revert a temp workaround for production sidekiq jobs
> re-enable disabled job after the worker api change

- app/controllers/api/v1/subjects_controller.rb
- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
this should fix the no method errors introduced from #1682 & #1676
> pass the user not the api_user to the subject selector

- app/models/concerns/subject_counts.rb
- lib/subjects/set_member_subject_selector.rb
- spec/lib/subjects/set_member_subject_selector_spec.rb
- spec/models/workflow_spec.rb
closes #1661 - new users should not see retired data and a fix for the workflow.finished? check.
Also turns out i hate my future self and wrote some hard to understand specs a while back...past_cam--
> rework SMS selector

- app/models/subject_queue.rb
- spec/models/subject_queue_spec.rb
Replenish the queue after a default size first selection and 1 classification comes back. This will work in tandem with stale queues to support a subject selection buffer during active classification sessions. This buffer will expire after 30 mins (currently) of classificaiton inactivity.
> replenish selection queues asap

- spec/models/subject_queue_spec.rb
make sure we use an attribute update that also touches the updated_at timestamp, as this is used to determine if a queue is stale and thus if a queue is used.
> spec timestamp updates

- app/serializers/event_stream_serializers/classification_serializer.rb
- app/serializers/event_stream_serializers/project_serializer.rb
- app/serializers/event_stream_serializers/workflow_content_serializer.rb
- app/serializers/event_stream_serializers/workflow_serializer.rb
- app/workers/publish_classification_worker.rb
- spec/serializers/event_stream_serializers/classification_serializer_spec.rb
- spec/workers/publish_classification_worker_spec.rb
I still intend to look at compressing this data down, but I'll handle that with an update to the ZooStream gem (and need to make Nero/ZooStats forwards-compatible first).
> Add project, workflow, workflow_content and user into stream

- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
may hit stale queue error when dequeuing in the request cycle for logged in users. this will catch the error and push it to the background.
> handle stale queue update error in selection

- config/routes.rb
This route will be used for specialized nginx directive to allow force_ssl to work with ELB health checks over http.
> add seperate route for health check

- app/services/media_storage/aws_adapter.rb
- app/workers/concerns/dump_worker.rb
- db/migrate/20160303163658_add_medium_fields_for_s3_path_details.rb
- db/structure.sql
- spec/services/media_storage/aws_adapter_spec.rb
- spec/support/dump_worker.rb
closes #1694 put the content disposition to the s3 resource via the medium attributes, currently only set via the dump workers but could be expanded out to other media resources.
> update s3 headers for data dump exports

- Gemfile.lock
- app/controllers/api/v1/classifications_controller.rb
- app/workers/honeybadger_worker.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
don't 500 that may cause a duplicate classification submission instead just carry on as the lifecycle event will eventually fire but still go ahead and notify that redis is down.
> ignore redis failure on classification create

- lib/subjects/fallback_selection.rb
- lib/subjects/postgresql_in_order_selection.rb
- lib/subjects/postgresql_random_selection.rb
- lib/subjects/postgresql_selection.rb
- spec/lib/subjects/fallback_selection_spec.rb
- spec/lib/subjects/postgresql_in_order_selection_spec.rb
- spec/lib/subjects/postgresql_random_selection_spec.rb
- spec/lib/subjects/postgresql_selection_spec.rb
- spec/support/shared_examples_for_postgresql_selection.rb
Started with removal of those `before(:all)` statements, then to keep stuff at least somewhat speedy I'm splitting up some stuff so tests can be more focussed. Not perfect yet, but time to merge this before it gets out of hand :P
```
1) Subjects::PostgresqlSelection selection #select grouped selection behaves like select for incomplete_project when a user has only seen a few subjects with a limit of 1 should return an unseen subject
Failure/Error: expect(uss.subject_ids).to_not include(subject.select.first)
expected [417, 430, 419, 427, 410] not to include 427
Shared Example Group: "select for incomplete_project" called from ./spec/lib/subjects/postgresql_selection_spec.rb:52
```
> Clean up PostgresqlSelection

- lib/subjects/cellect_client.rb
- lib/subjects/cellect_session.rb
- spec/lib/subjects/cellect_client_spec.rb
- spec/lib/subjects/cellect_session_spec.rb
handle the case where the cellect node_set is empty and thus the returned host will be nil.
> raise connection error when no cellect hosts available

- config/environments/production.rb
- config/environments/staging.rb
avoid subdomains leaking cookies 
Note to future selves, rails 5 offers more options on this like preload so we should update to those when bumping rails see [here](https://github.com/rails/rails/blob/823915da2873f110ecbecfdfe57a30f64af46d23/actionpack/lib/action_dispatch/middleware/ssl.rb#L40)
> set include subdomain hsts header

- apiary.apib
- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- config/routes.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/models/classification_spec.rb
closes #1713 
extracting the overloading the show/index query scopes to route concerns. 
**NOTE:** this may break some existing functionality since by default show / index routes will now return just completed classification for the requesting user and not all classifications the user has access to from a project / that are incomplete.  I don't think it does but I'd like to make sure this api change doesn't break any existing functionality that PFE / custom projects rely on.
new routes:
GET      /api/classifications                         -> default, completed classfications for this user
GET      /api/classifications/incomplete       -> only incomplete for the user 
GET      /api/classifications/project             -> all classifications the user has project access to
GET …
> extract scope concerns to seperate routes

- app/controllers/api/v1/users_controller.rb
- app/models/api_user.rb
- app/serializers/user_serializer.rb
- db/migrate/20160323101942_user_upload_whitelist.rb
- db/structure.sql
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/models/api_user_spec.rb
closes #1716 - skip subject limit checks when uploading for whitelisted users.
> skip subject limit checks for whitelisted users

- apiary.apib
workflows have retirement not subject sets and remove `for` param from classifications, i.e. finish last weeks changes.
> update api docs

- db/migrate/20160323101942_user_upload_whitelist.rb
- lib/tasks/migrate.rake
Moves the setting of the initial value to a rake task which we'll run out of band. A next PR will set the actual PSQL column default for whatever records are created after this, which we'll do in a second deploy.
> Move setting the default value to a rake task

- app/controllers/api/v1/workflow_contents_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/models/workflow_content.rb
- app/schemas/workflow_content_create_schema.rb
- app/schemas/workflow_content_update_schema.rb
- spec/controllers/api/v1/workflow_contents_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/workflow_content_spec.rb
closes #1728 allow empty workflow tasks
When creating / updateing workflow tasks, allow the workflow_content strings to be empty but ensure they are a hash (by default in db and controller task strings extractor) to avoid the null db constraint. This should be fine client side as the task set and the contents don't get out of sync, i.e both are `{}` so the serialized tasks object (i.e. the translated strings re-inserted) is just an empty hash.
> Allow empty workflow tasks on create / update

- Gemfile
- Gemfile.lock
sidekiq 3.5+ bumps celluloid but sidetiq fails with this on 0.6.3 as it needs 0.7+ and that requires sidekiq 4+. Eventually we should just bump to sidekiq 4 and fix the deps.
> lock sidekiq at 3.4.2

- app/workers/seen_cellect_worker.rb
these are pretty noisy and we don't need them to sit around in the dead queue
> skip dead queue for cellect seen workers

- db/migrate/20160406151657_add_user_upload_whitelist_defaults.rb
- db/structure.sql
- lib/tasks/migrate.rake
add a default value to the users upload whitelist table and fix the out of sync structure.sql file. Not sure we need to have the `NOT NULL` clause anymore since it won't affect the code but happy to add another  migration PR if needed.
Need to rerun the rake task after this is deployed.
> Users whiteload structure fix

- db/migrate/20160408104326_add_user_upload_whitelist_null_default.rb
- db/structure.sql
add not-null constraint to users table upload_whitelist attribute
good to merge but check with ops channel before running this migration.
> add not null constraint to users upload_whitelist

- lib/tasks/migrate.rake
closes #1734 & https://github.com/zooniverse/Panoptes-Front-End/issues/2328
Change the page title to Results, @brian-c this should be good to go out anytime as the `url_key` won't change, right?
> Change result page title to results

- app/workers/dequeue_subject_queue_worker.rb
- app/workers/non_logged_in_dequeue_subject_queue_worker.rb
- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
- spec/support/dequeue_subject_queue.rb
- spec/workers/non_logged_in_dequeue_subject_queue_worker_spec.rb
linked to #1640
rate limit non-logged in ones (no user) but do not skip the non-logged in ones. Also bump the queue priority for the logged in dequeue operation as we need to get this data out of the queue asap for a user session.
> split dequeue subject queue workers up

- app/models/membership.rb
- app/models/user_group.rb
- db/migrate/20160412125332_add_index_on_user_group_private.rb
- db/structure.sql
- lib/role_control/actor.rb
- lib/role_control/controlled.rb
Investigating why `/api/v1/user_groups` and `/api/v1/memberships` were so slow to load, I found that the issue could be solved by splitting the query up in two, rather than doing a subquery. PostgreSQL seems to be able to leverage indexes rather than doing seq scans this way.
I'd love to roll this out under Scientist, but we'd have to set that up first and since `scope_for` just returns a scope rather than records, I'm not too sure where I'd start measuring the difference and timing.
* If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the …
> Optimize role control

- app/models/concerns/extended_cache_key.rb
- spec/support/extended_cache_key.rb
Testing existence of instance methods before they were defined was stupid. Do not silently allow invalid method definitions in the cache key DSL, instead raise an error if the method doesn’t exist so it can be fixed.
> fix evaluation order of class / instance methods

- app/controllers/api/api_controller.rb
- app/models/subject_workflow_count.rb
- app/models/workflow.rb
- app/operations/workflows/retire_subjects.rb
- db/migrate/20160425190129_add_retirement_reason.rb
- db/structure.sql
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/subject_workflow_count_spec.rb
- spec/operations/workflows/retire_subjects_spec.rb
Reasons for retirement are stored in an enum on the SubjectWorkflowCount model. The current list of possible reasons looks like this:
[ :classification_count, :flagged, :blank, :consensus, :other ]
Nil is also still fine. Nero can set this value when it retires a subject after it detects it in a classification.
> Record a reason when a subject is retired

- app/models/project.rb
- app/serializers/project_serializer.rb
- db/migrate/20160427150421_add_project_state.rb
- db/migrate/20160506182308_add_project_state_index.rb
- db/structure.sql
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/serializers/project_serializer_spec.rb
Adds "state" as a project attribute and to its serializer. Project#state will, in the case of a nil value, return either "live" or "development" depending on launch_approved?. @marten assisted with the serializer portion on account of Restpack's confusion about the enum and my confusion about Restpack.
> Project state

- db/migrate/20160512181921_add_users_lower_names_index.rb
don't lock the users table from writes while this is building (staging took ~20s) - this won't run on staging but it hasn't run on prod.
> build users index concurrently

- app/serializers/user_serializer.rb
- spec/controllers/api/v1/users_controller_spec.rb
Linked to https://github.com/zooniverse/Panoptes-Front-End/pull/2379
Serialise the attribute name for use in the client. 
> serialize the subject_limit attribute name

- app/controllers/concerns/filter_by_current_user_roles.rb
- app/controllers/concerns/filter_by_owner.rb
- lib/role_control/owned.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/support/filter_by_current_user_roles.rb
- spec/support/filter_by_owner.rb
closes #1774 
the previous query was creating 2 inner joins on the access_control_lists and creating duplicates on the join which was affecting the overal sql count queries, i.e. 1 result but count was 2. This is mostly creating shared helpers to test the filtering (which we weren't before).
TODO:
* Are all the …
> simplify the owner filter join and eager load the identity group users

- lib/formatter/csv/annotation_for_csv.rb
- spec/factories/workflow_contents.rb
- spec/factories/workflows.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
- spec/lib/formatter/csv/workflow_content_spec.rb
- spec/lib/formatter/csv/workflow_spec.rb
- spec/workers/workflow_contents_dump_worker_spec.rb
- spec/workers/workflows_dump_worker_spec.rb
In order to allow the more complex Combo and Dropdown tasks to be correctly exported, I did some refactoring of Formatter::Csv::AnnotationForCsv. Hopefully this will make it easier to add new tasks in the future. 
~~This is a Work In Progress PR, and while it should all currently be working, not all the upstream specs are passing, it could be prettier/DRYer, and Hound is going to throw a fit. Please let me know, @marten or @camallen, about changes that you'd like to see. I anticipate there will be many, but I wanted to get this into your hands ASAP.~~
Update: ready to be reviewed.
> CSV export to allow new tasks

- app/models/membership.rb
- app/models/user.rb
- spec/lib/classification_lifecycle_spec.rb
- spec/models/user_spec.rb
Classification lifecycle was not taking into account membership state when adding user groups to classification metadata. This PR ensures that only active memberships are recorded.
> Do not track inactive memberships

- app/models/user_seen_subject.rb
- app/serializers/user_project_preference_serializer.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
- spec/models/user_seen_subject_spec.rb
Activity counts via UserSeenSubjects are included per workflow to calls made to /project_preferences. There could be the potential for performance issues related to these queries, but the association is already indexed and the non-legacy counts are being generated on the fly already, so this isn't much heavier.
Will close #1796.
> Adds 'activity_count_by_workflow' to /project_preferences

- app/serializers/subject_serializer.rb
- lib/subjects/selector.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
SubjectSerializer includes seen_all_live_data for each subject. Relevant line is 
`!!(user_seen && (user_seen.workflow.subject_ids.uniq.sort == user_seen.subject_ids.uniq.sort))`
If a user has seen all the subjects in the workflow, it'll be true and be included with each sample. If not, then the value will be false for all subjects (including those which have been seen).
> SubjectSerializer includes seen_all_live_data for each subject

- app/controllers/emails_controller.rb
- spec/controllers/emails_controller_spec.rb
let the list server decide if they user is to be unsubscribed regardless of if the user has put in the correct email
> call unsubscribe worker regardless of email correctness

- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
@mcbouslog found a couple of issues with the current export formatter, relating to combo and dropdown tasks, specifically:
* if a combo task contains a `multiple` task, only one selected value was exported instead of all
* if a dropdown task was answered with a custom string value, `option` and `value` were exported incorrectly.
> Combo dropdown export

- lib/subjects/strategy_selection.rb
- spec/lib/subjects/strategy_selection_spec.rb
Linked to #https://github.com/zooniverse/old-weather/issues/94
ensure the strategy selector passes the correct selection information to the different strategy selectors.
> fix param typo

- db/migrate/20160527140046_foreign_keys.rb
I've also made it more conservative with regards to nullable columns, that really aren't nullable due to Rails validations. Better safe than sorry, and FK constraints ignore null values. Gonna make those columns not-null soon, but we'll handle cleanup for that in another migration.
> Add clauses for cleanup of staging data

- Gemfile
- Gemfile.lock
- config/application.rb
- config/initializers/flipper.rb
- config/routes.rb
- db/migrate/20160601162035_create_flipper_tables.rb
- db/structure.sql
- spec/lib/flipper_spec.rb
Provide the ability to turn on features in the API. This does not do per actor (user/groups) feature flipping at the moment but we can add if needed. 
The UI for this is located at `host/flipper`, add features and then code for them in the API..
```
if Panoptes.flipper[:science_things].enabled?
#do all the science things
end
```
> Add feature flags and management tool

- spec/lib/flipper_spec.rb
Panoptes.flipper uses cached DSL instance that internally memoizes the features for re-use. DSL in master has a remove method but not released as a gem yet.
Fixes intermittent bug failures in travis.
> fix intermittent flipper spec failure

- apiary.apib
- app/serializers/concerns/owner_link_serializer.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/support/polymorphic_owner_links_serializer.rb
Fixes #1824.
Include display name when returning user as linked resource
> Include display name when returning user as linked resource

- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
Use feature flags for testing inband selection during a media event.
> feature flag testing of inband subject selection

- app/controllers/api/v1/workflows_controller.rb
Just call the render method once - i'm not sure exactly how this will be testable since the experiment being recorded will just be adding eager loading to the AR relation object. Though we can use this to ramp up the rate and check response times via new relic.
> do not double render in the experiement and add a user context

- lib/formatter/csv/annotation_for_csv.rb
Tasks are more varied than I thought. If the task isn't of a recognized type, instead of yielding an error, it will just pass the unaltered annotation through. Surveys now fall into this category, as well as whatever Old Weather uses. This was the previous behavior and I figured it was better to be specific, but turns out there's more out there than I thought. 
The exception is if an unsupported task (i.e. *not* drawing/single/multiple/text/dropdown) is inside of a combo task, it will still yield a "task cannot be exported" for the annotation.
> All non-standard tasks should pass unaltered annotations

- db/migrate/20160628165038_modify_subject_set_queues_fk_constraint.rb
- db/structure.sql
Delete subject queues with a subject_set_id when the subject_set is deleted.
@saschaishikawa once this is deployed you'll be able to remove subject sets for grouped workflows.
> cascade delete of subject set to subject queues

- app/workers/publish_retirement_event_worker.rb
- spec/workers/publish_retirement_event_worker_spec.rb
Add human readable names for published events. Classification stream has these by default from the serializer.
for use in stats streams
> add project and workflow names to retirement events

- app/models/set_member_subject.rb
- app/models/user.rb
Rather than having both a `seen` and an `unseen`, we can consolidate and say that you've finished a workflow if we can't find any unseen subjects.
I'm removing the experiments from SetMemberSubject so that we don't have nested experiments running.
I'm choosing the candidate for `unseen_for_user_by_workflow`, but the control for `seen_for_user_by_workflow`. Candidate in that case seemed much slower hence this alternate approach.
> Workflow is finished when there are no unseens

- .gitignore
- Gemfile
- Gemfile.lock
- config/initializers/doorkeeper.rb
- db/migrate/20160630150419_enlarge_access_token_column.rb
- db/structure.sql
- lib/tasks/configure.rake
- spec/support/controller_helpers.rb
This allows auxiliary services (Nero, EducationAPI, ZooEventStats, ...) to independently verify the validity of OAuth tokens sent to them by clients. Right now they have to make an API call to Panoptes to verify any tokens given to them (`GET /api/me`).
Currently issued tokens will expire at some point (a few hours) and get replaced with JWT-based ones.
> Doorkeeper access tokens can be JWT tokens

- lib/subjects/postgresql_random_selection.rb
- spec/lib/subjects/postgresql_random_selection_spec.rb
when the limit is greater than half the available count, resect the limit size, otherwise keep larger focus windows to sample from.
> respect limits on small available counts

- Dockerfile.dev
- Dockerfile.official-ruby
There's basically no point in us maintaining our own docker builds of Ruby since the official images are almost identical to ours. They're built on Debian rather than Ubuntu, but that shouldn't make any difference.
This also makes the resulting image about 100 MB larger, but that shouldn't be a problem and I think it's worth it to not have to maintain our own builds.
I've confirmed this starts as expected with `docker-compose`, but we'll want to thoroughly test this on staging too.
> Build from official ruby image

- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
provide the correct status code for retire subjects with no content reponse.
> return 204 on workflows retire subjects

- lib/formatter/csv/annotation_for_csv.rb
Added a debug notification to Honeybadger to provide more information on the project 2886's classification CSV export error.
> Debug Honeybadger notify for annotation export

- apiary.apib
- app/models/classification.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/models/classification_spec.rb
closes #1874 
Allow the api client to save incomplete classifications, todo this the etag (via get by id route) is called before running the PUT update method.
> allow show of incomplete classifications

- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
fixes #1881 - allows virtual attributes to be serialized via fields param.
> allow virtual field attributes to be specified for serializer response

- app/models/user.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
skip devise password length validation when updating / signing in old sha1 account passwords.
> allow short old hash_func passwords to still log in

- app/controllers/api/v1/classifications_controller.rb
- spec/support/updatable.rb
The classification update caused the completed field to change and thus the controlled_scope didn't resolve in the serializer so this change will provide the seriailzer with a new scope ref to the updated resource.
> ensure the resource is returned when updating classifications

- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
Closes #1891 - Do not filter out subjects that have been retired for another workflow. 
Also added in an explicit spec to ensure the subjects are returned in the order the selector chooses them. used mostly for priority selection but will preserve ordering for random too.
> respect workflow for retired filtering in selection

- app/models/workflow.rb
- spec/models/workflow_spec.rb
simple worfklow method to safely add the selection configuration instead respecting existing configuration directives.
> add method to easily update the selection strategy configuration

- apiary.apib
- spec/controllers/api/v1/subjects_controller_spec.rb
make a note that workflow_id is only used for when the sort=queued param is set, i.e. via subject selection and subject_set_id is required for subject selection when the workflow is grouped. Also subject_set_id can be used on normal index routes to narrow the result set scope.
> update docs for subject filtering by association

- app/workers/project_classifications_count_worker.rb
- spec/workers/project_classifications_count_worker_spec.rb
after resetting the project counts using a launch date the classification counts were resetting to there prev totals after normal classification. this PR will respect the launch date setting for the classification count.
> respect the project launch_date for classification counts

- app/models/user_seen_subject.rb
- app/serializers/user_project_preference_serializer.rb
when the project has no workflows ensure we dont' return all the workflow counts (across projects).
Also removed an old experiment while i was there...
> correct user projet preference activity counts

- app/controllers/cellect_controller.rb
- app/models/project.rb
- app/models/workflow.rb
- config/environments/test.rb
- config/routes.rb
- db/migrate/20160810140805_workflow_promote_cellect_to_own_attribute.rb
- db/structure.sql
- lib/subjects/strategy_selection.rb
- spec/controllers/cellect_controller_spec.rb
- spec/lib/subjects/strategy_selection_spec.rb
- spec/models/workflow_spec.rb
Provide cellect panoptes with api endpoints to enum the workflow to preload. Long term we can look to decouple the db connector and try api end points.
> add api routes for cellect

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/set_member_subjects_controller.rb
- app/controllers/api/v1/subject_sets_controller.rb
- app/controllers/api/v1/subjects_controller.rb
- app/models/set_member_subject.rb
- app/models/subject.rb
- app/workers/subject_removal_worker.rb
- db/migrate/20160630170502_add_subjects_activated_state.rb
- db/structure.sql
- lib/json_api_controller/deactivatable_resource.rb
- lib/subjects/remover.rb
- lib/subjects/selector.rb
- spec/controllers/api/v1/set_member_subjects_controller_spec.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/subjects/remover_spec.rb
- spec/lib/subjects/selector_spec.rb
- spec/models/subject_spec.rb
- spec/workers/subject_removal_worker_spec.rb
closes #1193
Don't delete subjects via the API. Mark them as deleted and process the actual deletion in the background so we can check if they are in use / have classifications, etc. 
TODO
Talk discussions are public by default but the actual subject data is private so we won't be leaking info and don't need to issue admin calls for the talk client.
> Deactivate subjects

- app/controllers/api/v1/subjects_controller.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/factories/subjects.rb
closes #1885 - avoid invalid location updates on the media resource. Make sure these validations pass before updating the relation to reflect the updated location resource.
> do not destroy location relations with invalid location updates

- app/controllers/cellect_controller.rb
- spec/controllers/cellect_controller_spec.rb
Add the subject's set infromation to the `/subjects` controller for use by cellect clients.
> add subject set ids for grouped workflow selection to cellect controller

- app/controllers/api/v1/subjects_controller.rb
- app/models/subject.rb
- db/migrate/20160630170502_add_subjects_activated_state.rb
- db/structure.sql
- lib/subjects/selector.rb
- lib/tasks/migrate.rake
- spec/models/subject_spec.rb
Let's try and avoid locking the large table so this will remove the addtional non-null constraint with the default value. On Staging - I'm going to undo the prev migration so this can run correctly this time.
> Break up subjects default add_column migration

- app/controllers/api/v1/subjects_controller.rb
- app/models/subject.rb
- db/migrate/20160819134413_subject_activated_state_default.rb
- db/structure.sql
- lib/subjects/selector.rb
- lib/tasks/migrate.rake
- spec/models/subject_spec.rb
Merge / deploy only after #1915 has been deployed and the default values filled in by the rake task.
> Re add default activated_state value to subjects table

- app/controllers/api/v1/project_preferences_controller.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
Combines @camallen's PR (#1914) and adds allowing collaborators to update UPPs for their projects.
> POST not PUT for UPP updates, collabs allowed

- app/workers/subject_removal_worker.rb
- lib/subjects/remover.rb
- spec/lib/subjects/remover_spec.rb
Make sure the panoptes client is using the correct operating env. Also lowered the subject removal worker queue priority.
> Correctly configure the panoptes client

- app/workers/subject_removal_worker.rb
- spec/workers/subject_removal_worker_spec.rb
cleaning up subjects is causing really high cpu on the db, skipping the cleanup in the meantime instead just leaving them as inactive.
> skip the subject removal temporarily

- .ruby-style.yml
Stops hound complaints about:
```ruby
Foo.bar
.baz
.quux
```
> Disable Hound multiline method chains indentation warnings

- app/services/cellect_ex_client.rb
Tiny snag: those self-signed certs I added at the last minute don't pass verification, and Faraday apparently enforces verification by default (which is great!).
> Do not verify self-signed SSL certs used by CellectEx

- app/workers/classification_count_worker.rb
- app/workers/project_classifications_count_worker.rb
- app/workers/project_classifiers_count_worker.rb
- spec/workers/project_classifications_count_worker_spec.rb
Temp for to skip long project counts and modified the rate limiting and the queue priorities to ensure high priority jobs run before the counts.
> unblock workers that counting changes introduced.

- app/counters/project_counter.rb
- db/migrate/20160901100944_add_classification_subject_join_index.rb
- db/structure.sql
- spec/counters/project_counter_spec.rb
- spec/workers/reset_project_counters_worker_spec.rb
Make sure the counter queries aren't forcing table scans and use fast queries where we can. This PR is a start, i'll review the lot and update with subsequent PRs.
> Fix slow count queries

- db/migrate/20160901141903_add_oauth_tokens_index.rb
- db/structure.sql
- lib/gem_ext/doorkeeper/access_cleanup.rb
- spec/lib/gem_ext/doorkeeper/access_cleanup_spec.rb
add index for doorkeeper authorisation lookup now with cleanup code that will remove old tokens / grants before running the migration. We should add (happy to do for this PR but can come in future) a rake task / scheduled worker for the cleanup
Also once these get cleanup up it'll help with the issue of the video showing on the home page for PFE.
> speed up doorkeeper lookups

- app/counters/project_counter.rb
- app/counters/workflow_counter.rb
- app/workers/project_classifications_count_worker.rb
- app/workers/reset_project_counters_worker.rb
- spec/counters/project_counter_spec.rb
- spec/counters/workflow_counter_spec.rb
- spec/factories/workflows.rb
- spec/workers/project_classifications_count_worker_spec.rb
- spec/workers/reset_project_counters_worker_spec.rb
Rely on the subject workflow status counts being the authoritative source of classification counts that respect the launch dates, just aggregate these up the chain via simple sum queries to avoid counting these again.
> summate the counters from the lowest level

- app/counters/project_counter.rb
- spec/counters/project_counter_spec.rb
Don't count testing / inactive workflow classifications. 
I did notice that the active field here clashes with the activatable enum scope active? which we should look at too, basically `workflow.active = false` => `workflow.active? == true` which threw me a bit. i'm wondering if / what to rename the active field to since i like the name active and people are used to it on the front end.
> respect active linked workflow state for counting at project level

- app/counters/workflow_counter.rb
- app/models/project.rb
- app/workers/workflow_retired_count_worker.rb
- spec/counters/workflow_counter_spec.rb
- spec/models/project_spec.rb
- spec/workers/workflow_retired_count_worker_spec.rb
Only count the current set of linked subjects to determine the retired subject count for the workflow and respect live workflows for the project counts.
> Fix early retire workflows

- app/workers/classification_count_worker.rb
- app/workers/subject_workflow_status_count_worker.rb
- spec/workers/classification_count_worker_spec.rb
- spec/workers/subject_workflow_status_count_worker_spec.rb
Try and not spam the db, instead use a increment counter on hopefully? non-deadlocking subject workflow status records and a rate limited worker to resolve the correct count.
> Avoid multiple classifcation counts on classification receipt

- app/workers/retirement_worker.rb
- app/workers/workflow_retired_count_worker.rb
- spec/workers/retirement_worker_spec.rb
- spec/workers/workflow_retired_count_worker_spec.rb
Closes #1571 
Basically, the `finished?` check is called before `WorkflowRetiredCountWorker` can update the retired counters used by `finished?`.  This just moves the `finished?` call to `WorkflowRetiredCountWorker`.
> Fix Workflow#finished_at assignment

- app/workers/reset_project_counters_worker.rb
- spec/workers/reset_project_counters_worker_spec.rb
make sure the reset count worker resets the retired subjects count for finished at calcs.
> reset the retired_subject_count on the worklfow too

- lib/subjects/postgresql_selection.rb
- spec/lib/subjects/postgresql_selection_spec.rb
- spec/support/shared_examples_for_postgresql_selection.rb
This is an attempt to fix the intermittent subject selection spec failure, e.g. https://travis-ci.org/zooniverse/Panoptes/jobs/157673258 and clean up the limit selection specs.
> clean up postgresql selection specs

- app/controllers/api/v1/users_controller.rb
- app/controllers/registrations_controller.rb
- app/mailers/user_info_changed_mailer.rb
- spec/controllers/api/v1/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/mailers/user_info_changed_mailer_spec.rb
- spec/workers/user_info_changed_mailer_worker_spec.rb
Switched from passing symbols to passing strings for sidekiq so that sidekiq knows what's up and correctly identifies which template to use.
> Symbols to strings for sidekiq's sake

- app/controllers/api/v1/project_roles_controller.rb
Checking to see why staging isn't sending project role change emails.
> Logging statement and arg check

- app/models/medium.rb
- app/services/media_storage/abstract_adapter.rb
- app/services/media_storage/aws_adapter.rb
- app/services/media_storage/test_adapter.rb
- spec/models/medium_spec.rb
- spec/services/media_storage/aws_adapter_spec.rb
This will no longer crash when people try to upload stuff with blank or weird filenames. Instead, it will get past the `before_validation` and then the validations on `src` and `mime_type` will fail, returning a correct error message back to API clients.
Resolves https://app.honeybadger.io/projects/40595/faults/30182593
> Set src to nil for unknown mime types

- app/controllers/api/events_controller.rb
- lib/classification_lifecycle.rb
- spec/controllers/api/events_controller_spec.rb
- spec/lib/classification_lifecycle_spec.rb
Closes #1794. Saves a user's project_id when the UPP is created for the first time so that we know which project was the first that a user contributed to.
> Save user project_id attr on first UPP save

- app/workers/classifications_dump_worker.rb
- lib/classification_dump_cache.rb
- lib/formatter/csv/annotation_for_csv.rb
- lib/formatter/csv/classification.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
- spec/lib/formatter/csv/classification_spec.rb
- spec/workers/classifications_dump_worker_spec.rb
add cache for classification -> subjects lookup (massive speed up here) and fixed some missing annotation tool label information in classifications. 
some classifications are missing the tool label index e.g. {"x"=>X, "y"=>Y} VS {"x"=>X, "y"=>Y, "tool"=>0, "frame"=>0, "details"=>[]} ~~most likely a borked PFE deploy that lost some frame info...~~ Seems to be the gold standard classification uploads after chatting to the researcher.
No will just return nil label as there is no information on the tool index that was being used.
> speed up and fix some csv annotation errors

- app/workers/classification_count_worker.rb
- app/workers/project_classifications_count_worker.rb
- app/workers/subject_workflow_status_count_worker.rb
- app/workers/workflow_classifications_count_worker.rb
- spec/workers/classification_count_worker_spec.rb
- spec/workers/project_classifications_count_worker_spec.rb
- spec/workers/subject_workflow_status_count_worker_spec.rb
- spec/workers/workflow_classifications_count_worker_spec.rb
I traced the deadlocking workflow update to the ProjectClassificationsCountWorker looping over all workflows and taking too long to finish. This allowed new jobs to pass the rate limiter (1 in 1 minute) and under certain circumstances try to update the same workflow at the same time (potential deadlock). 
I've split the count workers to now count the active classifying workflow (rate limited) and chain the project count update after a run that updates the workflow counts.
I've also introduced a freq backoff to ensure that we don't run these counters too often when lots of classifications are coming in short time frames. Note: I am happy to tweak these values. I based them testing counting large workflow counts (below) and guesstimated what i thought would be appropriate to avoid spamming …
> Count classifying workflow classifications not all of them

- app/controllers/api/events_controller.rb
- app/controllers/api/v1/subject_sets_controller.rb
- app/operations/user_project_preferences/find_or_create.rb
- lib/classification_lifecycle.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
- spec/operations/user_project_preferences/find_or_create_spec.rb
UPPs were created in multiple places, code for which is now consolidated into an operation. I'm not actually sure this will fix the counter, since it seemed to trigger recounts in both places.
SubjectSets would only recount if using the `update_links` action, creating a new set with subjects from the start, or updating with the normal update action wouldn't trigger a recount. To simplify this, let's just always recount. Even if maybe the subjects relation didn't actually change. There's not a lot of other attributes on a set, so most requests will probably update the subjects association anyways.
> Fix project classifiers counter and subject set subjects counter not updating

- app/controllers/api/v1/projects_controller.rb
- spec/controllers/api/v1/projects_controller_spec.rb
Adds the project updated_at attribute to the cards response object per project. This will be used by https://github.com/zooniverse/Panoptes-Front-End/pull/2979
> add updated_at attribute to project cards response

- app/controllers/concerns/recents.rb
- spec/support/recents.rb
avoid N+1 queries when serialising the link objects
> eager load the recents required models for serialization

- app/workers/calculate_project_completeness_worker.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
Projects that use never_retire will usually still have some kind of
retirement, but it will be externally managed (Nero, or custom).
In this case, since we can't tell how many classifications we will need,
we can only use the number of retired subjects as a guide to how far
along a project is.
> Add simplified completeness calculation for never_retire

- app/controllers/api/v1/subject_queues_controller.rb
- lib/json_api_controller/relation_manager.rb
- spec/lib/json_api_controller/relation_manager_spec.rb
Linking up an empty collection should not return errors, but should
simply assign the empty collection (or add no items).
Related: https://github.com/zooniverse/education-api/pull/34
> Allow sending in an empty collection

- app/models/subject.rb
- app/models/subject_workflow_status.rb
- app/operations/workflows/retire_subjects.rb
- spec/models/subject_workflow_status_spec.rb
- spec/operations/workflows/retire_subjects_spec.rb
Closes: https://github.com/zooniverse/Panoptes-Front-End/issues/3077
Rename the enum field to not override the instance `blank?` method.
``` ruby 
irb(main):041:0> SubjectWorkflowStatus.retired.by_subject_workflow(subject.id, workflow.id).present?
=> false
irb(main):042:0> SubjectWorkflowStatus.retired.by_subject_workflow(subject.id, workflow.id)         
=> #<SubjectWorkflowStatus id: .....>
irb(main):053:0> SubjectWorkflowStatus.retired.by_subject_workflow(subject.id, workflow.id).blank?  
=> true
```
this was returning false even though an AR instance was returned.
> correctly serialize the retired status of subjects

- app/counters/subject_workflow_counter.rb
- app/models/subject_workflow_status.rb
- spec/controllers/api/v1/subject_worfklow_statuses_controller_spec.rb
- spec/controllers/cellect_controller_spec.rb
- spec/counters/subject_workflow_counter_spec.rb
Closes #1932 - The subject workflow counters weren't correctly counting where subjects had been reused across worklfows.
> count the classifications correctly ignoring any subject reuse across workflows

- app/workers/publish_classification_worker.rb
- spec/workers/publish_classification_worker_spec.rb
Turns out NfN has a huge list of names in their workflow strings, which makes things too big to fit in the stream.
> Remove workflow contents from Kinesis

- app/models/workflow.rb
- spec/models/workflow_spec.rb
Avoid N+1 queries in the serializer
> eager load the linked resources used in the serializer

- app/workers/calculate_project_completeness_worker.rb
- spec/workers/calculate_project_completeness_worker_spec.rb
linked to https://github.com/zooniverse/Panoptes-Front-End/issues/3145
ignore the metrics based on classification counts and dealing with unlinked sets, just use the current linked set of subjects and retired counts to provide a ratio for completeness.
> use linked subject / retired ratio for project completion

- app/controllers/api/v1/projects_controller.rb
- spec/controllers/api/v1/projects_controller_spec.rb
closes #1765 - save the launch_date timestamp when we first approve a project.
also refactored the extra finds & save for update as the updating resource is already known and any has_many relation adds auto saves in the db.
> save the launch_approved timestamp when it's first pressed

- app/models/workflow.rb
- spec/models/workflow_spec.rb
Revert the eager load changes that seemed to be causing db cpu load.
> revert workflow eager load changes for scope_for

- app/counters/workflow_counter.rb
- spec/counters/workflow_counter_spec.rb
fixes #2023 compare apples and apples here as the SubjectWorkflowStatus will be created the first time it's classified not retired.
> use the reired_at timestamp not created_at

- app/serializers/project_serializer.rb
- spec/serializers/project_serializer_spec.rb
Serializes non-enum (presently `paused` and `finished`) states. If your params include `{ state: [live] }` (or any other boolean on Project, all of which are indexed), your results will be filtered by that attribute. Might have made this _too_ flexible, since any `state` sent that isn't in the enum will be set to `true` and thrown into the serializer, but we'll see if you think so.
> Include non-enum states in serialized projects

- app/serializers/project_serializer.rb
- spec/serializers/project_serializer_spec.rb
Allows for the confusing situation where you could have a `live: true` project that was also `state: paused`. This adds a scope to the serializer call to force `Project.where(state: nil)` if `?state=live` is passed as a param. Hacky also, but this is exactly why we need to consolidate all of these.
> No more paused projects in index

- lib/json_api_controller/json_schema_validator.rb
I've searched for `def create_params` more than a few times, and obviously that didn't work because of the alias. Next time I will get a match.
> Make create_params and update_params greppable

- lib/formatter/csv/annotation_for_csv.rb
- spec/factories/workflows.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
**MERGE DEPENDENT** on https://github.com/zooniverse/Panoptes-Front-End/pull/2914
Adds a new task type (persistent) that is always displayed for a workflow in PFE. This task can not be wired up in normal task flow. It's use case is for constant answers irrespective of specific tasks, e.g. nothing in the image? and fire? Similar to the way snapshot serengeti works with fire / nothing.
> handle persistent task type in csv annotation exports

- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
I'm not sure this is the best solution as it could swamp the database. 
The reason i'm proposing this is that cellect can be out of sync re loaded data so try and return useful data. This happened today with a project, for some reason cellect wasn't told / hadn't reloaded the new data that was linked up (not sure why) but there was plenty of data left to classify and the fallback selector was just showing any data...sad times.
> smarter fallback subject selection when using cellect

- app/models/aggregation.rb
- app/models/subject_queue.rb
- app/models/workflow.rb
- spec/models/workflow_spec.rb
Make sure the controller actually eager loads the relations for the serializer. Added feature flag and experimental setup to get metrics on any performance costs of using the eager loading strategy.
> eager_load the workflow relations used in the serializer

- app/controllers/api/v1/projects_controller.rb
- app/controllers/concerns/filter_by_current_user_roles.rb
- app/models/project.rb
- spec/models/project_spec.rb
If we're running an experiment then we should only call eager loading from one spot (project.scope_for) to isolate this testing. Also ensure we are preloading the owner relation that is used in the owner test and eager load the `project.tags` association as it's used in the serializer.
> Cleanup eager loading in projects controller

- lib/classification_dump_cache.rb
- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
Return the raw data instead of crashing on invalid annotation values. Also removed unnecessary db lookups in the annotation cache as we had the resource already.
> handle incorrectly formatted annotation values in classification dumps

- app/operations/workflows/retire_subjects.rb
- spec/operations/workflows/retire_subjects_spec.rb
return as fast as possible and don't do any work if the params are missing.
> do nothing when retirement subject_id(s) are missing

- lib/tasks/migrate.rake
set the cache attribute values via a rake task to avoid lookups in the serializer.
avoid the N+1 lookup in the serializer
> rake task to set the worfklow & contents version cache key

- lib/subjects/strategy_selection.rb
- spec/lib/subjects/strategy_selection_spec.rb
> Automatic Cellect activation should not happen when CellectEx is configured

- lib/subjects/selector.rb
In case of fallback we hit a logging statement which fails if there's no user.
> Fix logging for fallback

- app/controllers/api/v1/projects_controller.rb
- app/models/project_content.rb
- app/schemas/project_create_schema.rb
- app/serializers/project_content_serializer.rb
- app/serializers/project_serializer.rb
- db/migrate/20161128193435_add_researcher_quote_to_project_contents.rb
- db/structure.sql
- spec/factories/project_contents.rb
- spec/models/project_content_spec.rb
Adds "researcher_quote" field to project contents, including associated serializers and constants. Character min 255. Probably didn't need the index but I thought better to include than not. No default included, nil values should be dealt with on the front end since many projects will not have this quote. That'll also mean we won't have to backfill.
Closes #2035 .
> Adds researcher_quote to project contents

- app/models/project.rb
- spec/models/project_spec.rb
closes #1861 only link active workflows from the project resource
> respect activated_state enum for workflows association

- app/operations/workflows/retire_subjects.rb
- app/workers/retire_subject_worker.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/operations/workflows/retire_subjects_spec.rb
- spec/workers/retire_subject_worker_spec.rb
Use queued workers to retire subjects out of band as the serialized response doesn't depend on the actual retire operation [here](https://github.com/zooniverse/Panoptes/blob/7c0106054b20b4e13dc8e5f345784d8679b60e58/app/controllers/api/v1/workflows_controller.rb#L31)
Should see a marked improvement in performance when systems like aggregation bulk retire subjects at regular intervals.
> use workers to run the retire_subject code

- app/models/medium.rb
- app/workers/medium_removal_worker.rb
- spec/models/medium_spec.rb
- spec/workers/medium_removal_worker_spec.rb
closes #2065 - don't try and remove stuff we don't own.
> do not attempt to remove externally hosted media resources

- app/controllers/api/v1/subject_sets_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/subject_sets_controller_spec.rb
closes #1384 call a worker to unfinish the workflow when adding new data to existing subject sets or linking new sets.
> Unfinish workflows when adding new data

- app/serializers/collection_serializer.rb
- spec/serializers/collection_serializer_spec.rb
preload included relations where we can.
avoid N+1 on the belongs_to_many array relation, instead just serializer the fk_ids in the links at the cost of full resource side loading via ?includes=projects. 
Long term if this is an issue we will have to modify the custom AR Relation to preload properly.
> speed up the collection serializer

- app/mailers/classification_data_mailer.rb
- app/views/classification_data_mailer/classification_data.html.erb
- app/views/classification_data_mailer/classification_data.text.erb
- app/workers/classification_data_mailer_worker.rb
- app/workers/concerns/dump_mailer_worker.rb
- app/workers/concerns/dump_worker.rb
- spec/support/dump_worker.rb
- spec/workers/classification_data_mailer_worker_spec.rb
Classification data and dump mailer workers needed to be updated to handle workflow classification exports. Also fixed the email text.
> Send emails on workflow classification exports

- app/controllers/api/v1/projects_controller.rb
- spec/controllers/api/v1/projects_controller_spec.rb
The idea behind this was that project owners could make malicious changes and we need to double check them. In practise it just means both they and we ourselves forget this issue, and projects disappear from the launched list because of it.
> Keep projects as launched when set back to development

- app/workers/subject_data_mailer_worker.rb
- app/workers/workflow_content_data_mailer_worker.rb
- app/workers/workflow_data_mailer_worker.rb
- spec/workers/classification_data_mailer_worker_spec.rb
- spec/workers/concerns/dump_mailer_worker_spec.rb
- spec/workers/subject_data_mailer_worker_spec.rb
- spec/workers/workflow_content_data_mailer_worker_spec.rb
- spec/workers/workflow_data_mailer_worker_spec.rb
The classification dump mailer worker needs the resource type ("project", "workflow") along with the other arguments, so the dump worker concern was sending it along. The other mailers, however, didn't know what to do with the extra argument. 
This is currently not tested for because the DumpMailerWorkerSpec stubs out a worker class and doesn't test sending #perform_async to each mailer worker individually, so changing the number of args didn't send up any red flags. Trying to add some there began to feel extremely hacky and I get why it was done the way it was, but it'd have been nice for tests to catch this.
That, and I can't really be sure this'll fix the issue. See https://app.honeybadger.io/projects/40595/faults/31953245 for details.
> Fixes argument error on other mailer workers

- app/controllers/api/v1/project_roles_controller.rb
- spec/controllers/api/v1/project_roles_controller_spec.rb
- spec/factories/access_control_lists.rb
When a user is added to a project as a collaborator or expert, they should get an email, not the person who added them. Just looking for the first person in the ACL's user group, since 100% of the time they're identity groups.
> Send emails to the right people

- app/controllers/api/v1/subjects_controller.rb
- app/models/subject.rb
- app/models/user.rb
- app/serializers/subject_serializer.rb
- app/workers/classifications_dump_worker.rb
- db/migrate/20161125123824_add_active_controlled_indexes.rb
- db/structure.sql
- lib/formatter/csv/subject.rb
- lib/subjects/selector.rb
- spec/factories/media.rb
- spec/factories/subjects.rb
- spec/lib/subjects/selector_spec.rb
- spec/serializers/subject_serializer_spec.rb
supersedes #2060 and closes #1614 #1841 
- Remove the Subject locations default scope
- Add public/private & active scope indexes for controlled resources
- Add preloading to the subject serializer to avoid N+1 lookups and added the ability to turn off extra selection lookups (seen / retired / user_finished) in the serializer for peak load events (SGL) to avoid multiple extra db queries.
> Subject remove default scope and optimize the selector scope queries

- app/schemas/project_update_schema.rb
- spec/controllers/api/v1/projects_controller_spec.rb
It's already in ProjectCreateSchema, but #update was throwing a 422 when researcher quote was included in an update.
> Adds researcher quote to project update schema

- app/models/subject.rb
- app/serializers/subject_serializer.rb
- lib/formatter/csv/subject.rb
- spec/lib/formatter/csv/subject_spec.rb
- spec/models/subject_spec.rb
- spec/serializers/subject_serializer_spec.rb
Recent deploy breaks when serialising older subjects that have no location index metadata
> handle missing location metadata for older subjects

- app/models/project.rb
- spec/models/project_spec.rb
Fix #2052, so project subjects_counts only respect the active set of workflows -> subject_sets and not all workflows -> subject_sets
> Ensure subjects_count only includes sets from active workflows

- Gemfile.lock
Bump the point version of libv8 to hopefully stop it from breaking the install on OSX
> Bump libv8 to get it running on OSX

- spec/lib/formatter/csv/subject_spec.rb
- spec/models/subject_spec.rb
#2086 had an active focus set checked in, sorry, so the formatter spec failed to run properly on that PR. 
1. I had the column ordering wrong...fixed. 
2. The spec was relying on database ordering to build up an expectation, I've fixed it to be consistent with the expectations.
> Fix broken subject specs

- app/serializers/project_serializer.rb
- spec/serializers/project_serializer_spec.rb
compare apples and apples for this experiment, most of the index pages use the cards params. That param ignore the association links so we're testing preload against a control that doesn't use it.
> ignore the preload experiment for project cards that have no assocation links

- app/serializers/concerns/cached_serializer.rb
- app/serializers/tutorial_serializer.rb
- app/serializers/workflow_serializer.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
This adds a feature-flagged cache for the `as_json` hashes for models. 
Issues:
* Since we update counters without touching the `updated_at` timestamp, this will effectively keep them static until TTL (which I've set to 5 minutes for now).
> Add memory cache for testing out caching in staging

- app/models/subject_workflow_status.rb
- app/models/workflow.rb
- app/workers/retire_subject_worker.rb
- spec/controllers/api/v1/subject_worfklow_statuses_controller_spec.rb
- spec/factories/subject_workflow_statuses.rb
- spec/lib/formatter/csv/subject_spec.rb
- spec/lib/subjects/strategy_selection_spec.rb
- spec/models/subject_workflow_status_spec.rb
- spec/models/workflow_spec.rb
- spec/workers/reset_project_counters_worker_spec.rb
- spec/workers/retire_subject_worker_spec.rb
Avoid the counters running on each retire operation and hitting the db hard. Instead pay this cost once when creating the status resource. Note this doesn't check on updates as subjects can be unlinked form workflows over time.
> Avoid subject workflow link checks on a retire operation

- lib/formatter/csv/subject.rb
- spec/models/subject_spec.rb
- spec/serializers/subject_serializer_spec.rb
ensure we pass ids into the where scope and not the full workflow resources representations
Fixes a bug reported by a researcher that the subject dumps don't include all the project workflow retirement information.
> Report all project workflows in subject dumps

- app/workers/subjects_dump_worker.rb
- lib/formatter/csv/subject.rb
- spec/lib/formatter/csv/subject_spec.rb
Fixes #2101 - reset the subject workflow status cache for each new subject
> reset sws cache for each subject

- spec/serializers/subject_serializer_spec.rb
match array formatting not ordering as this is tested in the subject_spec.rb
> attempt to fix intermittent spec failure

- spec/spec_helper.rb
this time window will hang forked processes like spring, guard, etc until the timeout window. this will workaround it until we can bump celluloid to a fix.
> decrease the celluloid shutdown time window

- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
Closes #2104 - some annotations have out of bounds index lookups for the workflows answers array, this will mark them as invalid but still record the data in the export for the researcher.
> record unknown answer label for out of bounds lookups

- app/models/project.rb
- spec/models/project_spec.rb
Avoid calling sum N+1 queries in the project serializer if the model is preloaded (paging).
The subject_set & workflow calls here are the sum queries (note preloading was turned on @ 16:18):
> Use loaded associations to avoid sum db queries

- app/controllers/api/v1/organizations_controller.rb
- app/operations/concerns/url_labels.rb
- app/operations/organizations/create.rb
- app/operations/organizations/organizations.rb
- app/operations/organizations/update.rb
- config/application.rb
- db/migrate/20161221203241_add_urls_to_organizations.rb
- db/structure.sql
- spec/controllers/api/v1/organizations_controller_spec.rb
- spec/factories/organization.rb
I've added URLs to organizations! This involved duping some of the URL label translation code from the projects controller to the create and update org operations. It currently works, but that duped code is bugging me.
It seems like I should be able to inherit from an Organization class (within the same Organizations module) and put those methods in that class, but when I do, the operation doesn't run correctly. 
This is what I tried: I created `organization.rb`, which is in the Organizations module and starts with `class Organization < Operation`. Therein, `self.content_from_params` and `self.extract_url_labels` are defined. The error when the spec runs is this: `NoMethodError: undefined method `run!' for #<Organizations::Update::ActiveRecord_Relation:0x007fadbfe118c8>`
Not the end of …
> Adds URLs to organizations

- app/models/workflow.rb
- spec/lib/subjects/strategy_selection_spec.rb
- spec/models/workflow_spec.rb
use the optimized subjects_count method instead of a seq scan with a join query to avoid more complex join count calls when lots of subjects retire at once (think aggregation). 
This method ideally will be cached too.
> use the subjects_count method

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- config/initializers/cache_store.rb
override default env cache stores with elastic cache store but only if configured via env vars.
> elastic cache store integration

- app/models/classification.rb
- spec/models/classification_spec.rb
avoid a join on projects and instead use the indexed fk relation after checking the user has access to the project. This should alleviate timeout api calls when iterating from old last_ids for projects.
> optimize the query for classification project scope

- app/models/recent.rb
- db/migrate/20170112163747_modify_recents_fk_schema.rb
- db/migrate/20170113113532_add_recents_fk_indexes.rb
- db/structure.sql
- lib/tasks/migrate.rake
- spec/models/recent_spec.rb
move the has_one :through :classifications associations to belongs_to relations with indexes. Adds the belongs_to fkeys to recent schema and provides a rake task to backfill the missing information.
Once this is done we can remove the Recent has_one associations and modify the costly / complex recents query [here](https://github.com/zooniverse/Panoptes/blob/586f239d16a00fd75ef22df8498952e778684072/app/controllers/concerns/recents.rb#L9) to just use local indexes without the joins.
> simplify the recents schema for query optimization

- app/controllers/api/v1/subjects_controller.rb
- app/models/user.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
closes #2129 - avoid recounting the subjects_count where we can, instead cache the value and increment it on each successful subject create event.
> Cache uploaded subjects count

- app/controllers/cellect_controller.rb
- app/models/concerns/model_cache_key.rb
- app/models/workflow.rb
- db/migrate/20170116134142_workflow_drop_use_cellect.rb
- db/structure.sql
Avoid checking the subjects counts all the time, cache this value, expire every hour. 
Ideally it would be nice to cache the subjects_count method too but i'm not sure how to invalidate the cache on a new upload to a linked subject_set. Thoughts?
> Cache using_cellect? workflow call

- app/controllers/api/v1/classifications_controller.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
don't 500, catch this, report and return 201 so we don't get a duplicate submission
> handle redis timeout errors on classification lifecycle

- app/workers/workflow_retired_count_worker.rb
- spec/workers/workflow_retired_count_worker_spec.rb
and not when each subsequent time the count worker fires
> track the first workflow finished_at event

- app/models/user.rb
- spec/models/user_spec.rb
Related to https://app.honeybadger.io/projects/40595/faults/32346385#notice-summary
I can't figure out why the fetch / yield is returning "" / nil values. Let's just cast this to an int to avoid 500'ing on this route right now.
> don't fail to check the upload limits when uploading subjects

- app/controllers/api/v1/classifications_controller.rb
- app/controllers/api/v1/subjects_controller.rb
- app/models/user.rb
- lib/subjects/cellect_client.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/subjects/cellect_client_spec.rb
- spec/models/user_spec.rb
Don't 500 when submitting classifications, selecting subjects, registering users or deleting subjects. Instead just move on and fallback to default behaviour. Ideally this could be improved on by adding a refinement to sidekiq `peform_async` method that rescues all these errors and notifies honeybadger but i didn't do that :( 
Happy to rework this / have it added to by others.
> try and handle redis connection errors on critical API paths

- app/serializers/workflow_serializer.rb
Cut down on the number of preload requests, only preload has_* associations used in the serializer and not belongs_to relations as they are not needed by default (only when included by query params)
> only preload the has_ associations

- apiary.apib
- app/serializers/classification_serializer.rb
- app/serializers/concerns/no_count_serializer.rb
- spec/serializers/classification_serializer_spec.rb
Work around very query count calls that consume a lot of db resources / timeout api side buy manually set the classification serializer page values based on paging params to ensure we don't break clients that use the next/prev hrefs.
Long term this should be replaced with a modified Restpack::Serializer that uses the kaminari without_count page scopes, https://github.com/kaminari/kaminari#paginating-without-issuing-select-count-query
> avoid count queries on classifications end point that timeout / stress the db

- app/controllers/api/v1/organizations_controller.rb
- app/operations/organizations/create.rb
- app/operations/organizations/update.rb
- app/schemas/organization_update_schema.rb
- lib/filters/organization_filter.rb
- spec/controllers/api/v1/organizations_controller_spec.rb
- spec/controllers/api/v1/projects_controller_spec.rb
Updates to organizations were failing due to missing parameters. ActiveInteraction doesn't have an "optional" flag for filters, so when the JS client only sends the changed attributes, AI validation would fail. So instead, now there's an `organization_params` filter (alongside `string`, `integer`, etc) that does it's own validation against the standard format JSON schema. 
Few things:
* Not sure why the `require_relative` is...required. Seems like it should just be loaded automatically since it's in /lib.
* Most of what's in the filter could easily be abstracted out for all Org ops or even as a generic adapter for JSONSchema-->ActiveInteraction. Don't really need that now, though.
* Opted to put the filter into `lib/filters` instead of `lib/gem_ext/active_interaction` since I'm not …
> Adds a new ActiveInteraction filter for Organizations

- app/workers/subjects_dump_worker.rb
- lib/formatter/csv/subject.rb
- spec/lib/formatter/csv/subject_spec.rb
Every single row will now reference a specific workflow_id,
and detail the retirement status for that workflow.
This is also a first step to removing the JSON mess in our dumps.
The metadata column obviously remains as a JSON blob.
> Emit rows per workflow/subject_set in the subjects dump

- app/operations/organizations/create.rb
- app/schemas/organization_update_schema.rb
- app/serializers/organization_serializer.rb
- db/migrate/20170202200131_remove_name_from_organization.rb
- db/structure.sql
- spec/controllers/api/v1/organizations_controller_spec.rb
- spec/factories/organization.rb
Removes `name` attribute from db, serializer, and schema. It is redundant with `display_name` and will cause confusion.
> Remove redundant name column from Org

- app/serializers/organization_serializer.rb
- db/migrate/20170202202724_add_indices_to_organization.rb
- db/structure.sql
Adds `can_sort_by :display_name, :updated_at, :listed_at` to the org serializer as well as the appropriate indices for those three columns.
> Add sorting to organizations

- app/serializers/event_stream_serializers/subject_serializer.rb
- spec/serializers/event_stream_serializers/subject_serializer_spec.rb
SOCIAM would like to get these through Pusher (for which we'll also need to update the ZooEventStats) so that they can use them in visualisations.
> Add subject locations into stream

- app/controllers/api/v1/workflows_controller.rb
- app/serializers/concerns/panoptes_restpack_serializer.rb
- app/serializers/workflow_prp_serializer.rb
- app/serializers/workflow_serializer.rb
- config/routes.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/serializers/workflow_prp_serializer_spec.rb
- spec/serializers/workflow_serializer_spec.rb
- spec/support/panoptes_restpack_serializer.rb
replaces #2112
Added a custom panoptes wrapper over restpack serialzier to allow preloading on the page method.
This allows any valid include params to preload their associations and it provides a DSL to wire up preloads for each serializer.
I've created a code experiment to test this out on a custom route to see the performance of doing this.
> Custom preloading serializer

- app/controllers/concerns/recents.rb
- app/models/recent.rb
- db/migrate/20170118141452_add_recents_foreign_keys.rb
- db/structure.sql
- lib/tasks/migrate.rake
- spec/support/recents.rb
~~**DO NOT MERGE** until after the #2126 is deployed and backfilled. this will need a rebase and test to ensure the new recent_scope works as expected.~~
Rake task to cleanup invalid recents and a refactor of the recent's lookup scopes to use indexed cols and not joins on the classification table.
> Remove recents has associations and optimize recent scope

- app/models/subject_workflow_status.rb
- spec/models/subject_workflow_status_spec.rb
- spec/models/workflow_spec.rb
allow counts for subjects not linked to workflows. We should respect the classification data record and ignore any set linkage state as it changes with time.
> remove subject -> workflow link validation

- app/controllers/concerns/recents.rb
- app/models/concerns/ordered_locations.rb
- app/models/recent.rb
- app/models/subject.rb
- app/serializers/recent_serializer.rb
- db/migrate/20170118141452_add_recents_foreign_keys.rb
- db/migrate/20170210163241_recents_index_updates.rb
- db/structure.sql
- spec/models/recent_spec.rb
- spec/models/subject_spec.rb
- spec/serializers/recent_serializer_spec.rb
- spec/support/ordered_locations.rb
Cleanup invalid recent data to allow the fk migrations to pass. Rebuild the indexes as they are bloated and referencing old removed rows. Preload the recent media locations by reusing the extracted subject#ordered_locations code and finally add an index for created_at sorting without scans.
> Recents schema, index and serialzier updates

- app/models/collection.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/models/collection_spec.rb
You can now `update_links` on Collections if you have the "contributor" role. This was extremely simple on the model side. The controller specs were more proving it to myself than anything else.
Most of the effort on this feature will be on the front end, which I'm gonna give a shot soon.
> Added "contributor" role to Collections

- lib/role_control/controlled.rb
- spec/lib/role_control/controlled_spec.rb
Avoid testing the public_scope unless the public flag is set.
> simplify and test public scopes for resource access

- app/models/user.rb
- spec/models/user_spec.rb
ensure we don't 500 during registration when redis is down / hard to reach and we still send the email.
> handle more redis errors on registration

- .travis.yml
- Gemfile
- Gemfile.lock
- lib/devise_mailer/background_mailer.rb
- spec/lib/background_mailer_spec.rb
- spec/spec_helper.rb
make sure we still send emails for devise user registrations, passwords, etc if redis is down.
@marten this sets up mock redis for sidekiq unique testing as i didn't want to run another redis dep for local testing. Should i remove redis setup for travis?
> Send email if redis is down

- app/controllers/api/v1/subjects_controller.rb
- config/routes.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
Splitting this up means that it splits up in our monitoring tools too: NewRelic, logs, etc. The route does exactly the same as the index when `params[:sort] == 'queued'`, and the old method stays supported (but we should stop using it to get the most out of the mentioned benefit). 
If merged, I'll update PFE to use this for subject selection.
> Add queued route for subjects

- app/models/project.rb
- spec/models/project_spec.rb
Fixes #2191 - don't serialize deleted workflows
> respect the activated_state of the active workflows

- app/models/workflow.rb
- spec/models/workflow_spec.rb
keep the distributed systems seperate, if we're using cellect talk to cellect, if we using cellect_ex do that..otherwise default back to the subjects space size.
> using_cellect? should not return true if cellect_ex is set

- app/controllers/api/v1/classifications_controller.rb
- app/controllers/concerns/recents.rb
- app/serializers/classification_serializer.rb
- app/serializers/concerns/panoptes/restpack_serializer.rb
- app/serializers/recent_serializer.rb
- spec/serializers/classification_serializer_spec.rb
- spec/serializers/recent_serializer_spec.rb
Custom member / collection routes weren't serializing the correct paging *_href url's in the resource responses. This PR adds the ability to modify the paging URL's with serializer contexts via the Restpack::Serializer wrapper.
I still need to finalize testing on the serializer wrapper before merging this
> fix serialzied paging url's for custom nested resource routes

- lib/subjects/selector.rb
- spec/lib/subjects/selector_spec.rb
avoid the potential heavy cost of selection diffs when all subjects are retired, just fallback to anything. This may frustrate some users so we need to combine this with a signal in the subject_selector_serializer.rb that the workflow is finished
> only use fallback selection if the workflow is finished

- app/models/workflow.rb
- app/services/cellect_ex_client.rb
- app/services/designator_client.rb
- config/initializers/cellect_ex.rb
- config/initializers/designator.rb
- lib/subjects/designator_selector.rb
- lib/subjects/strategy_selection.rb
- spec/lib/subjects/designator_selector_spec.rb
- spec/lib/subjects/strategy_selection_spec.rb
- spec/models/workflow_spec.rb
- spec/services/designator_client_spec.rb
- spec/spec_helper.rb
This pushes the service rename through to Panoptes. Additionally, this adds support for the authentication that will soon be required on reload/retire endpoints of Designator.
> Rename CellectEx to Designator, and start sending authentication

- app/controllers/api/v1/subjects_controller.rb
- app/models/user.rb
- app/serializers/subject_selector_serializer.rb
- app/serializers/subject_serializer.rb
- lib/favorites_finder.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/favorites_finder_spec.rb
- spec/models/user_spec.rb
- spec/serializers/subject_selector_serializer_spec.rb
- spec/support/favorited_subjects.rb
Now with includes @camallen's updated subject serializer! `favorite` is an optional subject attribute along with the others, all behind a single flipper.
> Optional 'favorite' attr now available on subject

- app/schemas/project_preference_update_schema.rb
- spec/controllers/api/v1/project_preferences_controller_spec.rb
The settings property should be in the ProjectPreferencesUpdate schema so that PFE can update a user's project preferences.
> Add settings to project prefs update schema

- app/controllers/api/v1/media_controller.rb
- lib/json_api_controller/precondition_check.rb
- spec/requests/v1/api_conditional_request_spec.rb
Allow weak etag comparison if we receive a weak_etag server side for modifications, etc. This is due to adding gzip compression to nginx as it modifes the etag to be weak as this is correct etag spec. Rails is off spec with strong etags (changing in ver 5 to be weak) and this change allows the etags to not be rejected api side.
> compare weak etags for update / destroy actions precondition checks

- app/serializers/concerns/no_count_serializer.rb
- spec/serializers/classification_serializer_spec.rb
- spec/support/no_count_serializer.rb
test the page has data before adding a next page href to the metadata but still avoid counting the page scopes
> do not add a next href page url if there is no data

- lib/formatter/csv/annotation_for_csv.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
Shortcut tasks, like multiples, should export as their values an array instead of a string. This is the only difference between these two tasks. This, along with the rest of the exporter, is on the list of things to refactor.
Fixes #2228
> Shortcut task type value is an array, not a string

- lib/subjects/strategy_selection.rb
- spec/lib/subjects/strategy_selection_spec.rb
Only remove complete subjects from the set returned from the selector if the feature flag is enabled.
> Add a feature flag for completed subject removal

- lib/json_api_controller/relation_manager.rb
- spec/lib/json_api_controller/relation_manager_spec.rb
Calling this a WIP just now because I'd like to see what color the other specs will be with just this change. Can't really think of a situation where we'd want to do the opposite of what `delete` does here, i.e. actually delete the join table row OR set the relation's foreign key on the resource to nil.
update: refactored `destroy_relation` specs a bit and added a few more to cover all association types. Seems to behave as expected/desired.
> Destroy should be delete in the relation manager

- db/migrate/20170316170501_remove_inverted_indices.rb
- db/structure.sql
Drops:
`index_media_on_linked_type_and_linked_id`
and
`index_tagged_resources_on_resource_type_and_resource_id`
now that the correct "id, type" indices are built and can be used for ID-only queries.
> Drops incorrectly inverted indices

- app/controllers/emails_controller.rb
- spec/controllers/emails_controller_spec.rb
devise uses case insensitive email fields (lower case) so make sure we match against this to unsubscribe users via the webform.
> handle unsubscribing users with arbitrary case in their email address

- app/serializers/collection_serializer.rb
- app/serializers/concerns/filter_has_many.rb
- app/serializers/subject_set_serializer.rb
- lib/serialization/has_many_filtering/options.rb
- lib/serialization/panoptes_restpack.rb
- spec/serializers/collection_serializer_spec.rb
- spec/serializers/subject_serializer_spec.rb
- spec/serializers/subject_set_serializer_spec.rb
- spec/serializers/workflow_serializer_spec.rb
- spec/support/filter_has_many_serializer.rb
- spec/support/panoptes_restpack_serializer.rb
closes https://github.com/zooniverse/panoptes-python-client/issues/76
ensure the has many filters percolate into the paging url params
> provide correct paging urls with has_many relations

- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- app/serializers/classification_serializer.rb
- app/serializers/concerns/filter_has_many.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
Avoid the join on public workflows, use an in query for filtering the gold standard index hits. Also use the filter_has_many serializer for proper paging urls in #2239. Will need a rebase after that is in.
> Optimize gold standard queries

- app/controllers/api/v1/subjects_controller.rb
- app/models/subject_workflow_status.rb
- app/serializers/subject_selector_serializer.rb
- lib/subject_workflow_retirements.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
Moves the checking of whether a subject is retired for a given workflow to the selector context and asks about them all at once rather than one at a time in the serializer. A one liner that might not need it's own lib, but looks nice next to FavoriteFinder and I got to call a method `#find_retirees`. 
Good eye, btw. Is there a good way to test for these? I tried testing this with Bullet but it didn't detect this one in particular. Didn't expect it to but it's probably just the non-obvious ones left.
Fixes #2236
> Check for retirements all at once, remove n+1

- app/controllers/api/api_controller.rb
- app/controllers/concerns/api_errors.rb
- app/workers/aggregations_dump_worker.rb
- app/workers/classifications_dump_worker.rb
- app/workers/subjects_dump_worker.rb
- app/workers/workflow_contents_dump_worker.rb
- app/workers/workflows_dump_worker.rb
- spec/support/dump_worker.rb
- spec/workers/aggregations_dump_worker_spec.rb
- spec/workers/workflow_contents_dump_worker_spec.rb
- spec/workers/workflows_dump_worker_spec.rb
Adds a feature flag check to the dump workers for classifications, workflows, subjects, and aggregations. The API will return an error that says that exports are disabled. The sidekiq jobs will hit the flag, raise an exception, and fail however many (25?) times and then be put in the dead queue where we can run them later...or not.
I have been messing with sidekiq middleware all afternoon trying to conditionally set the retry amount but it doesn't really matter. If we want to reschedule these jobs instead of basically ignoring them, I'll need to know what that schedule looks like. **If we do flip this switch, we should ensure that PFE is going to do something smart with the response.**
Closes https://github.com/zooniverse/Panoptes/issues/2252 and …
> Adds feature flag to dump workers

- app/controllers/api/api_controller.rb
- app/controllers/api/v1/classifications_controller.rb
- app/controllers/api/v1/subjects_controller.rb
- app/controllers/concerns/api_errors.rb
- app/workers/aggregations_dump_worker.rb
- app/workers/classifications_dump_worker.rb
- app/workers/subjects_dump_worker.rb
- app/workers/workflow_contents_dump_worker.rb
- app/workers/workflows_dump_worker.rb
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/lib/subjects/strategy_selection_spec.rb
- spec/spec_helper.rb
- spec/support/dump_worker.rb
- spec/support/flipper.rb
- spec/workers/aggregations_dump_worker_spec.rb
- spec/workers/workflow_contents_dump_worker_spec.rb
- spec/workers/workflows_dump_worker_spec.rb
Builds on the subject uploading feature flag and adds one for classification lifecycle processing. When it is on, lifecycle processing is done normally: thrown into sidekiq via `perform_async` and left in the queue. When the flag is turned off, the processing will be done immediately at the cost of performance but preventing a race condition on postgresql subject selection.
Flag exists and enabled on production and staging.
> Adds feature flag for classification lifecycle processing

- app/controllers/api/v1/project_contents_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/models/project.rb
- app/models/workflow.rb
- app/operations/concerns/content_from_params.rb
- app/operations/concerns/url_labels.rb
- app/operations/organizations/create.rb
- app/operations/organizations/update.rb
- lib/json_api_controller/json_schema_validator.rb
- lib/json_api_controller/updatable_resource.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/project_spec.rb
- spec/models/workflow_spec.rb
- spec/support/extended_cache_key.rb
Instead of including the associated resources with an N+1 in the extended cache_key call for ETAG generation this will ensure the relevant linked model gets a touched updated_at timestamp so the etag gets changed and the browser doesn't use a cached version of the resource. 
PFE - doesn't use this anymore so the original bugs that the extended cache key fixed don't necessarily apply (index vs show routes) but we're still paying the cost of lookup on the associated models here.
> Touch model updated_at vs cache key include

- app/controllers/api/v1/classifications_controller.rb
- app/models/classification.rb
- app/models/gold_standard_annotation.rb
- app/serializers/concerns/filter_has_many.rb
- app/serializers/gold_standard_annotation_serializer.rb
- db/migrate/20170320203350_create_gold_standard_annotations.rb
- db/structure.sql
- lib/tasks/migrate.rake
- spec/controllers/api/v1/classifications_controller_spec.rb
- spec/factories/gold_standard_annotations.rb
- spec/models/classification_spec.rb
- spec/models/gold_standard_annotation_spec.rb
- spec/serializers/gold_standard_annotation_serializer_spec.rb
- spec/support/no_count_serializer.rb
- spec/support/panoptes_restpack_serializer.rb
Searching for gold standard classifications is not efficient over the classifications table space. Long term we're moving to a different summary mechanism for the UI. Isolate the existing gold standard classifications in their own table for fast index lookup 
TODO
~- [ ] Remove sparse gold standard classifications index~ do this in a future PR after data is migrated
This can be deployed by 
1. running the migration to add the table
2. run the rake task to migrate the gold standard data
3. deploy the code to start serving the migrated gold standard data
> Duplicate gold standard classifications to own model for faster lookups

- app/models/classification.rb
- app/models/membership.rb
- app/models/user_group.rb
- lib/role_control/controlled.rb
- lib/role_control/parental_controlled.rb
- spec/lib/role_control/parental_controlled_spec.rb
let AR do it's job constructing sub select statements instead of plucking data from possibly big scopes and feeding them into a secondary query.
I can split this up for the non-feature flagged scopes. in theory it'll just run the same query in a subselect but won't serialize the data back to rails with AR records being created so it should be faster / more efficient.
> use sub selects instead of two queries

- .rubocop.yml
- .travis.yml
Consistent and up to date ruby versions for the CI tools - it's pity that travis doesn't offer a newer rvm so we can use the 2.3 directive to install the latest minor version. In the meantime we have to manually set this or pay the cost to update upgrade rvm before install ruby... sigh.
> Ci ruby version

- app/serializers/project_serializer.rb
- spec/serializers/project_serializer_spec.rb
Only bummer here might be if the `@model.workflows.where(active: true)` call in the project serializer is making an extra db query, but hopefully it's just filtering what it's already pulled. Could have put that method on the model, but made more sense this way to me just now.
Closes https://github.com/zooniverse/Panoptes/issues/2251
> Include list of active workflows in serialized projects

- app/controllers/api/v1/subject_queues_controller.rb
- app/models/classification.rb
- app/models/user_group.rb
- lib/json_api_controller/creatable_resource.rb
- lib/json_api_controller/relation_manager.rb
- lib/role_control/controlled.rb
This PR tries to reduce the number of calls when saving resources generally and specifically looks at classification saves. 
I've modified the default scope_for private query to not use joins (see commit message for benchmarking). Also I've modified the relation_manager to not issue count queries when testing link resource existence where it can.
Finally a small change to not validate the subjects on classification save, seems has_many and has_and_belongs_to_many run the linked resources validations on record save. Either i've forgotten this or I never know and this caused other resource loads on classification save (subject project and uploader). We don't need to validate the subjects when saving classifications as they are just being linked. Note: the extra resource calls are only …
> Faster classification saves

- db/migrate/20170325135953_remove_unused_indexes_sgl2017.rb
- db/structure.sql
Remove indexes that aren't being used in query paths. 
I ran this sql to find them, https://gist.github.com/camallen/4d46cc0853efefbf55fb7ed0a4a4afa3 You can modify the idx_scan value to find less used queries too.
> remove unused indexes to free up db memory

- app/controllers/concerns/json_api_render.rb
- app/serializers/concerns/filter_has_many.rb
- lib/http_cacheable.rb
- lib/json_api_controller/indexable_resource.rb
- lib/json_api_controller/showable_resource.rb
- lib/role_control/parental_controlled.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/lib/http_cacheable_spec.rb
- spec/support/flipper.rb
- spec/support/http_cacheable_resource.rb
- spec/support/showable.rb
Add ability to cache public resources with http cache directives, currently only subjects, worfklows, projects but expandable to others. 
This uses the json_api render to test the serialized controlled_resources scope for any private resources. If the response is not cacheable or has any private resources it will not add the cache directives. Additionally a specific query param has to be provided to turn the caching feature on, e.g. `/subjects?http_cache=true`.
> Http caching public resources on index / show routes

- app/workers/classification_count_worker.rb
- app/workers/project_classifications_count_worker.rb
- app/workers/project_classifiers_count_worker.rb
- app/workers/reset_project_counters_worker.rb
- app/workers/subject_set_subject_counter_worker.rb
- app/workers/subject_workflow_status_count_worker.rb
- app/workers/workflow_classifications_count_worker.rb
- app/workers/workflow_retired_count_worker.rb
- spec/support/flipper.rb
- spec/workers/classification_count_worker_spec.rb
- spec/workers/project_classifications_count_worker_spec.rb
- spec/workers/subject_workflow_status_count_worker_spec.rb
- spec/workers/workflow_classifications_count_worker_spec.rb
add a feature flag to disable count workers and cancel count workers if rate limited to avoid feedback loop.
> Sgl dont reschedule counts and add feature flag to disable the count workers

- lib/role_control/controlled.rb
- spec/lib/role_control/controlled_spec.rb
make sure we don't test on polymorphic resource id's but only on the controlled type we're testing.
This will need some testing in staging to make sure there aren't any complications as it's been like this for a while. We could in theory be selecting the wrong resources based on other table id's in the private query.
> only return resource under control

- app/workers/classifications_dump_worker.rb
- app/workers/concerns/dump_worker.rb
This should prevent the generic begin/ensure that runs #perform_dump from suppressing the FeatureDisabled error. This appears to only happen in certain cases as I've definitely seen that error in Sidekiq's retry queue, so I'll be looking into this more later.
> Move FeatureDisabled raise to DumpWorker#perform

- app/controllers/api/v1/project_contents_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/models/concerns/translated_content.rb
- app/models/project.rb
- app/models/workflow.rb
- app/operations/concerns/content_from_params.rb
- app/operations/concerns/url_labels.rb
- app/operations/organizations/create.rb
- app/operations/organizations/update.rb
- lib/json_api_controller/json_schema_validator.rb
- lib/json_api_controller/updatable_resource.rb
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
- spec/models/project_spec.rb
- spec/models/workflow_spec.rb
- spec/support/extended_cache_key.rb
- spec/support/translated_content.rb
closes #2212, second attempt at #2169 
Refactor the controller actions to not require the content relations in the extended_cache_key. Also ensure we touch the parent translated resource when updating the content child relations, think just content updates like workflow task text changes.
> refactor update the project / workflow contents

- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
only update the tasks and strings if the tasks params is provided. this was setting content strings to the empty hash when not supplied with a tasks param
> respect tasks params on update

- lib/role_control/parental_controlled.rb
- spec/lib/role_control/parental_controlled_spec.rb
remove the feature flag conditional behaviour and implement the IN avoiding join scopes for queries.
~**DO NOT MERGE THIS** until we've tested the behaviour and determined that we want to move away from the join scopes on all parental controlled resources.~
I've tested this live without incident.
> move to IN sub select queries instead of JOINS on parental controlled

- app/serializers/classification_serializer.rb
- spec/serializers/classification_serializer_spec.rb
avoid paging with offsets when using the last_id param on the classification/project route. Instead manually override the next/previous hrefs to track the last_id for the client.
This should speed up the `/api/classifications/project?last_id=X` routes by providing the correct page last_id in the prev/next paging hrefs.
Also in theory this could be applied to the `/api/classifications/project` scope as a whole (i.e. multiple projects you have access to) if the scope always returns the lowest IDs as the first page but i'm not sure the database will guarantee this order. Something to think about and test.
> override the last_id paging hrefs for classification project routes

- app/models/concerns/ordered_locations.rb
- spec/support/ordered_locations.rb
closes #2293 and fixes https://github.com/zooniverse/Panoptes-Front-End/issues/3577
Ensure we sort the location metadata indexes as integers and not text in sql. This would have affected any subjects with more than 10 locations, so not many projects.
I tested the new code with the the example data in PFE issue, e.g:
```
irb(main):040:0> loc = subject.locations.sort_by { |loc| loc.metadata["index"] }.map { |loc| loc.metadata["index"] }
=> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]
irb(main):041:0> subject.locations.order("\"media\".\"metadata\"->>'index' ASC").map { |loc| loc.metadata["index"] }
=> [0, 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, …
```
> sort location metadata index as ints not strings

- app/counters/workflow_counter.rb
- spec/counters/workflow_counter_spec.rb
only count the currently linked set classifications for the workflow. 
Found this bug after I unlined data on exoplanets, the retired counts came down but the total classifications didn't leading to the complete signal in the stats summary.
> respect the linked sets when counting classifications

- apiary.apib
- app/controllers/api/v1/collections_controller.rb
- app/models/collection.rb
- app/serializers/collection_serializer.rb
- config/routes.rb
- db/migrate/20170403194826_add_default_subject_to_collections.rb
- db/structure.sql
- spec/serializers/collection_serializer_spec.rb
Collections now have a default subject field. It's serialized as either the media's first location's URL or just the collection's first subject's if nil. This creates an extra db query for the medium but prevents an entire extra API call from PFE for the first linked subject just to get its URL.
I need to test this on staging with the JS client and make sure it's set up to handle however it builds requests (via `/api/collections/:id` and `/api/collections/:id/links/default_subject`)
> Add default subject to Collections

- app/serializers/user_project_preference_serializer.rb
This adds `:created_at` attribute to the user project preferences serializer. The first a/b split that Gravity Spy ran was to study behavior with users new to the project and the only way we can determine that is by the existence of the user project preferences for the project. If they want to run any future experiments with new users, it will be useful to have the `created_at` timestamp available via the API and possibly log it to geordi for the researcher's use in data analysis.
I looked through the spec files and didn't see anything that I would need to update in the tests, but do let me know if I missed something.
> Add :created_at attribute to UPP serializer

- app/controllers/api/v1/collections_controller.rb
- app/serializers/collection_serializer.rb
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/serializers/collection_serializer_spec.rb
* Adds proper URL formatting to the default subject src URL returned from the collection serializer.
* If a subject is being unlinked from a collection, check to see if it's the current default. If it is, null the default subject before unlinking.
> Collection Default Subject updates

- app/schemas/project_create_schema.rb
- app/schemas/project_update_schema.rb
- app/schemas/workflow_create_schema.rb
- app/schemas/workflow_update_schema.rb
- app/serializers/project_serializer.rb
- app/serializers/workflow_serializer.rb
- db/migrate/20170420095703_alter_projects_add_mobile_friendly.rb
- db/migrate/20170425110939_alter_workflows_add_mobile_friendly.rb
- db/structure.sql
- spec/controllers/api/v1/projects_controller_spec.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
This lets the mobile app filter the projects listing to just projects that have been marked as mobile-friendly. This can be set by owners via the API since we don't want to have to manage this long-term. 
Short term we probably will be setting this ourselves without any UI, we'll think about adding it to the project builder at some point.
> Add project/workflow mobile_friendly

- app/serializers/concerns/cached_serializer.rb
- app/serializers/user_project_preference_serializer.rb
- app/serializers/version_serializer.rb
- lib/gem_ext/paper_trail/virtual_updated_at.rb
- spec/serializers/user_project_preference_serializer_spec.rb
- spec/support/flipper.rb
Use the created_at timestamp when generating the version cache key as PaperTrail::Version has no updated_at timestamp. I tried to use refinements to add a virtual attribute to the model but couldn't get it working in the for just the VersionSerializer through the CachedSerializer module due to refinement lexical scope. Oh well...it was a refinement adventure.
~Add a refined virtual updated_at attribute to PaperTrail::Version model that proxies the created_at attribute. This is only used in the version serializer. I used the refinement to avoid serializer code duplication and should not impact anywhere else in the system with the refinement.~
~Side note, this was so much nicer than monkey patching the virtual attribute and wondering about the impact of such a change.~
> fix version serializer caching

- app/controllers/api/v1/organization_pages_controller.rb
- app/models/organization.rb
- app/models/organization_page.rb
- app/serializers/organization_page_serializer.rb
- app/serializers/project_page_serializer.rb
- config/routes.rb
- db/migrate/20170426162708_add_organization_pages.rb
- db/structure.sql
- spec/controllers/api/v1/organization_pages_controller_spec.rb
- spec/controllers/api/v1/project_pages_controller_spec.rb
- spec/factories/organization_pages.rb
Adds pages to organizations, just like projects. This is mostly duplicated code from the projects version of pages. I would like to extract it all out and DRY it all up, but with only these two uses it seems a bit like a waste of effort. This was everyone's take when orgs were first dropped in (new controller scheme aside) and it's still true. When something comes along that can make use of this code again, I think that'll be the time.
> Organization pages

- app/operations/organizations/create.rb
- app/operations/organizations/update.rb
- app/schemas/organization_update_schema.rb
- app/serializers/organization_serializer.rb
- spec/controllers/api/v1/organizations_controller_spec.rb
Title is no longer a required param for create and is removed from the update schema. It is set to the display name for the content's language.
listed_at is now serialized
> Set organization title by display_name param

- app/controllers/api/v1/workflows_controller.rb
- spec/controllers/api/v1/workflows_controller_spec.rb
closes #2201 - recount the retired currently linked subjects and recalculate the completeness metrics. This should ensure the stats are updated and the finished banner doesn't show when new data is uploaded after a project finished.
> update retired counts and completeness metrics when linking new data sets

- app/serializers/classification_serializer.rb
- spec/serializers/classification_serializer_spec.rb
This fixes an error when accessing project classification data using the last_id offset. It now will handle empty pages of data and construct the last_id href without string manipulations.
> construct valid refs when there is no page data for classification last_id queries

- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/workflows_controller.rb
- app/controllers/concerns/json_api_responses.rb
- app/controllers/concerns/medium_response.rb
- spec/support/creatable.rb
- spec/support/showable.rb
linked to #https://github.com/zooniverse/panoptes-python-client/issues/83
add the resource etag on create actions to avoid an extra lookup to manipulate the resource. This etag should be the same as a subsequent get etag as long as the cache key hasn't changed.
> Etag on create

- db/migrate/20170523135118_remove_dup_indexes_use_compounds.rb
- db/structure.sql
use first col of compound indexes and remove the single column indexes where we can
I'd like to test this in staging and if you all feel strongly maybe against a production version with some timing tests. The query planner should be able to use the compound indexes if the first column is a match instead of the separate indexes.
> remove duplicate indexes

- app/controllers/api/v1/collections_controller.rb
- app/serializers/collection_serializer.rb
- db/migrate/20170519181110_add_description_to_collections.rb
- db/structure.sql
- spec/controllers/api/v1/collections_controller_spec.rb
- spec/factories/collections.rb
The only thing here is the `default: ""` and subsequent `Collection.update_all(display_name: "")`. There are 60k of them and so I think this should be fine, but if anyone's worried, maybe there's in a more forgiving way.
> Adds a description text field to collections

- db/migrate/20170525151142_rebuild_oauth_token_index.rb
- db/structure.sql
ensure this is run after cleaning up the table so the index can build quickly.
Only merge / deploy this after #2329 has been deployed and taken effect to cleanup the table space. Check the index size after cleanup and see how it looks.
> rebuild the oauth access token index

- app/controllers/api/v1/organization_pages_controller.rb
- app/controllers/api/v1/project_pages_controller.rb
- app/controllers/concerns/pages.rb
- app/serializers/organization_serializer.rb
Reference: #2318 
Just stuck pages into the org serializer's can_include. Index methods aren't authenticated and therefore won't show you pages from private projects or orgs.
EXTRA CREDIT: I took the opportunity to actually extract out the page controller stuff from the org and project controllers into it's own concern.
> Optionally include Pages in serialized organizations

- app/models/organization.rb
- app/operations/organizations/update.rb
- app/schemas/organization_update_schema.rb
- app/serializers/organization_serializer.rb
- db/migrate/20170524210302_add_listed_boolean_to_organizations.rb
- db/structure.sql
- spec/controllers/api/v1/organization_contents_controller_spec.rb
- spec/controllers/api/v1/organization_roles_controller_spec.rb
- spec/controllers/api/v1/organizations_controller_spec.rb
- spec/factories/organization.rb
Having a timestamp field for public/private seemed like a good idea, but Restpack isn't having it. You can't filter by anything you can't put after an equals sign. So I added a `listed` boolean to Organizations and set up the controller to touch the `listed_at` timestamp on update when `listed` is present in the params and true and nil it when false.
> Adds boolean to Organizations that touches/nulls listed_at on update

- db/migrate/20170524205300_add_index_to_organization_slug.rb
I did this on the console to ensure that it would work, this will make sure that future from-scratch migrations won't have the same issue.
> Saves all orgs to ensure non-blank slug attributes before adding unique index

- app/serializers/classification_serializer.rb
- app/serializers/gold_standard_annotation_serializer.rb
- app/serializers/recent_serializer.rb
- app/serializers/subject_workflow_status_serializer.rb
We found that classifications weren't serializing the updated_at timestamp. This PR adds that in all instances.
> Always serialize updated_at if serializing created_at

- apiary.apib
- app/controllers/api/v1/projects_controller.rb
- spec/controllers/api/v1/projects_controller_spec.rb
Avatar URL is an optional attribute on the project serializer. However, there was no way to indicate via param that it should be included. Now there is.
Sarah and I were working on reduxifying watch.zooniverse.org and we need the avatar--but we also need classification, which isn't included in the 'card' serialization method.
I thought about taking the opportunity to switch to PanoptesRestpack on the project serializer, but it occurred to me that I don't really know what the difference is supposed to be. This works with both.
> Add param to include avatar in serializer context

- db/migrate/20150427171257_create_subject_workflow_counts.rb
- db/migrate/20160613075003_foreign_keys_workflows.rb
- db/structure.sql
Migrations via `db:migrate` (rather than `db:setup`, which pulls directly from structure.rb) were broken because of the renaming of `SubjectWorkflowCount` to `SubjectWorkflowStatus`. 
Renamed!
> Fix renamed classes in migrations

- app/serializers/project_serializer.rb
- spec/serializers/project_serializer_spec.rb
fixes #2375 - serializer the tag names only in the project tags attribute.
> serialise the tag names array in project tags attribute

- Dockerfile
- scripts/docker/start.sh
`/tmp` is now mounted from EFS to remove storage limits for exports. This means any orphaned files will persist indefinitely unless we remove them.
> Clean old tmp files on start

- .rubocop.yml
- lib/formatter/csv/annotation_for_csv.rb
- spec/factories/workflow_contents.rb
- spec/factories/workflows.rb
- spec/lib/formatter/csv/annotation_for_csv_spec.rb
some combo task annotations are malformed and do not embed as the annotation values in the expected format (see specs).
Now the code will report an error in the output file and move on instead of failing.
> handle invalid combo task annotations in csv formatter

- app/controllers/api/v1/subjects_controller.rb
- app/models/user.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
- spec/models/user_spec.rb
Partly addresses #2406 do not touch the user model on each upload (and stress the db), instead use the uploaded_subjects_count as part of the rails cache key to invalidated the serializer.
The only down side is without caching layers this can spam the db with subjects table counts for each user request. our setup has the caching layer so won't be impacted but i wanted to get this up for discussion.
> avoid updating user on each subject upload

- db/migrate/20170215151802_change_oauth_application_default_trust_level.rb
- db/structure.sql
Oauth apps should be able to be used for authentication by default.
> make insecure oauth apps useful by default
